Core standalone sim
OpenRailAssociation/osrd pull request #1007
Opened 2022-05-19 10:16 UTC by estia-m

2022-05-24 08:28 UTC, flomonster requested changes
Thanks for this PR. Their is some changes to make. We can discuss further about this later.

2022-05-24 08:28 UTC, flomonster commented on core/src/main/java/fr/sncf/osrd/cli/StandaloneSimulationCommand.java
> +            names = {"--infra_path" },
If you specify `names` without `--` this option become a main parameter which is better in our case.

You can check the documentation of jcommander here: https://jcommander.org/#_overview
```suggestion
            names = {"infra_path" },
```

2022-05-24 08:28 UTC, flomonster commented on core/src/main/java/fr/sncf/osrd/cli/StandaloneSimulationCommand.java
> +            names = {"--sim_path" },
Same

2022-05-24 08:28 UTC, flomonster commented on core/src/main/java/fr/sncf/osrd/cli/StandaloneSimulationCommand.java
> +            names = {"--res_path" },
Same

2022-05-24 08:28 UTC, flomonster commented on core/src/main/java/fr/sncf/osrd/cli/StandaloneSimulationCommand.java
> +            }
It seems like you're doing this to get a list of `RJSRoutePath` corresponding to `RJSRoute`. This doesn't make sense.

2022-05-24 08:28 UTC, flomonster commented on core/src/main/java/fr/sncf/osrd/cli/StandaloneSimulationCommand.java
> +                for (RJSTrainSchedule sched : sim.trainSchedules) {
Why iterate twice on train schedule?

2022-05-24 08:28 UTC, flomonster commented on core/src/main/java/fr/sncf/osrd/cli/StandaloneSimulationCommand.java
> +            StringBuilder finalResult = new StringBuilder("{ \"results\": [ ");
You shouldn't build a json manualy. We're using a library named `Moshi` to do this work for you.

2022-06-02 12:30 UTC, flomonster requested changes

2022-06-02 12:30 UTC, flomonster commented on core/examples/generated/generate2.py
> +#!/usr/bin/env python3
I think this file was added by error

2022-06-02 12:30 UTC, flomonster commented on core/examples/generated/my_scripts/RL_test.py
> +#!/usr/bin/env python3
I think you added the folder `my_script` by error.

2022-06-02 12:30 UTC, flomonster commented on core/examples/generated/scripts/tiny_tiny_infra.py
> +#!/usr/bin/env python3
Added by error ?

2022-06-02 12:30 UTC, flomonster commented on core/examples/generated/tiny_tiny_infra.py
> +#!/usr/bin/env python3
Duplicate of `core/examples/generated/scripts/tiny_tiny_infra.py`

2022-06-02 12:30 UTC, flomonster commented on core/src/main/java/fr/sncf/osrd/cli/StandaloneSimulationCommand.java
> +            var sim = RJSSimulation.adapter.fromJson(simFile);
```suggestion
            var rjsSimulation = RJSSimulation.adapter.fromJson(simFile);
```

2022-06-02 12:30 UTC, flomonster commented on core/src/main/java/fr/sncf/osrd/cli/StandaloneSimulationCommand.java
> +            assert sim != null;
You can check that `sim` is not null directly after serializing it.
If it's null you should throw an exception instead of an `AssertError`.

2022-06-02 12:30 UTC, flomonster commented on core/src/main/java/fr/sncf/osrd/cli/StandaloneSimulationCommand.java
> +            for (RJSTrainSchedule sched : sim.trainSchedules) {
```suggestion
            for (RJSTrainSchedule schedule : sim.trainSchedules) {
```

2022-06-02 12:30 UTC, flomonster commented on core/src/main/java/fr/sncf/osrd/cli/StandaloneSimulationCommand.java
> +                );
You can probably oneline this.

2022-06-02 12:30 UTC, flomonster commented on core/src/main/java/fr/sncf/osrd/standalone_sim/result/StandaloneSimResultAllTrains.java
> +public class StandaloneSimResultAllTrains {
You don't really need this class. You can create an adapter which is a simple list of StandaloneSimResultAllTrains

2022-06-02 12:37 UTC, estia-m commented on core/examples/generated/my_scripts/RL_test.py
> +#!/usr/bin/env python3
Yes, that's right!

2022-06-02 14:44 UTC, flomonster submitted a review, later dismissed

2022-06-02 15:10 UTC, flomonster approved these changes

2022-06-02 15:17 UTC, merged