front: fix train selection in the anterior or posterior train list
OpenRailAssociation/osrd pull request #10154
Opened 2024-12-20 11:01 UTC by theocrsb

closes #10133

2025-01-02 16:30 UTC, clarani requested changes
Actually, the issue is not in this function, it's because we should not receive a string if we're expecting a date.

I let you search a bit, the problem comes from the action `updateLinkedTrainExtremity` :wink:

2025-01-03 13:15 UTC, clarani commented on front/src/applications/stdcm/utils/computeOpSchedules.ts
> +      isoArrivalTime: new Date(subtractDurationFromDate(startTime, 1800)),
`subtractDurationFromDate` already returns a date, so you just need to remove the toISOString()
```suggestion
      isoArrivalTime: subtractDurationFromDate(startTime, 1800),
```

2025-01-03 13:15 UTC, clarani commented on front/src/applications/stdcm/types.ts
> +  isoArrivalTime: Date;
Can you rename the field here ? Maybe arrivalDate ?

2025-01-04 09:22 UTC, theocrsb commented on front/src/applications/stdcm/types.ts
> +  isoArrivalTime: Date;
Done

2025-01-04 09:22 UTC, theocrsb commented on front/src/applications/stdcm/utils/computeOpSchedules.ts
> +      isoArrivalTime: new Date(subtractDurationFromDate(startTime, 1800)),
Done

2025-01-06 09:50 UTC, clarani approved these changes
LGTM :white_check_mark:

2025-01-06 12:47 UTC, Akctarus approved these changes
tested, LGTM :)

2025-01-06 16:26 UTC, merged