front: fix sass deprecation warnings
OpenRailAssociation/osrd pull request #10165
Opened 2024-12-23 09:26 UTC by emersion

Fixes the following two warnings:

    DEPRECATION WARNING: Sass @import rules are deprecated and will be removed in Dart Sass 3.0.0.
    DEPRECATION WARNING: Global built-in functions are deprecated and will be removed in Dart Sass 3.0.0.

The migration was performed using the following command:

    sass-migrator module --migrate-deps src/styles/styles.scss

And then removing a duplicate `@import 'map/popup'`, which was causing an error when migrated to `@use`.

See https://sass-lang.com/documentation/breaking-changes/import/

To test: restart the front container and look for any sass-related warnings.

2024-12-23 11:36 UTC, theocrsb approved these changes

2024-12-24 13:47 UTC, clarani requested changes
I restart the docker container, but I still have css issues :/ 

![image](https://github.com/user-attachments/assets/afb5d4b5-8690-4488-817f-9732e6239ec2)

2025-01-03 09:14 UTC, emersion commented
For some reason the migration script left behind some `@import` rules, now fixed:
https://github.com/OpenRailAssociation/osrd/compare/e98de7e94f0d03babe0a1db00ff5148b9569f108..6d8d56d9068fc735b1991676de3fdd93d710e823

2025-01-07 11:35 UTC, clarani approved these changes

2025-01-07 12:06 UTC, merged