core, editoast, python: stop train on next signal instead of OP
OpenRailAssociation/osrd pull request #10200
Opened 2024-12-27 13:38 UTC by louisgreiner

Close https://github.com/osrd-project/osrd-confidential/issues/892
Close https://github.com/osrd-project/osrd-confidential/issues/830

2025-01-08 15:49 UTC, louisgreiner commented on editoast/editoast_schemas/src/train_schedule/train_schedule_options.rs
> +    #[derivative(Default(value = "true"))]
```suggestion
    #[derivative(Default(value = "false"))]
```

We keep this flag to false for review purpose, but before merging, we need to set it to `false`

2025-01-08 15:49 UTC, louisgreiner commented on editoast/editoast_schemas/src/train_schedule/train_schedule_options.rs
> +}
```suggestion
```

We keep this flag to `true` for review purpose, but before merging, we need to set it to `false`

2025-01-08 15:50 UTC, louisgreiner commented on front/src/applications/operationalStudies/hooks/useSetupItineraryForTrainUpdate.ts
> +          stop_at_next_signal: true, // TODO: change to false and set to true elsewhere if needed
```suggestion
          stop_at_next_signal: false,
```

We keep this flag to `true` for review purpose, but before merging, we need to set it to `false`

2025-01-08 15:50 UTC, louisgreiner commented on front/src/modules/pathfinding/utils.ts
> +        stop_at_next_signal: true, // TODO: change to false and set to true elsewhere if needed
```suggestion
        stop_at_next_signal: false,
```

We keep this flag to `true` for review purpose, but before merging, we need to set it to `false`

2025-01-08 15:55 UTC, louisgreiner reviewed
We keep this flag to `true` for review purpose, but before merging, we need to set it to `false`

2025-01-08 15:55 UTC, louisgreiner commented on editoast/editoast_schemas/src/train_schedule/train_schedule_options.rs
> +    #[serde(default = "default_stop_at_next_signal")]
```suggestion
    #[derivative(Default(value = "false"))]
```

2025-01-08 15:55 UTC, louisgreiner commented on editoast/editoast_schemas/src/train_schedule/train_schedule_options.rs
> +}
```suggestion
```

2025-01-08 15:55 UTC, louisgreiner commented on front/src/applications/operationalStudies/hooks/useSetupItineraryForTrainUpdate.ts
> +          stop_at_next_signal: true, // TODO: change to false and set to true elsewhere if needed
```suggestion
          stop_at_next_signal: false,
```

2025-01-08 15:55 UTC, louisgreiner commented on front/src/modules/pathfinding/utils.ts
> +        stop_at_next_signal: true, // TODO: change to false and set to true elsewhere if needed
```suggestion
        stop_at_next_signal: false,
```

2025-01-08 16:16 UTC, louisgreiner commented
Questions : 
- Currently it moves all the waypoints of the train schedules instead of only the stops ; is it a real problem ?

2025-01-09 09:44 UTC, eckter reviewed
That's the right approach, good job :+1:

2025-01-09 09:44 UTC, eckter commented on core/src/main/kotlin/fr/sncf/osrd/api/api_v2/pathfinding/PathfindingBlocksEndpointV2.kt
> +            blockOffset.distance
That `if` feels wrong, if the train starts at the beginning of the block, then we don't use the next signal offset?

2025-01-09 10:00 UTC, louisgreiner commented on core/src/main/kotlin/fr/sncf/osrd/api/api_v2/pathfinding/PathfindingBlocksEndpointV2.kt
> +            blockOffset.distance
I do not like this also, but I couldn't manage otherwise to deal with that later in the code, if the train stops **exactly** on one of a border of the block (either `start` or `end` if block is `[start ; end]`), I then don't know how it will react.
That's why I introduced a magic value (1m) to make sure this will not happen.

Do you have any better solution ? Or insight

2025-01-09 10:10 UTC, eckter commented on core/src/main/kotlin/fr/sncf/osrd/api/api_v2/pathfinding/PathfindingBlocksEndpointV2.kt
> +            blockOffset.distance
I don't think we should really handle it in any specific way.

When the point is exactly at the end of a block, there's not much we can do anyway to move it further. It's supposed to be near a signal or buffer stop anyway. 

When it's at the beginning of a block, we can handle it normally by moving it forward using the same rules.

2025-01-15 10:39 UTC, louisgreiner commented
Question : is the type of signalisation (here `TVM` instead of `BAL`) could affect the behaviour of the code ? 

![image](https://github.com/user-attachments/assets/ee148e0e-76d5-4c65-892e-16e1f87e2785)

Because here, the waypoint is moved AFTER the signal, which is not correct (but I only see that behaviour on `TVM` signals)

2025-01-16 14:57 UTC, woshilapin approved these changes
Looks good. I'm just wondering about making it a default option?

2025-01-16 14:57 UTC, woshilapin commented on editoast/editoast_schemas/src/train_schedule/train_schedule_options.rs
> +    #[serde(default = "default_stop_at_next_signal")]
Hmm, I'm curious, but why not keeping `true` as a default value? Seems (naively maybe) like a good default, isn't it?

2025-01-16 16:13 UTC, flomonster requested changes

2025-01-16 16:13 UTC, flomonster commented on editoast/src/views/path/pathfinding.rs
> +                "stop_at_next_signal":false
We can omit this and use the default value.

2025-01-16 16:13 UTC, flomonster commented on editoast/editoast_schemas/src/train_schedule/train_schedule_options.rs
> +    #[serde(default = "default_stop_at_next_signal")]
The current behavior is `false`. If we set the new default behavior to `true` we need to add a migration to this PR. I do prefer to keep the behavior as `false`.

2025-01-16 19:03 UTC, Caracol3 approved these changes
LGTM

2025-01-17 16:21 UTC, clarani commented on front/src/modules/pathfinding/utils.ts
> +        stop_at_next_signal: true, // TODO: change to false and set to true elsewhere if needed
Hmm I think it should be false by default ?

2025-01-17 16:21 UTC, clarani commented on front/src/applications/operationalStudies/hooks/useSetupItineraryForTrainUpdate.ts
> +          stop_at_next_signal: true, // TODO: change to false and set to true elsewhere if needed
Same here

2025-01-17 16:25 UTC, louisgreiner commented on front/src/modules/pathfinding/utils.ts
> +        stop_at_next_signal: true, // TODO: change to false and set to true elsewhere if needed
Indeed, it wrote above a comment about this : I kept it `true` to make it easier to test, but I will update these values at `false` as soon as the tests are done from the reviewers' side

2025-01-27 16:00 UTC, Khoyo commented on core/src/main/kotlin/fr/sncf/osrd/api/api_v2/pathfinding/PathfindingBlocksEndpointV2.kt
> +): Offset<Block> {
This needs some documentation, it's quite unclear why a function called `getNextSignalOffset()` cares about the `rollingStockLength`

2025-01-27 16:00 UTC, Khoyo commented on core/src/main/kotlin/fr/sncf/osrd/api/api_v2/pathfinding/PathfindingBlocksEndpointV2.kt
> + * Returns the block of the signal next to a waypoint block.
This doesn't return a Block

2025-01-27 16:00 UTC, Khoyo commented on core/src/main/kotlin/fr/sncf/osrd/api/api_v2/pathfinding/PathfindingBlocksEndpointV2.kt
> +    val maxHeadOffset = if (blockOffset.distance < 0.01.meters) {
We should probably use `10.millimeters` instead of a floating point approximation. (It should also be a constant instead of a magic number)

2025-01-27 16:00 UTC, Khoyo commented on core/src/main/kotlin/fr/sncf/osrd/api/api_v2/pathfinding/PathfindingBlocksEndpointV2.kt
> +        (nextSignalPosition?.distance ?: blockLength) - 0.01.meters
Ditto

2025-01-27 17:07 UTC, Erashin commented on core/src/main/kotlin/fr/sncf/osrd/api/api_v2/pathfinding/PathfindingBlocksEndpointV2.kt
> +    val maxHeadOffset = if (blockOffset.distance < 0.01.meters) {
It is unclear whether this is still necessary or not. I'm down for a check/quick explanation :)

2025-01-28 15:23 UTC, louisgreiner commented on core/src/main/kotlin/fr/sncf/osrd/api/api_v2/pathfinding/PathfindingBlocksEndpointV2.kt
> +): Offset<Block> {
You're totally right ; I moved and renamed some of this stuff, and also re-wrote the documentation attached. Is that ok that way ?

2025-01-28 15:29 UTC, louisgreiner commented on core/src/main/kotlin/fr/sncf/osrd/api/api_v2/pathfinding/PathfindingBlocksEndpointV2.kt
> + * Returns the block of the signal next to a waypoint block.
I rephrased, in 
```kt
 * @return stop position on the signal next to the waypoint block.
```
But I also could have had been more concise : 

```kt
 * @return the stop position
```

What do you think ?

2025-01-28 15:30 UTC, louisgreiner commented on core/src/main/kotlin/fr/sncf/osrd/api/api_v2/pathfinding/PathfindingBlocksEndpointV2.kt
> +    val maxHeadOffset = if (blockOffset.distance < 0.01.meters) {
It has been removed, since a heavenly fix came meanwhile

2025-02-04 09:29 UTC, flomonster requested changes

2025-02-04 09:29 UTC, flomonster commented on editoast/editoast_schemas/src/train_schedule/train_schedule_options.rs
> +    #[derivative(Default(value = "false"))]
1. Default `bool` is already `false`. Check the doc [here](https://doc.rust-lang.org/std/primitive.bool.html#impl-Default-for-bool).
2. We should indicate to serde that the value can be omitted. 

```suggestion
    #[serde(default)]
```

2025-02-04 14:59 UTC, bougue-pe reviewed
🎉 Nice job (especially with the side-bug messing around)

Just comments on the form, the content is good to me.
Feel free to reject the nitpicks, they're not mandatory IMO and sometimes just a matter of taste.

2025-02-04 14:59 UTC, bougue-pe commented on editoast/src/core/pathfinding.rs
> +    /// If the train should stop on the next signal instead of on the operational point
nit: This could match the comment from editoast's API (which may be rephrased as mentioned in another comment)

2025-02-04 14:59 UTC, bougue-pe commented on core/src/main/kotlin/fr/sncf/osrd/api/api_v2/pathfinding/PathfindingBlocksEndpointV2.kt
> + * @return stop position on the signal next to the waypoint block.
nit: Those can be removed as, to my knowledge, it's not a target to document all inputs/outputs in core, and those don't add information to the existing code or comment above.

2025-02-04 14:59 UTC, bougue-pe commented on core/src/main/kotlin/fr/sncf/osrd/api/api_v2/pathfinding/PathfindingBlocksEndpointV2.kt
> + * rolling stock length.
As:
* waypoint block is not so obvious name
* it does more than just get the position of the next signal
```suggestion
 * Given a waypoint block (initial position of a train stop), returns the new stop position of a train: next signal, with the constraint of staying in the same block and keeping the tail of the train on the initial position.
 * Note that nodes of the infra are not considered.
```

2025-02-04 14:59 UTC, bougue-pe commented on core/src/main/kotlin/fr/sncf/osrd/api/api_v2/pathfinding/PathfindingBlocksEndpointV2.kt
> +    val minTailOffset = waypointBlock.offset.distance + rollingStockLength.meters
It's more of a max limit, no? (applying the min to the 2 max values at the end)
```suggestion
    val maxTailOffset = waypointBlock.offset.distance + rollingStockLength.meters
```

2025-02-04 14:59 UTC, bougue-pe commented on core/src/main/kotlin/fr/sncf/osrd/api/api_v2/pathfinding/PathfindingBlocksEndpointV2.kt
> +    // To ensure that the tail of the rolling stock is not further back than the operational point
nit:
```suggestion
    // To ensure that the tail of the rolling stock is not further back than the operational point (waypointBlock)
```

2025-02-04 14:59 UTC, bougue-pe commented on core/src/main/kotlin/fr/sncf/osrd/api/api_v2/pathfinding/PathfindingBlocksEndpointV2.kt
> +    // If there is no signal after the block, we consider the end of the block as the stop position
```suggestion
    // If there is no signal in the block after the operational point (waypointBlock), we consider the end of the block as the new stop position
```

2025-02-04 14:59 UTC, bougue-pe commented on core/src/test/kotlin/fr/sncf/osrd/pathfinding/PathfindingV2Test.kt
> +        val reverseWaypoints = listOf(waypointsEnd, waypointsIntermediate, waypointsStart)
I'd use `waypoints.reversed()` directly, instead.
(then maybe remove the 3 intermediate lists `waypointsStart`, etc. is a valid option)

2025-02-04 14:59 UTC, bougue-pe commented on core/src/test/kotlin/fr/sncf/osrd/pathfinding/PathfindingV2Test.kt
> +            )
nit: This could be mutualized in a free fn.

2025-02-04 14:59 UTC, bougue-pe commented on core/src/test/kotlin/fr/sncf/osrd/pathfinding/PathfindingV2Test.kt
> +        assertEquals(26500.meters, nonStopAtNextSignalParsed.pathItemPositions[2].distance)
nit: I would use this one also for the reversed case: it tests/explains the control-case.

2025-02-04 14:59 UTC, bougue-pe commented on core/src/test/kotlin/fr/sncf/osrd/pathfinding/PathfindingV2Test.kt
> +        assertEquals(26517.5.meters, longTrainParsed.pathItemPositions[2].distance)
* Is this the only case tested on the signal?
* Should we also test the block-end?

2025-02-04 14:59 UTC, bougue-pe commented on core/src/test/kotlin/fr/sncf/osrd/pathfinding/PathfindingV2Test.kt
> +        assertEquals(12060.meters, shortTrainParsed.pathItemPositions[1].distance)
nit for explicitness:
How about defining before (ditto for other values):
```kt
val shortTrainLength = 10.meters
val initialIntermediateStop = 12050.meters
```
then use `initialIntermediateStop + shortTrainLength`

2025-02-04 14:59 UTC, bougue-pe commented on core/src/test/kotlin/fr/sncf/osrd/pathfinding/PathfindingV2Test.kt
> +                as? PathfindingBlockSuccess)!!
nit: Mutualizing this would be nice too.

2025-02-04 14:59 UTC, bougue-pe commented on core/src/test/kotlin/fr/sncf/osrd/pathfinding/PathfindingV2Test.kt
> +        assertEquals(3, shortTrainParsed.pathItemPositions.size)
nit: Also, I would rather have each case separated (one test fn for each, or at least group body+request+assert)

2025-02-04 14:59 UTC, bougue-pe commented on editoast/src/views/path/pathfinding.rs
> +    /// Stops the train at next signal instead of on path item
As it does more than just this (see suggestion of code comment in core), it would be nice to elaborate more in the doc of the API.

2025-02-04 14:59 UTC, bougue-pe commented on python/osrd_schemas/osrd_schemas/train_schedule.py
> +        description="If true, the train will stop at the next signal instead of at the operational point",
Same here, it would be nice to have the same description than editoast's API (and more explicit on what's done).

2025-02-04 15:36 UTC, louisgreiner commented on editoast/editoast_schemas/src/train_schedule/train_schedule_options.rs
> +    #[derivative(Default(value = "false"))]
thanks for the explanation :-)

2025-02-04 15:38 UTC, louisgreiner commented on core/src/main/kotlin/fr/sncf/osrd/api/api_v2/pathfinding/PathfindingBlocksEndpointV2.kt
> + * @return stop position on the signal next to the waypoint block.
removed then, I thought we add documentation to public functions

2025-02-04 15:41 UTC, louisgreiner commented on core/src/main/kotlin/fr/sncf/osrd/api/api_v2/pathfinding/PathfindingBlocksEndpointV2.kt
> +    val minTailOffset = waypointBlock.offset.distance + rollingStockLength.meters
Totally right !! 💯

2025-02-04 16:26 UTC, louisgreiner commented on core/src/test/kotlin/fr/sncf/osrd/pathfinding/PathfindingV2Test.kt
> +        assertEquals(26500.meters, nonStopAtNextSignalParsed.pathItemPositions[2].distance)
Right, added

2025-02-04 16:29 UTC, louisgreiner commented on core/src/test/kotlin/fr/sncf/osrd/pathfinding/PathfindingV2Test.kt
> +        assertEquals(26517.5.meters, longTrainParsed.pathItemPositions[2].distance)
Using small infra, it's hard to test more hazardous cases :/

2025-02-04 17:16 UTC, louisgreiner commented on core/src/test/kotlin/fr/sncf/osrd/pathfinding/PathfindingV2Test.kt
> +        assertEquals(3, shortTrainParsed.pathItemPositions.size)
Done, is it conform to what you expected ?

2025-02-05 10:29 UTC, bougue-pe commented on core/src/test/kotlin/fr/sncf/osrd/pathfinding/PathfindingV2Test.kt
> +        assertEquals(3, shortTrainParsed.pathItemPositions.size)
Yes, thank you very much!

2025-02-05 10:31 UTC, bougue-pe commented on core/src/test/kotlin/fr/sncf/osrd/pathfinding/PathfindingV2Test.kt
> +        assertEquals(26517.5.meters, longTrainParsed.pathItemPositions[2].distance)
As discussed:
* this does test the signal case indeed.
* we should add a test on the "end-of-block" case, and the easiest is to use a very long (600m) train on the reverse case and check that it stops after 500m (buffer-stop of TA1)

2025-02-05 12:51 UTC, bougue-pe approved these changes
Thanks!

2025-02-07 10:31 UTC, bougue-pe commented on front/tests/assets/trainSchedule/train_schedules.json
> +    "options": { "use_electrical_profiles": true, "stop_at_next_signal": false }
From previous value, it looks like a bad copy-paste:
```suggestion
    "options": { "use_electrical_profiles": false, "stop_at_next_signal": false }
```

2025-02-07 10:31 UTC, bougue-pe commented on front/tests/assets/trainSchedule/train_schedules.json
> +    "options": { "use_electrical_profiles": true, "stop_at_next_signal": false }
```suggestion
    "options": { "use_electrical_profiles": false, "stop_at_next_signal": false }
```

2025-02-07 10:31 UTC, bougue-pe commented on front/tests/assets/trainSchedule/train_schedules.json
> +    "options": { "use_electrical_profiles": true, "stop_at_next_signal": false }
```suggestion
    "options": { "use_electrical_profiles": false, "stop_at_next_signal": false }
```

2025-02-07 10:31 UTC, bougue-pe commented on front/tests/assets/trainSchedule/train_schedules.json
> +    "options": { "use_electrical_profiles": true, "stop_at_next_signal": false }
```suggestion
    "options": { "use_electrical_profiles": false, "stop_at_next_signal": false }
```

2025-02-07 11:00 UTC, louisgreiner commented on front/tests/assets/trainSchedule/train_schedules.json
> +    "options": { "use_electrical_profiles": true, "stop_at_next_signal": false }
oops, thanks for the spot 🎯

2025-02-07 16:21 UTC, louisgreiner commented
## Feature not ready for STDCM simulation

Last commit `core: add feature flag to disable feature for stdcm` is meant to disable the feature for the simulated trains of STDCM. 

The issue is that, after having moved the waypoints, we can't match the new track positions with actual operational points. Then, the output tables can't match the stops information of the newly moved waypoints with actual operational points.

Example what we should get versus what we get with the feature:
![Capture d'écran 2025-02-07 110951](https://github.com/user-attachments/assets/f2e79184-ad85-4d80-ad5f-7b159ac56ebd)
![Capture d'écran 2025-02-07 111552](https://github.com/user-attachments/assets/ba0d3374-b16a-48d3-9141-96d2e51f2ed4)

However, it is still not an ideal trade-off, because with the feature disabled for STDCM only, if we want to debug the STDCM timetables, we still face this issue on the Operational Studies module.

Example, the stop information has disapeared from the output table, because, and we see it, the waypoint has moved:
![Capture d'écran 2025-02-07 165731](https://github.com/user-attachments/assets/790febfc-934c-4bf6-990a-cbf9b2c121e4)
![Capture d'écran 2025-02-07 165744](https://github.com/user-attachments/assets/0d537511-6e45-4772-b10f-cedbd7404dea)
![Capture d'écran 2025-02-07 165851](https://github.com/user-attachments/assets/3fdbc521-34e3-4691-89ca-abd8e6500176)

### Feature still interesting for filling the STDCM timetable

The feature remains enabled for simulating the trains of the timetable STDCM stands on, thus potentially gaining still a good part of the capacity the feature should provide. But as mentionned above, it breaks the debug functionnality for STDCM timetable for the stops.

With the [current state of code](https://github.com/OpenRailAssociation/osrd/blob/dev/core/src/main/kotlin/fr/sncf/osrd/stdcm/graph/STDCMPostProcessing.kt#L104-L106), it is difficult not to break anything to make the new positions of waypoints match with actual waypoints.

2025-02-14 16:09 UTC, flomonster approved these changes
LGTM for the editoast part, we should add a migration to drop this field (up.sql should be empty).

2025-07-07 23:35 UTC, Synar approved these changes
E2e-tests : LGTM!

2025-07-22 16:55 UTC, louisgreiner commented
Thanks to @Synar [PR](https://github.com/OpenRailAssociation/osrd/pull/12474) that fixes the issue on the operational studies output table (the moved stops were not displayed in the output table, when debugging an STDCM timetable), this PR will soon come to its end 🤞 

We need to wait that the above PR is merged, then final review can be done. I also fixed some tests to make sure that only the intermediate stops are moved close to the following signal (and not the start nor the last stop).

2025-08-06 14:24 UTC, louisgreiner commented
Dear reviewers, this PR is finally working 🎉 Because the PR is old, it might be necessary to review it once again.

Quick recap:
- this PR enables to move the stops of a pathfinding closer to the signal next to the requested stop
  - ⚠️ **the first and last stops are not moved** ⚠️
- the feature is enabled for STDCM (for all the trains simulated in the stdcm search environment AND for the simulated train)
- the feature is disabled for Operational Studies (trains created from this module cannot enable the feature, however imported trains that have the feature enabled (such as BASIC timetables) can be looked at in this module)
- [osrd-data associated MR](https://gitlab-repo-res.apps.eul.sncf.fr/dsir/groupedxs-dsir/04735/osrd-data/-/merge_requests/8)

To test this PR:
- either import this timetable in the Operational Studies module (you can first look at the stops on the map that they are indeed moved, train `"870004"` that stops at `"Gragnague"`, [timetable_chenille.json](https://github.com/user-attachments/files/21599681/timetable_chenille.json)), use this scenario as STDCM search environment (debug mode) and simulate trains in STDCM
- either locally import a BASIC timetable and run STDCM on it (also take a look at this timetable in OP module)

Questions: 
- should I do something about the [API changes automatic comment](https://github.com/OpenRailAssociation/osrd/pull/10200#issuecomment-3153925166)?
- ETCS simulations are missing in this PR, should it be part of it?

2025-08-07 08:19 UTC, Khoyo commented
> should I do something about the [API changes automatic comment](https://github.com/OpenRailAssociation/osrd/pull/10200#issuecomment-3153925166)?

You already did by opening the `osrd-data` MR. AFAIK, it's the only consumer project of editoast's API that we know of ;)

> ETCS simulations are missing in this PR, should it be part of it?

For now, ETCS is not supported in STDCM - but I don't see what ETCS (with fixed blocks) would have to do with this?

2025-08-08 12:56 UTC, eckter approved these changes
Some small comments, but for the most part, LGTM

2025-08-08 12:56 UTC, eckter commented on core/src/main/kotlin/fr/sncf/osrd/api/pathfinding/PathfindingBlocksEndpoint.kt
> +        findNextSignalPositionFromBlockOffset(infra, waypointBlock.edge, waypointBlock.offset)
I don't think we need to bother with that. Only block-delimiting signals are relevant here (no point in stopping at a BAPR announcer signal). And block delimiting signals, well, they delimit blocks, can't move past one without changing block.

2025-08-08 12:56 UTC, eckter commented on core/src/main/kotlin/fr/sncf/osrd/api/pathfinding/PathfindingBlocksEndpoint.kt
> +    return PathfindingEdgeLocationId(waypointBlock.edge, Offset(min(maxTailOffset, maxHeadOffset)))
We can keep offset types as `Offset<Block>` without too much troubles. You'd need the specific min method here (`Offset.min`), and remove a few `.distance` here and there. (note: `Offset + Distance` is OK and returns an `Offset`)

2025-08-08 12:56 UTC, eckter commented on core/src/main/kotlin/fr/sncf/osrd/api/pathfinding/PathfindingBlockRequest.kt
> +    @Json(name = "stops_at_next_signal") val stopsAtNextSignal: Boolean,
I think I would have preferred if the flag were optional (with default to false), like how it's optional in the editoast API. The behavior with flag enable not that intuitive, while the behavior with no flag is what you'd normally expect. And the usecase is fairly niche. 

Ideally someone could start using the endpoint without having to wonder what that actually does and which value to chose.

2025-08-11 16:04 UTC, louisgreiner commented on core/src/main/kotlin/fr/sncf/osrd/api/pathfinding/PathfindingBlocksEndpoint.kt
> +        findNextSignalPositionFromBlockOffset(infra, waypointBlock.edge, waypointBlock.offset)
Oh yes, I did not thought of this case. Should we then rename the feature (flag and etc.) to precise that we specificly stop at block-delimiting signals only? Like "stops_at_end_of_block" or something similar?

2025-08-12 09:04 UTC, louisgreiner commented on core/src/main/kotlin/fr/sncf/osrd/api/pathfinding/PathfindingBlocksEndpoint.kt
> +        findNextSignalPositionFromBlockOffset(infra, waypointBlock.edge, waypointBlock.offset)
Ok, done

2025-08-12 09:04 UTC, louisgreiner commented on core/src/main/kotlin/fr/sncf/osrd/api/pathfinding/PathfindingBlockRequest.kt
> +    @Json(name = "stops_at_next_signal") val stopsAtNextSignal: Boolean,
I agree, done

2025-08-12 09:15 UTC, louisgreiner commented on core/src/main/kotlin/fr/sncf/osrd/api/pathfinding/PathfindingBlocksEndpoint.kt
> +    return PathfindingEdgeLocationId(waypointBlock.edge, Offset(min(maxTailOffset, maxHeadOffset)))
Nice, done

2025-08-13 10:32 UTC, bougue-pe reviewed
At least testing the case of penultimate "overtaking" the ultimate stop seems important.

I can give a hand around this, NP.

2025-08-13 10:32 UTC, bougue-pe commented on core/src/main/kotlin/fr/sncf/osrd/api/pathfinding/PathfindingBlocksEndpoint.kt
> +                        stepIndex != request.pathItems.size - 1
We could end with a penultimate stop being pushed after the ultimate one, no?

What we could do about it:
* Add a test on a penultimate stop being before the ultimate one and in the same block, ultimate stop being before the end of the block.
* Cap the offset to the initial length of the TravelledPath (if we have it) while finding new stop position, or after when filling `waypoints` (to be applied for STDCM too in that case). It may require passing the positions of the possible last steps to compare if on the same edge?
* I don't think it's necessary to prevent the move before first stop, but if it's easy and clear we can add it.

2025-08-13 10:32 UTC, bougue-pe commented on front/tests/assets/stdcm/linked-train/anterior-linked-train-table.json
> +    "endStop": "13:17",
Just curious: why those 1 min changes?

2025-08-13 10:32 UTC, bougue-pe commented on core/src/test/kotlin/fr/sncf/osrd/pathfinding/PathfindingTest.kt
> +        false,
nit: you may add a new param defaulting to `false`

also nit: you may use this method in your tests (there is a `VERY_SHORT_FAST_TRAIN`, `REALISTIC_FAST_TRAIN` and `VERY_LONG_FAST_TRAIN`)


Please feel very free to dismiss this as the fatigue on this much delayed PR is perfectly understandable.

2025-08-13 10:32 UTC, bougue-pe commented on core/src/test/kotlin/fr/sncf/osrd/pathfinding/PathfindingTest.kt
> +    private fun pathfindingRequest(
It looks like it can now be replaced by `checkPathfindingSuccess()`
The expected length will have to be provided, which is easy to have (may be manually compared to the case of `stopsAtEndOfBlock = false` if not already done for the last stop).

2025-08-13 10:32 UTC, bougue-pe commented on python/osrd_schemas/osrd_schemas/train_schedule.py
> +    stops_at_end_of_block: bool = Field(
Should we change (bump from 0.8.19 to 0.8.20) the version of the Python package in [`osrd_schemas::pyproject.toml`](https://github.com/OpenRailAssociation/osrd/tree/dev/python/osrd_schemas/pyproject.toml#L3) ?
I guess it depends mostly on how we want to handle it in osrd-data.

2025-09-18 10:22 UTC, louisgreiner commented on python/osrd_schemas/osrd_schemas/train_schedule.py
> +    stops_at_end_of_block: bool = Field(
Done

2025-09-18 16:05 UTC, louisgreiner commented on core/src/test/kotlin/fr/sncf/osrd/pathfinding/PathfindingTest.kt
> +        false,
Done

2025-09-18 16:06 UTC, louisgreiner commented on front/tests/assets/stdcm/linked-train/anterior-linked-train-table.json
> +    "endStop": "13:17",
It may be because the previous stop is now closer to this stop? I don't really know

2025-09-18 16:10 UTC, louisgreiner commented on core/src/test/kotlin/fr/sncf/osrd/pathfinding/PathfindingTest.kt
> +    private fun pathfindingRequest(
Done, the long train tests now fail. It outputs something interesting: 
```sh
expected: <[0m, 112050m, 26537.500m, 45900m]> but was: <[0m, 12320m, 26537.500m, 45900m]>
```

The first stop is way further than the next ones (because now the rs length is 100 000m)

It must be fixed

2025-11-20 13:17 UTC, shenriotpro approved these changes

2025-11-20 13:17 UTC, shenriotpro commented on python/osrd_schemas/osrd_schemas/train_schedule.py
> +    - `stops_at_end_of_block` : stops the train at the next block-delimiting signal instead of on the waypoint
nit: use imperative form (ditto for all occurrences)

2025-11-20 13:17 UTC, shenriotpro commented on python/osrd_schemas/osrd_schemas/train_schedule.py
> +        description="If true, the train will stop at a new stop position: near next block-delimiting signal, \
nit: not sure new is the right word, it won't be new for long..

2025-11-20 14:13 UTC, ppitou commented on core/src/main/kotlin/fr/sncf/osrd/api/pathfinding/PathfindingBlocksEndpoint.kt
> +                        stepIndex != request.pathItems.size - 1
@bougue-pe I handled this case and added tests if you could review it again.

2025-11-26 10:23 UTC, Khoyo commented on python/osrd_schemas/osrd_schemas/train_schedule.py
> +        description="If true, the train will stop at a new stop position: near next block-delimiting signal, \
"If true, stop positions will be shifted toward the next block-delimiting signal" ?

2025-11-27 14:32 UTC, bougue-pe commented on python/osrd_schemas/osrd_schemas/train_schedule.py
> +        description="If true, the train will stop at a new stop position: near next block-delimiting signal, \
> "If true, stop positions will be shifted toward the next block-delimiting signal" ?

👍 that (and keeping the details of the second line below) would be nice IMO.

2025-11-27 14:33 UTC, bougue-pe commented on python/osrd_schemas/osrd_schemas/train_schedule.py
> +    stops_at_end_of_block: bool = Field(
It (expectedly) got lost in rebases.

2025-11-27 14:49 UTC, bougue-pe commented on front/tests/assets/stdcm/linked-train/anterior-linked-train-table.json
> +    "endStop": "13:17",
It's now gone, resolving it.

It may have been that the application of safe approach speed around signal matches better the train's braking to a stop 🤷

2025-11-27 14:51 UTC, bougue-pe commented on core/src/test/kotlin/fr/sncf/osrd/pathfinding/PathfindingTest.kt
> +    private fun pathfindingRequest(
Oh, maybe add a check on the sort of offsets would be nice on the way, then?

I let you see if you want to handle it or not, resolving without it is fine by me.

2025-11-27 16:32 UTC, bougue-pe reviewed
The last 3 comments are especially important.

2025-11-27 16:32 UTC, bougue-pe commented on core/src/test/kotlin/fr/sncf/osrd/pathfinding/PathfindingTest.kt
> +        // (270 meters after the first intermediate stop)
nit: you got bitten by spotless (ditto on all the comments of the file) 😿
And my other suggestions might be affected too, of course 😓
```suggestion
        // block (270 meters after the first intermediate stop)
```

2025-11-27 16:32 UTC, bougue-pe commented on core/src/test/kotlin/fr/sncf/osrd/pathfinding/PathfindingTest.kt
> +        // same
Not testing versus the end of the block here, just the destination:
```suggestion
        // distance available is more than the length of the train, so it would be moved by the length of the train (400m)
        // but this is also exactly the destination so the intermediate stop remains the same
```

2025-11-27 16:32 UTC, bougue-pe commented on core/src/test/kotlin/fr/sncf/osrd/pathfinding/PathfindingTest.kt
> +    fun penultimateStopInsideDestinationBlock() {
To me this test is currently a corner case (exact limit) of the next test, and the naming may be misleading.
```suggestion
    fun penultimateStopNotMovedExactlyToDestination() {
```

2025-11-27 16:32 UTC, bougue-pe commented on core/src/test/kotlin/fr/sncf/osrd/pathfinding/PathfindingTest.kt
> +    fun penultimateStopInsideDestinationBlock() {
This may be worth testing that it's correctly moved in the same block, with intermediateWaypoint at 12550 (previous signal is at 12500): i.e. not hitting destination.

----

Then we can also think of a some weird cases:
* intermediate 50m before destination
* destination just at the end of a TrackSection, along with the signal

Then the same (functionnaly speaking, exactly the same), but:
* the destination is right at the start of next TrackSection (signal stays on previous TrackSection).

I guess (not sure) we would end-up with different outputs.
I also guess it's not really an issue to actually push the intermediate to the exact same position of the destination.
(@louisgreiner) If you think it is, we may work on it.

2025-11-27 16:32 UTC, bougue-pe commented on core/src/test/kotlin/fr/sncf/osrd/pathfinding/PathfindingTest.kt
> +        // but the end of the block after the destination so the intermediate stop remains the same
```suggestion
        // distance available is more than the length of the train, so it would be moved by the length of the train,
        // but that is after the destination so the intermediate stop remains the same
```

2025-11-27 16:32 UTC, bougue-pe commented on core/src/test/kotlin/fr/sncf/osrd/pathfinding/PathfindingTest.kt
> +    fun penultimateStopCloseToDestination() {
```suggestion
    fun penultimateStopTooCloseToDestination() {
```

2025-11-27 16:32 UTC, bougue-pe commented on core/src/main/kotlin/fr/sncf/osrd/api/pathfinding/PathfindingBlocksEndpoint.kt
> +                        findWaypointBlocks(infra, destinationTrack, direction).last()
There's a problem here: the pathItems (destination also) can be OP (with multiple OP-parts, on different tracks) and each can be in different blocks (one for each signaling system protecting the range).
So we're only considering the last OP-part of the destination, and the last signaling-system, which may not be the ones actually used as destination.

It looks like:
* we should get all the blocks+offsets of the destination (function without `direction` param)
* then only in the `findStopPositionAtEndOfBlockConsideringRollingStock`, filter on the actual block of the waypoint, keeping only the minimal offset if multiple parts are in the block.

2025-11-27 16:32 UTC, bougue-pe commented on core/src/main/kotlin/fr/sncf/osrd/api/stdcm/STDCMEndpoint.kt
> +                    val destinationBlock = findWaypointBlocks(infra, it.locations).last()
Kind of the same problem here: we're considering (only) the last block-location of the current item (not the destination).

2025-11-27 16:32 UTC, bougue-pe commented on core/src/test/kotlin/fr/sncf/osrd/pathfinding/PathfindingTest.kt
> +}
After the review, should we test also:
* 2 penultimate stops being too close from destination
* destination and penultimate stops having different parts and different signaling systems

?

IMO: "No, it's not worth the hastle" is a valid answer (especially for the second one), but if you think of an easy way to manage it...

2025-12-01 10:19 UTC, bougue-pe reviewed
✅ LGTM: The code logic matches the business logic as I understand it, thanks for the work!

I suspect tests are breaking now with the correction :-/
I can probably peer on fixing tests if needed.

2025-12-01 10:19 UTC, bougue-pe commented on core/src/test/kotlin/fr/sncf/osrd/pathfinding/PathfindingTest.kt
> +        // length of the train, but that is after the destination so the intermediate stop remains the same
```suggestion
        // The intermediate stops are moved to the next block-delimiting signal, but the
        // distance available is more than the length of the train, so it would be moved by the
        // length of the train, but that is after the destination so the intermediate stops remain the same
```

2025-12-01 10:19 UTC, bougue-pe commented on core/src/main/kotlin/fr/sncf/osrd/api/stdcm/STDCMEndpoint.kt
> +fun findWaypointBlocks(
nit: better grouping it next to the other one in `PathfindingBlocksEndpoint.kt` (and if a rename is necessary, I'd go for "find`Directed`WaypointBlocks" for the other function).

2025-12-01 10:19 UTC, bougue-pe commented on core/src/main/kotlin/fr/sncf/osrd/api/pathfinding/PathfindingBlocksEndpoint.kt
> +                    val destinationBlock = findWaypointBlocks(infra, destinationTrack)
nit: this can be moved out of the `forEachIndexed` loop and computed only once.

2025-12-01 10:23 UTC, bougue-pe commented on core/src/test/kotlin/fr/sncf/osrd/pathfinding/PathfindingTest.kt
> +}
✅ OK to resolve IMO (I let it open just in case it acts as a reminder for you)

✔️ Done for the first suggestion of two intermediate stops too close to destination.
✖️ Not done for the multiple parts and multiple signaling systems one (much heavier probably)

2025-12-04 16:20 UTC, ppitou commented on python/osrd_schemas/osrd_schemas/train_schedule.py
> +    - `stops_at_end_of_block` : stops the train at the next block-delimiting signal instead of on the waypoint
Done

2025-12-04 16:20 UTC, ppitou commented on python/osrd_schemas/osrd_schemas/train_schedule.py
> +        description="If true, the train will stop at a new stop position: near next block-delimiting signal, \
Done

2025-12-04 16:21 UTC, ppitou commented on core/src/main/kotlin/fr/sncf/osrd/api/pathfinding/PathfindingBlocksEndpoint.kt
> +                    val destinationBlock = findWaypointBlocks(infra, destinationTrack)
Done

2025-12-04 16:21 UTC, ppitou commented on core/src/main/kotlin/fr/sncf/osrd/api/stdcm/STDCMEndpoint.kt
> +fun findWaypointBlocks(
Done

2025-12-04 16:21 UTC, ppitou commented on core/src/test/kotlin/fr/sncf/osrd/pathfinding/PathfindingTest.kt
> +        // length of the train, but that is after the destination so the intermediate stop remains the same
Done

2025-12-04 16:23 UTC, ppitou commented on core/src/main/kotlin/fr/sncf/osrd/api/pathfinding/PathfindingBlocksEndpoint.kt
> +                        findWaypointBlocks(infra, destinationTrack, direction).last()
Thank you ! Done

2025-12-04 16:23 UTC, ppitou commented on core/src/main/kotlin/fr/sncf/osrd/api/stdcm/STDCMEndpoint.kt
> +                    val destinationBlock = findWaypointBlocks(infra, it.locations).last()
Done

2025-12-04 16:23 UTC, ppitou commented on core/src/test/kotlin/fr/sncf/osrd/pathfinding/PathfindingTest.kt
> +}
Thank you ! :dragon:

2025-12-04 17:54 UTC, bougue-pe approved these changes
LGTM, thanks very much for the work!

There are 2 comments hanging (conveniently 😬 hidden by github's UX):
* https://github.com/OpenRailAssociation/osrd/pull/10200#discussion_r2569079043
* https://github.com/OpenRailAssociation/osrd/pull/10200#discussion_r2272878629

Also gl for the squash and the fix of e2e tests 💪

2025-12-08 13:50 UTC, ppitou commented on python/osrd_schemas/osrd_schemas/train_schedule.py
> +    stops_at_end_of_block: bool = Field(
Done :P

2025-12-08 13:51 UTC, ppitou commented on core/src/test/kotlin/fr/sncf/osrd/pathfinding/PathfindingTest.kt
> +    private fun pathfindingRequest(
Done

2025-12-08 16:33 UTC, bougue-pe commented
It looks like we are only missing a front review (+squash) before merge, no?

[What is the strategy for client repository on this](https://github.com/OpenRailAssociation/osrd/pull/10200#issuecomment-3153925166)? Merging this one in OSRD, and later activate it in client project (data import), I guess?

2025-12-09 08:51 UTC, Khoyo commented
Indeed, since this is a non-breaking change, we can merge it now and the downstream repos can use it at their leisure. For osrd-data, that'll be any point after this hits the deployed dev env.

2025-12-09 11:28 UTC, SharglutDev approved these changes
Lgtm (not tested), good job ! You can close the comment after fixing it.

2025-12-09 11:28 UTC, SharglutDev commented on front/src/common/api/generatedEditoastApi.ts
> +  stops_at_end_of_block?: boolean;
Maybe we could also handle the case in `selectTrainToEdit` function (l.82) in `front/src/reducers/osrdconf/operationalStudiesConf/index.ts`

2025-12-09 13:19 UTC, bougue-pe commented on editoast/openapi.yaml
> +        stops_at_end_of_block:
If I understand correctly, this is optional for pathfinding (and TrainSchedule when storing the information).
And this is now automatic for STDCM, right?

🙏 Can you please edit the main (top) comment of the PR to express that (or correct me if I'm mistaken)?
Not sure if we can document it clearly in STDCM's API, also.

2025-12-09 15:33 UTC, ppitou commented on editoast/openapi.yaml
> +        stops_at_end_of_block:
Is it clearer for the top comment ?

2025-12-09 15:34 UTC, ppitou commented on front/src/common/api/generatedEditoastApi.ts
> +  stops_at_end_of_block?: boolean;
Done

2025-12-09 18:07 UTC, bougue-pe commented on editoast/openapi.yaml
> +        stops_at_end_of_block:
It is already clearer, yes, thanks.

---

For the trains simulated in the stdcm search environment, it depends on what was picked when importing data (like BASIC imports), no? (in practice we are gonna use it, but it's not tied to OSRD, just how we use it)

And I also plan to mention that:
* the feature can't be deactivated (front or back) for STDCM's path output.
* the feature can be switched on/off for pathfinding and train-schedule (operational studies) in the backend, but it can't be activated in the frontend.

If you don't correct me, I'm OK to change a bit more myself.

2025-12-10 14:02 UTC, ppitou commented on editoast/openapi.yaml
> +        stops_at_end_of_block:
Yes it's good for me !

2025-12-11 18:02 UTC, bougue-pe commented on editoast/openapi.yaml
> +        stops_at_end_of_block:
Thanks, done.

2025-12-11 18:09 UTC, Khoyo approved these changes
<img width="350" height="457" alt="Ship it" src="https://github.com/user-attachments/assets/687e888e-02e7-47e4-8b4d-e22d7badab31" />

2025-12-12 10:35 UTC, merged