editoast: endpoints to retrieve stdcm payloads
OpenRailAssociation/osrd pull request #10212
Opened 2024-12-31 15:13 UTC by hamz2a

Part of https://github.com/OpenRailAssociation/osrd/issues/9724 

> [!WARNING]
> We need to wait for this [PR](https://github.com/OpenRailAssociation/osrd/pull/10197) to be merged before merging that one.

2025-01-02 09:47 UTC, SharglutDev commented on front/src/common/api/generatedEditoastApi.ts
> +export type Response =
Looks like the same type as `PostTimetableByIdStdcmApiResponse`, do we need another one ? Or we could reuse this in it with : `export type PostTimetableByIdStdcmApiResponse = Response`.

Also `Request` and `Response` are too vague imo, we could do `StdcmRequest` and `StdcmResponse` ?

2025-01-02 09:47 UTC, SharglutDev commented on front/src/common/api/generatedEditoastApi.ts
> +export type Request = {
Same type as `PostTimetableByIdStdcmApiArg['body']`, we could reuse it inside ?

2025-01-06 16:14 UTC, hamz2a commented on front/src/common/api/generatedEditoastApi.ts
> +export type Response =
We have structures that are quite similar, but some are specific to Core. This is the case for the two I use for the logs.
I have renamed them.

2025-01-06 16:15 UTC, hamz2a commented on front/src/common/api/generatedEditoastApi.ts
> +export type Request = {
Please look at the previous comment.

2025-01-07 10:46 UTC, woshilapin requested changes
Nice work, especially on the tests! I left a few comments.

2025-01-07 10:46 UTC, woshilapin commented on editoast/src/views/test_app.rs
> +    fn with_user(self, user: &UserInfo) -> Self;
nitpick: Why did you change this signature? The intent of the function is to consume the information in order to inject it somewhere (`with_user` means you'll take that `UserInfo` to make something about it, not just read it). I would rather let the caller of this function `.clone()` if it needs the `UserInfo` instance multiple times.

2025-01-07 10:46 UTC, woshilapin commented on front/public/locales/en/errors.json
> +      "NotFound": ""
Is there a reason no message is provided here (same in `fr/errors.json`).

2025-01-07 10:46 UTC, woshilapin commented on editoast/src/views/timetable/stdcm.rs
> +pub mod tests {
How about moving all the needed functions into `fixtures.rs` instead of making `pub` this module and the functions (the pattern seems really weird).

2025-01-07 10:46 UTC, leovalais requested changes

2025-01-07 10:46 UTC, leovalais commented on editoast/src/core/stdcm.rs
> +pub struct StdcmRequest {
The renaming should only occur in the OpenAPI.

2025-01-07 10:46 UTC, leovalais commented on editoast/src/core/stdcm.rs
>  pub struct TemporarySpeedLimit {
Could be inlined instead.

2025-01-07 10:46 UTC, leovalais commented on editoast/src/models/stdcm_log.rs
>      pub trace_id: String,
```suggestion
	#[model(identifier)]
    pub trace_id: String,
```

Allows you to use Model traits by trace id.

2025-01-07 10:46 UTC, leovalais commented on editoast/src/models/stdcm_log.rs
> +    }
`Retrieve` should be used instead, cf. previous comments.

2025-01-07 10:46 UTC, leovalais commented on editoast/src/views/stdcm_logs.rs
> +    #[error("StdcmLog '{trace_id}', could not be found")]
```suggestion
    #[error("STDCM log entry '{trace_id}' could not be found")]
```

2025-01-07 10:46 UTC, leovalais commented on editoast/src/views/stdcm_logs.rs
> +    trace_id: String,
There's no notion of `trace` in the API.

```suggestion
    id: String,
```

2025-01-07 10:46 UTC, leovalais commented on editoast/src/views/stdcm_logs.rs
> +    Path(trace_id): Path<String>,
```suggestion
    Path(StdcmLogTraceIdParam { id: trace_id }): Path<StdcmLogTraceIdParam>,
```

2025-01-07 10:46 UTC, leovalais commented on editoast/src/views/stdcm_logs.rs
> +        (status = 404, body = InternalError, description = "The stdcm log was not found"),
```suggestion
```

2025-01-07 10:46 UTC, leovalais commented on editoast/src/views/stdcm_logs.rs
> +    let authorized = auth
Should be paginated.

2025-01-07 10:46 UTC, leovalais commented on editoast/src/views/timetable/stdcm.rs
> +pub mod tests {
I'd prefer to duplicate the test data instead of sharing them in unrelated contexts. I think locality is important especially for test readability. In case of a schema change we'll rely on the help of the compiler anyways (provided we change the `json!` by a struct initialization).

2025-01-07 10:46 UTC, leovalais commented on front/public/locales/en/errors.json
> +      "NotFound": ""
An error message would be nice

2025-01-07 10:46 UTC, leovalais commented on front/public/locales/fr/errors.json
> +      "NotFound": ""
An error message would be nice

2025-01-07 11:02 UTC, leovalais commented on front/src/common/api/generatedEditoastApi.ts
> +export type Response =
You can remove the `inline` in the stdcm endpoint to `$ref` it.

2025-01-07 13:03 UTC, woshilapin commented on editoast/src/models/stdcm_log.rs
> +    }
Doesn't retrieve forces you consider cases where no response or more than one response is returned? `.first()` does get you only one result or none.

2025-01-07 13:05 UTC, woshilapin commented on editoast/src/views/stdcm_logs.rs
> +    trace_id: String,
Maybe the struct can be renamed too?

2025-01-07 13:12 UTC, leovalais commented on editoast/src/models/stdcm_log.rs
> +    }
The `Retrieve` implementation that's generated includes the `first()`. And you can choose how to handle a missing row. If you expect multiple rows you need to use `RetrieveBatch`.

```rust
pub trait Retrieve<K>: Sized
where
    for<'async_trait> K: Send + 'async_trait,
{
    /// Retrieves the row #`id` and deserializes it as a model instance
    async fn retrieve(conn: &mut DbConnection, id: K) -> Result<Option<Self>>;

    /// Just like [Retrieve::retrieve] but returns `Err(fail())` if the row was not found
    async fn retrieve_or_fail<E, F>(
        conn: &'async_trait mut DbConnection,
        id: K,
        fail: F,
    ) -> Result<Self>
    where
        E: EditoastError,
        F: FnOnce() -> E + Send + 'async_trait,
    {
        match Self::retrieve(conn, id).await {
            Ok(Some(obj)) => Ok(obj),
            Ok(None) => Err(fail().into()),
            Err(e) => Err(e),
        }
    }
}
```

2025-01-07 13:21 UTC, leovalais commented on editoast/src/views/stdcm_logs.rs
> +        (status = 404, body = InternalError, description = "The stdcm log was not found"),
* Only a few endpoints list their errors, so I'd still suggest to remove it, at least for consistency's sake.
* Besides, it's not the only error the endpoint can return (authentication, forbidden access, database-related error, serde, ...). I'd argue that no list is more correct than an incomplete one.
* This part will be reworked (soon hopefully) once the new error system is embarked (which design doc I updated recently, input much appreciated 👀😬)

I don't really mind if the line stays, but it doesn't bring much information imo and `$ref`s a schema that will disappear so :shrug:

2025-01-07 13:35 UTC, leovalais commented on editoast/src/models/stdcm_log.rs
>      pub trace_id: String,
We should checked that the `trace_id` column is actually indexed in DB

2025-01-07 14:24 UTC, hamz2a commented on front/public/locales/en/errors.json
> +      "NotFound": ""
The API will be used directly without going through the frontend, so no message is needed.

2025-01-07 14:24 UTC, hamz2a commented on front/public/locales/en/errors.json
> +      "NotFound": ""
The API will be used directly without going through the frontend, so no message is needed.

2025-01-07 14:24 UTC, hamz2a commented on front/public/locales/fr/errors.json
> +      "NotFound": ""
The API will be used directly without going through the frontend, so no message is needed.

2025-01-07 16:31 UTC, hamz2a commented on editoast/src/views/stdcm_logs.rs
> +        (status = 404, body = InternalError, description = "The stdcm log was not found"),
Done.

2025-01-07 16:32 UTC, hamz2a commented on editoast/src/views/test_app.rs
> +    fn with_user(self, user: &UserInfo) -> Self;
Done.

2025-01-07 16:42 UTC, hamz2a commented on editoast/src/models/stdcm_log.rs
>      pub trace_id: String,
Done.

2025-01-07 16:47 UTC, hamz2a commented on editoast/src/models/stdcm_log.rs
> +    }
The `stdcm_logs` table has `id` and `trace_id`. In this case, I want to search by `trace_id` instead of `id`, but I don't know how to use `retrieve` for this. Can you give me an example, please?

2025-01-07 16:48 UTC, hamz2a commented on editoast/src/views/stdcm_logs.rs
> +    #[error("StdcmLog '{trace_id}', could not be found")]
Done.

2025-01-07 16:51 UTC, hamz2a commented on editoast/src/views/stdcm_logs.rs
> +    trace_id: String,
Maybe I misunderstood the comment, but the purpose of the endpoint is to search by `trace_id`, not by the stdcm_log `id`.

2025-01-07 16:59 UTC, hamz2a commented on editoast/src/views/stdcm_logs.rs
> +    Path(trace_id): Path<String>,
I got this error:
```bash
error[E0277]: the trait bound `fn(axum::extract::State<editoast_models::DbConnectionPoolV2>, axum::Extension<views::Authentication>, axum::extract::Path<views::stdcm_logs::StdcmLogTraceIdParam>) -> impl futures_util::Future<Output = std::result::Result<axum::Json<models::stdcm_log::StdcmLog>, error::InternalError>> {views::stdcm_logs::stdcm_log_by_trace_id}: axum::handler::Handler<_, views::AppState>` is not satisfied
   --> src/views/openapi.rs:202:92
    |
202 |           $crate::views::openapi::make_method_router::<$crate::routes!(@utoipa_type $route), _, _>(
    |                                                                                              ^ the trait `axum::handler::Handler<_, views::AppState>` is not implemented for fn item `fn(State<DbConnectionPoolV2>, ..., ...) -> ... {stdcm_log_by_trace_id}`
    |
   ::: src/views/stdcm_logs.rs:19:1
    |
19  | / crate::routes! {
20  | |     "/stdcm_logs" => {
21  | |         list_stdcm_logs,
22  | |         "/{trace_id}" => {
...   |
25  | |     },
26  | | }
    | |_- in this macro invocation
    |
    = note: the full name for the type has been written to '/Users/home/Desktop/osrd/editoast/target/debug/deps/editoast-5034878a3500a78c.long-type-13579499270931352073.txt'
    = note: consider using `--verbose` to print the full type name to the console
    = note: Consider using `#[axum::debug_handler]` to improve the error message
    = help: the following other types implement trait `axum::handler::Handler<T, S>`:
              `axum::handler::Layered<L, H, T, S>` implements `axum::handler::Handler<T, S>`
              `axum::routing::MethodRouter<S>` implements `axum::handler::Handler<(), S>`
              `axum_extra::handler::IntoHandler<H, T, S>` implements `axum::handler::Handler<T, S>`
              `axum_extra::handler::Or<L, R, Lt, Rt, S>` implements `axum::handler::Handler<(M, Lt, Rt), S>`
```

2025-01-08 10:21 UTC, woshilapin commented on editoast/src/views/stdcm_logs.rs
> +    trace_id: String,
Mmmh, I believe you're right indeed. So maybe it makes sense to expose the notion of "trace" in the API. If I recall correctly, the idea is to detect a problem through our observability stack (OpenTelemetry), and therefore find a trace ID, then ask `editoast` for more information about it (STDCM logs). Do you agree @leovalais? We might be able to resolve that comment and leave the code as is?

2025-01-08 10:24 UTC, woshilapin commented on editoast/src/views/stdcm_logs.rs
> +    Path(trace_id): Path<String>,
You may need to `#[derive(axum::IntoParams)]` on `StdcmLogTraceIdParam`. You can try, as suggested, to add (temporary, only for debugging the problem), the `#[axum::debug_handler]` above the endpoint's function, the compiler might give you a better hint on what the problem is.

2025-01-08 10:42 UTC, hamz2a commented on editoast/src/views/stdcm_logs.rs
> +    Path(trace_id): Path<String>,
It was missing `#[derive(serde::Deserialize)]`, thank you!

2025-01-08 10:46 UTC, hamz2a commented on editoast/src/views/stdcm_logs.rs
> +    Path(trace_id): Path<String>,
Done.

2025-01-08 10:46 UTC, hamz2a commented on editoast/src/views/stdcm_logs.rs
> +    let authorized = auth
Done.

2025-01-08 12:05 UTC, hamz2a commented on editoast/src/core/stdcm.rs
>  pub struct TemporarySpeedLimit {
Done.

2025-01-08 12:05 UTC, hamz2a commented on editoast/src/views/timetable/stdcm.rs
> +pub mod tests {
I created `views::fixtures` to place these functions, not in `models::fixtures`, because they depend on `axum::http::StatusCode` and `views::path::pathfinding::PathfindingResult`.

2025-01-08 12:06 UTC, hamz2a commented on editoast/src/core/stdcm.rs
>  pub struct TemporarySpeedLimit {
Done.

2025-01-08 12:07 UTC, hamz2a commented on editoast/src/core/stdcm.rs
> +pub struct StdcmRequest {
I used `#[schema(inline)]`.

2025-01-08 12:07 UTC, hamz2a commented on editoast/src/views/timetable/stdcm.rs
> +pub mod tests {
I created `views::fixtures` to place these functions, not in `models::fixtures`, because they depend on `axum::http::StatusCode` and `views::path::pathfinding::PathfindingResult`.

2025-01-08 13:34 UTC, woshilapin commented on front/public/locales/en/errors.json
> +      "NotFound": ""
Right, but yet, I'd rather add a message even if never used by the front. My idea is to not cause a later developer that come see this piece of code and ask question around why, and lose some time about this weirdness, what do you think?

2025-01-08 13:36 UTC, woshilapin approved these changes
Thank you for all the improvements, I've resolved most of my comments (only left one opened, feel free to resolve if you fix, if you disagree, either way).

2025-01-08 13:49 UTC, hamz2a commented on front/public/locales/en/errors.json
> +      "NotFound": ""
Done.

2025-01-08 13:50 UTC, hamz2a commented on front/public/locales/en/errors.json
> +      "NotFound": ""
I added the message.

2025-01-08 13:50 UTC, hamz2a commented on front/public/locales/fr/errors.json
> +      "NotFound": ""
I added the message.

2025-01-08 18:27 UTC, leovalais commented on editoast/openapi.yaml
> +          description: The list of Stdcm Logs
```suggestion
          description: The list of STDCM logs
```

2025-01-08 18:27 UTC, leovalais commented on editoast/openapi.yaml
> +          description: The stdcm log
```suggestion
          description: The STDCM log
```

2025-01-08 18:27 UTC, leovalais commented on editoast/src/models/stdcm_log.rs
> +    }
`StcdmLog::retrieve(conn, String::from("trace id"))` should work, lmk if it doesnt

2025-01-08 18:27 UTC, leovalais commented on editoast/src/views/stdcm_logs.rs
> +        .warn_page_size(100)
```suggestion
        .validate(10)?
```

2025-01-08 18:27 UTC, leovalais commented on editoast/src/views/stdcm_logs.rs
> +    trace_id: String,
You're right. These are just IDs when looking just at the API, but since this is the goal workflow let's keep `trace_id`.

2025-01-08 18:27 UTC, leovalais commented on editoast/src/core/stdcm.rs
> +#[derive(Debug, Clone, Serialize, Deserialize, ToSchema)]
I think @SharglutDev wants it to be named `StdcmRequest` and referenced in the OpenApi. This can be done without renaming the strut using utoipa.

2025-01-08 18:27 UTC, leovalais commented on editoast/src/views/stdcm_logs.rs
> +pub enum StdcmLogError {
```suggestion
enum StdcmLogError {
```

2025-01-08 18:27 UTC, leovalais commented on editoast/src/views/stdcm_logs.rs
> +pub struct StdcmLogTraceIdParam {
```suggestion
struct StdcmLogTraceIdParam {
```

2025-01-08 18:28 UTC, leovalais commented on editoast/src/core/stdcm.rs
> +pub struct StdcmRequest {
https://github.com/OpenRailAssociation/osrd/pull/10212#discussion_r1907607694

2025-01-08 18:43 UTC, leovalais commented on editoast/src/views/timetable/stdcm.rs
> +pub mod tests {
I'm not at all against having views fixtures. But since we did not have any discussion involving @woshilapin on this matter, can you at least argue about why you went this way?

2025-01-09 08:38 UTC, hamz2a commented on editoast/openapi.yaml
> +          description: The list of Stdcm Logs
Done.

2025-01-09 08:38 UTC, hamz2a commented on editoast/openapi.yaml
> +          description: The stdcm log
Done.

2025-01-09 08:38 UTC, hamz2a commented on editoast/src/views/stdcm_logs.rs
> +        .warn_page_size(100)
Done.

2025-01-09 08:46 UTC, hamz2a commented on editoast/src/views/stdcm_logs.rs
> +pub enum StdcmLogError {
Done.

2025-01-09 08:46 UTC, hamz2a commented on editoast/src/views/stdcm_logs.rs
> +pub struct StdcmLogTraceIdParam {
Done.

2025-01-09 08:51 UTC, woshilapin commented on editoast/src/core/stdcm.rs
> +#[derive(Debug, Clone, Serialize, Deserialize, ToSchema)]
Something like `#[schema(as = StdcmRequest)]` I believe.

2025-01-09 08:52 UTC, hamz2a commented on editoast/src/core/stdcm.rs
> +#[derive(Debug, Clone, Serialize, Deserialize, ToSchema)]
`StdcmRequest` isn’t used on the front; the main struct is `StdcmLog`. @SharglutDev, would it be okay to inline `StdcmRequest` in `StdcmLog`?

2025-01-09 10:27 UTC, hamz2a commented on editoast/src/views/timetable/stdcm.rs
> +pub mod tests {
We have functions used in two places, so I created a file to centralize them. Normally, such functions go in `models::fixtures`, but since they depend on `axum::http::StatusCode` and `views::path::pathfinding::PathfindingResult`, I placed them in `views::fixtures` to avoid introducing dependencies between models, views, and axum.

2025-01-09 10:28 UTC, hamz2a commented on editoast/src/models/stdcm_log.rs
> +    }
it works, thank you!

2025-01-10 08:43 UTC, SharglutDev commented on front/src/common/api/generatedEditoastApi.ts
> +      | null;
Is it normal that this margin is more specific than the margin in `PostTimetableByIdStdcmApiArg` ?

2025-01-10 08:43 UTC, SharglutDev commented on front/src/common/api/generatedEditoastApi.ts
> +    path_items: PathItem[];
Why not use `PathfindingItem` which is more "stdcm" specific since it also has the duration and timing data ?

2025-01-10 08:43 UTC, SharglutDev commented on editoast/src/core/stdcm.rs
> +#[derive(Debug, Clone, Serialize, Deserialize, ToSchema)]
It isn't used in the front we can manage the type safety by using `PostTimetableByIdStdcmApiResponse` and `PostTimetableByIdStdcmApiArg`. But I just thought it's a shame that we duplicate these 2 types in `postTimetableByIdStdcm` args and response and in this new `StdcmLog`.

2025-01-10 08:59 UTC, SharglutDev commented on front/src/common/api/generatedEditoastApi.ts
> +export type StdcmLog = {
If I understand correctly, this type differs from the one we use in `postTimetableByIdStdcm` because these are the datas editoast sends to core and they might differ from the. one we use in the front.
If that's the case, would it be possible to add a comment/doc on this type to explain that because most of the front devs don't now this and might think it's strange.

2025-01-10 08:59 UTC, SharglutDev commented on front/src/common/api/generatedEditoastApi.ts
> +    path_items: PathItem[];
It contains information about the tolerance, the time arrival, the stop duration. Don't the log should give us these informations ?

2025-01-10 09:25 UTC, woshilapin commented on editoast/src/views/timetable/stdcm.rs
> +pub mod tests {
I'm fine with your proposition @hamz2a

2025-01-10 10:19 UTC, hamz2a commented on front/src/common/api/generatedEditoastApi.ts
> +export type StdcmLog = {
`StdcmLog` represents the data sent to and received from the `core` system. This format may differ from the one used in the frontend (like in `postTimetableByIdStdcm`), as it is specifically designed for communication with the `core` system. It may include extra fields, different formatting, or structures that aren't needed in the frontend.

Unfortunately, I can't add this comment to the frontend file.

2025-01-10 10:19 UTC, hamz2a commented on front/src/common/api/generatedEditoastApi.ts
> +    path_items: PathItem[];
https://github.com/OpenRailAssociation/osrd/pull/10212#discussion_r1910152922

2025-01-10 10:19 UTC, hamz2a commented on front/src/common/api/generatedEditoastApi.ts
> +      | null;
https://github.com/OpenRailAssociation/osrd/pull/10212#discussion_r1910152922

2025-01-10 10:20 UTC, hamz2a commented on editoast/src/core/stdcm.rs
> +#[derive(Debug, Clone, Serialize, Deserialize, ToSchema)]
https://github.com/OpenRailAssociation/osrd/pull/10212#discussion_r1910152922

2025-01-10 10:58 UTC, leovalais commented on editoast/src/views/stdcm_logs.rs
> +            }))
Can the struct representing the response be used instead (avoids `to_value` + type system)?

2025-01-10 10:58 UTC, leovalais commented on editoast/src/views/fixtures.rs
> +pub fn core_mocking_client() -> MockingClient {
The name isn't specific enough

2025-01-10 10:58 UTC, leovalais commented on editoast/src/views/fixtures.rs
> +        .json(serde_json::to_value(simulation_response()).unwrap())
```suggestion
        .json(simulation_response())
```

should work?

2025-01-10 11:05 UTC, hamz2a commented on editoast/src/views/fixtures.rs
> +        .json(serde_json::to_value(simulation_response()).unwrap())
Done.

2025-01-10 11:05 UTC, hamz2a commented on editoast/src/views/fixtures.rs
> +pub fn core_mocking_client() -> MockingClient {
`init_core_mocking_client` ?

2025-01-10 11:29 UTC, leovalais commented on editoast/src/views/timetable/stdcm.rs
> +pub mod tests {
I not really satisfied with view fixtures (*here, not in general*) for two reasons (mainly):

1. Locality is important. For example, when the functions of `views::fixtures` were in `views::stdcm`, I believe things were much easier to read and explicit. Take `fn core_mocking_client() -> MockingClient`, by not being `pub`, we know it's only used in the tests module. So we immediately understand that it returns a configured mocking client for STDCM. Now that it's in a shared context (`fixtures`), it becomes named incorrectly (not specific enough), and because of it's `pub` visibility, we don't know to which extent it's used without searching for all it's references. Additionally, since they're not localized to a single `mod tests`, we don't know which fixtures are related: here `pathfinding_...` and `simulation_response` are tied together to form a basis for a STDCM call. When they were just local `fn`s, it was easy to figure that out, but know they all live freely in a shared context, that's not so obvious. I don't think we should have fixtures that are not self-contained. 
3. Before the test refactoring a year ago, we had an `src/fixtures.rs` file centralizing all shared or atomic test data. Theoretically it works, but in practice, apart from infras and rolling stocks, it was mostly a pain to use. Sharing fixtures was difficult, we often needed to change a value here and there to write a new test, but since these were shared with others, we often ended up duplicating the whole fixture. We had quite a lot of fixtures that were almost identical, but not strictly. Many of them were therefore used in only one or two tests, often in the same `mod tests`, defeating the purpose of fixtures and hindering readability.

Imo fixtures are useful in the following cases:

1. We know the data is general enough and represent a constant well-defined object (`small_infra`, `fast_rolling_stock`, ...)
2. The data is already stored in a different file (`src/tests/*.json`), so since we loose locality, we might as well make it available to every test.

I don't intent to block this PR at all, but I'm not convinced this is the right move yet, sorry.

Wdyt?

2025-01-10 11:29 UTC, leovalais commented on editoast/src/views/fixtures.rs
> +pub fn core_mocking_client() -> MockingClient {
https://github.com/OpenRailAssociation/osrd/pull/10212#discussion_r1910244205

2025-01-10 11:39 UTC, leovalais commented on front/src/common/api/generatedEditoastApi.ts
> +export type StdcmLog = {
Okay, by looking at the OpenAPI, it is wrong. Currently:

* `Request` represents the STDCM **view request**
* `Response` represents the STDCM **core response**
* `StdcmLog` is linked to both of them, so it's wrong

Here's my proposition. **In the OpenAPI only**:

1. inline the view request
2. put the core STDCM responses and requests in `components/schemas` as `StdcmRequest` and `StdcmResponse`
3. `$ref` them in `StdcmLog`

Is everyone ok with that? (plz :+1: and click the notification bell 🔔)

2025-01-10 15:41 UTC, hamz2a commented on editoast/src/views/stdcm_logs.rs
> +            }))
I tried this:
```rust
            .json(crate::core::stdcm::Response::Success {
                simulation: simulation_response(),
                path: pathfinding_result_success(),
                departure_time: DateTime::from_str("2024-01-02T00:00:00Z")
                    .expect("Failed to parse datetime"),
            })
```
i got this error:
```bash
mocked response body should deserialize faultlessly: InternalError { status: 500, error_type: "editoast:coreclient:CoreResponseFormatError", context: {"msg": String("missing field `status` at line 1 column 91")}, message: "Cannot parse Core response: missing field `status` at line 1 column 91" }
```

what you think ? @leovalais

2025-01-10 15:50 UTC, hamz2a commented on editoast/src/views/timetable/stdcm.rs
> +pub mod tests {
I see your point. I wanted to avoid duplicating the code, but I understand it can get tricky later. So, I’m fine with redefining `core_mocking_client`, `pathfinding_result_success`, and `simulation_response`.
What you think @woshilapin ?

2025-01-10 16:18 UTC, hamz2a commented on front/src/common/api/generatedEditoastApi.ts
> +export type StdcmLog = {
https://github.com/OpenRailAssociation/osrd/blob/hai/editoast-endpoint-to-retrieve-stdcm-payloads/editoast/src/models/stdcm_log.rs#L20
`StdcmLog` is linked only to `crate::core::stdcm::Request` and `crate::core::stdcm::Response`

2025-01-10 16:28 UTC, leovalais commented on front/src/common/api/generatedEditoastApi.ts
> +export type StdcmLog = {
Not in the openapi

2025-01-10 16:31 UTC, hamz2a commented on front/src/common/api/generatedEditoastApi.ts
> +export type StdcmLog = {
If I understand correctly, `ToSchema` in this [code](https://github.com/OpenRailAssociation/osrd/blob/hai/editoast-endpoint-to-retrieve-stdcm-payloads/editoast/src/models/stdcm_log.rs#L17) doesn't work.

2025-01-10 16:41 UTC, leovalais commented on editoast/src/views/stdcm_logs.rs
> +            }))
That's weird, it should be identical 🤔 

```rust
#[derive(Serialize, Deserialize, Clone, Debug, PartialEq, ToSchema)]
#[serde(tag = "status", rename_all = "snake_case")]
// We accepted the difference of memory size taken by variants
// Since there is only on success and others are error cases
#[allow(clippy::large_enum_variant)]
pub enum Response {
    Success {
        simulation: SimulationResponse,
        path: PathfindingResultSuccess,
        departure_time: DateTime<Utc>,
    },
    PathNotFound,
    PreprocessingSimulationError {
        error: SimulationResponse,
    },
}
```

Is the response serialized correctly in the stubbed response?

2025-01-10 17:05 UTC, woshilapin commented on editoast/src/views/timetable/stdcm.rs
> +pub mod tests {
@leovalais Thanks for the detail response and I see your point and do agree to a degree. I see 2 solutions (and I'd be fine with both):
- keeping the concept of fixtures, but moving them in a less general module (so, instead of `views`, moving them one level deeper in `views::stdcm` and not `pub` (they should be accessible in sub-modules if you keep them in `views::stdcm` and not `views::stdcm::tests`).
- just keep it simple and copy/paste the functions, we don't get to factorize code but I sometimes see that less as a problem for tests (for reasons @leovalais mentioned, locality and simplicity of code instead of abstractions).

2025-01-10 17:32 UTC, hamz2a commented on editoast/src/views/stdcm_logs.rs
> +            }))
it works now 😂

2025-01-13 09:49 UTC, leovalais commented on front/src/common/api/generatedEditoastApi.ts
> +export type StdcmLog = {
`utoipa` doesn't care which type is used in the rust struct, it only reads the type name to generate the $ref, and the schema `Request` in the OpenAPI describes the view request, not core's one.

2025-01-13 09:59 UTC, leovalais commented on editoast/src/views/timetable/stdcm.rs
> +pub mod tests {
About the first solution: the initial problem was that `pub` was added to the module because of the module tree (we currently have `crate::views::stdcm_logs` and `crate::views::timetable::stdcm`). I would have been fine with the addition of a `pub(in crate::views::stdcm)` if we had that module. I don't see `stdcm_logs` fitting as a submodule of `timetable` though. 🤷

Maybe I can see another solution: we could extend the `CoreClient` to provide an `stdcm_on_small_infra(&mut self, rs_id: i64) -> StdcmFixture`. `StdcmFixture` would gather all information related to the STDCM call and the stubbed core API calls. Thus making the fixture “atomic“. But that's quite a lot of work for just two usages. And we loose locality.

2025-01-13 14:44 UTC, hamz2a commented on editoast/src/views/timetable/stdcm.rs
> +pub mod tests {
As we discussed, I duplicated the code and fixed the schemas.

2025-01-13 14:45 UTC, hamz2a commented on front/src/common/api/generatedEditoastApi.ts
> +export type StdcmLog = {
https://github.com/OpenRailAssociation/osrd/pull/10212#discussion_r1913306144

2025-01-13 14:45 UTC, hamz2a commented on editoast/src/views/fixtures.rs
> +pub fn core_mocking_client() -> MockingClient {
https://github.com/OpenRailAssociation/osrd/pull/10212#discussion_r1913306144

2025-01-13 15:23 UTC, leovalais reviewed
LGTM, thank you for all the changes!

2025-01-13 15:23 UTC, leovalais commented on editoast/src/views/timetable/stdcm/request.rs
I don't think that's necessary to change the visibility here? 🤔

2025-01-13 15:28 UTC, hamz2a commented on editoast/src/views/timetable/stdcm/request.rs
I got this error:
```bash
error[E0603]: struct `PathfindingItem` is private
   --> src/views/stdcm_logs.rs:154:50
    |
154 |     use crate::views::timetable::stdcm::request::PathfindingItem;
    |                                                  ^^^^^^^^^^^^^^^ private struct
    |
note: the struct `PathfindingItem` is defined here
   --> src/views/timetable/stdcm/request.rs:35:1
    |
35  | pub(super) struct PathfindingItem {
```

2025-01-13 16:01 UTC, leovalais commented on editoast/src/views/timetable/stdcm/request.rs
Ha, the tests... Ok nevermind. Maybe we should revise the module tree for stdcm features. We'll see later

2025-01-14 08:17 UTC, SharglutDev approved these changes
Lgtm

2025-01-14 09:12 UTC, leovalais commented
While trying to test the new endpoints I cam across a few bugs 🥲

With authorization disabled: 
![image](https://github.com/user-attachments/assets/93d5100b-f9e2-4625-a73b-d3afce7096b9)

With authorization enabled, the first request works, but its trace id is `00000000....`.
The second request fails:
<img width="772" alt="Capture d’écran 2025-01-14 à 09 59 09" src="https://github.com/user-attachments/assets/cad1e871-75dc-4731-b940-7802bf6e7a2e" />

Steps to reproduce:

1. (I loaded a new DB dump)
2. Authorization enabled
3. Open the frontend
4. Give mock.identity the role Superuser
5. LMR request
6. The log appear on DB with trace-id 00000000000...
7. Another LMR request
8. Contraint violation

2025-01-15 15:20 UTC, woshilapin approved these changes
Really nice and exhaustive suite of tests. Thank you.

2025-01-15 15:20 UTC, woshilapin commented on editoast/src/views/stdcm_logs.rs
> +    async fn prepare_test_context(config: TestContextConfig) -> TestContextOutput {
Not a huge fan of this "function does it all", especially the not so obvious way it creates `App` and returns it. An idea would just be to separate things a bit by having a `init_app` then a `prepare_test_context` (and maybe name it better, something like `execute_stdcm_request`?).

```rust
struct TestContextOutput {
  user: UserInfo,
  trace_id: String,
}
fn init_app(config: &TestContextConfig) -> TestApp {
  /* ... */
}
async fn execute_stdcm_request(app: &TestApp, config: &TestContextConfig) -> TestContextOutput {
  /* ... */
}
#[rstest]
async fn list_stdcm_logs_return_success() {
  let config = TestContextConfig {
    disable_superuser: false,
    enable_authorization: true,
    enable_stdcm_log: true,
    enable_telemetry: true,
  };
  let app = init_app(&config);
  let TestContextOutput {
    user,
    trace_id,
  } = execute_stdcm_request(&app, &config).await;
  /* ... */
}
```

2025-01-15 16:09 UTC, hamz2a commented on editoast/src/views/stdcm_logs.rs
> +    async fn prepare_test_context(config: TestContextConfig) -> TestContextOutput {
Done.

2025-01-16 10:33 UTC, leovalais approved these changes
Thanks a lot for all the changes! I'll test it a bit to make sure I didn't miss anything but things look fine to me :)

2025-01-16 10:33 UTC, leovalais commented on editoast/src/client/runserver.rs
> +    enable_stdcm_log: bool,
nit: would

```suggestion
    enable_stdcm_logging: bool,
```

or

```suggestion
    log_stdcm: bool,
```

be more correct?

2025-01-16 10:33 UTC, leovalais commented on editoast/src/views/stdcm_logs.rs
> +    let stdcm_log = StdcmLog::retrieve_or_fail(conn, Some(trace_id.clone()), || {
```suggestion
    let stdcm_log = StdcmLog::retrieve_or_fail(conn, Some(trace_id), || {
```

2025-01-16 10:41 UTC, hamz2a commented on editoast/src/views/stdcm_logs.rs
> +    let stdcm_log = StdcmLog::retrieve_or_fail(conn, Some(trace_id.clone()), || {
We need to call `clone()`, as `trace_id` is used in the next line.

2025-01-16 10:53 UTC, hamz2a commented on editoast/src/client/runserver.rs
> +    enable_stdcm_log: bool,
Done.

2025-01-16 11:03 UTC, leovalais commented on editoast/src/views/stdcm_logs.rs
> +    let stdcm_log = StdcmLog::retrieve_or_fail(conn, Some(trace_id.clone()), || {
Oh yeah the error I missed it, my bad

2025-01-16 11:33 UTC, leovalais commented
Sorry found a new problem:

```
❯ xh :8090/stdcm_logs x-remote-user-identity:'mock.identity/Example User'
HTTP/1.1 400 Bad Request
Access-Control-Allow-Origin: *
Content-Length: 190
Content-Type: application/json
Date: Thu, 16 Jan 2025 11:31:29 GMT
Vary: origin, access-control-request-method, access-control-request-headers

{
    "status": 400,
    "type": "editoast:pagination:InvalidPageSize",
    "context": {
        "max_page_size": 10,
        "provided_page_size": 25
    },
    "message": "Invalid page size (25), expected an integer 0 < page_size <= 10"
}
```

2025-01-16 11:39 UTC, hamz2a commented
> Sorry found a new problem:
> 
> ```
> ❯ xh :8090/stdcm_logs x-remote-user-identity:'mock.identity/Example User'
> HTTP/1.1 400 Bad Request
> Access-Control-Allow-Origin: *
> Content-Length: 190
> Content-Type: application/json
> Date: Thu, 16 Jan 2025 11:31:29 GMT
> Vary: origin, access-control-request-method, access-control-request-headers
> 
> {
>     "status": 400,
>     "type": "editoast:pagination:InvalidPageSize",
>     "context": {
>         "max_page_size": 10,
>         "provided_page_size": 25
>     },
>     "message": "Invalid page size (25), expected an integer 0 < page_size <= 10"
> }
> ```

The error occurs because the default value for [pagination is 25](https://github.com/OpenRailAssociation/osrd/blob/hai/editoast-endpoint-to-retrieve-stdcm-payloads/editoast/src/views/pagination.rs#L19), but for this endpoint, we've set it to [10 as specified in the pagination validation](https://github.com/OpenRailAssociation/osrd/blob/hai/editoast-endpoint-to-retrieve-stdcm-payloads/editoast/src/views/stdcm_logs.rs#L73).

2025-01-16 16:42 UTC, hamz2a commented
As we discussed, we'll keep the `page_size` at 25, but the endpoint is less verbose, it now returns results like: `[{'id': 1, 'trace_id': 'AZERT'}, {'id': 2, 'trace_id': null}]`.
I've also updated the endpoint to allow access to the logs by`id`.

2025-01-17 10:43 UTC, leovalais approved these changes
Thanks and sorry about all the back and forth! I can see a few things to improve (especially the `/stdcm_log` vs `/stdcm_logS`, these mistakes are hard to find 😨), but that's for another PR if any. Let's merge this :)

2025-01-17 11:44 UTC, merged