New RailScript primitive and RouteStatus for CBTC compatibilty
OpenRailAssociation/osrd pull request #106
Opened 2021-07-06 14:01 UTC by gostreap

The `infra.json` files have been modified to take into account the CBTC in some functions. However, others may need to be modified (`check-route` ?).  This modifications are supposed to be 100% compatible with BAL3.

The `cbtcReserve` function is not used yet and will probably be modified - or even deleted - with the merge of switch-post.

It may also be necessary to modify the class `DependencyBinder` to complete a correct implementation of the `is_incoming_route_cbtc` primitive.

2021-07-09 09:34 UTC, eckter requested changes

2021-07-09 09:34 UTC, eckter commented on examples/circular_infra/infra.json
> +            "aspect": "WHITE_CROSS"
No need for extra indentation (here and elsewhere)

2021-07-09 09:34 UTC, eckter commented on src/main/java/fr/sncf/osrd/infra_state/RouteState.java
>          }
Be careful about this block. It seems those status are only set in this function, so we will always be false. Why is it needed?

2021-07-09 09:34 UTC, eckter commented on src/main/java/fr/sncf/osrd/infra_state/RouteState.java
> +        RouteStatus newStatus = movingSwitchesLeft > 0 ? RouteStatus.CBTC_REQUESTED : RouteStatus.CBTC_RESERVED;
This will set the appropriate requested status, but once the switches have moved you'll get the normal reserved state.

2021-07-09 09:35 UTC, eckter commented
You could look into adding a few unit tests. It's not always easy though, maybe it would be simpler to wait for the complete CBTC implementation for that.

2021-07-12 08:10 UTC, closed without merging

2021-07-12 08:17 UTC, gostreap commented
I will rework this with the new phases and switch-post taking into account @eckter 's comments, then submit a new PR with other new stuff related to CBTC.