Allowances API rework
OpenRailAssociation/osrd pull request #1065
Opened 2022-05-24 14:46 UTC by axrolld

This PR separates construction, mareco, and linear allowance and builds two things :
- RJSAllowance is now either Engineering or Standard
- RJSAllowanceDistribution that is either MARECO or LINEAR

2022-05-31 18:34 UTC, alexandredamiron commented
For @nicolaswurtz rebuild for new allowance logic core/api

2022-06-01 13:37 UTC, flomonster requested changes
A `.DS_Store` file was pushed by error

2022-06-02 13:46 UTC, axrolld commented on core/src/main/java/fr/sncf/osrd/railjson/parser/RJSStandaloneTrainScheduleParser.java
> +            beginPos = engineeringAllowance.beginPosition;
Apparently these lines are not covered by tests, I'll right one to make code coverage work

2022-06-02 13:46 UTC, axrolld commented on front/public/locales/fr/allowances.json
> +    "construction": "Construction",
Probably not my scope to review front but i'm curious : why is there a `"construction": "Construction"` if there is a `"engineering": "Construction"` ?

2022-06-02 13:46 UTC, axrolld commented on front/public/locales/fr/allowances.json
> +    "construction": "Marge modifiée"
I don't quite get this part, I think it is still quite confused between mareco, construction, etc.
For example why is construction corresponding to a modified allowance ?

2022-06-02 17:57 UTC, nicolaswurtz approved these changes, later dismissed

2022-06-03 07:30 UTC, nicolaswurtz submitted a review, later dismissed

2022-06-10 14:27 UTC, flomonster approved these changes

2022-06-10 14:35 UTC, eckter approved these changes

2022-06-13 16:33 UTC, elzinko approved these changes
Big review but good job

2022-06-13 16:33 UTC, elzinko commented on core/src/main/java/fr/sncf/osrd/railjson/schema/schedule/RJSAllowance.java
> +                    .withSubtype(StandardAllowance.class, "standard")
I prefer using constants when using functional strings

2022-06-16 07:37 UTC, elzinko approved these changes

2022-06-17 08:57 UTC, multun approved these changes

2022-06-17 09:07 UTC, nicolaswurtz approved these changes

2022-06-17 09:07 UTC, merged