editoast: add switch type edition
OpenRailAssociation/osrd pull request #1089
Opened 2022-06-07 12:39 UTC by Tguisnet

close #999 
close #1042 
close #1047 
close #1049 
close #1050

2022-06-07 17:05 UTC, flomonster requested changes

2022-06-07 17:05 UTC, flomonster commented on api/osrd_infra/schemas/generated.py
> +class SwitchPortsDoesNotMatchSwitchTypePorts(InfraErrorTrait):
`InvalidSwitchPorts`
`SwitchPortsDoesNotMatch`

2022-06-07 17:05 UTC, flomonster commented on editoast/src/infra_cache.rs
> +        .load::<SwitchTypeQueryable>(conn).expect("Error loading s refwitch types").into_iter().for_each(|switch_type|
typo

2022-06-07 17:05 UTC, flomonster commented on editoast/src/infra_cache.rs
> +            }
```suggestion
            } => switch_types.remove(obj_id).unwrap(),
```

2022-06-07 17:05 UTC, flomonster commented on editoast/src/models/bounding_box.rs
> +    #[allow(unused_variables)]
We can simply add a `_` case that doesn't do anything.

2022-06-07 17:05 UTC, flomonster commented on api/osrd_infra/schemas/generated.py
> +class UnknownPortName(InfraErrorTrait):
Add `port_name`

2022-06-07 17:05 UTC, flomonster commented on api/osrd_infra/schemas/generated.py
> +    error_type: Literal["unused_port"] = Field(default="unused_port")
Add field `port_name`

2022-06-07 17:05 UTC, flomonster commented on api/osrd_infra/schemas/generated.py
> +    error_type: Literal["duplicated_group"] = Field(default="duplicated_group")
Add field `duplicated_group` which is the path to the original group.

2022-06-07 17:05 UTC, flomonster commented on editoast/src/models/errors/switch_types.rs
> +        for port in switch_type.ports.iter() {
Use an iterator with a filter.

2022-06-07 17:05 UTC, flomonster commented on editoast/src/models/errors/switches.rs
> +        let mut match_ports = Vec::new();
- Use an HashSet instead.
- `switch.ports.keys.collect()`

2022-06-10 08:25 UTC, Tguisnet commented on editoast/src/infra_cache.rs
> +            }
I want to return `()`

2022-06-10 08:26 UTC, Tguisnet commented on editoast/src/models/errors/switch_types.rs
> +        for port in switch_type.ports.iter() {
Could I use filter and enumerate ?

2022-06-10 08:39 UTC, flomonster requested changes

2022-06-10 08:39 UTC, flomonster commented on editoast/src/models/errors/switches.rs
> +            .collect();
I don't like the fact that we're doing it for each switch. The best thing to do is to change the railjson schema to have a set instead of a list.

Another solution will be to cache the ports hashset of each switch type before checking switch errors.

2022-06-10 08:39 UTC, flomonster commented on editoast/src/models/errors/switch_types.rs
> +    }
```suggestion
        for (pos, port) in switch_type
            .ports
            .iter()
            .enumerate()
            .filter(|(_, ports)| !used_port.contains(ports))
        {
            let infra_error = InfraError::new_unused_port(format!("ports.{}", pos), port.into());
            errors.push(to_value(infra_error).unwrap());
            switch_type_ids.push(switch_type_id.clone());
        }
```

2022-06-10 09:05 UTC, flomonster commented on editoast/src/models/errors/switch_types.rs
> +        for port in switch_type.ports.iter() {
Yes filter works for any type that implement the trait Iterator.
The trait Enumerator implements automatically the trait Iterator.

2022-06-10 10:01 UTC, flomonster requested changes

2022-06-10 10:01 UTC, flomonster commented on editoast/src/models/errors/switch_types.rs
> +    // warning outside the loop ?
I think that it shouldn't be here

2022-06-10 16:19 UTC, flomonster requested changes

2022-06-10 16:19 UTC, flomonster commented on editoast/src/models/errors/switch_types.rs
> +                if !switch_type.ports.contains(&group.src) {
You can factorize this using a loop on `(group.src, group.dst)`

2022-06-10 16:19 UTC, flomonster commented on editoast/src/models/errors/switch_types.rs
> +            for group in groups {
```suggestion
        for (pos, (group_name, group)) in switch_type.groups.iter().enumerate() {
            for connection in group {
```

2022-06-10 16:19 UTC, flomonster commented on editoast/src/models/errors/switches.rs
> +                .unwrap()
Try to put this in variable:
```rust
let switch_type = infra_cache.switch_types.get(&switch.switch_type).unwrap();
// ...
```

2022-06-10 16:19 UTC, flomonster commented on editoast/src/models/errors/mod.rs
> +    let invalid_switch_types = switch_types::generate_errors(conn, infra, infra_cache)?;
Nope

2022-06-16 13:29 UTC, flomonster approved these changes

2022-06-16 13:50 UTC, merged