api: add default aspect field to signal model
OpenRailAssociation/osrd pull request #1137
Opened 2022-06-10 08:58 UTC by eckter

First step to fix https://github.com/DGEXSolutions/osrd/issues/1111

2022-06-13 15:48 UTC, flomonster requested changes

2022-06-13 15:48 UTC, flomonster commented on api/osrd_infra/schemas/infra.py
> +    default_aspect: str = Field("", description="Aspect displayed when no train is around")
Why did you put a default value?
Is this field optional? In this case you should adapt the type to `Optional[str]`

2022-06-16 07:36 UTC, elzinko submitted a review, later dismissed

2022-06-24 14:50 UTC, flomonster approved these changes

2022-06-24 14:51 UTC, merged