Connect new APIs for the editor
OpenRailAssociation/osrd pull request #1144
Opened 2022-06-13 07:52 UTC by sim51

See #791

* Select an area for the edition
* Create/Read/Update/Delete items in the selection

TBD: the update call the API with the full updated object in the body, instead of an array of modification

2022-06-13 12:15 UTC, flomonster requested changes
Something went wrong when you rebased your branch.
We should only see your commits.

2022-06-13 14:37 UTC, sim51 commented
It should be better now :)
It was due to some commit I picked during the dev to fix some blocking point (like CORS for the API).
I have rewritten my history, so you only have my commits

2022-06-22 07:45 UTC, flomonster approved these changes, later dismissed

2022-07-01 08:00 UTC, jacomyal approved these changes

2022-07-01 08:01 UTC, merged