ci: gitpod integration
OpenRailAssociation/osrd pull request #1184
Opened 2022-06-19 22:28 UTC by elzinko

This feature launchs a remote development environment having all the docker compose stack running for the current branch/commit/pull request.

2022-06-19 22:37 UTC, elzinko commented
@flomonster @alexandredamiron : please, I need some help to check if the api [cors](https://www.gitpod.io/docs/config-ports#cross-origin-resource-sharing-cors) configuration is ok.

2022-06-20 09:07 UTC, flomonster requested changes

2022-06-20 09:07 UTC, flomonster commented on README.md
> +### gitpod way
```suggestion
### Gitpod way
```

2022-06-20 09:07 UTC, flomonster commented on README.md
> +### local way
```suggestion
### Local way
```

2022-06-20 09:07 UTC, flomonster commented on api/config/settings.py
> +CORS_ALLOW_ALL_ORIGINS = True
This is not a good idea to move these settings here because it will be used in production.
We only want to allow all request origins in development environment.

2022-06-20 09:07 UTC, flomonster commented on docker-compose-gitpod.yml
> +  redis_data:
Can you move this at the top of the file to be consistent with other docker compose files.

2022-06-20 09:07 UTC, flomonster commented on front/yarn.lock
> +"@babel/code-frame@^7.0.0", "@babel/code-frame@^7.10.4", "@babel/code-frame@^7.16.0", "@babel/code-frame@^7.16.7", "@babel/code-frame@^7.5.5", "@babel/code-frame@^7.8.3":
Why did bump front dependencies? Can it be done in another PR?

2022-06-20 09:07 UTC, flomonster commented on .gitpod.yml
> +    - formulahendry.docker-extension-pack
I can't find most of these extensions...

Here a list of extensions I'm using to dev on chartos, api and editoast:

Docker:
- ms-azuretools.vscode-docker

Python:
- ms-python.python

Postgres:
- mtxr.sqltools
- mtxr.sqltools-driver-pg

Rust:
- serayuzgur.crates
- rust-lang.rust-analyzer
- hbenl.vscode-test-explorer
- Swellaby.vscode-rust-test-adapter
- ms-vscode.test-adapter-converter
- usernamehw.errorlens

Tools:
- bungcip.better-toml
- oliversturm.fix-json
- redhat.vscode-yaml
- markis.code-coverage
- 42Crunch.vscode-openapi

2022-11-24 22:29 UTC, closed without merging