editoast: add infragraph
OpenRailAssociation/osrd pull request #1191
Opened 2022-06-22 14:37 UTC by Tguisnet

close #1034

2022-06-24 08:11 UTC, flomonster requested changes

2022-06-24 08:11 UTC, flomonster commented on editoast/src/models/errors/track_section_links.rs
> +            .contains_key(&link.dst.track.obj_id)
You can factorize it

2022-06-24 08:11 UTC, flomonster commented on editoast/src/models/errors/graph.rs
> +    }
why not implementing a `new` function to `TrackEndpoint`, `TrackSectionLink`, `SwitchPortConnection`...?

2022-06-24 08:11 UTC, flomonster commented on editoast/src/models/errors/graph.rs
> +        }
You can define the json using `json!` then parse it.

2022-06-24 08:11 UTC, flomonster commented on editoast/src/models/errors/graph.rs
> +        let mut ports = HashMap::default();
You can use `map!` to create and fill the hashmap at the same time

2022-06-24 08:11 UTC, flomonster commented on editoast/src/models/errors/graph.rs
> +    }
```suggestion
    fn create_track_endpoint<T: AsRef<str>>(endpoint: Endpoint, obj_id: T) -> TrackEndpoint {
        TrackEndpoint {
            endpoint,
            track: ObjectRef {
                obj_type: ObjectType::TrackSection,
                obj_id.as_ref().into(),
            },
        }
    }
```

With this implementation you can call this function with `&str` or `String` or `&String`...

2022-06-24 08:11 UTC, flomonster commented on editoast/src/models/errors/graph.rs
> +        }
I don't agree with these tests.

- You should `expect` some branch and no test it. If you can't find a branch in your graph then we have an issue.
- All the endpoints should be tested. You can at least check that the number of neighbors is correct.

2022-06-24 08:11 UTC, flomonster commented on editoast/src/railjson/mod.rs
> +#[derive(Debug, Derivative, Clone, Deserialize, PartialEq, Eq, Hash, Serialize)]
```suggestion
#[derive(Debug, Derivative, Clone, Deserialize, Serialize, PartialEq, Eq, Hash)]
```

2022-07-06 11:22 UTC, Tguisnet commented on editoast/src/models/errors/graph.rs
> +        }
Static Hashmap doesn't exist, maybe use lazy_static ? (overkill ?)

2022-07-06 12:04 UTC, flomonster requested changes

2022-07-06 12:04 UTC, flomonster commented on editoast/src/infra_cache.rs
> +    };*/
dead code

2022-07-06 12:04 UTC, flomonster commented on editoast/src/infra_cache.rs
> +        }
use `hash!`

2022-07-06 12:04 UTC, flomonster commented on editoast/src/models/errors/graph.rs
> +        for (_link_id, link) in infra_cache.track_section_links.iter() {
```suggestion
        for link in infra_cache.track_section_links.values() {
```

2022-07-06 12:04 UTC, flomonster commented on editoast/src/models/errors/graph.rs
> +                crate::railjson::ApplicableDirections::StartToStop => {
Import `railjson::ApplicableDirections`

2022-07-06 12:04 UTC, flomonster commented on editoast/src/models/errors/graph.rs
> +        for (_switch_id, switch) in infra_cache.switches.iter() {
```suggestion
        for switch in infra_cache.switches.values() {
```

2022-07-06 12:04 UTC, flomonster commented on editoast/src/models/errors/graph.rs
> +                            if let Some(dst) = switch.ports.get(&connection.dst) {
use `unwrap()`

2022-07-06 12:04 UTC, flomonster commented on editoast/src/models/errors/graph.rs
> +            if let Some(switch_type) = infra_cache.switch_types.get(&switch.switch_type) {
use `unwrap`

2022-07-06 16:24 UTC, flomonster commented on editoast/src/models/errors/graph.rs
> +        ];
You can use loop instead of having to list all possible endpoints.

2022-07-07 08:00 UTC, flomonster approved these changes, later dismissed

2022-07-07 08:20 UTC, merged