WIP: catenaries and new rolling stock model
OpenRailAssociation/osrd pull request #141
Opened 2021-08-11 12:43 UTC by multun

2021-08-11 13:00 UTC, multun commented on src/main/java/fr/sncf/osrd/railjson/parser/RJSRollingStockParser.java
> +    parseEffortCurves(RJSRollingStock rjsRollingStock) throws InvalidRollingStock {
the method should be called parseEffortCurvesProfiles

2021-08-11 13:00 UTC, multun commented on src/main/java/fr/sncf/osrd/railjson/parser/RJSRollingStockParser.java
> +    }
These two methods should be merged into one: the "electric" or "diesel_battery" names aren't special

2021-08-11 13:00 UTC, multun commented on src/main/java/fr/sncf/osrd/railjson/parser/RJSRollingStockParser.java
> +        Map<String, RJSRollingStock.RJSMode[]> variant = new HashMap<>();
you can just use `var`

2021-08-11 13:00 UTC, multun commented on src/main/java/fr/sncf/osrd/railjson/schema/infra/RJSCatenarySection.java
> +    /** the type of curve to use */
the comment is incorrect: this isn't the type of the curve to use, just the type of the catenary

2021-08-11 13:00 UTC, multun commented on src/main/java/fr/sncf/osrd/railjson/schema/infra/RJSCatenarySection.java
> +
TODO: add the tension / other necessary details

2021-08-11 13:00 UTC, multun commented on src/main/java/fr/sncf/osrd/railjson/schema/rollingstock/RJSRollingStock.java
> +    public RJSVariant variantElectric;
replace with a list of variants, without dedicated fields per variant

2021-08-11 13:00 UTC, multun commented on src/main/java/fr/sncf/osrd/railjson/schema/rollingstock/RJSRollingStock.java
> +        public Double voltage;
please use `double` instead of `Double`

2021-08-11 13:00 UTC, multun commented on src/main/java/fr/sncf/osrd/railjson/schema/rollingstock/RJSRollingStock.java
> +        public double voltage;
this is gone

2021-08-11 13:00 UTC, multun commented on src/main/java/fr/sncf/osrd/railjson/schema/rollingstock/RJSRollingStock.java
> +
effort_curve_profile is missing

2021-09-02 13:03 UTC, multun commented
The comfortAcceleration should be moved to the mode section, as it sometimes varies per mode

2021-09-02 13:11 UTC, multun commented on src/main/java/fr/sncf/osrd/railjson/schema/infra/trackranges/RJSCatenarySectionPart.java
> +public class RJSCatenarySectionPart extends DirectionalRJSTrackRange {
can you rename this to RJSCatenarySection?

2021-09-02 13:11 UTC, multun commented on src/main/java/fr/sncf/osrd/railjson/schema/rollingstock/RJSRollingStock.java
> -    public double gamma;
please rename to brakingDeceleration

2021-09-02 13:11 UTC, multun commented on src/main/java/fr/sncf/osrd/railjson/schema/rollingstock/RJSRollingStock.java
> -    public RollingStock.GammaType gammaType;
please rename to brakingDecelerationType

2021-09-02 13:11 UTC, multun commented on src/test/resources/tiny_infra/simulation.json
> +  ],
this uses the old format, we should convert it to the new one

2021-09-02 13:11 UTC, multun commented on src/test/resources/tiny_infra/simulation_keyboard.json
> +    }
same here

2021-09-02 13:11 UTC, multun commented on src/test/resources/tiny_infra/simulation_several_phases.json
> +    }
same here

2021-09-02 14:07 UTC, multun commented on src/main/java/fr/sncf/osrd/railjson/schema/rollingstock/RJSRollingStock.java
> +    public double startUpAcceleration = Double.NaN;
startup is a single word, written either start-up or startup. as using `-` in field names is bad practice, I'd rather use `start_up_acceleration` for the json and `startupAcceleration` for java, just like before

2021-09-29 14:38 UTC, flomonster requested changes

2021-09-29 14:38 UTC, flomonster commented on src/main/java/fr/sncf/osrd/railjson/schema/rollingstock/RJSRollingStock.java
> +    public int unitsCount = -1;
We could add a description for these fields.

2021-09-29 14:38 UTC, flomonster commented on src/utils/migrate_rolling_stock.py
> +def migrate_v1_to_v2(old):
We could add a version field to `RJSRollingStock` and use it for validation.
We have a similar field for `RJSInfra` but we're not using it yet.

2021-10-01 07:56 UTC, flomonster approved these changes

2021-10-01 08:10 UTC, merged