add stop behavior
OpenRailAssociation/osrd pull request #149
Opened 2021-08-23 09:11 UTC by eckter

Fixes #112 #137 

I still have tests to do

2021-08-26 09:17 UTC, flomonster requested changes

2021-08-26 09:17 UTC, flomonster commented on src/main/java/fr/sncf/osrd/speedcontroller/SpeedController.java
> +    public int linkedStopIndex;
We could create a new class that inherit from SpeedController and have this  additional field.

2021-08-26 16:00 UTC, flomonster requested changes

2021-08-26 16:00 UTC, flomonster commented on src/main/java/fr/sncf/osrd/speedcontroller/StopSpeedController.java
> +        return linkedStopIndex < 0 || currentStopIndex <= linkedStopIndex;
I think this function should return `false` if `linkedStopIndex < 0`. If so, we can simplify:
```java
return currentStopIndex <= linkedStopIndex;
```

2021-08-26 16:07 UTC, eckter commented on src/main/java/fr/sncf/osrd/speedcontroller/StopSpeedController.java
> +        return linkedStopIndex < 0 || currentStopIndex <= linkedStopIndex;
A negative `linkedStopIndex` means that it's unconditional and not linked to a stop, so we should return `true`

2021-08-27 09:52 UTC, flomonster approved these changes

2021-08-27 10:18 UTC, merged