api: idea of a railjson V3
OpenRailAssociation/osrd pull request #1933
Opened 2022-09-20 15:25 UTC by Tguisnet

2022-09-21 08:43 UTC, multun commented
how about that?
```json
{
    "id": "track.42",
    "extensions": {
        "sncf": {"foo": "bar"}
    }
}
```

2022-09-21 10:09 UTC, flomonster commented
It's exactly what we want to achieve here. Metaprog kind of simplified a lot the code.

2022-09-21 12:55 UTC, flomonster requested changes
- Remove `applicable_train_type` (not used in core)
- API could adapt its endpoint to download railjson without extensions
- Rework refs. Could be less flexible.
- Rework signals cosmetic fields  
- Remove `bidirectional` from the SwitchPortConnection
  - The navigability is manged only with routes (needed to be documented)

2022-09-21 12:55 UTC, flomonster commented on api/osrd_infra/schemas/infra.py
>      name: constr(max_length=255) = Field(description="Name of the operational point")
Add it to an extension

2022-09-21 12:55 UTC, flomonster commented on api/osrd_infra/schemas/infra.py
> +    uic: int
Move it to another extension

2022-09-21 12:56 UTC, flomonster commented
New route schema suggestion:

```python
    entry_point: ObjectReference = Field(description="Identifier and type used to define an entry point for the route")
    entry_point_direction: ObjectReference = Field(description="Identifier and type used to define an entry point for the route")
    exit_point: ObjectReference = Field(description="Identifier and type used to define an exit point for the route")
    release_detectors: List[ObjectReference] = Field(
        description="Detector allowing the release of resources reserved from the beginning of the route until this one"
    )
    switches_directions: List[Tuple[ObjectReference, str]]
```

2022-10-04 07:59 UTC, Castavo commented on api/osrd_infra/schemas/infra.py
> +        return DetectorReference(type="Detector", id=self.id)
There must be something Ihave misunderstood, why is it not :
```suggestion
        return BufferStopReference(type="BufferStop", id=self.id)
```

2022-10-04 09:31 UTC, multun commented on api/osrd_infra/schemas/infra.py
> +    responsible_group: str
I think these can be safely removed

2022-10-04 09:41 UTC, multun submitted a review, later dismissed

2022-10-04 10:11 UTC, flomonster requested changes

2022-10-04 10:11 UTC, flomonster commented on api/osrd_infra/schemas/infra.py
> +    This decorator is used to register an extension.
```suggestion
    This decorator is used to easily add an extension to an existing object.
```

2022-10-04 10:11 UTC, flomonster commented on api/osrd_infra/schemas/infra.py
> +    trigram: constr(max_length=3)
We could add description

2022-10-04 10:11 UTC, flomonster commented on core/src/main/java/fr/sncf/osrd/railjson/schema/infra/trackranges/SingleDirectionalRJSTrackRange.java
> +        if (direction == EdgeDirection.START_TO_STOP) return ApplicableDirection.START_TO_STOP;
Weird checkstyle

2022-10-04 10:17 UTC, flomonster commented on api/osrd_infra/schemas/infra.py
> +    responsible_group: str
Done

2022-10-04 10:54 UTC, flomonster approved these changes, later dismissed

2022-10-04 10:59 UTC, flomonster submitted a review, later dismissed

2022-10-04 14:00 UTC, merged