ProjectionAndSingleSTDCM
OpenRailAssociation/osrd pull request #1937
Opened 2022-09-21 16:57 UTC by alexandredamiron

2022-09-21 16:58 UTC, alexandredamiron commented
This will ensure that only one stdcm (last called is shown, that GET use its projection). It also increase the size of the GET in stdcm context

2022-09-23 12:26 UTC, anisometropie requested changes

2022-09-23 12:26 UTC, anisometropie commented on front/src/applications/stdcm/views/StdcmRequestModal.js
> +import { post } from 'common/requests.ts';
.ts to remove

2022-09-23 12:26 UTC, anisometropie commented on front/src/applications/stdcm/views/StdcmRequestModal.js
> +          /*
comment to remove

2022-09-26 08:30 UTC, alexandredamiron commented on front/src/applications/stdcm/views/StdcmRequestModal.js
> +import { post } from 'common/requests.ts';
done

2022-09-26 08:30 UTC, alexandredamiron commented on front/src/applications/stdcm/views/StdcmRequestModal.js
> +          /*
done

2022-09-26 12:07 UTC, anisometropie approved these changes

2022-09-26 12:07 UTC, merged