editoast: split generated errors in different functions
OpenRailAssociation/osrd pull request #2248
Opened 2022-11-02 11:07 UTC by younesschrifi

2022-11-07 19:40 UTC, flomonster requested changes
You shoud rename your commit message

2022-11-07 19:40 UTC, flomonster commented on editoast/src/generated_data/error/buffer_stops.rs
> +    if !infra_cache
You don't need to create a mutable `Vec`. You can return directly either `vec![]` or `vec![/* Your generated error */]` 

This change must be applied everywhere.

2022-11-07 19:40 UTC, flomonster commented on editoast/src/generated_data/error/operational_points.rs
> +) -> Vec<InfraError> {
This is not right. The goal here is to harmonize functions signature. The function should take an operational point and the `InfraCache`.

To put it another way, the loop over operational point parts should be done in this function.

This problem appears elsewhere, thanks for fixing it there too.

2022-11-07 19:40 UTC, flomonster commented on editoast/src/generated_data/error/speed_sections.rs
> +//use crate::generated_data::speed_section;
Dead code

2022-11-07 21:29 UTC, younesschrifi commented on editoast/src/generated_data/error/operational_points.rs
> +) -> Vec<InfraError> {
Thanks for your comment @flomonster . However, in operational_points for example, there are 2 generated_errors in the loop over operational point parts (invalid_ref and out_of_range) should I combine the two functions in one or something else ?

2022-11-07 21:31 UTC, younesschrifi commented on editoast/src/generated_data/error/buffer_stops.rs
> +    if !infra_cache
Thanks for the comment. Should I let it for functions which contain a loop because they return a list of Infra_errors ?

2022-11-09 10:59 UTC, flomonster requested changes

2022-11-09 10:59 UTC, flomonster commented on editoast/src/generated_data/error/routes.rs
> +    vec![]
You can slightly change this:

```rust
if cond {
  vec![InfraError:...]
} else {
  vec![]
}
```

2022-11-09 10:59 UTC, flomonster commented on editoast/src/generated_data/error/routes.rs
> +            skip_continuous_path = true;
Useless variable. You can directly `continue` here.

2022-11-09 10:59 UTC, flomonster commented on editoast/src/generated_data/error/routes.rs
> +            },
We could have a utility function to do that.

2022-11-09 10:59 UTC, flomonster commented on editoast/src/generated_data/error/signals.rs
> +    vec![]
```suggestion
    if !infra_cache.track_sections().contains_key(&signal.track) {
        let obj_ref = ObjectRef::new(ObjectType::TrackSection, signal.track.clone());
        vec![InfraError::new_invalid_reference(signal, "track", obj_ref)]
    } else {
      vec![]
    }
```

You have the problem in several locations.

2022-11-09 10:59 UTC, flomonster commented on editoast/src/generated_data/error/track_section_links.rs
> +//use rocket::form::Errors;
deadcode

2022-11-09 14:40 UTC, flomonster requested changes

2022-11-09 14:40 UTC, flomonster commented on editoast/src/generated_data/error/switches.rs
> +            skip_error = true;
Useless variable

2022-11-10 08:43 UTC, flomonster requested changes

2022-11-10 08:43 UTC, flomonster commented on editoast/src/schema/mod.rs
> +}
You don't need to create trait for that. You can directly `impl Waypoint`.

2022-11-10 09:21 UTC, flomonster approved these changes

2022-11-10 09:28 UTC, merged