Minor bugfixes
OpenRailAssociation/osrd pull request #225
Opened 2021-10-11 15:13 UTC by eckter

Minor bugfixes:

* Fix an issue with deep copies of TrainStates
* Remove a potential infinite loop with margins
* Reflect train deletion in debug viewer
* Fix tvd free when trains disappear
* Add tests

2021-10-12 15:01 UTC, flomonster submitted a review, later dismissed

2021-10-12 15:42 UTC, multun commented on src/main/java/fr/sncf/osrd/infra/TVDSectionPath.java
> +        return Arrays.stream(trackSections).anyMatch(range -> range.containsLocation(location));
I'm thinking there might be a corner case where the range isn't contained by any individual range, but is contained by the union of all ranges

2021-10-12 15:47 UTC, multun commented on src/main/java/fr/sncf/osrd/train/Train.java
> +    }
this seems super fishy to me, we have a queue of actions points waiting for a tail interaction, why can't we just empty this queue and signal all tvdsections the train is gone?

see https://github.com/DGEXSolutions/osrd-core/blob/853d02ff907aabe3ddd003e7a3f6889f0f47e1a5/src/main/java/fr/sncf/osrd/train/TrainState.java#L43

2021-10-12 15:49 UTC, multun requested changes

2021-10-12 15:49 UTC, multun commented on src/main/java/fr/sncf/osrd/train/TrainState.java
> +        var trackLocation = location.trackSectionRanges.getFirst().getEndLocation();
can you add a comment which explains why this check is in place?

2021-10-12 16:00 UTC, eckter commented on src/main/java/fr/sncf/osrd/train/Train.java
> +    }
It's not that simple: the tvd sections are reserved up to the end of the last route, but the train may not go that far.

There's probably a better way to write it but it's not an easy problem.

2021-10-14 15:09 UTC, multun submitted a review, later dismissed

2021-10-14 15:12 UTC, flomonster approved these changes

2021-10-14 15:14 UTC, multun approved these changes

2021-10-14 15:17 UTC, merged