Debug train stop
OpenRailAssociation/osrd pull request #229
Opened 2021-10-12 15:57 UTC by axrolld

I substracted the total duration of TrainStops in the dichotomy process so that the margin don't apply on stop durations.
I also created 3 tests in StopTests to make sure stop are compatible with linear, construction, and mareco margins.

2021-10-12 16:15 UTC, flomonster requested changes

2021-10-12 16:15 UTC, flomonster commented on src/main/java/fr/sncf/osrd/speedcontroller/generators/DichotomyControllerGenerator.java
> +            totalStopsDuration += stop.stopDuration;
This can be move in a method of `TrainSchedule`. Then we can do:
```java
var stopsDuration = schedule.getStopDuration();
```

2021-10-13 08:48 UTC, axrolld commented on src/main/java/fr/sncf/osrd/speedcontroller/generators/DichotomyControllerGenerator.java
> +            totalStopsDuration += stop.stopDuration;
Good idea ! I'll do that.

2021-10-13 09:36 UTC, flomonster submitted a review, later dismissed

2021-10-13 12:54 UTC, flomonster approved these changes

2021-10-13 12:54 UTC, merged