interactive: implement get_train_delays
OpenRailAssociation/osrd pull request #237
Opened 2021-10-13 15:45 UTC by multun

2021-10-13 16:00 UTC, flomonster requested changes
This won't work if we don't have a time table as input

2021-10-13 16:00 UTC, flomonster commented on src/main/java/fr/sncf/osrd/interactive/InteractiveSimulation.java
> +        if (hasUnexpectedState(SessionState.INITIALIZED))
`PAUSE` is also a valid state

2021-10-14 08:40 UTC, eckter submitted a review, later dismissed

2021-10-15 08:32 UTC, flomonster approved these changes, later dismissed

2021-10-15 08:38 UTC, flomonster submitted a review, later dismissed

2021-10-18 11:49 UTC, flomonster approved these changes

2021-10-18 11:51 UTC, merged