make editoast load the infra cache when needed instead of at startup
OpenRailAssociation/osrd pull request #2383
Opened 2022-11-21 14:28 UTC by majaziri

2022-11-21 22:20 UTC, flomonster requested changes

2022-11-21 22:20 UTC, flomonster commented on editoast/src/main.rs
> +}
- This function should be moved to a more proper place.
- You should implement a variant that returns a `WriteGuard` (to be able to get a mutable version of the infra_cache)

--------

Here is a more clean way to implement it.

```rust
/// This function tries to get the infra from the cache, if it fails, it loads it from the database
fn get_or_load_infra_cache<'a>(
    conn: &PgConnection,
    infra_caches: &'a CHashMap<i32, InfraCache>,
    infra_id: i32,
) -> ReadGuard<'a, i32, InfraCache> {
    // Cache hit
    if let Some(infra_cache) = infra_caches.get(&infra_id) {
        return infra_cache;
    }
    // Cache miss
    infra_caches.insert_new(infra_id, InfraCache::load(conn, infra_id));
    infra_caches.get(&infra_id).unwrap()
}
```

2022-11-21 22:20 UTC, flomonster commented on editoast/src/main.rs
> +        let infra_caches: &State<Arc<CHashMap<i32, InfraCache>>>;
None of these variables are initialized

2022-11-21 22:20 UTC, flomonster commented on editoast/src/main.rs
> +        assert!(infra_caches.values().any(|&result| *result == *result));
I'm not sure, what you're trying to achieve here?

2022-11-24 15:15 UTC, younesschrifi approved these changes

2022-11-24 15:15 UTC, flomonster approved these changes

2022-11-24 15:26 UTC, merged