Adn/refacto osrd simulation
OpenRailAssociation/osrd pull request #2387
Opened 2022-11-21 17:39 UTC by alexandredamiron

Base Refacto, test well if main ops ok

2022-11-22 09:15 UTC, anisometropie requested changes

2022-11-22 09:15 UTC, anisometropie commented on front/src/applications/osrd/views/OSRDSimulation/OSRDSimulation.tsx
>    useEffect(() => {
remove 199-212

2022-11-22 13:25 UTC, alexandredamiron commented on front/src/applications/osrd/views/OSRDSimulation/OSRDSimulation.tsx
>    useEffect(() => {
Fait, mais tester le fonctionnel avec attention sur cette PR

2022-11-24 22:05 UTC, nicolaswurtz submitted a review, later dismissed

2022-11-25 15:58 UTC, closed without merging