Implement Runge-Kutta 4
OpenRailAssociation/osrd pull request #249
Opened 2021-10-22 08:28 UTC by axrolld

Implement Runge-Kutta 4 method in OSRD.

2021-10-22 14:49 UTC, bgiuliana commented on src/main/java/fr/sncf/osrd/train/TrainPhysicsIntegrator.java
> +     * @param end end position of the route
typo: end twice

2021-10-22 14:49 UTC, bgiuliana commented on src/main/java/fr/sncf/osrd/train/TrainPhysicsIntegrator.java
> +     * @param directionSign +1 if forward circulation, -1 if backwards
you should update the comments with makeAction

2021-10-22 15:26 UTC, flomonster requested changes
I didn't get all the physics part but the pr seems good.

2021-10-22 15:26 UTC, flomonster commented on src/test/java/fr/sncf/osrd/Helpers.java
> +    private static final boolean saveCSVFiles = true;
This shouldn't be changed...

2021-10-22 15:26 UTC, flomonster commented on src/test/java/fr/sncf/osrd/speedcontroller/MarginTests.java
> +    @ValueSource(ints = {0})
Why reduce the number of tests?

2021-10-22 15:32 UTC, bgiuliana commented on src/test/java/fr/sncf/osrd/train/TrainPhysics.java
>          // how fast would a train go after 10 steps of 1 sec, full throttle on a 45deg slope?
45 deg does not correspond to the line 63?

2021-10-25 11:29 UTC, axrolld commented on src/test/java/fr/sncf/osrd/speedcontroller/MarginTests.java
> +    @ValueSource(ints = {0})
My bad, i did it for debug but forgot to put it back to normal.

2021-10-25 12:02 UTC, bgiuliana commented on src/main/java/fr/sncf/osrd/train/TrainPhysicsIntegrator.java
> +                                                boolean isRKStep, double directionSign) {
comment isRKStep

2021-10-25 12:03 UTC, bgiuliana commented on src/main/java/fr/sncf/osrd/train/TrainPhysicsIntegrator.java
> +        if (!isRKStep && currentSpeed != 0.0
add a comment

2021-10-25 16:17 UTC, axrolld commented on src/test/java/fr/sncf/osrd/Helpers.java
> +    private static final boolean saveCSVFiles = true;
I keep forgetting to set this back to false....

2021-10-25 16:18 UTC, axrolld commented on src/test/java/fr/sncf/osrd/train/TrainPhysics.java
>          // how fast would a train go after 10 steps of 1 sec, full throttle on a 45deg slope?
Yes is does, 45 deg is 1000 %o

2021-10-25 16:20 UTC, axrolld commented on src/main/java/fr/sncf/osrd/train/TrainPhysicsIntegrator.java
> +                                                boolean isRKStep, double directionSign) {
Done

2021-10-25 16:25 UTC, axrolld commented on src/main/java/fr/sncf/osrd/train/TrainPhysicsIntegrator.java
> +        if (!isRKStep && currentSpeed != 0.0
Done

2021-10-26 08:30 UTC, bgiuliana approved these changes

2021-10-26 08:48 UTC, flomonster approved these changes

2021-10-26 08:48 UTC, merged