Fix backward simulations and edge cases
OpenRailAssociation/osrd pull request #252
Opened 2021-10-22 14:48 UTC by eckter

2021-10-26 12:44 UTC, flomonster submitted a review, later dismissed

2021-10-26 12:52 UTC, multun commented on src/main/java/fr/sncf/osrd/speedcontroller/generators/ConstructionAllowanceGenerator.java
> +        return max(speeds.values()) * 1.1;
does this always work?

2021-10-26 12:52 UTC, multun commented on src/main/java/fr/sncf/osrd/train/TrainPath.java
> +            if (edge.edge.id.equals(location.edge.id))
I don't think that's legit

2021-10-26 12:56 UTC, eckter commented on src/main/java/fr/sncf/osrd/speedcontroller/generators/ConstructionAllowanceGenerator.java
> +        return max(speeds.values()) * 1.1;
Not always, but it seems to be for different reasons. The solution is sometimes slightly above the max speed.

2021-10-26 13:00 UTC, multun commented on src/main/java/fr/sncf/osrd/speedcontroller/generators/ConstructionAllowanceGenerator.java
> +        return max(speeds.values()) * 1.1;
is there a meaningful high bound for this? I suspect other weird inputs could make it fail even with this multiplier

2021-10-26 13:04 UTC, axrolld commented on src/main/java/fr/sncf/osrd/speedcontroller/generators/ConstructionAllowanceGenerator.java
> +        return max(speeds.values()) * 1.1;
I agree that it would be good to have a meaningful high estimate that doesn't require an input. I'm available if we want to think about a solution.

2021-10-26 13:05 UTC, eckter commented on src/main/java/fr/sncf/osrd/train/TrainPath.java
> +            if (edge.edge.id.equals(location.edge.id))
It can be outside of the range, which would give a position outside of the [0, path length] range. But that is what I need here, sometimes we have locations that are an epsilon away from the path limit. It's actually not an error case as it's generally used to define ranges.

2021-10-26 13:05 UTC, axrolld commented on src/main/java/fr/sncf/osrd/speedcontroller/generators/ConstructionAllowanceGenerator.java
> +                && location.getPathPosition() > 0. && speed >= 1e-5 && location.getPathPosition() > 1e-5) {
Redundant check on location.getPathPosition(), keep the most constraining one

2021-10-26 13:06 UTC, axrolld commented on src/main/java/fr/sncf/osrd/speedcontroller/generators/SpeedControllerGenerator.java
> +            if (stopIndex < schedule.stops.size() && schedule.stops.get(stopIndex).position - 1e-2 <= k) {
Could this 1e-2 be inside a variable ?

2021-10-26 13:10 UTC, axrolld commented on src/main/java/fr/sncf/osrd/train/TrainPhysicsIntegrator.java
> +        if (abs(newPositionDelta) < 1e-6)
That might trigger infinite calculation on some margin tests with high values like I had when implementing runge-kutta 4. If we wanna keep it, it would make more sense to set this limit inside computePositionDelta and have a variable for the limit of 1e-6

2021-10-26 13:12 UTC, axrolld commented on src/main/java/fr/sncf/osrd/train/TrainPositionTracker.java
> +        while (remainingDist > 1e-10) {
Same here, if this is a limit under which we consider a distance step to be zero, it would make sense that the limit is the same than in TrainPhysicsIntegrator ?

2021-10-26 13:13 UTC, axrolld requested changes
We already discussed some of the points i commented, it's only small changes, otherwise everything seems fine.

2021-10-29 12:30 UTC, flomonster requested changes

2021-10-29 12:30 UTC, flomonster commented on src/main/java/fr/sncf/osrd/speedcontroller/generators/DichotomyControllerGenerator.java
> +    protected static final double dichotomyMargin = 2;
```suggestion
    protected static final double DICHOTOMY_MARGIN = 2;
```

2021-11-02 09:32 UTC, axrolld approved these changes

2021-11-02 12:48 UTC, bgiuliana approved these changes

2021-11-02 12:58 UTC, bgiuliana approved these changes

2021-11-02 13:35 UTC, bgiuliana approved these changes

2021-11-02 14:35 UTC, flomonster approved these changes

2021-11-02 14:36 UTC, merged