dotenv
OpenRailAssociation/osrd pull request #2520
Opened 2022-12-07 17:49 UTC by anisometropie

2023-01-06 09:35 UTC, flomonster requested changes
Great we should also update the docker compose files

2023-01-06 09:35 UTC, flomonster commented on front/launch_dev_front.sh
>  export REACT_APP_EDITOAST_URL=https://gateway.dev.dgexsol.fr/editoast
This file is not used and should be deleted

2023-01-09 14:37 UTC, alexandredamiron commented
front/README.md should be updated, save interns soul

2023-01-09 14:38 UTC, alexandredamiron requested changes
README.md must be updated, save interns soul

2023-01-12 07:25 UTC, flomonster requested changes

2023-01-12 07:25 UTC, flomonster commented on docker-compose.yml
> +        REACT_APP_EDITOAST_URL: "${REACT_APP_EDITOAST_URL:-http://localhost:8090}"
Few things here:
- These variable must be moved to environment
- It's not really useful to get the use var env if it exists
- We can rename them (removing the prefix `REACT_APP_`)

2023-01-17 08:53 UTC, flomonster approved these changes

2023-01-17 10:43 UTC, alexandredamiron approved these changes

2023-01-17 10:43 UTC, merged