editoast: adapt endpoints needed to retrieve infra errors
OpenRailAssociation/osrd pull request #2585
Opened 2022-12-13 10:16 UTC by younesschrifi

close #2583

2022-12-13 10:21 UTC, flomonster commented on editoast/openapi.yaml
> +          name: exclude_errors_or_warnings
It's a bit verbose. We can come with something like: `level`

2022-12-13 10:21 UTC, flomonster commented on editoast/openapi.yaml
> +          name: error_type
```suggestion
          name: type
```

2022-12-13 16:10 UTC, flomonster requested changes

2022-12-13 16:10 UTC, flomonster commented on editoast/src/views/infra/errors.rs
> +        println!("not empty: {}", error_type);
To remove

2022-12-13 16:10 UTC, flomonster commented on editoast/src/views/infra/mod.rs
> +    level: Option<String>,
You should constraint the `String` with an enum instead.

2022-12-13 16:10 UTC, flomonster commented on editoast/src/views/infra/mod.rs
> +    error_type: Option<String>,
Same here

2022-12-13 16:10 UTC, flomonster commented on editoast/src/views/infra/mod.rs
> +    let object_id = object_id.unwrap_or_else(|| "".into());
No need to unwrap values here you can simply pass `Options` to the `get_paginated_infra_errors` function.

2022-12-13 16:10 UTC, flomonster commented on editoast/src/views/infra/errors.rs
> +        .bind::<Text, _>(object_id)
Did you check that it still working even if the `$2` or `$3` is not in the query?

2022-12-13 17:30 UTC, younesschrifi commented on editoast/src/views/infra/errors.rs
> +        .bind::<Text, _>(object_id)
Yes !

2022-12-16 13:08 UTC, flomonster requested changes

2022-12-16 13:08 UTC, flomonster commented on editoast/src/main.rs
> +        .merge(("databases.postgres.timeout", 10))// Timeout needed for MacOS M1 & M2
Is it really usefull ?

```suggestion
        .merge(("databases.postgres.timeout", 10)) // Timeout needed for MacOS M1 & M2 
```

2022-12-16 13:08 UTC, flomonster commented on editoast/src/views/infra/mod.rs
> +    let error_type = error_type.unwrap_or_else(|| "None".into());
It's kind of hacky. You should check the content of error_type only if it's not `None`.

- If `error_type` is not None:
  - If error_type is invalid return an error
- Give an `Option<String>` to `get_paginated_infra_errors` instead of a String.

2022-12-16 13:08 UTC, flomonster commented on editoast/src/views/infra/mod.rs
> +    }
You could use iterator.

2022-12-16 13:08 UTC, flomonster commented on editoast/src/views/infra/mod.rs
> +    }
This should be removed

2022-12-19 16:00 UTC, flomonster submitted a review, later dismissed

2022-12-20 14:20 UTC, flomonster requested changes

2022-12-20 14:20 UTC, flomonster commented on editoast/src/views/infra/mod.rs
> +        let client = Client::tracked(rocket).expect("valid rocket instance");
After the rebase use `create_test_client()`

2022-12-20 15:00 UTC, flomonster approved these changes

2022-12-20 15:00 UTC, merged