Update Rolling_stock model
OpenRailAssociation/osrd pull request #2717
Opened 2022-12-28 15:53 UTC by clarani

Solves #2706

2023-01-04 15:38 UTC, multun requested changes
Looks good to me, apart from the name of the field. Thanks!

2023-01-04 15:38 UTC, multun commented on api/osrd_infra/models/rolling_stock.py
> +    meta_data = models.JSONField(
meta_data is usually written `metadata`, as [a single word](https://en.wikipedia.org/wiki/Metadata)

2023-01-04 16:09 UTC, multun approved these changes, later dismissed

2023-01-05 21:19 UTC, nicolaswurtz approved these changes

2023-01-05 23:01 UTC, Tguisnet approved these changes

2023-01-05 23:01 UTC, merged