Generate and test complex infras
OpenRailAssociation/osrd pull request #272
Opened 2021-11-05 10:08 UTC by eckter

2021-11-10 13:41 UTC, flomonster requested changes

2021-11-10 13:41 UTC, flomonster commented on examples/generator/railjson_generator/schema/infra/endpoint.py
> +            return TrackEndpoint(self.track_section, Endpoint.BEGIN)
```suggestion
        return TrackEndpoint(self.track_section, Endpoint.BEGIN)
```

2021-11-10 13:41 UTC, flomonster commented on examples/generator/railjson_generator/schema/infra/infra.py
> +    speed_limits: List[Dict] = field(default_factory=list)
Do we need to specify the label of a speed limit, we could generate it from speed limits in track sections.

2021-11-10 13:41 UTC, flomonster commented on examples/generator/railjson_generator/schema/infra/track_section.py
> +    speed_limits: List[Tuple[float, float, str]] = field(default_factory=list)
I would have added multiple datastruct such as `RangeElement`, `Slope`, `Curve` and `SpeedLimit`  to stay consistent with the rest of the library.

2021-11-10 13:41 UTC, flomonster commented on examples/generator/railjson_generator/schema/infra/track_section.py
> +                "applicable_direction": "BOTH"
All of this could be simplify by calling a `format()` method

2021-11-15 16:13 UTC, bgiuliana approved these changes

2021-11-16 09:53 UTC, flomonster approved these changes

2021-11-16 10:04 UTC, merged