allow to run `api` tests locally
OpenRailAssociation/osrd pull request #2723
Opened 2022-12-29 13:44 UTC by anisometropie

The user osrd needs to be able to create and delete a database in postgres. (Django creates a test database when running the tests and delete it at the end)

https://docs.djangoproject.com/en/4.1/topics/testing/overview/#the-test-database

2022-12-30 22:45 UTC, flomonster submitted a review, later dismissed

2023-01-01 16:42 UTC, multun requested changes

2023-01-01 16:42 UTC, multun commented on init_db.sql
> +alter user osrd with createdb;
you can `create user osrd password 'password' with createdb;` instead

2023-01-02 09:42 UTC, multun submitted a review, later dismissed

2023-01-02 19:30 UTC, multun approved these changes

2023-01-02 19:33 UTC, merged