Refactor railjson track ranges classes in core
OpenRailAssociation/osrd pull request #2754
Opened 2023-01-03 18:01 UTC by Castavo

Some things were odd and no longer used.

I needed the name `RJSTrackRange` to be available for an actual track range (with a track reference in it) so I renamed the former class to `RJSRange` and propagated the changes.

2023-01-04 08:09 UTC, bloussou reviewed
I'm not sure `isOverlapping()` is used in the code (I did not found where), is the usage coming in a following PR ?

2023-01-04 08:09 UTC, bloussou commented on core/osrd-railjson/src/main/java/fr/sncf/osrd/railjson/schema/infra/trackranges/RJSRange.java
> +    public static boolean isOverlaping(List<? extends RJSRange> ranges) {
Typo in Overlapping

Not sure about the rules for documentation in OSRD, is there a doc ? Otherwise I think it's cool to have very explicit names and remove paraphrasing docs
```suggestion
    public static boolean areRangesOverlapping(List<? extends RJSRange> ranges) {
```

2023-01-04 08:09 UTC, bloussou commented on core/osrd-railjson/src/main/java/fr/sncf/osrd/railjson/schema/infra/trackranges/RJSRange.java
> +        for (var i = 0; i < ranges.size() - 1; i++) {
```suggestion
        for (int i = 0; i < ranges.size() - 1; i++) {
```

2023-01-04 08:24 UTC, Castavo commented on core/osrd-railjson/src/main/java/fr/sncf/osrd/railjson/schema/infra/trackranges/RJSRange.java
> +    public static boolean isOverlaping(List<? extends RJSRange> ranges) {
I don't think this is used, it is heritage, I did not delete it, maybe I should

2023-01-04 09:10 UTC, multun requested changes

2023-01-04 09:10 UTC, multun commented on core/osrd-railjson/src/main/java/fr/sncf/osrd/railjson/schema/infra/trackranges/RJSRange.java
> +    public static boolean isOverlaping(List<? extends RJSRange> ranges) {
@Castavo you can ditch it

2023-01-04 09:10 UTC, multun commented on core/osrd-railjson/src/main/java/fr/sncf/osrd/railjson/schema/infra/trackranges/RJSRange.java
> +        for (var i = 0; i < ranges.size() - 1; i++) {
your suggested change does nothing; please keep in mind that very, very minor changes harm more by taking time to implement than benefit the project

2023-01-04 09:11 UTC, multun commented on core/osrd-railjson/src/main/java/fr/sncf/osrd/railjson/schema/infra/trackranges/RJSRange.java
> +        for (var i = 0; i < ranges.size() - 1; i++) {
does it really matter? please keep in mind changes take time to implement

2023-01-04 09:18 UTC, bloussou commented on core/osrd-railjson/src/main/java/fr/sncf/osrd/railjson/schema/infra/trackranges/RJSRange.java
> +        for (var i = 0; i < ranges.size() - 1; i++) {
It is more explicit (and not longer), @castavo can just click on the button `commit suggestion` and it is done but I'm not blocking this PR anyway so if you don't want to do it don't do it I won't be upset

2023-01-05 15:45 UTC, multun approved these changes

2023-01-05 15:45 UTC, merged