api : add Project, OperationalStudy and Scenario classes to models
OpenRailAssociation/osrd pull request #2776
Opened 2023-01-05 17:03 UTC by younesschrifi

Close #2769

2023-01-12 07:41 UTC, flomonster requested changes
Great PR. You have a few things to change .

2023-01-12 07:41 UTC, flomonster commented on api/osrd_infra/models/study.py
> +    scenarios = ArrayField(models.IntegerField(), null=True)
This field should be removed. `Scenario` already contains a foreign key to this table.

2023-01-12 07:41 UTC, flomonster commented on api/osrd_infra/schemas/study.py
> +    Disturbance = "Disturbance tests"
I would have keep the value as simple as possible. It won't be by the front.

2023-01-12 07:41 UTC, flomonster commented on api/osrd_infra/models/timetable.py
> +    scenario = models.OneToOneField(Scenario, on_delete=models.CASCADE, null=True)
This should be move to `Scenario` (replacing `time_table_id`).

2023-01-12 07:41 UTC, flomonster commented on api/osrd_infra/models/study.py
> +    studies = ArrayField(models.IntegerField(), null=True)
You already have a foreign key in `OperationalStudy`.

There is no reason to "double link" your tables.

2023-01-12 07:41 UTC, flomonster commented on api/osrd_infra/models/study.py
> +    infra_name = models.CharField(max_length=128)
This info can be retrieve via the timetable. You shouldn't have duplicate information in your tables. It's going to be a nightmare to synchronize.

2023-01-12 07:41 UTC, flomonster commented on api/osrd_infra/migrations/0015_operationalstudy_project_scenario_and_more.py
> +class Migration(migrations.Migration):
You have one big issue here. You need to manually create the ForeignKey and OneToOne fields. Ny default, these constraint are handle by django ORM and not Postgres engine. You should use the custom function `run_sql_add_foreign_key`. Some example are available in previous migrations.

2023-01-23 15:00 UTC, flomonster requested changes
Great PR. I didn't look much at the filters since we gonna use the generic system soon.

2023-01-23 15:00 UTC, flomonster commented on api/osrd_infra/migrations/0018_operationalstudy_project_scenario_and_more.py
> +            ),
These operations shouldn't be necessary since you're using `run_sql_add_foreign_key`

2023-01-23 15:00 UTC, flomonster commented on api/osrd_infra/migrations/__init__.py
> +    )
useless function. If we have a foreign key without a cascade then we can use the standard django migration.

2023-01-23 15:00 UTC, flomonster commented on api/osrd_infra/models/study.py
> +    timetable = models.OneToOneField(Timetable, related_name="scenario", on_delete=models.SET_NULL, null=True)
I'm confused. If a scenario is deleted we want to delete it's related timetable.

2023-01-23 15:00 UTC, flomonster commented on api/osrd_infra/models/study.py
> +    infra = models.ForeignKey(Infra, on_delete=models.SET_NULL, null=True)
Why this field should be nullable?

2023-01-23 15:00 UTC, flomonster commented on api/osrd_infra/urls.py
> +# /clients/{client_pk}/operationalstudies/{operational_study_pk}/
I don't thing this comment is usefull.

2023-01-27 00:30 UTC, flomonster requested changes

2023-01-27 00:30 UTC, flomonster commented on tests/fuzzer/fuzzer.py
> +    s = requests.post(URL + "projects/1/operational_studies/", json=op_study_payload)
To delete

2023-01-27 00:30 UTC, flomonster commented on tests/tests/utils/timetable.py
> +        raise RuntimeError(err)
To delete

2023-01-27 00:33 UTC, Tguisnet approved these changes, later dismissed

2023-01-31 08:26 UTC, closed without merging