front: Wrap sub-section under expand menus in settings modal in Cartographie
OpenRailAssociation/osrd pull request #2784
Opened 2023-01-06 15:01 UTC by Uriel-Sautron

close #2782

2023-01-12 15:49 UTC, Math-R submitted a review, later dismissed

2023-01-17 14:10 UTC, anisometropie requested changes

2023-01-17 14:10 UTC, anisometropie commented on .vscode/settings.json
> +  "java.compile.nullAnalysis.mode": "automatic"
we don’t commit vscode settings in the repo. it’s weird it ended up here, it should be blocked by .gitignore.

2023-01-17 14:21 UTC, Uriel-Sautron commented on .vscode/settings.json
> +  "java.compile.nullAnalysis.mode": "automatic"
Done

2023-01-17 14:38 UTC, anisometropie approved these changes

2023-01-17 14:39 UTC, merged