Add power class field to rolling stocks
OpenRailAssociation/osrd pull request #2806
Opened 2023-01-09 13:47 UTC by Castavo

There is an osrd-dags PR linked to this one: https://github.com/DGEXSolutions/osrd-dags/pull/32

2023-01-09 15:36 UTC, eckter approved these changes, later dismissed

2023-01-10 08:46 UTC, flomonster requested changes

2023-01-10 08:46 UTC, flomonster commented on api/osrd_infra/schemas/rolling_stock.py
> +        description="The power usage class of the train (optional because it is specific to SNCF)"
The powerclass should be an `Optional[int]` no?

2023-01-10 08:49 UTC, Castavo commented on api/osrd_infra/schemas/rolling_stock.py
> +        description="The power usage class of the train (optional because it is specific to SNCF)"
Why limit it to `int`, we are not going to use it as a numerical value, only as a categorical value ?

2023-01-10 08:59 UTC, flomonster approved these changes

2023-01-10 09:04 UTC, eckter approved these changes

2023-01-10 09:05 UTC, merged