Adapt simulation to take into account electrical profiles and adapt endpoints
OpenRailAssociation/osrd pull request #2886
Opened 2023-01-13 21:41 UTC by Castavo

2023-01-19 18:01 UTC, flomonster requested changes
Thanks for this PR!

2023-01-19 18:01 UTC, flomonster commented on api/openapi.yaml
> +                            format: float
Can you add:

- Description to the objects
- Example values

------

You can also create a component `ElectricalProfile` and reference it.

2023-01-19 18:01 UTC, flomonster commented on api/osrd_infra/migrations/0018_add_electrical_profiles_to_schedules.py
> +            ),
Foreign key migration should be done using `run_sql_add_foreign_key_infra`. Examples of use can be found in the first migration.

2023-01-19 18:01 UTC, flomonster commented on api/osrd_infra/urls.py
> +router.register("electrical_profile_set", ElectricalProfileSetView, basename="electrical_profile_set")
```suggestion
router.register("electrical_profiles", ElectricalProfilesView, basename="electrical_profiles")
```

2023-01-19 18:01 UTC, flomonster commented on api/osrd_infra/models/external_generated_inputs.py
>  from django.contrib.gis.db import models
Can you rename this file into `electrical_profile.py`

2023-01-19 18:01 UTC, flomonster commented on api/osrd_infra/models/external_generated_inputs.py
> +    level_order = models.JSONField(validators=[PydanticValidator(ElectricalProfileLevelOrder)], default=dict)
Can you include this data into the electrical profile schema.

2023-01-19 18:01 UTC, flomonster commented on api/osrd_infra/views/electrical_profiles.py
> +        return Response(ElectricalProfilesSet.objects.get(pk=pk).level_order, content_type="application/json")
Move these endpoints to editoast

2023-01-19 18:01 UTC, flomonster commented on core/src/main/java/fr/sncf/osrd/cli/StandaloneSimulationCommand.java
> +            var allowance = new RJSAllowance[]{
```suggestion
            var allowance = new RJSAllowance[] {
```

2023-01-19 18:01 UTC, flomonster commented on core/src/main/java/fr/sncf/osrd/external_generated_inputs/ElectricalProfileMapping.java
> +package fr.sncf.osrd.external_generated_inputs;
```suggestion
package fr.sncf.osrd.electrical_profiles;
```

2023-01-19 18:01 UTC, flomonster commented on core/src/main/java/fr/sncf/osrd/envelope_sim/EnvelopeSimContext.java
> +        this.modeAndProfilesUsed = curvesAndConditions.conditions();
With the idea to keep a constructor as simple as possible (without computation).
Can you add a static method `build` that compute `curvesAndConditions` and then call the constructor with the `tractiveEffortCurveMap` and `modeAndProfileUsed`.

2023-01-23 10:11 UTC, multun requested changes

2023-01-23 10:11 UTC, multun commented on api/openapi.yaml
> +                  electrical_profile_set:
what's that?

2023-01-23 10:11 UTC, multun commented on api/openapi.yaml
> +        modes_and_profiles:
why is this exported to the front-end?

2023-01-23 10:11 UTC, multun commented on api/osrd_infra/models/electrical_profiles.py
>  class ElectricalProfilesSet(models.Model):
the description says "Profile" and the class name "Profiles"

2023-01-23 10:11 UTC, multun commented on api/osrd_infra/models/timetable.py
> +    electrical_profile_set = models.ForeignKey(ElectricalProfilesSet, on_delete=models.CASCADE, null=True, blank=True)
is'nt it linked to the infra?

2023-01-23 10:11 UTC, multun commented on api/osrd_infra/models/train_schedule.py
> +    modes_and_profiles = models.JSONField(default=[])
we usually have a schema validator. having a list as a default also is not safe, please use default_factory

2023-01-23 10:11 UTC, multun commented on core/openapi.yaml
> +          example: "ID"
why does the back need to return that?

2023-01-23 10:11 UTC, multun commented on core/src/main/java/fr/sncf/osrd/api/MiddleWareInteraction.java
> +public abstract class MiddleWareInteraction {
how about just "APIClient"?

2023-01-23 10:11 UTC, multun commented on core/src/main/java/fr/sncf/osrd/api/StandaloneSimulationEndpoint.java
> +            var electricalProfileMap = electricalProfileSetManager.getProfileMap(request.electricalProfileSet);
I think ElectricalProfileMap is a better name, couln't the class use it too?

2023-01-23 10:11 UTC, multun commented on core/src/main/java/fr/sncf/osrd/envelope_sim/EnvelopePath.java
> +    private final ImmutableRangeMap<Double, ModeAndProfile> catenaryModeMap;
RangeMaps aren't exactly fast, have you benchmarked the impact of your implementation?

2023-01-23 10:11 UTC, multun commented on core/src/main/java/fr/sncf/osrd/envelope_sim/PhysicsPath.java
> +    record ModeAndProfile(String mode, String profile) {}
what's the "mode"?

2023-01-23 10:11 UTC, multun commented on core/src/main/java/fr/sncf/osrd/envelope_sim/PhysicsRollingStock.java
> +                               RangeMap<Double, PhysicsPath.ModeAndProfile> conditions) {
I just don't get it, aren't conditions used to get the curves? is it just to debug / display?

2023-01-25 12:57 UTC, Castavo commented on core/src/main/java/fr/sncf/osrd/envelope_sim/PhysicsPath.java
> +    record ModeAndProfile(String mode, String profile) {}
I'll elaborate in all doctstrings

2023-01-25 14:55 UTC, multun submitted a review, later dismissed

2023-01-26 10:34 UTC, flomonster requested changes
Almost there!

2023-01-26 10:34 UTC, flomonster commented on api/osrd_infra/migrations/__init__.py
> +                ADD {field_name}_id INTEGER {"NULL" * nullable},
Using a ternary condition looks better.

```suggestion
                ADD {field_name}_id INTEGER {"NULL" if nullable else ""},
```

2023-01-26 10:34 UTC, flomonster commented on api/osrd_infra/models/timetable.py
> +    electrical_profile_set = models.ForeignKey(ElectricalProfileSet, on_delete=models.CASCADE, null=True, blank=True)
`blank` doesn't make sens since it's not a `CharField`.

2023-01-26 10:34 UTC, flomonster commented on core/examples/generated/lib/railjson_generator/external_generated_inputs.py
> +            },
Is this normal ? It should be part of the schema no?

2023-01-26 10:34 UTC, flomonster commented on editoast/openapi.yaml
> +            $ref: "#/components/schemas/TrackRange"
Missing line feed

2023-01-26 10:34 UTC, flomonster commented on editoast/src/schema/electrical_profiles.rs
> +}
Queryable, errors and implementations should be moved to the view. 
The `schema` module is here to declare serializers.

2023-01-26 10:34 UTC, flomonster commented on editoast/src/views/electrical_profiles.rs
> +}
Can you move this at the top of the file.

2023-01-26 13:34 UTC, Tguisnet approved these changes, later dismissed

2023-01-26 15:06 UTC, flomonster approved these changes

2023-01-26 15:06 UTC, merged