front: create DisplayMissingInfo component with HOC
OpenRailAssociation/osrd pull request #2933
Opened 2023-01-18 12:19 UTC by Yohh

close #2798

2023-01-18 12:45 UTC, Uriel-Sautron commented
It would be good to start the translation sentences with a capital letter in front/public/locales/fr/missingInfo.json

2023-01-23 09:21 UTC, alexandredamiron requested changes

2023-01-23 09:21 UTC, alexandredamiron commented on front/src/common/DisplayMissingInfo/withOSRDStdcmMissingInfo.tsx
> +      !speedLimitByTag ? t('missingSpeedLimitByTag') : '',
Je ne crois pas que 'speed limit by tag' soit nécessaire ni timetable -> voir openapi.yml, pathquery

2023-01-23 09:21 UTC, alexandredamiron commented on front/src/common/DisplayMissingInfo/withOSRDStdcmMissingInfo.tsx
> +    useEffect(() => {
Serait-il possible de changer quelque peu la logique et de mettre l'alerte seulement si origin et destination sont set (il y a des selecteurs) MAIS qu'il manque un des autre parametres (infra, rollingStock)

2023-01-23 09:21 UTC, alexandredamiron commented on front/src/applications/osrd/views/OSRDConfig/Itinerary.js
> +        <div className="osrd-config-item-missingInfo">
il faudrait mettre ça dans la container de DisplayIntinary

2023-01-23 16:54 UTC, Yohh commented on front/src/common/DisplayMissingInfo/withOSRDStdcmMissingInfo.tsx
> +      !speedLimitByTag ? t('missingSpeedLimitByTag') : '',
Done

2023-01-23 16:54 UTC, Yohh commented on front/src/common/DisplayMissingInfo/withOSRDStdcmMissingInfo.tsx
> +    useEffect(() => {
Done

2023-01-23 16:54 UTC, Yohh commented on front/src/applications/osrd/views/OSRDConfig/Itinerary.js
> +        <div className="osrd-config-item-missingInfo">
Done

2023-01-26 08:30 UTC, alexandredamiron approved these changes

2023-01-26 08:43 UTC, merged