core: improve getmaxeffort method
OpenRailAssociation/osrd pull request #2938
Opened 2023-01-18 16:32 UTC by majaziri

2023-01-20 10:50 UTC, axrolld approved these changes, later dismissed

2023-01-20 14:41 UTC, flomonster requested changes
Few things should be adapted. Can you run a profiler to validate that this change actually improve performances.

2023-01-20 14:41 UTC, flomonster commented on core/src/main/java/fr/sncf/osrd/envelope_sim/PhysicsRollingStock.java
> +        Arrays.sort(tractiveEffortCurve, Comparator.comparing(tractiveEffortPoint -> speed));
This is already sorted.

2023-01-20 14:41 UTC, flomonster commented on core/src/main/java/fr/sncf/osrd/envelope_sim/PhysicsRollingStock.java
> +                Arrays.stream(tractiveEffortCurve).mapToDouble(TractiveEffortPoint::speed).toArray();
This line breaks performance and makes the patch less efficient than before I think.

2023-01-20 16:03 UTC, axrolld submitted a review, later dismissed
The effort returned is correct, you can consider the pysics part approved.

2023-01-26 09:29 UTC, eckter commented on core/src/main/java/fr/sncf/osrd/envelope_sim/PhysicsRollingStock.java
> +            int mid = (left + right) >>> 1;
I assume this is to avoid overflows when computing the average? I didn't know this worked. I think a comment here would be helpful.

2023-01-26 09:29 UTC, eckter commented on core/src/main/java/fr/sncf/osrd/envelope_sim/PhysicsRollingStock.java
> +            if (Double.compare(tractiveEffortCurve[mid].speed, Math.abs(speed)) == 0) {
This doesn't really solve the "float comparaison" problem, it just hides it from spotbugs. If you think an equality test actually makes sense here, the correct way to remove the warning is to add `@SuppressFBWarnings({"FE_FLOATING_POINT_EQUALITY"})` before the method.

There's probably a way to remove this `if` branch, but that's not really important.

2023-01-31 13:18 UTC, flomonster requested changes
Waiting for a benchmark

2023-01-31 16:26 UTC, majaziri commented
[benchmark.ods](https://github.com/DGEXSolutions/osrd/files/10548638/benchmark.ods)
After 20 iteration, i managed to fill this file to test the 'act' method in StandaloneSimulationEndpoint.
the values provided are in nanoseconds, they are slightly improved compared to the original code.
The first column represents the average of all 20 iterations.

2023-01-31 16:45 UTC, bloussou commented
I'm not sure that 20 iteration are enough to see [JVM warm up](https://www.baeldung.com/java-jvm-warmup), but I'm also not sure that this code is supposed to be warmed up at some point in a normal usage of the app.

2023-01-31 17:06 UTC, multun approved these changes

2023-02-01 00:15 UTC, majaziri commented
> Which tool did you use to run the iteration ?

I calculated the difference of time between the start and the end of the method

2023-02-01 08:35 UTC, bloussou commented
Ok, in the future to test such code you can use tools like `java-micro-benchmark` : https://www.baeldung.com/java-microbenchmark-harness in order to see jvm optimizations like [jvm warmup](https://www.baeldung.com/java-jvm-warmup) (because 20 iterations is not enough to see these iterations). We can talk about it later if you have such  benchmark to run in the future :smile:

2023-02-02 08:53 UTC, flomonster approved these changes

2023-02-02 08:56 UTC, merged