README: various improvements
OpenRailAssociation/osrd pull request #3057
Opened 2023-01-31 18:10 UTC by multun

- move acknowledgements to the website
- make the project's description clearer
- add working getting started instructions
- make generate-infra.sh load small_infra by default

![2023-01-31_19-01-1675188586](https://user-images.githubusercontent.com/5047140/215846604-78e71841-8463-4070-a3df-03858f5b59ff.jpg)

2023-01-31 18:23 UTC, loic-hamelin commented
I would add in the 'what is OSRD section': OSRD has been launched by SNCF Réseau, the French Infrastructure Manager. OSRD is founded by European Union and French State to help to develop freight railway.

2023-02-01 14:05 UTC, celine-sncf commented
Add OSRD.fr link and quick summary of what we can find on the website

2023-02-01 17:44 UTC, axrolld requested changes
I agree with the comments above

2023-02-01 18:00 UTC, axrolld approved these changes

2023-02-01 18:04 UTC, merged