Cni: front: GET/GEV get coordinated cursors
OpenRailAssociation/osrd pull request #3134
Opened 2023-02-09 11:04 UTC by clarani

2023-02-13 08:09 UTC, alexandredamiron commented
On storybook, updatePointer is not applied (plain circle along the vertical line)
AND GEV starts empty need to use the reset button
![Capture d’écran 2023-02-13 à 09 08 46](https://user-images.githubusercontent.com/765626/218403988-fc22d487-ecdb-4361-b5f3-7262cb911855.png)

![Capture d’écran 2023-02-13 à 09 07 19](https://user-images.githubusercontent.com/765626/218403916-0e347e61-2c4b-45b7-933d-7a75aeeeff3a.png)

2023-02-16 14:10 UTC, anisometropie requested changes

2023-02-16 14:10 UTC, anisometropie commented on front/src/applications/operationalStudies/components/SimulationResults/SpaceTimeChart/SpaceTimeChart.js
> +  const [, setDragEnding] = useState(false);
might as well completely remove this useState. the value is set but never used ?

2023-02-16 14:10 UTC, anisometropie commented on front/src/applications/operationalStudies/components/SimulationResults/SpaceTimeChart/SpaceTimeChart.js
> +    console.log('on resize');
log

2023-02-16 14:10 UTC, anisometropie commented on front/src/applications/operationalStudies/components/SimulationResults/ChartHelpers/ChartHelpers.ts
> +            index !== section.length &&
does this happen ? bisect can give out of bound indices ?

2023-02-16 14:10 UTC, anisometropie commented on front/src/applications/operationalStudies/components/SimulationResults/SpaceTimeChart/d3Helpers.js
> +  // difference entre mustRedraw et forceRedraw ?
ask in slack and see if you need to change this.
otherwise this comment will most likely stay there forever and will not be answered.

2023-02-17 08:34 UTC, clarani commented on front/src/applications/operationalStudies/components/SimulationResults/SpaceTimeChart/SpaceTimeChart.js
> +    console.log('on resize');
Already fixed :)

2023-02-17 08:35 UTC, clarani commented on front/src/applications/operationalStudies/components/SimulationResults/SpaceTimeChart/d3Helpers.js
> +  // difference entre mustRedraw et forceRedraw ?
Ok, I will remove this comment and try to tackle this issue in my next PR

2023-02-17 08:45 UTC, clarani commented on front/src/applications/operationalStudies/components/SimulationResults/ChartHelpers/ChartHelpers.ts
> +            index !== section.length &&
Hum actually I haven't modified the logic of this code, only added the line 298 and brackets.
But yes I think bisect can give out of bound indices, for instance if the element needs to be added at the end of the array (https://www.geeksforgeeks.org/d3-js-bisect-function/)

2023-02-17 08:46 UTC, clarani commented on front/src/applications/operationalStudies/components/SimulationResults/SpaceTimeChart/SpaceTimeChart.js
> +  const [, setDragEnding] = useState(false);
Well, I tried to remove it but then a new error appear in the console, so I think I need more time to remove this and resolve the error in the console. I will let a comment on this line, thanks

2023-02-17 10:30 UTC, anisometropie approved these changes, later dismissed

2023-02-17 10:44 UTC, anisometropie approved these changes

2023-02-17 11:03 UTC, merged