front: migrate to vite
OpenRailAssociation/osrd pull request #3211
Opened 2023-02-18 01:11 UTC by multun

This change switch from react-create-app to vite. Build times are reduced down to a minute.

A few things need to be done before this can be merged:
 - [ ] fix tests / coverage
 - [ ] fix storybook

2023-02-21 09:11 UTC, alexandredamiron commented on front/src/applications/operationalStudies/components/SimulationResults/SpaceTimeChart.jsx
> +import * as d3 from 'd3';
ce fichier n'est normalement plus utilisé, il ne faut pas le remettre

2023-02-21 09:16 UTC, multun commented on front/src/applications/operationalStudies/components/SimulationResults/SpaceTimeChart.jsx
> +import * as d3 from 'd3';
je pense que c'est une erreur de rebase, merci

2023-02-22 00:12 UTC, alexandredamiron submitted a review, later dismissed

2023-02-22 10:00 UTC, anisometropie requested changes

2023-02-22 10:00 UTC, anisometropie commented on front/src/env.ts
> +export const env: Env = { ...window.env };
you can delete this file since env.js is gone

2023-02-22 10:41 UTC, alexandredamiron approved these changes

2023-02-22 10:43 UTC, anisometropie approved these changes

2023-02-22 10:50 UTC, merged