Replace name speed_limit_composition with speed_limit_tags
OpenRailAssociation/osrd pull request #3343
Opened 2023-02-27 08:38 UTC by younesschrifi

Close #2435

2023-02-27 14:51 UTC, flomonster requested changes
Thanks! We should have a review from a front maintainer too.

2023-02-27 14:51 UTC, flomonster commented on api/osrd_infra/migrations/0001_initial.py
> -                ("speed_limit_composition", models.CharField(max_length=128, null=True)),
You can't change an old migration. You must create a new one that actually changes the column name.

2023-02-27 15:05 UTC, eckter approved these changes, later dismissed
I haven't checked the details, but for variable renames, as long as the CI passes then it's good for me

2023-02-27 16:09 UTC, flomonster approved these changes

2023-02-27 16:21 UTC, eckter approved these changes

2023-02-28 09:50 UTC, anisometropie approved these changes

2023-02-28 09:51 UTC, Math-R approved these changes

2023-02-28 09:51 UTC, merged