front: remove useless requests in Scenario page
OpenRailAssociation/osrd pull request #3369
Opened 2023-03-01 16:53 UTC by clarani

Fixes #554 
Removed 2 useless requests (still have 2, but to reduce to 1, I think we will have to refactor the whole component/store system)

2023-03-01 17:37 UTC, nicolaswurtz requested changes

2023-03-01 17:37 UTC, nicolaswurtz commented on front/src/applications/operationalStudies/views/Scenario.jsx
> +      console.log('hello from Scenario');
Nope :P

2023-03-02 08:18 UTC, clarani commented on front/src/applications/operationalStudies/views/Scenario.jsx
> +      console.log('hello from Scenario');
Thanks !! ^^

2023-03-02 12:12 UTC, nicolaswurtz approved these changes

2023-03-02 12:13 UTC, merged