front: linter: decrease warnings number
OpenRailAssociation/osrd pull request #3580
Opened 2023-03-17 11:18 UTC by clarani

2023-03-17 12:03 UTC, alexandredamiron commented on front/package.json
> +    "lint": "eslint --ext .ts,.tsx,.js,.jsx src --fix",
Where's the number now ?

2023-03-17 13:45 UTC, clarani commented on front/package.json
> +    "lint": "eslint --ext .ts,.tsx,.js,.jsx src --fix",
No need for the number here, this is the script you can launch in local to fix all your linter errors (not the one which will be run during the build, see vite.config)

2023-03-17 13:57 UTC, anisometropie requested changes

2023-03-17 13:57 UTC, anisometropie commented on front/package.json
> +    "lint": "eslint --ext .ts,.tsx,.js,.jsx src --fix",
no need to force the option --fix, it has to be an option

2023-03-17 15:23 UTC, alexandredamiron submitted a review, later dismissed

2023-03-17 16:19 UTC, alexandredamiron approved these changes

2023-03-20 09:22 UTC, anisometropie approved these changes

2023-03-20 09:22 UTC, merged