codecov: java: fix coverage for assertions
OpenRailAssociation/osrd pull request #3632
Opened 2023-03-21 14:46 UTC by eckter

Assertions lowering the coverage value because of "partial hits" is a problem, this change tries to fix it.

I couldn't just filter out the assert statements, so the only option I've found was to consider partials  hits as covered.

2023-04-04 14:49 UTC, Khoyo commented
Why is there still partials ?

Anyway, it is wrong to count partial as hits. Maybe if it was only for the percentage computation, or only for asserts, but this isn't the case...

2023-04-04 14:49 UTC, Khoyo requested changes
Why are there still partials ?

Anyway, I think it is wrong to count partial as hits. Maybe if it was only for the percentage computation, or only for asserts, but this isn't the case...

2023-04-04 15:22 UTC, eckter commented
Yeah I'm not really convinced by this solution either...

> Why are there still partials ?

It considers that an assertion that never fails is a partial hit. Since we mostly use assert statements to express pre/post conditions, they only fail when there is a bug. That means every assert is a partial hit, and because it lowers the coverage value, simply adding asserts can actually block merges. It's a real pain and actively discourages cleaner code.

2023-04-05 09:20 UTC, multun commented
> It considers that an assertion that never fails is a partial hit. Since we mostly use assert statements to express pre/post conditions, they only fail when there is a bug. That means every assert is a partial hit, and because it lowers the coverage value, simply adding asserts can actually block merges. It's a real pain and actively discourages cleaner code.

There must be a misunderstanding: codecov still reports some partial hits, even though your config option should have converted all partial hits to hits.

> It's a real pain and actively discourages cleaner code

I see two other options:
 - accept adding some partial hits. coverage is just one more tool to measure how well tested code is, it's not like changing how we measure things will actually change anything
 - use a fork of jacoco which does what we need https://github.com/jacoco/jacoco/pull/1379

2023-06-12 08:04 UTC, eckter commented
closing: it's too much effort to do this properly for what it's worth

2023-06-12 08:04 UTC, closed without merging