editoast : add delete endpoint for scenario
OpenRailAssociation/osrd pull request #3636
Opened 2023-03-21 23:07 UTC by younesschrifi

Close #3599

2023-03-22 14:00 UTC, flomonster requested changes
Thanks for this PR. I have a question and a suggestion.

2023-03-22 14:00 UTC, flomonster commented on editoast/src/models/scenario.rs
> +    fn delete_conn(conn: &mut diesel::PgConnection, scenario_id: i64) -> Result<bool> {
We can add documentation?

2023-03-22 14:00 UTC, flomonster commented on editoast/src/models/scenario.rs
> +        }
The timetable is not deleted in cascade?

2023-03-22 14:00 UTC, flomonster commented on editoast/src/views/scenario.rs
> +    Scenario { scenario_id: i64 },
Keeping the `NotFound` suffix is useful to have a better error id.

2023-03-22 14:00 UTC, flomonster commented on editoast/src/views/scenario.rs
> +    study.expect("Study should exist");
We could factorize this code with a private utility function.

2023-03-22 15:25 UTC, younesschrifi commented on editoast/src/models/scenario.rs
> +        }
No the timetable is not deleted in cascade. We have the same issue as for image in project

2023-03-22 15:26 UTC, younesschrifi commented on editoast/src/models/scenario.rs
> +    fn delete_conn(conn: &mut diesel::PgConnection, scenario_id: i64) -> Result<bool> {
Of course, thanks !

2023-03-22 15:27 UTC, younesschrifi commented on editoast/src/views/scenario.rs
> +    Scenario { scenario_id: i64 },
There are clippy warnings when I keep NotFound, what should I do ?

2023-03-22 16:53 UTC, flomonster commented on editoast/src/models/scenario.rs
> +        }
Okay, let's keep it that way. The foreign key can be reversed later.

2023-03-22 17:05 UTC, flomonster requested changes

2023-03-22 17:05 UTC, flomonster commented on editoast/src/models/scenario.rs
> +        }
```suggestion
        delete(
            timetable_dsl::osrd_infra_timetable
                .filter(timetable_dsl::id.eq(scenario.timetable.unwrap())),
        )
        .execute(conn)?;
        Ok(true)
```

2023-03-22 17:05 UTC, flomonster commented on editoast/src/views/scenario.rs
> +            .to_request()
```suggestion
        let url = format!("/projects/{project_id}/studies/{study_id}/scenarios/{scenario_id}");
        TestRequest::delete().uri(url.as_str()).to_request()
```

2023-03-24 10:52 UTC, flomonster requested changes

2023-03-24 10:52 UTC, flomonster commented on editoast/src/tables.rs
> +    osrd_infra_scenario(id) {
```suggestion
    osrd_infra_scenario {
```

2023-03-24 10:56 UTC, flomonster approved these changes

2023-03-24 11:29 UTC, merged