schemas: replace applicable directions to direction for buffer stops
OpenRailAssociation/osrd pull request #3664
Opened 2023-03-24 11:00 UTC by flomonster

Linked to #3607 
close #3391

2023-03-24 17:16 UTC, multun commented on core/examples/generated/infra.json
it adding this file intended?

2023-03-24 17:16 UTC, multun commented on core/examples/generated/simulation.json
is this intended?

2023-03-27 08:37 UTC, Castavo submitted a review, later dismissed

2023-03-29 07:51 UTC, Tguisnet requested changes

2023-03-29 07:51 UTC, Tguisnet commented on core/examples/generated/lib/railjson_generator/schema/infra/waypoint.py
> +    def get_direction(self, track) -> Direction:
I don't understand this function

2023-03-29 07:51 UTC, Tguisnet commented on core/examples/generated/lib/railjson_generator/infra_builder.py
> +from .schema.infra.direction import Direction
I think this is not use

2023-03-29 07:55 UTC, Tguisnet approved these changes

2023-03-29 08:19 UTC, merged