front: stdcm: STDCM display overhaul
OpenRailAssociation/osrd pull request #3665
Opened 2023-03-24 11:05 UTC by Yohh

2023-03-24 15:29 UTC, clarani requested changes

2023-03-24 15:29 UTC, clarani commented on front/src/applications/stdcm/views/OSRDStdcmResults.tsx
> +  }, [simulation]);
```suggestion
```
I think this is not needed because consolidatedSimulation is updated at the same time as simulation (see StdcmRequestModal, l99-100)

2023-03-24 15:29 UTC, clarani commented on front/src/applications/stdcm/views/OSRDStdcmResults.tsx
> +  return (
So this case is if there is a result but no selected train id ?
I think we can factorize some code here: 
- first manage the case no-result
- then manage the case with result:
  - always show the spaceTimeChart
  - show the speedSpaceChart only if there is a selectedTrainId

2023-03-24 15:29 UTC, clarani commented on front/src/applications/stdcm/views/OSRDCStdcmConfig.tsx
> +                    setCurrentStdcmRequestStatus(STDCM_REQUEST_STATUS.pending);
We should use RTK request status to do this, but we can refacto this later. Can you please add a comment before this line with "TODO: ...", and explain why we should refacto this ?
Thanks :)

2023-03-24 16:19 UTC, Yohh commented on front/src/applications/stdcm/views/OSRDStdcmResults.tsx
> +  }, [simulation]);
done

2023-03-24 16:20 UTC, Yohh commented on front/src/applications/stdcm/views/OSRDStdcmResults.tsx
> +  return (
done, display was bad, fixed

2023-03-24 16:20 UTC, Yohh commented on front/src/applications/stdcm/views/OSRDCStdcmConfig.tsx
> +                    setCurrentStdcmRequestStatus(STDCM_REQUEST_STATUS.pending);
done

2023-03-30 08:40 UTC, alexandredamiron submitted a review, later dismissed

2023-03-30 09:30 UTC, clarani reviewed
Only 1 typo to fix

2023-03-30 09:30 UTC, clarani commented on front/src/applications/stdcm/views/OSRDStdcmResults.tsx
> +  const [speedSpaceTimeChartHeight, setSpeedSpaceTimeChartHeight] = useState(450);
```suggestion
  const [speedSpaceChartHeight, setSpeedSpaceChartHeight] = useState(450);
```
Typo

2023-03-30 09:33 UTC, Yohh commented on front/src/applications/stdcm/views/OSRDStdcmResults.tsx
> +  const [speedSpaceTimeChartHeight, setSpeedSpaceTimeChartHeight] = useState(450);
done

2023-03-30 09:42 UTC, clarani approved these changes
Nice job !!

2023-03-30 09:57 UTC, merged