front: fix-bug: display rolling stock images
OpenRailAssociation/osrd pull request #3696
Opened 2023-03-27 13:45 UTC by clarani

closes #3695

2023-03-27 13:47 UTC, bloussou submitted a review, later dismissed
:rocket:

2023-03-27 17:10 UTC, nicolaswurtz requested changes
Use new marvelous RTK queries pleeeease :D

2023-03-28 11:50 UTC, nicolaswurtz commented on front/src/common/RollingStockSelector/RollingStock2Img.jsx
>        /* empty */
No empty catch error (at least put a `console.error`, thx !)

2023-03-28 11:50 UTC, nicolaswurtz commented on front/src/common/RollingStockSelector/RollingStock2Img.tsx
>    return imageUrl ? <LazyLoadImage src={imageUrl} alt={rollingStock?.name} key={nextId()} /> : null;
Please use something else than `nextId()`, why not create a unique id key with a prefix associated to rolling stock unique name ?

2023-03-28 13:26 UTC, nicolaswurtz approved these changes

2023-03-28 13:27 UTC, merged