wip: stdcm waypoints and intermediate stops
OpenRailAssociation/osrd pull request #3791
Opened 2023-04-04 12:47 UTC by eckter

2023-04-06 15:43 UTC, flomonster requested changes
API lgtm. I did some test and get a 500 running the `stdcm` endpoint:

```json
{
  "type": "core:assert_error",
  "assert_message": "Assertion failed",
  "cause": "INTERNAL",
  "message": "Assertion failed",
  "stack_trace": [
    "LoadedSignalingInfra.kt:169",
    "LoadedSignalingInfra.kt:184",
    "ScheduleMetadataExtractor.kt:45",
    "StandaloneSim.java:61",
    "STDCMEndpoint.java:226",
    "STDCMEndpoint.java:114",
    "FkRegex.java:153",
    "FkRegex.java:217",
    "FkChain.java:72",
    "TkFork.java:98",
    "TkFallback.java:84",
    "TkFallback.java:66",
    "TkWrap.java:58",
    "TkSlf4j.java:110",
    "BkBasic.java:123",
    "BkBasic.java:99",
    "BkSafe.java:46",
    "BkWrap.java:51",
    "BkParallel.java:81",
    "ThreadPoolExecutor.java:1136",
    "ThreadPoolExecutor.java:635",
    "Thread.java:833"
  ],
  "trace": []
}
```

2023-04-07 10:36 UTC, multun commented on core/src/main/java/fr/sncf/osrd/stdcm/graph/STDCMPathfinding.java
>          var envelope = range.edge().envelope();
can this function be renamed so that its name does not imply that it returns a distance? it returns a weight

2023-04-07 10:36 UTC, multun commented on core/src/main/java/fr/sncf/osrd/stdcm/graph/STDCMPostProcessing.java
> +import java.nio.file.Path;
```suggestion
```

2023-04-25 07:45 UTC, eckter commented
@flomonster the assert you had is unrelated. It's still around (https://github.com/DGEXSolutions/osrd/issues/3746), but now it only happens when using routes that go from signal to signal, which should be very uncommon.

2023-04-25 10:13 UTC, flomonster approved these changes
LGTM. I tested stdcm with stops everything seems to work.

2023-05-04 13:26 UTC, multun approved these changes
Untested, LGTM

2023-05-04 15:16 UTC, Khoyo approved these changes

2023-05-05 11:38 UTC, anisometropie approved these changes

2023-05-05 11:52 UTC, merged