Ard/update rs json schema qualesi
OpenRailAssociation/osrd pull request #3811
Opened 2023-04-05 05:45 UTC by axrolld

2023-04-06 13:14 UTC, clarani commented
@maintainers should we update the railjson version ?

2023-04-07 12:20 UTC, flomonster requested changes
You forgot to adapt the RS schema of editoast.

2023-04-07 12:20 UTC, flomonster commented on python/osrd_schemas/osrd_schemas/rolling_stock.py
> +    energy_sources: Optional[List[EnergySource]]
Instead of an optional list can we have a default empty list? This implies adding this empty list to your migration.

2023-04-25 11:41 UTC, flomonster requested changes
Thanks for the PR, I requested a few changes but nothing too major.

2023-04-25 11:41 UTC, flomonster commented on editoast/src/models/rolling_stock/mod.rs
> +    pub energy_sources: Option<Vec<DieselJson<EnergySource>>>,
```suggestion
    pub energy_sources: Option<DieselJson<Vec<EnergySource>>>,
```

2023-04-25 11:41 UTC, flomonster commented on editoast/src/schema/rolling_stock/mod.rs
> +    Battery { railjson: Battery},
You can inline the structs `Catenary`, `PowerPack` and `Battery` here.

2023-04-25 11:41 UTC, flomonster commented on editoast/src/schema/rolling_stock/mod.rs
> +    energy_source_type: EnergySourceType,
```suggestion
```

This field is automatically parsed by `serde`.

2023-04-25 11:41 UTC, flomonster commented on editoast/src/schema/rolling_stock/mod.rs
> +    pub energy_sources: Vec<EnergySource>,
This field could be optional (default: empty list). This allows to remain compatible with the old schema.
You will no longer need to specify `"energy_sources": []` for all examples of rolling stock.

```suggestion
    #[serde(default)]
    pub energy_sources: Vec<EnergySource>,
```

2023-04-25 11:41 UTC, flomonster commented on python/api/openapi.yaml
> +              nullable: true
```suggestion
```

2023-04-25 11:41 UTC, flomonster commented on python/api/openapi.yaml
> +          format: float
We must adapt the openapi with the new schema using `oneOf`. Check the documentation [here](https://swagger.io/docs/specification/data-models/inheritance-and-polymorphism/)

2023-04-25 11:41 UTC, flomonster commented on python/osrd_schemas/osrd_schemas/rolling_stock.py
> +    energy_sources: List[EnergySource]
```suggestion
    energy_sources: List[EnergySource] = Field(default_factory=list)
```

2023-05-16 14:00 UTC, clarani reviewed
Reviewed and tested with postman

2023-05-16 14:37 UTC, clarani reviewed
Reviewed

2023-05-17 09:20 UTC, flomonster approved these changes
LGTM.

2023-05-17 09:20 UTC, flomonster commented on editoast/README.md
> + - [clippy](https://github.com/rust-lang/rust-clippy): Run a powerful linter `cargo clippy --all-features --all-targets --manifest-path=Cargo.toml -- -D warnings`
The default value for `--manifest-path` is `Cargo.toml`
```suggestion
 - [clippy](https://github.com/rust-lang/rust-clippy): Run a powerful linter `cargo clippy --all-features --all-targets -- -D warnings`
```

2023-05-17 09:20 UTC, flomonster commented on editoast/src/tests/example_rolling_stock_2.json
We could rename this file `example_rolling_stock_battery`.

2023-05-22 09:05 UTC, eckter approved these changes

2023-05-22 09:37 UTC, merged