front: use Editoast endpoint for light_rolling_stock
OpenRailAssociation/osrd pull request #3820
Opened 2023-04-05 13:56 UTC by clarani

- use RTK
- refacto the function to filter the rolling_stocks in the rolling_stock_modal

2023-04-14 07:28 UTC, nicolaswurtz requested changes

2023-04-14 07:28 UTC, nicolaswurtz commented on front/public/locales/fr/rollingstock.json
> +    "ressourcesNotFound": "Ressources introuvables, veuillez réessayer plus tard"
« veuillez réessayer plus tard » is useless, the user knows that it could try later ;)

I think an interface should only say what it is and not what it could. Here, "later" is a "perhaps" and not "for sure", so the information has no utility.

2023-04-14 07:28 UTC, nicolaswurtz commented on front/src/common/RollingStockSelector/RollingStockModal.jsx
> +            const { rollingStockMetadata } = rollingStock;
This is more concise but a waaay more complicated to read, don't you think ?

2023-04-14 07:28 UTC, nicolaswurtz commented on front/src/common/RollingStockSelector/RollingStockModal.jsx
> +            const { rollingStockMetadata } = rollingStock;
I prefer to keep the old version, it is much easier to read and understand.

2023-04-14 16:23 UTC, clarani commented on front/public/locales/fr/rollingstock.json
> +    "ressourcesNotFound": "Ressources introuvables, veuillez réessayer plus tard"
I have modified the translation, tell me if it's okay for you :)

2023-04-14 16:25 UTC, clarani commented on front/src/common/RollingStockSelector/RollingStockModal.jsx
> +            const { rollingStockMetadata } = rollingStock;
Hm the old version is quite inefficient as it iterates through the same array 4 times. Also, it does not seem clearer to me (especially the lines for the thermal and electrical filters).
I have tried to add some comments on the new version, do you think it is better now ?

2023-04-19 09:08 UTC, SharglutDev commented on front/src/common/RollingStockSelector/RollingStockModal.jsx
> +    const filterIsEmpty = filterText || filters.elec || filters.thermal;
The variable name should be filterIsNotEmpty or filterIsActive maybe ?

2023-04-19 09:09 UTC, clarani commented on front/src/common/RollingStockSelector/RollingStockModal.jsx
> +    const filterIsEmpty = filterText || filters.elec || filters.thermal;
Done, thanks !! :smile:

2023-04-19 10:19 UTC, Math-R commented on front/src/common/RollingStockSelector/RollingStockModal.jsx
> +            const { rollingStockMetadata } = rollingStock;
LGTM ! 😃

2023-04-19 10:24 UTC, Math-R approved these changes

2023-04-19 10:47 UTC, nicolaswurtz approved these changes

2023-04-19 12:03 UTC, merged