front: i18n for editor's forms
OpenRailAssociation/osrd pull request #3845
Opened 2023-04-07 11:27 UTC by sim51

This PR fixes #2231 and  contains : 

- upgrade of rjsf to use the version 5
- using i18n validator for generic validator (like mandatory)
- convert the jsonschema to an i18n json schema
-  in dev mode, missing keys are written in console debug

/!\ Locale files were not populated, just a few  example are done

2023-04-09 22:21 UTC, nicolaswurtz requested changes
As said before, it's time ! Please create different files dedicated to translation for Editor, thanx :)

2023-04-09 22:21 UTC, nicolaswurtz commented on front/public/locales/fr/translation.json
Please create different files dedicated to translation for Editor, thanx !

2023-04-11 09:03 UTC, sim51 commented on front/public/locales/fr/translation.json
doing it right now

2023-04-11 11:14 UTC, sim51 commented on front/public/locales/fr/translation.json
Done in [c4a81da](https://github.com/DGEXSolutions/osrd/pull/3845/commits/c4a81da1370ba2415f5c6fb92a4d6cdc8693c9df)

2023-06-12 13:46 UTC, alexandredamiron commented
Plz rebase and check yarn.lock. @nicolaswurtz plz rereview

2023-11-20 10:23 UTC, closed without merging