editoast: add coreclient module & POST /pathfinding
OpenRailAssociation/osrd pull request #3879
Opened 2023-04-12 16:23 UTC by leovalais

2023-04-12 20:21 UTC, flomonster requested changes
Thanks for your PR.

2023-04-12 20:21 UTC, flomonster commented on docker-compose.yml
> +      OSRD_BACKEND_URL: "http://osrd-core"
This url is not valid (should use `http://localhost:8080`). We can use the default value.

```suggestion
```

2023-04-12 20:21 UTC, flomonster commented on editoast/src/client/mod.rs
> +    pub backend_token: String,
```suggestion
    #[clap(long, env = "OSRD_BACKEND_TOKEN", default_value_t = String::from(""))]
    pub backend_token: String,
```

2023-04-12 20:21 UTC, flomonster commented on editoast/src/schema/rolling_stock/mod.rs
> +#[derive(Debug, Default, Deserialize, Serialize)]
Unused.

2023-04-12 20:21 UTC, flomonster commented on editoast/src/main.rs
> +            )))
We could have a reqwest Client setting the backend URL and a default header containing the token. We won't need `CoreClient` after that change.

2023-04-12 20:21 UTC, flomonster commented on editoast/src/models/pathfinding.rs
> +        } = value;
Note: **Completely subjective**

 I don't find it very elegant when we have a lot of fields.

2023-04-12 20:21 UTC, flomonster commented on editoast/src/schema/coreclient/mod.rs
We could rename this module `core`. This file could be removed.
The idea of schema is to contain only struct definition (that can implement some trait if needed).

2023-04-12 20:21 UTC, flomonster commented on editoast/src/schema/coreclient/pathfinding.rs
> +}
We don't need to define this structure here (two possibilities to get rid of it):

1. Use this struct [here](https://github.com/DGEXSolutions/osrd/blob/d0098d19c08becfb30f39c6e29700236643aef7f/editoast/src/views/rolling_stocks.rs#L41-L60)
  - We can move it to the `src/schema/rolling_stock/mod.rs` and rename it.
2. Use the `schema::rolling_stock::RollingStock` that contains the `id`. Core accepts extra fields and it will simply be ignored.

2023-04-12 20:21 UTC, flomonster commented on editoast/src/views/pathfinding.rs
> +        .unwrap();
We should return a `PathfindingError::InfraNotFound` error instead of unwrapping.

2023-04-12 20:21 UTC, flomonster commented on editoast/src/views/pathfinding.rs
> +    let conn = &mut db_pool.get()?;
This must be done in a `actix_web::block` scope.

2023-04-12 20:21 UTC, flomonster commented on editoast/src/views/pathfinding.rs
This file contains a lot of functions not documented/tested.

2023-04-18 19:22 UTC, Khoyo commented on editoast/src/schema/coreclient/pathfinding.rs
> +}
Isn't that a `DirectionalTrackRange` ? https://github.com/DGEXSolutions/osrd/blob/5cfdb304d7e5ab9d8d2815ba645d1447af26fc56/editoast/src/schema/mod.rs#L208-L219

2023-04-20 05:45 UTC, Khoyo commented on editoast/src/models/pathfinding.rs
> +    pub payload: Option<diesel_json::Json<PathfindingPayload>>,
I believe `diesel_json::Json` is only meant for table definitions.

`serde_json::Value` (aka `JsonValue`) is the one you should be using, it has the proper `ToSql`/`FromSql` and is *way* nicer to use

2023-04-20 05:45 UTC, Khoyo commented on editoast/src/models/pathfinding.rs
> +    pub curves: Option<diesel_json::Json<CurveGraph>>,
Ditto

2023-04-20 07:48 UTC, leovalais commented on editoast/src/main.rs
> +            )))
Isn't it better to wrap that in another type? That would:

* let us have more than one `request::Client` that can be passed to the endpoints
* it's more explicit

Besides at this point we don't know which Core request will be performed (well, there's just pathfinding requests for now but I'm sure there will be more in the future) so we can't really set the client whole URL (`CoreClient::backend_url` is just `localhost:8000`). Cf. https://github.com/DGEXSolutions/osrd/pull/3879/files#diff-f4c7f592e6a63c477e5a3e2994833952dd90c90c7cf1d4f2debb3a6590d78f2cR53

2023-04-27 12:28 UTC, leovalais commented on editoast/src/main.rs
> +            )))
Update on that, `CoreClient` is now defined like so:

```rust
pub struct CoreClient(Arc<dyn Client>);
```

That allows us to switch to a `MockingClient` in unit tests to expect requests payloads and mock a response.

2023-04-27 12:31 UTC, leovalais commented on editoast/src/views/pathfinding.rs
I've added a few unit tests in order to show how core requests can be tested, but there will be a third PR for these endpoints that covers what's left to do (cf. PR desc). I planned to add the remaining unit tests there in order not to make this PR even bigger (and get core client merged faster), but I can add them now if you prefer.

2023-05-15 16:22 UTC, flomonster approved these changes

2023-05-15 16:45 UTC, merged