front: migrate DriverTrainSchedule files to ts
OpenRailAssociation/osrd pull request #3971
Opened 2023-04-20 15:29 UTC by clarani

2023-04-25 08:38 UTC, Uriel-Sautron reviewed
Good work, ok for me

2023-04-25 08:45 UTC, Uriel-Sautron approved these changes

2023-04-25 10:09 UTC, Akctarus approved these changes

2023-04-25 12:05 UTC, SharglutDev commented on front/src/applications/operationalStudies/components/SimulationResults/DriverTrainSchedule/DriverTrainScheduleHelpers.tsx
> +  if (sixthDigit >= 1 && sixthDigit < 5) {
There is a typo here, I think it should be `sixthDigit > 1` because "=1" is already checked at line 16.

But I had a hard time understanding the whole getTime function (Theo explained me that it should add a "+" at the end of the schedule if the second is between 15 and 44 and the minute should increment if second >= 45).
Do you think it's ok if we change the function to be like that : 
```suggestion
function getTime(sec) {
  let timeplus = new Date(sec * 1000);
  let time = timeplus.toISOString().substr(11, 8);
  const seconds = Number(time.slice(-2));
  if (seconds >= 15 && seconds <= 44) {
    return `${time.slice(0, 5)}+`;
  }
  if (seconds >= 45) {
    const minInMs = 60 * 1000;
    timeplus = new Date(sec * 1000 + minInMs);
    time = timeplus.toISOString().substr(11, 8);
  }
  return `${time.slice(0, 5)}`;
}
``` 
? :) (seems to be still working as expected for me and more understandable)

2023-04-25 16:02 UTC, anisometropie requested changes
good stuff :)

2023-04-25 16:02 UTC, anisometropie commented on front/src/applications/operationalStudies/components/SimulationResults/DriverTrainSchedule/DriverTrainSchedule.jsx
> -    <DriverTrainScheduleContent data={data} rollingStockSelected={rollingStockSelected} />
how does the selection work now ?

2023-04-25 16:02 UTC, anisometropie commented on front/src/applications/operationalStudies/components/SimulationResults/DriverTrainSchedule/DriverTrainScheduleHelpers.tsx
> +          <small> {stop.track_name}</small>
to remove

2023-04-25 16:02 UTC, anisometropie commented on front/src/applications/operationalStudies/components/SimulationResults/DriverTrainSchedule/DriverTrainScheduleHelpers.tsx
> +  if (sixthDigit >= 1 && sixthDigit < 5) {
Make another PR to isolate that specifically, This really needs to be tested before any such refactoring 
@SharglutDev

2023-04-28 14:29 UTC, clarani commented on front/src/applications/operationalStudies/components/SimulationResults/DriverTrainSchedule/DriverTrainScheduleHelpers.tsx
> +  if (sixthDigit >= 1 && sixthDigit < 5) {
Ok, I won't touch this !

2023-04-28 14:41 UTC, clarani commented on front/src/applications/operationalStudies/components/SimulationResults/DriverTrainSchedule/DriverTrainScheduleHelpers.tsx
> +          <small> {stop.track_name}</small>
Thanks, done !

2023-04-28 14:48 UTC, anisometropie approved these changes

2023-04-28 15:05 UTC, merged