front:ensure right section is not there if stdcm fail
OpenRailAssociation/osrd pull request #3972
Opened 2023-04-20 15:53 UTC by alexandredamiron

Just warn the user if stdcm request fail and keep the map

<img width="1720" alt="Capture d’écran 2023-04-20 à 17 52 47" src="https://user-images.githubusercontent.com/765626/233420527-c1f80749-982a-4ee6-b9ef-562379b12c0a.png">

2023-04-21 14:43 UTC, clarani commented on front/public/locales/fr/stdcm.json
> +}
```suggestion
}

```
Missing new line

2023-04-21 14:43 UTC, clarani commented on front/src/styles/scss/applications/_stdcm.scss
> +}
```suggestion
}

```
Missing new line

2023-05-05 08:24 UTC, clarani approved these changes

2023-06-12 13:50 UTC, Yohh approved these changes
LGTM

2023-09-05 10:17 UTC, clarani requested changes
You need to squash your commits before merging

2023-10-12 10:29 UTC, closed without merging