front: migrate RTK endpoint in Study.tsx
OpenRailAssociation/osrd pull request #4067
Opened 2023-05-09 14:58 UTC by SarahBellaha

Closes #4050

2023-05-22 14:52 UTC, clarani requested changes
Nice PR :)

2023-05-22 14:52 UTC, clarani commented on front/src/applications/operationalStudies/views/Study.tsx
> -      navigate('/operational-studies/project');
I think you should keep this: if there is no studyId or no projectId, we should redirect the user :) But this can be done outside the useEffect if possible ?

2023-05-22 14:52 UTC, clarani commented on front/src/applications/operationalStudies/views/Study.tsx
> +    }
```suggestion
    {
      skip: !projectId,
      selectFromResult: (response) => ({
        ...response,
        project: response.data,
      }),
    }
```
We should also skip this call if there is no projectId

2023-05-22 14:52 UTC, clarani commented on front/src/applications/operationalStudies/views/Study.tsx
> +  const { data: studyStates, isError: studyStateError } =
```suggestion
  const { data: studyStates, isError: isStudyStateError } =
```
Can you harmonize the name of the isError variables ? :)

2023-05-22 14:52 UTC, clarani commented on front/src/applications/operationalStudies/views/Study.tsx
> +  const { study, isError: currentStudyError } =
```suggestion
  const { study, isError: isCurrentStudyError } =
```

2023-05-22 14:52 UTC, clarani commented on front/src/applications/operationalStudies/views/Study.tsx
> +          message: t('rollingstock:errorMessages.unableToRetrieveRollingStockMessage'),
I think you should modify the error text :) You can add a new message in `study.json`, for instance 
```
{
  "unableToRetrieveStudyState": "Echec de la récupération des types d'étude",
  "errorHappened": "Une erreur est survenue",  
}
```

We order the translation by alphabetical order for information

2023-05-22 14:52 UTC, clarani commented on front/src/applications/operationalStudies/views/Study.tsx
> +          message: t('errorMessages.errorNoFrom'),
Same here, you need to write new messages in study.json

2023-05-22 14:52 UTC, clarani commented on front/src/applications/operationalStudies/views/Study.tsx
> +      );
```suggestion
```
You can totally remove this function, and move the notification directly in the `AddOrEditStudyModal`, in `updateStudy` :)

2023-05-22 14:52 UTC, clarani commented on python/api/openapi.yaml
> +                  enum: ["started", "inProgress", "finish"]
Nice, thanks ! :)

2023-05-22 14:52 UTC, clarani commented on front/src/config/openapi-editoast-config.ts
> +  tag: true,
Why have you added this ?

2023-05-25 11:50 UTC, Khoyo approved these changes
This no longer has anything to do with `core`, github is just being dumb

2023-05-30 12:59 UTC, Khoyo commented
Please don't forget to `squash and merge` ;)

2023-05-30 13:57 UTC, flomonster requested changes

2023-05-30 13:57 UTC, flomonster commented on python/api/openapi.yaml
> +                  enum: ["started", "inProgress", "finish"]
This endpoint is used to retrieve the possible values. It will be soon fixed in the openapi (then we can delete this endpoint).

2023-05-30 16:09 UTC, clarani reviewed
I left some comments ! :)

2023-05-30 16:09 UTC, clarani commented on front/src/applications/operationalStudies/components/Study/AddOrEditStudyModal.tsx
> +  const formatDateForInput = (date?: string | null) => (date ? date.substring(0, 11) : '');
Why have you change 10 to 11 here ? (just to check)

2023-05-30 16:09 UTC, clarani commented on front/src/applications/operationalStudies/components/Study/AddOrEditStudyModal.tsx
> +    if (!currentStudy) {
```suggestion
    if (!currentStudy?.name) {
```
Here we need to check that the new study has at least a name

2023-05-30 16:09 UTC, clarani commented on front/src/applications/operationalStudies/components/Study/AddOrEditStudyModal.tsx
> +      }).then(() => {
I think it's clearer when we use directly the result of the request like this (you can have a look at AddOrEditProjectModal.tsx)
```suggestion
      })
        .unwrap()
        .then((createdStudy) => {
```

2023-05-30 16:09 UTC, clarani commented on front/src/applications/operationalStudies/components/Study/AddOrEditStudyModal.tsx
> +                  {studyCategories && (
We need to check that studyCategories is not empty (because by default, it is [], so the current condition will always be true
```suggestion
                  {!isEmpty(studyCategories) && (
```

2023-05-30 16:09 UTC, clarani commented on front/src/applications/operationalStudies/components/Study/AddOrEditStudyModal.tsx
> +                  {studyStates && (
Same here
```suggestion
                  {!isEmpty(studyStates) && (
```

2023-05-30 16:09 UTC, clarani commented on front/src/applications/operationalStudies/views/Study.tsx
> +  );
It's the same thing, bu shorter :) 
```suggestion
  const { data: project, isError: isProjectError } = osrdEditoastApi.useGetProjectsByProjectIdQuery(
    { projectId: projectId as number },
    {
      skip: !projectId,
    }
  );
```

2023-05-30 16:09 UTC, clarani commented on front/src/applications/operationalStudies/views/Study.tsx
> +    });
```suggestion
  const { data: studyStates, isError: isStudyStateError } =
    osrdMiddlewareApi.useGetProjectsStudyStatesQuery();
```

2023-05-30 16:09 UTC, clarani commented on front/src/applications/operationalStudies/views/Study.tsx
> +    );
```suggestion
  const { data: study, isError: isCurrentStudyError } =
    osrdEditoastApi.useGetProjectsByProjectIdStudiesAndStudyIdQuery(
      {
        projectId: projectId as number,
        studyId: studyId as number,
      },
      {
        skip: !projectId || !studyId,
      }
    );
```

2023-05-30 16:09 UTC, clarani commented on front/src/applications/operationalStudies/views/Study.tsx
> +                        openModal(<AddOrEditStudyModal editionMode study={study} />, 'xl')
NIce !! :D

2023-05-30 16:09 UTC, clarani commented on front/src/applications/operationalStudies/views/Study.tsx
>                    {study.state && (
This way, you can remove the ? (line 280)
```suggestion
                  {study.state && studyStates && (
```

2023-05-30 16:51 UTC, clarani reviewed
I left some comments ! :)

2023-06-05 15:58 UTC, clarani reviewed
LGTM, but need to fix some TS errors !

2023-06-05 15:58 UTC, clarani commented on front/src/applications/operationalStudies/components/Study/AddOrEditStudyModal.tsx
> +type OptionsList = undefined | StudyType[] | StudyState[];
```suggestion
type OptionsList = StudyType[] | StudyState[];
```

2023-06-05 15:58 UTC, clarani commented on front/src/applications/operationalStudies/components/Study/AddOrEditStudyModal.tsx
> +    Object.keys(StudyStates).filter((item) => Number.isNaN(Number(item))) as StudyState[]
```suggestion
    studyStates
```

2023-06-05 15:58 UTC, clarani commented on front/src/applications/operationalStudies/components/Study/AddOrEditStudyModal.tsx
> +    Object.keys(StudyTypes).filter((item) => Number.isNaN(Number(item))) as StudyType[]
```suggestion
    StudyTypes
```

2023-06-05 15:58 UTC, clarani commented on editoast/openapi.yaml
Need @younesschrifi's review :)

2023-06-09 14:30 UTC, clarani approved these changes
LGTM !! Nice work :muscle:

2023-06-23 10:48 UTC, flomonster approved these changes

2023-06-23 13:12 UTC, merged