editoast: fix infra update
OpenRailAssociation/osrd pull request #4136
Opened 2023-05-16 16:37 UTC by Erashin

Remove default values in infra model (except modified_date which must be always modified) and replace them with Option. Set default values at creation. Default values will not be set at update anymore.

Fixes #4108.

2023-05-17 15:07 UTC, flomonster requested changes
Thanks for this bug fix. Except for the unnecessary query param, everything looks good to me.

2023-05-17 15:07 UTC, flomonster commented on editoast/openapi.yaml
> +            type: bool
We don't need to specify if an empty infra should be locked or not.

2023-05-22 06:29 UTC, Erashin commented on editoast/openapi.yaml
> +            type: bool
100%. Confusion with my other PR. Will get rid of this.

2023-05-22 15:05 UTC, clarani reviewed
LGTM

2023-05-23 07:50 UTC, leovalais approved these changes

2023-05-23 09:57 UTC, flomonster approved these changes
LGTM. Thanks for this bug fix :tada:

2023-05-25 12:41 UTC, merged