editoast: fix osrd_search_operationalpoint.uic type
OpenRailAssociation/osrd pull request #4140
Opened 2023-05-17 09:51 UTC by leovalais

The uic column type was `text`, which is wrong, and was declared as being an int in search.yml.

**The trigram column type was changed to VARCHAR(3) which would make sense for a trigram, but is it always true in practice? (It is in the DB, at least for now)**

Required by #4139

2023-05-24 05:49 UTC, laggron42 approved these changes

2023-05-24 07:25 UTC, laggron42 requested changes
The Django migration file must be renamed to `30`, as there are existing migrations with numbers `28` and `29`.

2023-05-24 16:08 UTC, flomonster approved these changes

2023-05-25 07:40 UTC, laggron42 approved these changes

2023-05-30 12:08 UTC, merged