delays: fix cases with several events at same location
OpenRailAssociation/osrd pull request #421
Opened 2021-12-13 15:31 UTC by eckter

2021-12-14 15:57 UTC, multun requested changes

2021-12-14 15:57 UTC, multun commented on core/src/main/java/fr/sncf/osrd/train/Train.java
> +        lastState.nextDepartureTime = time;
that should be done inside the change `apply`

2021-12-15 09:19 UTC, flomonster approved these changes, later dismissed

2022-02-03 09:23 UTC, flomonster submitted a review, later dismissed

2022-02-03 09:45 UTC, multun commented on core/src/main/java/fr/sncf/osrd/train/Train.java
> +        new TrainStopChange(sim, this, time, stopIndex).apply(sim);
this change needs to be logged

2022-02-04 09:38 UTC, multun approved these changes

2022-02-04 09:38 UTC, merged