migration of GET /infra/schema endpoint
OpenRailAssociation/osrd pull request #4278
Opened 2023-06-05 16:18 UTC by leovalais

2023-06-06 13:57 UTC, multun approved these changes

2023-06-06 14:44 UTC, flomonster requested changes
We should delete this endpoint and move the json schema to the front sources.

2023-06-06 14:44 UTC, flomonster commented on .github/workflows/editoast.yml
> +            diff current_infra_schema.json ../../editoast/src/views/infra/infra_schema.json
We should do this in `osrd_schema.yml`. So we check that only when the python schema changes.

2023-06-08 09:29 UTC, flomonster approved these changes
LGTM

2023-06-12 08:50 UTC, Math-R approved these changes
LGTM !

2023-06-12 09:39 UTC, merged