Change route def in railjson
OpenRailAssociation/osrd pull request #43
Opened 2021-05-10 14:55 UTC by eckter

Fixes #42 

Route:
```json
    {
      "id": "rt.C1-S7",
      "entry_point": "buffer_stop_b",
      "switches_position": {
        "il.switch_foo": "RIGHT"
      },
      "release_groups": [
        [
          "tvd.track"
        ],
        [
          "tvd.switch_foo"
        ]
      ]
    }
```

Signal:
```json
{
  "expr": {
    "type": "call",
    "function": "warn_signal",
    "arguments": [
      {
        "type": "signal",
        "signal": "il.sig.C6"
      }
    ]
  },
  "id": "il.sig.W4",
  "applicable_direction": "REVERSE",
  "position": 1025,
  "sight_distance": 400,
  "linked_detector": "tde.foo_a-switch_foo"
}
```

Railjson:
- [ ] Suppress `waypoints` field
- [ ] Add `entry_point`. Takes a `waypoint`.
- [ ] Add field `linked_detector` for signal. This field is optional.

Core:
- [ ] `RouteGraph.makeRoute()` must retrieve `TVDSectionPath` from `entryPoint` and `tvdSections`.
- [ ] If `entry_point` is a detector then we must have at least one signal linked to it.

RailML:
- [ ] Adapt railml parser.

2021-05-11 15:14 UTC, eckter commented on examples/tiny_infra/infra.json
>        },
This was an error in the infra and required some changes in the tests

2021-05-12 12:14 UTC, flomonster requested changes
Can you fix the example `circular_infra` ?

2021-05-12 12:14 UTC, flomonster commented on src/main/java/fr/sncf/osrd/infra/signaling/Signal.java
> +import fr.sncf.osrd.infra.trackgraph.Detector;
Unused import

2021-05-12 13:27 UTC, flomonster approved these changes

2021-05-12 13:36 UTC, merged