editoast: detect spacing conflicts
OpenRailAssociation/osrd pull request #4339
Opened 2023-06-12 08:49 UTC by Khoyo

2023-06-12 08:50 UTC, multun commented on core/src/main/java/fr/sncf/osrd/infra/implementation/tracks/undirected/UndirectedInfraBuilder.java
> +            deadSections = new ArrayList<>();
how about just returning?

2023-06-12 08:53 UTC, Khoyo commented on core/src/main/java/fr/sncf/osrd/infra/implementation/tracks/undirected/UndirectedInfraBuilder.java
> +            deadSections = new ArrayList<>();
Sure

2023-06-12 09:13 UTC, multun requested changes

2023-06-12 09:13 UTC, multun commented on editoast/src/models/train_schedule.rs
> +    #[serde(rename = "isEntry")]
```suggestion
    // TODO: see https://github.com/DGEXSolutions/osrd/issues/4294
    #[serde(rename = "isEntry")]
```

2023-06-12 09:13 UTC, multun commented on editoast/src/views/timetable.rs
> +}
```suggestion
}

```

2023-06-12 09:13 UTC, multun commented on editoast/src/views/timetable.rs
> +        );
this loop runs N sql requests, when N is the number of trains in the timetable; that's not great, can you run a single request instead?

2023-06-12 09:13 UTC, multun commented on editoast/src/views/timetable.rs
> +            let start_time = conflict[0].begin.round() as u64; // FIXME: those aren't actually the conflict times
do you want it merged without the fix?

2023-06-15 07:04 UTC, multun approved these changes

2023-06-16 07:34 UTC, merged