editoast: add TrainSchedule id
OpenRailAssociation/osrd pull request #4390
Opened 2023-06-19 15:18 UTC by Akctarus

2023-06-20 07:45 UTC, flomonster approved these changes

2023-06-20 07:46 UTC, flomonster requested changes
You must generate the rtk files.

2023-06-20 08:23 UTC, younesschrifi approved these changes

2023-06-20 08:29 UTC, Akctarus commented
> You must generate the rtk files.

Done

2023-06-20 22:36 UTC, younesschrifi approved these changes

2023-06-21 12:22 UTC, flomonster approved these changes

2023-07-21 12:45 UTC, Akctarus commented
not needed anymore. Already fixed

2023-07-21 12:45 UTC, closed without merging