core: avoid adding an invalid cache entry when using an unloaded infra
OpenRailAssociation/osrd pull request #4496
Opened 2023-07-04 13:27 UTC by eckter

Fixes a bug that would prevent infra loading when receiving a request before the infra has started loading.

We would put a default `InfraCacheEntry` (`INITIALIZING`) when missing from the cache, but the infra isn't actually being loaded.

2023-07-04 13:32 UTC, flomonster approved these changes

2023-07-04 14:17 UTC, Erashin approved these changes

2023-07-05 09:20 UTC, multun requested changes

2023-07-05 09:20 UTC, multun commented on core/src/main/java/fr/sncf/osrd/api/InfraManager.java
> +            var cacheEntry = infraCache.getOrDefault(infraId, new InfraCacheEntry());
I don't think that's right. Sure, it's better than what was there before, but not great either: if the new InfraCacheEntry is used:

 - either loadIfMissing is true, and it's just discarded
 - or elaborate checks run on this cache entry, which is just empty

I would rather do something like
```java
            var cacheEntry = infraCache.get(infraId);
            if (cacheEntry == null)
                // return an error or something
```

2023-07-26 08:18 UTC, multun approved these changes

2024-01-18 12:43 UTC, Khoyo approved these changes

2024-01-18 12:56 UTC, merged