api: editoast: add rollingstock_version and rename railjson_version field
OpenRailAssociation/osrd pull request #4593
Opened 2023-07-17 13:36 UTC by younesschrifi

close #4584

2023-07-18 10:05 UTC, Akctarus reviewed
LGTM for the front part

2023-07-18 10:27 UTC, multun commented
I have questions:
 - my understanding is that the new version fields get incremented as the infrastructure changes. I don't think it's a good idea to call that "version" is the name is already used for something else. How about "generation"?
 - why store it inside railjson at all? For all I know, it could be external metadata, hidden inside editoast

2023-07-18 16:14 UTC, flomonster commented
> I have questions:
> 
>     * my understanding is that the new version fields get incremented as the infrastructure changes. I don't think it's a good idea to call that "version" is the name is already used for something else. How about "generation"?

We want to rename the existing field to `railjson_version` to be consistent with the infra.

>     * why store it inside railjson at all? For all I know, it could be external metadata, hidden inside editoast

I agree, we don't need to expose this field outside editoast.

2023-07-19 08:43 UTC, clarani approved these changes
Front looks good to me, tested in local

2023-07-19 12:56 UTC, flomonster requested changes
Thanks for the PR.
I didn't tested it yet (waiting for the rename)

2023-07-19 12:56 UTC, flomonster commented on python/api/osrd_infra/models/rolling_stock.py
> +    rollingstock_version = models.BigIntegerField(help_text=_("Rolling stock version"), default=0)
We can keep the name `version` to match the infra model

2023-07-19 12:56 UTC, flomonster commented on tests/fuzzer/fuzzer.py
> +    print(schedule_payload)
```suggestion
```

2023-07-19 12:56 UTC, flomonster commented on tests/tests/test_regressions.py
> +    print(payload)
```suggestion
```

2023-07-19 12:56 UTC, flomonster commented on core/src/main/java/fr/sncf/osrd/api/pathfinding/PathfindingRoutesEndpoint.java
> +
```suggestion
```

2023-07-19 15:00 UTC, flomonster approved these changes
LGTM (tested)

2023-07-19 15:09 UTC, Tguisnet approved these changes
LGTM

2023-07-20 08:11 UTC, eckter approved these changes

2023-07-20 13:00 UTC, merged