Migrate conflict detection from core to editoast
OpenRailAssociation/osrd pull request #4601
Opened 2023-07-18 13:35 UTC by Khoyo

Fixes #4577

2023-07-18 16:45 UTC, flomonster approved these changes
Reviewed the editoast part.

2023-07-18 17:46 UTC, Tguisnet approved these changes
LGTM for Editoast part

2023-07-19 13:06 UTC, multun requested changes

2023-07-19 13:06 UTC, multun commented on core/src/main/java/fr/sncf/osrd/api/ConflictDetectionEndpoint.java
> +            public final String conflictType;
Not a fan of that, can you make it an enum?

2023-07-19 13:24 UTC, multun approved these changes

2023-07-19 14:11 UTC, merged