Add more getting started infos in README.md
OpenRailAssociation/osrd pull request #468
Opened 2022-01-09 21:46 UTC by KikiManjaro

Feel free to add modifications to what i've written :) you know the project better than me

2022-01-11 14:18 UTC, flomonster approved these changes, later dismissed

2022-01-11 14:25 UTC, multun requested changes

2022-01-11 14:25 UTC, multun commented on README.md
> +Run this command in root of this project should start the docker :
This command shouldn't run as root, you only have to be in the proper group. Typography rules in English also are different: there are no spaces before colons.

2022-01-11 14:25 UTC, multun commented on README.md
> +You can find install process right [here](https://docs.docker.com/compose/install/).
Can you keep the list just like previously, and just add the links to the install page? People also still need to install docker, installing just docker-compose wont work (even though both are packaged together on windows)

2022-01-11 14:53 UTC, KikiManjaro commented on README.md
> +You can find install process right [here](https://docs.docker.com/compose/install/).
Ok, done :)

2022-01-11 14:56 UTC, KikiManjaro commented on README.md
> +Run this command in root of this project should start the docker :
As I'm saying :
This command should be run in root of this project (such as 'osrd/')
I'm not saying that this command should be run as root user. Please tell me if you have a better way to explain that.

I've removed the space, my bad :)

2022-01-14 14:12 UTC, multun commented
@KikiManjaro just so you know, we have not forgotten this PR, we'd just like to add some more stuff to it

2022-05-04 14:41 UTC, multun commented
We're making a documentation website which already contains most of what's in there. I'll change this PR to add a link to this documentation once it's in a satisfying state

https://dgexsolutions.github.io/osrd-website/fr/developers/

2023-02-09 18:30 UTC, multun commented
Time has passed, and a lot of things have changed (including the README). I don't think it makes sense to merge anymore

2023-02-09 18:30 UTC, closed without merging