editoast: fix train schedule get endpoints
OpenRailAssociation/osrd pull request #4722
Opened 2023-08-01 13:57 UTC by Khoyo

2023-08-01 14:33 UTC, multun commented on tests/tests/test_train_schedule.py
> +    print(schedules)
I'm pretty sure it's not meant to be here

2023-08-01 15:03 UTC, multun approved these changes

2023-08-03 09:18 UTC, Tguisnet requested changes

2023-08-03 09:18 UTC, Tguisnet commented on tests/tests/test_train_schedule.py
>      ).json()  # TODO: switch this to editoast
This comment is not needed anymore

2023-08-03 09:27 UTC, flomonster approved these changes
LGTM. Thanks for the fix!

2023-08-03 09:32 UTC, Tguisnet approved these changes

2023-08-03 10:31 UTC, merged