Refactor dead sections
OpenRailAssociation/osrd pull request #4726
Opened 2023-08-02 10:15 UTC by Castavo

In this PR there is, for now
* Removal of an unused field (planned to use it but it got scrapped)
* Renaming of classes and attributes

2023-08-03 16:11 UTC, clarani reviewed
Great PR, thank you :pray:
I can approve the frontend part once the PR is ready (I will have to test)

2023-08-04 15:43 UTC, multun requested changes

2023-08-04 15:43 UTC, multun commented on core/kt-osrd-sim-infra/src/main/kotlin/fr/sncf/osrd/sim_infra/api/TrackProperties.kt
> +    fun getTrackChunkNeutralSection(trackChunk: DirTrackChunkId): DistanceRangeMap<NeutralSection>
```suggestion
    fun getTrackChunkNeutralSections(trackChunk: DirTrackChunkId): DistanceRangeMap<NeutralSection>
```

2023-08-04 15:43 UTC, multun commented on core/kt-osrd-sim-infra/src/main/kotlin/fr/sncf/osrd/sim_infra/impl/RawInfraImpl.kt
> +    override fun getTrackChunkNeutralSection(trackChunk: DirTrackChunkId): DistanceRangeMap<NeutralSection> {
```suggestion
    override fun getTrackChunkNeutralSections(trackChunk: DirTrackChunkId): DistanceRangeMap<NeutralSection> {
```

2023-08-04 15:43 UTC, multun commented on core/osrd-railjson/src/main/java/fr/sncf/osrd/railjson/schema/infra/RJSInfra.java
> +    public static final transient String CURRENT_VERSION = "3.6.0";
That's quite a bump, why is that?

2023-08-04 15:43 UTC, multun commented on editoast/src/tests/small_infra/small_infra.json
> +    "version": "3.6.0",
This will need a rebase once https://github.com/osrd-project/osrd/pull/4728 is merged

2023-08-04 16:06 UTC, multun commented
A very nice PR, thanks :) Please change it as you see fit, and ask @flomonster to merge it you think it's ready (all core maintainers are away next week)

2023-08-07 09:07 UTC, flomonster approved these changes
Thanks for this PR!
LGTM

2023-08-07 16:01 UTC, clarani approved these changes
Front looks good to me, tested in local :heavy_check_mark:

2023-08-08 08:27 UTC, younesschrifi approved these changes
LGTM

2023-08-08 12:27 UTC, merged