editoast : remove invalid trains from results
OpenRailAssociation/osrd pull request #4773
Opened 2023-08-08 21:49 UTC by younesschrifi

Close #4700

2023-08-10 12:28 UTC, leovalais requested changes
Read the code and left a few comments, let me know if you want to discuss those :)
I'll test your changes a bit later

2023-08-10 12:28 UTC, leovalais commented on editoast/src/models/timetable.rs
> +                .unwrap()
Better use `expect` in case something breaks

2023-08-10 12:28 UTC, leovalais commented on editoast/src/views/stdcm/mod.rs
> +    let train_schedules = schedules.clone();
Can't you return the moved `schedules` in the closure below and avoid cloning?

2023-08-10 12:28 UTC, leovalais commented on editoast/src/views/train_schedule/mod.rs
> +    let schedules = block::<_, Result<_>>(move || {
Can you try to factorize this part (and the STDCM one) to keep that function smaller?

2023-08-11 14:14 UTC, leovalais requested changes
A few extra clones that I didn't spot last time, but otherwise LGTM, I'll try to test it locally today

2023-08-11 14:14 UTC, leovalais commented on editoast/src/models/timetable.rs
> +                .expect("error while retrieving infra")
```suggestion
                .expect("could not retrieve the version of the infra of a scenario using its timetable")
```

2023-08-11 14:14 UTC, leovalais commented on editoast/src/models/train_schedule.rs
> +                LightRollingStockModel::retrieve_conn(&mut conn, schedule.rolling_stock_id)
The `block` is unnecessary, you can just `retrieve(db_pool, id)` the LightRollingStock.

2023-08-11 14:14 UTC, leovalais commented on editoast/src/views/train_schedule/mod.rs
> +    if schedules.clone().is_empty() {
```suggestion
    if schedules.is_empty() {
```

2023-08-11 14:14 UTC, leovalais commented on editoast/src/views/stdcm/mod.rs
> +                .clone()
```suggestion
```

You don't need to clone the whole Vec here

2023-08-13 15:58 UTC, younesschrifi commented on editoast/src/models/train_schedule.rs
> +                LightRollingStockModel::retrieve_conn(&mut conn, schedule.rolling_stock_id)
the problem here is that `retain` function can't have an async block in it. That's why I used the `block`.

2023-08-14 14:08 UTC, leovalais approved these changes
Tested both /train_schedule/results and /stdcm using curl.
The OpenAPI needs to be updated, either change `openapi_legacy.myl` or add utoipa annotations (you can ask Auguste to show you, he's done it a bunch of times already). If you decide to use utoipa, please make a different commit to help with the review :)

2023-08-14 15:24 UTC, merged