renamed Panel to Sign in the backend.
OpenRailAssociation/osrd pull request #4810
Opened 2023-08-14 07:51 UTC by Bubullzz

Also need a front to finish the rename in the front-end.

2023-09-04 12:57 UTC, kmer2016 commented
editoast docker didn't start anymore

2023-09-05 08:53 UTC, flomonster requested changes
Thanks for the PR.
I only reviewed `python` and `editoast`. Waiting for final version to test it.

2023-09-05 08:53 UTC, flomonster commented on python/api/osrd_infra/migrations/0047_rename_lpvsignlayer_pslsignlayer.py
This can be merged with this migration: `python/api/osrd_infra/migrations/0046_rename_lpvpanellayer_lpvsignlayer.py`

2023-09-12 14:54 UTC, clarani commented
This PR will be merged after the drop of API, so I convert it to draft again

2023-10-02 13:00 UTC, leovalais reviewed
LGTM, left a few questions

2023-10-02 13:00 UTC, leovalais commented on editoast/src/generated_data/psl_sign.rs
> +pub struct PSLSignLayer;
I'd like someone to weigh on this but I'd rather have it named `PslSignLayer` to respect the CamelCase convention.

2023-10-02 13:00 UTC, leovalais commented on editoast/src/schema/speed_section.rs
> +pub struct SpeedSectionPslSncfExtension {
That's nitpicking but are there speed sections that are not speed limits? If not, `PermanentSpeedSectionSncfExtension` seems less redundant to me, but I'm ok with both.

2023-10-03 12:08 UTC, multun commented on editoast/src/generated_data/psl_sign.rs
> +pub struct PSLSignLayer;
I like PSLSign better

2023-10-03 12:09 UTC, multun commented on editoast/src/schema/speed_section.rs
> +pub struct SpeedSectionPslSncfExtension {
it's just a rename, let's leave this for later

2023-10-03 12:10 UTC, multun approved these changes

2023-10-03 12:16 UTC, eckter approved these changes
minor typo, otherwise LGTM (I didn't check front or editoast changes)

2023-10-03 12:16 UTC, eckter commented on python/osrd_schemas/osrd_schemas/infra.py
> +    This is a physical, ponctual, cosmetic object.
```suggestion
    This is a physical, punctual, cosmetic object.
```

2023-10-04 08:47 UTC, flomonster approved these changes
LGTM

Reviewed and tested.

2023-10-04 08:47 UTC, flomonster commented on editoast/src/generated_data/psl_sign.rs
> +pub struct PSLSignLayer;
Personally, I don't have preferences.  We can keep it that way.

2023-10-04 09:16 UTC, clarani commented on python/osrd_schemas/osrd_schemas/infra.py
> +    This is a physical, ponctual, cosmetic object.
Fixed, thanks !

2023-10-04 09:40 UTC, clarani approved these changes
LGTM, tested in local :heavy_check_mark: 
- all the maps: simulationMap (manageTrainSchedule and SimulationRestults), referenceMap, EditorMap, Stdcm
- pls edition

2023-10-04 10:35 UTC, merged