add a new Duration class in utils
OpenRailAssociation/osrd pull request #5010
Opened 2023-09-08 15:12 UTC by anglnn

New class just like Distance.

Acceptance criteria

**A list of conditions which define when this task shall be considered complete:**

- [ ] We have a time place
- [ ] It is used in everywhere it can be in the kotlin code. Java can't do that efficiently however as it lacks value types.

2023-09-11 07:40 UTC, multun requested changes

2023-09-11 07:40 UTC, multun commented on core/kt-osrd-utils/src/main/kotlin/fr/sncf/osrd/utils/units/Duration.kt
> +        fun fromSeconds(seconds: Double) = Duration(milliseconds = (seconds * 1_000.0).toLong())
```suggestion
        @JvmStatic
        @JvmName("fromSeconds")
        fun fromSeconds(time: Double): Duration = time.seconds
        @JvmStatic
        @JvmName("toSeconds")
        fun fromSeconds(time: Duration): Double = time.seconds
```

These methods are meant to help work with Durations from java

2023-09-11 07:40 UTC, multun commented on core/kt-osrd-utils/src/main/kotlin/fr/sncf/osrd/utils/units/Duration.kt
> +value class Duration(val milliseconds: Long) : Comparable<Duration> {
Can you add a toString method, like the one Distance has? It helps display the type while debugging

2023-09-11 09:53 UTC, Khoyo commented on core/kt-osrd-utils/src/main/kotlin/fr/sncf/osrd/utils/units/Duration.kt
> +val Int.seconds: Duration get() = Duration(this.toLong() * 1000)
Missing newline at EOF

2023-09-19 12:13 UTC, multun approved these changes

2023-09-19 12:15 UTC, merged