editoast: add macros schemas! and routes!
OpenRailAssociation/osrd pull request #5044
Opened 2023-09-13 17:35 UTC by leovalais

Part of #3625

2023-09-15 10:35 UTC, flomonster requested changes
Thanks for this PR.
I made a few suggestions.
I'm not a declarative macro expert so I hope I didn't miss something.

2023-09-15 10:35 UTC, flomonster commented on editoast/src/views/mod.rs
> +fn remove_discriminator(schema: &mut RefOr<Schema>) {
We could move this to the `openapi` module.

2023-09-15 10:35 UTC, flomonster commented on editoast/src/views/mod.rs
> +        }
We could make a function for this

2023-09-15 10:35 UTC, flomonster commented on editoast/src/views/mod.rs
> +fn routes_v2() -> Routes<impl HttpServiceFactory> {
We could add a comment to explain that this is temporarily used for the migration to utoipa.

2023-09-15 10:35 UTC, flomonster commented on editoast/src/views/mod.rs
> +    }
Shouldn't we call `timetable::routes()` here?

2023-09-15 16:05 UTC, flomonster approved these changes

2023-09-16 15:51 UTC, Akctarus approved these changes
LGTM

2023-09-18 13:43 UTC, clarani requested changes

2023-09-18 13:43 UTC, clarani commented on front/src/modules/conflict/components/ConflictsList.tsx
>  export type Conflict = {
Can you remove this type and use the new one from osrdEditoastApi ? :) Also you should use the new type in Timetable.tsx too

2023-09-29 13:48 UTC, clarani approved these changes
LGTM, tested in local ! :heavy_check_mark:

2023-09-29 14:07 UTC, merged