front: fix wrong selection when updating train
OpenRailAssociation/osrd pull request #5139
Opened 2023-09-22 13:32 UTC by SharglutDev

and refacto getSimulationResults with rtk

close #5135

2023-09-29 11:52 UTC, leovalais approved these changes

2023-09-29 16:14 UTC, clarani requested changes
Only left 1 comment :)

2023-09-29 16:14 UTC, clarani commented on editoast/openapi.yaml
Nice !! :tada:

2023-09-29 16:14 UTC, clarani commented on front/src/applications/operationalStudies/components/Scenario/getSimulationResults.ts
> +    if (!selectedTrainId || trainSchedulesIDs.length === 1) {
You should update the selectedTrainId (with the id of the first trainSchedule) if:
- selectedTrainId is undefined
- selectedTrainId is not in trainSchedulesIds

```suggestion
    if (!selectedTrainId || !trainSchedulesIDs.includes(selectedTrainId)) {
```

2023-09-29 16:14 UTC, clarani commented on front/src/applications/operationalStudies/components/Scenario/getSimulationResults.ts
> +      store.dispatch(updateSelectedTrainId(timetable.train_schedule_summaries[0].id));
```suggestion
      store.dispatch(updateSelectedTrainId(trainSchedulesIDs[0]));
```

2023-10-02 07:56 UTC, SharglutDev commented on front/src/applications/operationalStudies/components/Scenario/getSimulationResults.ts
> +    if (!selectedTrainId || trainSchedulesIDs.length === 1) {
Done :)

2023-10-02 07:57 UTC, SharglutDev commented on front/src/applications/operationalStudies/components/Scenario/getSimulationResults.ts
> +      store.dispatch(updateSelectedTrainId(timetable.train_schedule_summaries[0].id));
Done :)

2023-10-02 09:54 UTC, clarani approved these changes
LGTM and tested on my local !

2023-10-02 12:54 UTC, merged