Refacto store:  userSlice
OpenRailAssociation/osrd pull request #5188
Opened 2023-10-03 13:23 UTC by Uriel-Sautron

close #5173 
- Creating userSlice
- Create userSelector and use it in the application
- Creating tests for userSlice

2023-10-03 14:17 UTC, kmer2016 commented
Well done ! Just, In the "common" folder, I would have called the reducer store folder because it actually contains a bit more than just reducers (reducer, slice, selectors)

2023-10-03 15:47 UTC, anisometropie requested changes

2023-10-03 15:47 UTC, anisometropie commented on front/src/main/home.jsx
> -      <NavBarSNCF appName="OSRD" username={user.username} logo={logo} />
this wasn’t used anymore ?

2023-10-03 15:47 UTC, anisometropie commented on front/src/reducers/__tests__/userReducer.spec.ts
> +    const action = loginSuccess({ accessToken: '', username: 'Test userSlice' });
```suggestion
    const action = loginSuccess({ accessToken: 'fake_token', username: 'Test userSlice' });
```
Here use something that’s not going to be a default value, or something that can end up here by chance

2023-10-03 15:47 UTC, anisometropie commented on front/src/reducers/__tests__/userReducer.spec.ts
> +      accessToken: '',
```suggestion
      accessToken: 'fake_token',
```

2023-10-03 18:07 UTC, Uriel-Sautron commented on front/src/reducers/__tests__/userReducer.spec.ts
> +    const action = loginSuccess({ accessToken: '', username: 'Test userSlice' });
Thank you, done !!

2023-10-03 18:07 UTC, Uriel-Sautron commented on front/src/reducers/__tests__/userReducer.spec.ts
> +      accessToken: '',
Done

2023-10-03 20:37 UTC, anisometropie approved these changes

2023-10-04 08:08 UTC, Math-R approved these changes
LGTM

2023-10-04 08:17 UTC, merged