front: migrate delete project in rtk
OpenRailAssociation/osrd pull request #5192
Opened 2023-10-03 16:32 UTC by SharglutDev

close #5186

2023-10-03 19:02 UTC, anisometropie requested changes

2023-10-03 19:02 UTC, anisometropie commented on front/src/modules/project/components/AddOrEditProjectModal.tsx
> +      await deleteProject({ projectId: 50 })
```suggestion
      await deleteProject({ projectId: project.id })
```

2023-10-03 19:04 UTC, SharglutDev commented on front/src/modules/project/components/AddOrEditProjectModal.tsx
> +      await deleteProject({ projectId: 50 })
Wow good catch, I forgot to change it back 😬

2023-10-03 19:11 UTC, SharglutDev commented on front/src/modules/project/components/AddOrEditProjectModal.tsx
> +      await deleteProject({ projectId: 50 })
It's fixed

2023-10-04 07:47 UTC, Uriel-Sautron approved these changes
Good job !!!

2023-10-04 14:52 UTC, anisometropie approved these changes

2023-10-05 10:09 UTC, clarani approved these changes
LGTM, tested :heavy_check_mark:

2023-10-05 10:30 UTC, merged