editoast: adapt signal search to use logical_signals and drop aspects
OpenRailAssociation/osrd pull request #5260
Opened 2023-10-09 16:06 UTC by leovalais

2023-10-10 15:37 UTC, flomonster commented
## A few things to fix

1. We should be able to search any type of signals
2. The naming could be improved (and translate)
3. The sprite isn't shown

![image](https://github.com/osrd-project/osrd/assets/15349030/7af22452-37fe-4a9b-852c-e7c976524bcd)

2023-10-10 15:38 UTC, flomonster requested changes
Thanks for this PR.
The back looks good to me.
Some front stuff has to be fixed to be merged.

2023-10-10 15:38 UTC, flomonster commented on editoast/migrations/2023-10-05-160419_logical_signals_search/up.sql
> +                AND track_section.obj_id = infra_object_signal.data->>'track';
The generating migration misses a line feed.

2023-10-19 15:27 UTC, flomonster reviewed
LGTM.
Waiting for the merge of #5166 to test it.

2023-10-20 13:18 UTC, flomonster approved these changes
Thanks again for this PR!
Reviewed + Tested

2023-10-23 15:05 UTC, clarani reviewed
Left some comments, thanks for your PR :pray:

2023-10-23 15:05 UTC, clarani commented on front/public/locales/fr/map-search.json
You need to add the translation in english too (in front/public/locales/en/map-search.json)

2023-10-23 15:05 UTC, clarani commented on front/src/common/BootstrapSNCF/MultiSelectSNCF.tsx
> +  const multiSelectOptions = options.map((optionGroup) => optionGroup.options).flat();
```suggestion
  const multiSelectOptions = useMemo(() => options.map((optionGroup) => optionGroup.options).flat(), [options]);
```

2023-10-23 15:05 UTC, clarani commented on front/src/common/BootstrapSNCF/MultiSelectSNCF.tsx
> +                <div data-role="group" data-id="0" role="list">
You need to add a key to avoid a react warning.
Edit l136 like this:
```
{options.map((selectOption, index) =>
```
and then
```suggestion
                <div data-role="group" data-id="0" role="list" key={`group-${index}`}>
```

2023-10-23 15:05 UTC, clarani commented on front/src/common/BootstrapSNCF/SelectImprovedSNCF.tsx
> +          <div className={`select-menu ${blockMenu ? 'position-relative' : ''}`} id="-selecttoggle">
Import cx
```
import cx from 'classnames';
```

 and use it like this 
```suggestion
          <div className={cx('select-menu', { 'position-relative': blockMenu })} id="-selecttoggle">
```

2023-10-23 15:05 UTC, clarani commented on front/src/common/Map/Search/MapSearchSignal.tsx
> +  );
If this is only const, can you move it outside the component ? (above const MapSearchSignal, l29). Otherwise it will be re-instantiated at each re-render 

Also we use capital letters for const and enums: SIGNALING_SYSTEMS, SIGNAL_SETTINGS_MAP, SIGNAL_SETTINGS_DISPLAY
```suggestion
  const signalSystems = {
    ALL: t('map-search:all'),
    BAL: 'BAL',
    BAPR: 'BAPR',
    TVM: 'TVM',
  };

  const signalSettingsMap = {
    [signalSystems.ALL]: [],
    [signalSystems.BAL]: ['Nf'],
    [signalSystems.BAPR]: ['Nf', 'distant'],
    [signalSystems.TVM]: ['is_430'],
  };

  const signalSettingsDisplay: { [key: string]: string } = {
    Nf: t('map-search:signalSettings.Nf'),
    distant: t('map-search:signalSettings.distant'),
    is_430: t('map-search:signalSettings.is_430'),
  };

  const reversedSignalSettingsDisplay = Object.entries(signalSettingsDisplay).reduce(
    (acc, [key, value]) => {
      acc[value] = key;
      return acc;
    },
    {} as { [key: string]: string }
  );
```

2023-10-23 16:02 UTC, leovalais commented on front/public/locales/fr/map-search.json
Oops, thanks 🙈

2023-10-24 12:57 UTC, leovalais commented on front/src/common/Map/Search/MapSearchSignal.tsx
> +        !settings.length || ['contains', ['settings'], ['list', ...settings]],
@flomonster @clarani I've swapped the inclusion condition for settings since your last review to make the usage a little more intuitive. Let me know what you think. Now it only displays the signals that have *at most* the selected settings.

2023-10-24 13:02 UTC, flomonster commented on front/src/common/Map/Search/MapSearchSignal.tsx
> +        !settings.length || ['contains', ['settings'], ['list', ...settings]],
I'm okay with this change.

2023-10-24 13:34 UTC, clarani commented on front/src/common/Map/Search/MapSearchSignal.tsx
> +        !settings.length || ['contains', ['settings'], ['list', ...settings]],
Me too !

2023-10-24 13:43 UTC, clarani approved these changes
LGTM, tested :heavy_check_mark:

2023-10-24 14:38 UTC, merged