tests: add pytype
OpenRailAssociation/osrd pull request #5387
Opened 2023-10-18 15:30 UTC by shenriotpro

2023-10-18 15:34 UTC, shenriotpro commented
Note that there are other type issues in tests/

2023-10-18 16:23 UTC, Tguisnet requested changes

2023-10-18 16:23 UTC, Tguisnet commented on tests/fuzzer/fuzzer.py
> +            raise ValueError(f"Unsupported requst type {request_type}")
```suggestion
            raise ValueError(f"Unsupported request type {request_type}")
```

2023-10-19 08:34 UTC, eckter approved these changes
Nice !

There seems to be errors in the other test files, but still, it's progress

2023-10-19 10:09 UTC, Tguisnet approved these changes

2023-10-19 10:22 UTC, merged