Nwz/show pks
OpenRailAssociation/osrd pull request #5402
Opened 2023-10-19 12:49 UTC by nicolaswurtz

2023-10-19 13:38 UTC, sim51 commented
Is it useful to have them at this level of zoom ? 

![image](https://github.com/osrd-project/osrd/assets/231657/1c7d47b9-5773-4ee2-a657-eab3e7a53a17)
![image](https://github.com/osrd-project/osrd/assets/231657/e61abfd8-68ce-46b5-b157-c70fe67a26cc)

Should we have the PK also on the editor ?

2023-10-23 08:55 UTC, SharglutDev requested changes
Tested in local and it seems that even when the signals layer is disabled, the PK from the signal is still displayed.

![image](https://github.com/osrd-project/osrd/assets/113104137/ca5c2a51-cbf1-48ec-be1e-486820d4104a)

2023-10-23 17:35 UTC, nicolaswurtz commented
> Is it useful to have them at this level of zoom ?
> 
> ![image](https://user-images.githubusercontent.com/231657/276631793-1c7d47b9-5773-4ee2-a657-eab3e7a53a17.png) ![image](https://user-images.githubusercontent.com/231657/276632300-e61abfd8-68ce-46b5-b157-c70fe67a26cc.png)
> 
> Should we have the PK also on the editor ?

Corrected !

2023-10-23 17:35 UTC, nicolaswurtz commented
> Tested in local and it seems that even when the signals layer is disabled, the PK from the signal is still displayed.
> 
> ![image](https://user-images.githubusercontent.com/113104137/277281815-ca5c2a51-cbf1-48ec-be1e-486820d4104a.png)

corrected

2023-10-24 08:07 UTC, SharglutDev approved these changes
Lgtm, nice feature !

2023-10-24 09:38 UTC, sim51 commented
You replaced the map item's label (generally the item's ID)  for Detector & BufferStop by the KP value. 

For me (as a not rails guy), it was hard to figure out that the label is the KP and not the ID/name of the object. 
Can we prefix the value by `KP `  ?

Moreover on signals, KPs are displayed just under the signal name. So there is 2 ways of how a KP is displayed on the map.

2023-10-24 14:58 UTC, nicolaswurtz commented
> You replaced the map item's label (generally the item's ID) for Detector & BufferStop by the KP value.
> For me (as a not rails guy), it was hard to figure out that the label is the KP and not the ID/name of the object. Can we prefix the value by `KP ` ?

As the KP becomes a `label` "KP" mention is useless BECAUSE it's firstly a label.

> Moreover on signals, KPs are displayed just under the signal name. So there is 2 ways of how a KP is displayed on the map.

KPs are centered under centered signals, lefted or righted along signal's position.

2023-10-24 15:49 UTC, sim51 commented
As discussed with @nicolaswurtz  : 
 * KP as label makes sense for rails expert (also without the KP prefix).
 * There is a general bug of signals, so my comment on the 'stops' is not linked to this PR

2023-10-24 15:52 UTC, sim51 approved these changes

2023-10-24 15:52 UTC, sim51 commented on front/src/common/Map/Settings/MapSettingsSignals.tsx
> +const SIGNAL_SETTINGS: Array<keyof SettingsSignals> = ['lights']; // 'all', 'stops' temporarely desactivated
"stops" is enabled in the default state (see https://github.com/osrd-project/osrd/blob/nwz/show-pks/front/src/reducers/map/index.ts#L81C4-L81C17).
So in locally I see them, and I can't disabled them.
is it intended ?

2023-10-25 12:57 UTC, Math-R approved these changes

2023-10-25 17:38 UTC, merged