core: fix identical positions when shifting envelope parts
OpenRailAssociation/osrd pull request #5432
Opened 2023-10-23 13:07 UTC by eckter

Fix #5426 

I couldn't quite reproduced it in a regression test, but I found a scenario that reproduced it and it was fixed after this change.

2023-10-24 08:46 UTC, multun requested changes

2023-10-24 08:46 UTC, multun commented on core/envelope-sim/src/main/java/fr/sncf/osrd/envelope/part/EnvelopePart.java
> +        var newTimeDeltas = new ArrayList<Double>();
You can use [hppc's DoubleArrayList](http://carrotsearch.github.io/hppc/releases/0.7.1/api/com/carrotsearch/hppc/DoubleArrayList.html) for better performance and decreased memory usage

2023-10-24 08:46 UTC, multun commented on core/envelope-sim/src/main/java/fr/sncf/osrd/envelope/part/EnvelopePart.java
> +                newTimeDeltas.stream().mapToDouble(x -> x).toArray()
[hppc's DoubleArrayList has a toArray method](http://carrotsearch.github.io/hppc/releases/0.7.1/api/com/carrotsearch/hppc/DoubleArrayList.html#toArray--)

2023-10-30 09:51 UTC, Erashin approved these changes

2023-10-30 10:23 UTC, multun approved these changes

2023-10-30 10:30 UTC, merged