front: router: add id support on EEX routes, need to replace modal cont…
OpenRailAssociation/osrd pull request #5435
Opened 2023-10-23 14:19 UTC by Math-R

…ext by react createPortal hook

close #3661

2023-11-07 14:12 UTC, clarani requested changes
I left some comments, can you apply these changes in Project but also Study and Scenario ? Also you have 4 warnings and some functions are commented in ProjectCard, but it breaks a behaviour

2023-11-07 14:12 UTC, clarani commented on front/src/applications/operationalStudies/components/BreadCrumbs.tsx
> +      {!project && !study && !scenario ? (
The conditions are quite redundant and hard to read, do you want to refactor this here or should I open a new ticket to refactor it ?

Here is an example of rendering more explicit I think:
```
<div className="navbar-breadcrumbs">
      {!project ? (
        t('projectsList')
      ) : (
        <>
          <Link to="/operational-studies/projects">{t('projectsList')}</Link>
          <i className="icons-arrow-next icons-size-x75 text-muted" />
          {!study ? (
            project.name
          ) : (
            <>
              <Link to={`/operational-studies/projects/${project.id}`}>{project.name}</Link>
              <i className="icons-arrow-next icons-size-x75 text-muted" />
              {!scenario ? (
                study.name
              ) : (
                <>
                  <Link to={`/operational-studies/projects/${project.id}/studies/${study.id}`}>
                    {study.name}
                  </Link>
                  <i className="icons-arrow-next icons-size-x75 text-muted" />
                  {scenario.name}
                </>
              )}
            </>
          )}
        </>
      )}
    </div>
```

2023-11-07 14:12 UTC, clarani commented on front/src/applications/operationalStudies/views/Project.tsx
> +  const { projectId } = useParams();
I think it's not a good thing to cast it to number and directly use it without any test. Maybe we can do this :
```suggestion
  const { projectId: urlProjectId } = useParams();
  const projectId = useMemo(() => Number(urlProjectId) || INVALID_ID, [urlProjectId]); // set INVALID_ID = -1 outside the component
```

2023-11-07 14:12 UTC, clarani commented on front/src/applications/operationalStudies/views/Project.tsx
> +    { projectId: Number(projectId) },
Then you need to check everywhere that projectId is not invalid
```suggestion
    { projectId },
    {
      skip: projectId === INVALID_ID,
    }
```

Also, you need to update the useEffect which redirect the user if the id is invalid. You can test this case by setting the id to 'a' for instance
```
  useEffect(() => {
    if (projectId === INVALID_ID) {
      navigate('/operational-studies/projects');
    }
  }, [projectId]);
```

2023-11-07 14:12 UTC, clarani commented on front/package.json
> +    "localforage": "^1.10.0",
why did you install these librairies ? localforage, match-sorter and sort-by

2023-11-08 11:52 UTC, Yohh commented on front/src/applications/operationalStudies/components/BreadCrumbs.tsx
> +      {!project && !study && !scenario ? (
In my opinion nested ternary is quite more difficult to read, not sure this is the best idea

2023-11-09 15:35 UTC, clarani approved these changes
LGTM, tested :white_check_mark:

2023-11-09 15:35 UTC, clarani commented on front/package.json
> +    "localforage": "^1.10.0",
Specified in react-router-dom documentation

2023-11-09 15:35 UTC, clarani commented on front/src/applications/operationalStudies/components/BreadCrumbs.tsx
> +      {!project && !study && !scenario ? (
Ok fine :)

2023-11-09 15:35 UTC, clarani commented on front/src/applications/operationalStudies/views/Scenario.tsx
> +    // redirect if projectId or studyId is not a number
Move this comment above the useEffet and remove the lines 148/149
```suggestion
    // redirect if projectId, studyId or scenarioId is not a number
```

2023-11-09 17:42 UTC, merged