front: update selected projection after train deletion
OpenRailAssociation/osrd pull request #5438
Opened 2023-10-23 16:08 UTC by clarani

closes #5403

2023-10-24 15:21 UTC, Akctarus approved these changes
LGTM

2023-10-24 15:35 UTC, SharglutDev requested changes
Thank you for this PR ! Left two comments. 

Tested and it works if the remaining train has a different path, it gets the projection.

But if we have 3 trains, 2 with same path and one different, if we delete one of the "common path" train, the projection isn't set on any train in the list.

2023-10-24 15:35 UTC, SharglutDev commented on front/src/utils/array.ts
> +export const distinctElements = <T>(array: T[]) => [...new Set(array)];
```suggestion
export const uniqueElements = <T>(array: T[]) => [...new Set(array)];
```

2023-10-24 15:35 UTC, SharglutDev commented on front/src/applications/operationalStudies/components/Scenario/getSimulationResults.ts
> +
There is a warning here

2023-10-25 14:49 UTC, clarani commented on front/src/utils/array.ts
> +export const distinctElements = <T>(array: T[]) => [...new Set(array)];
Renamed :heavy_check_mark:

2023-10-25 14:49 UTC, clarani commented on front/src/applications/operationalStudies/components/Scenario/getSimulationResults.ts
> +
Thanks !

2023-11-13 09:07 UTC, SharglutDev approved these changes
Lgtm, tested in local, very nice job :)

2023-11-13 11:00 UTC, nicolaswurtz approved these changes
👍

2023-11-13 13:33 UTC, merged

2023-11-13 13:36 UTC, Akctarus approved these changes
Tested in local, LGTM