.github: split integration tests CI into jobs
OpenRailAssociation/osrd pull request #5442
Opened 2023-10-24 09:55 UTC by shenriotpro

closes https://github.com/osrd-project/osrd/issues/5440

2023-10-25 09:28 UTC, flomonster requested changes
Thanks for the PR!

We need to fix the trigger condition otherwise there is no point in splitting the job in two.

2023-10-25 09:28 UTC, flomonster commented on .github/workflows/integration_tests.yml
> +  integration_tests_quality:
This job is run for all PR. Ideally, it should be triggered only when changes are made in the `/tests` folder. The easy way to do so is to have another workflow. Maybe it's possible to configure it in a job.

2023-10-25 09:32 UTC, shenriotpro commented
> Thanks for the PR!
> 
> We need to fix the trigger condition otherwise there is no point in splitting the job in two.

It's still nice to have both jobs run in parallel, but I'll take a look.

2023-10-26 08:55 UTC, Khoyo commented on .github/workflows/integration_tests_quality.yml
> +          poetry run pytype -j auto
Missing newline at EOF

2023-10-26 09:21 UTC, Khoyo approved these changes

2023-10-27 12:50 UTC, flomonster approved these changes
LGTM!

2023-10-27 13:07 UTC, merged