renaming occurences of standard allowance into performance allowance #1178
OpenRailAssociation/osrd pull request #5449
Opened 2023-10-24 13:11 UTC by anglnn

renaming standard allowance into performance allowance in core/* editoast/* tests/* python/*

2023-10-25 09:23 UTC, flomonster requested changes
Thanks for your PR!

Some changes required:
- The branch needs to be rebased to fix conflicts.
- We should add a migration to rename the allowance type into `performance` where needed.

2024-01-12 11:32 UTC, shenriotpro approved these changes
OK for tests/, assuming they pass.

2024-01-12 11:32 UTC, shenriotpro commented on python/osrd_schemas/osrd_schemas/train_schedule.py
Please update versions for the 2 Python packages you're updating.

2024-11-26 09:52 UTC, closed without merging

2024-11-26 09:52 UTC, flomonster commented
Closing for unactivity and too many conflicts.