Mise en forme et correction bug sur MapSearchSignal, ajout llimitatio…
OpenRailAssociation/osrd pull request #546
Opened 2022-02-07 16:59 UTC by alexandredamiron

…n de dépendance sur react-overlay-error

Attention: les erreurs TS sautent, changement de config

2022-02-07 17:04 UTC, nicolaswurtz approved these changes

2022-02-15 09:13 UTC, flomonster requested changes
I didn't check the file `MapSearchSignal.js`...

2022-02-15 09:13 UTC, flomonster commented on .gitignore
> +osrd_2022-01-31_new_rolling_stocks.backup
```suggestion
*.backup
```

2022-02-15 09:13 UTC, flomonster commented on .gitignore
> +front/launch_local_front.sh
These lines should be moved in `front/.gitignore`
You shouldn't ignore `yarn.lock` this file is important to track.
I don't know about `tsconfig.json` and but it feels weird to ignore this file.

2022-02-15 09:13 UTC, flomonster commented on front/launch_local_front.sh
> +TSC_COMPILE_ON_ERROR=true REACT_APP_LOCAL_BACKEND=True REACT_APP_API_URL=http://localhost:8000 REACT_APP_CHARTIS_URL=http://localhost:7000 yarn start
It this file is ignore it should be remove from git. `git rm front/launch_local_front.sh`

2022-02-15 09:13 UTC, flomonster commented on front/tsconfig.json
> +    "strict": false,
This might be the reason why the CI fails.

2022-02-15 09:24 UTC, flomonster commented on front/tsconfig.json
> +    "strict": false,
Actually that's not why the CI is failing. We should still leave it strict.

2022-02-15 16:17 UTC, closed without merging