front: editor-slopes-fix-form-validation
OpenRailAssociation/osrd pull request #5581
Opened 2023-11-02 16:14 UTC by Wadjetz

Remove local errors check in slopes form and let global form validate data

close #3479

2023-11-07 08:19 UTC, SharglutDev approved these changes
Good job for the catch of this customOnChange ! 

Tested in local and everything seems to be working as expected. Tried also the forms for signals, detectors, switches, buffer stops and seen nothing strange.

2023-11-08 14:23 UTC, clarani approved these changes
LGTM :white_check_mark:

2023-11-08 14:46 UTC, clarani requested changes
We need to wait for Giuliana's point of view

2023-11-09 16:15 UTC, SharglutDev requested changes
Take you for the changes. As checked with you, I think the curves and slopes values should be set to 0 as soon as we enter in the form.

Otherwise, I think it's strange that if the value is at 0, we see a `-` when hovering the interval editor. It might mislead the user as it's the same behavior than the `undefined` one.

![image](https://github.com/osrd-project/osrd/assets/113104137/808b0a1e-29b5-4ae3-a18c-fc5b8d8a76b6)

Also you have some warnings in the file

2023-11-14 08:23 UTC, SharglutDev requested changes
Thank you for the changes.
When I try to create a new tracksection, after drawing it and fill the required inputs, doesn't work. Its saying that curves and slopes are required properties even though gradiant and radius are set to 0 when entering the form.

![image](https://github.com/osrd-project/osrd/assets/113104137/74d7413a-fe63-45a3-b8bb-5088a7b1b7f2)

On the other hand, the behavior when editing a track section with unspecified gradiants or radius is great, they are set automatically to 0, good job !

2023-11-16 17:50 UTC, SharglutDev approved these changes
Great job for this PR, thank you ! Tested and everything works as expected.

Left some naming comments. As I will be away the next 2 business days, I'll let @clarani resolve those so you are not blocked to merge the PR.

2023-11-16 17:50 UTC, SharglutDev commented on front/src/common/IntervalsDataViz/IntervalItem.tsx
> +  const isNoData =
```suggestion
  const hasNoData =
```

2023-11-16 17:50 UTC, SharglutDev commented on front/src/common/IntervalsDataViz/IntervalItem.tsx
> +  const isHasData =
```suggestion
  const hasData =
```

2023-11-16 17:50 UTC, SharglutDev commented on front/src/common/IntervalsDataViz/IntervalItem.tsx
> +        isNoData && 'no-data',
We have a convention when using condition in cx
```suggestion
        { 
          'with-data': isHasData,
          'no-data': isNoData,
        },
```

2023-11-17 14:31 UTC, clarani requested changes
Thanks for this PR, almost there :)

2023-11-17 14:31 UTC, clarani commented on front/src/common/IntervalsDataViz/data.ts
> +  const enhancementValues = enhancement ?? {};
Why did you do that ? I find it clearer to have the default value in the definition of the function (see before changes)
```suggestion
```

2023-11-17 14:31 UTC, clarani commented on front/src/applications/editor/components/EditorForm.tsx
> +  }, [data.properties.length]);
You don't need this, the best thing to do I think is to initialize curves and slopes to [] in getInitialState (see getNewLine, add curves: [] and slopes: []).
You will need to add curves and slopes to the TrackSectionEntity
```
      slopes: LinearMetadataItem<{ gradient: number }>[];
      curves: LinearMetadataItem<{ radius: number }>[];
```
So you can remove the useEffect
```suggestion
```

2023-11-17 14:40 UTC, Wadjetz commented on front/src/common/IntervalsDataViz/data.ts
> +  const enhancementValues = enhancement ?? {};
The linter require params with default values to be the last

2023-11-17 15:56 UTC, clarani approved these changes
LGTM and tested ! Nice job, thank you very much :pray: :tada:

2023-11-17 16:11 UTC, merged