front: fix translation panto to pantographe
OpenRailAssociation/osrd pull request #5586
Opened 2023-11-03 09:22 UTC by RomainValls

closes #5566

2023-11-03 09:24 UTC, SarahBellaha approved these changes
LGTM :)

2023-11-03 14:44 UTC, clarani requested changes
Ahhh thanks for fixing this bug !! Can you also change the english translation in `en/map-key.json` ? :)

2023-11-08 10:13 UTC, RomainValls commented
Thanks Clara, just modified the english translation !

2023-11-08 12:36 UTC, clarani approved these changes
LGTM

2023-11-09 18:49 UTC, nicolaswurtz commented
It's the right term, no need to change it.

2023-11-10 14:02 UTC, clarani requested changes

2023-11-10 14:02 UTC, clarani commented on front/public/locales/fr/map-key.json
> +  "lower_pantograph": "Baissez pantographe",
```suggestion
  "lower_pantograph": "Zone \"Baissez panto\"",
```

2023-11-10 14:02 UTC, clarani commented on front/public/locales/en/map-key.json
> +  "lower_pantograph": "Lower pantograph",
```suggestion
  "lower_pantograph": "\"Baissez-panto\" zone",
```

2023-11-22 12:25 UTC, nicolaswurtz approved these changes

2023-11-22 14:00 UTC, clarani approved these changes
LGTM thanks :)

2023-11-23 08:47 UTC, merged