stdcm : fix margin card width
OpenRailAssociation/osrd pull request #5590
Opened 2023-11-03 09:46 UTC by RomainValls

closes #5565

2023-11-03 10:21 UTC, Yohh requested changes

2023-11-03 10:21 UTC, Yohh commented on front/src/modules/stdcmAllowances/components/STDCMAllowances.tsx
> +    <div className="d-flex my-2 p-2 align-items-center osrd-config-item-container">
```suggestion
    <div className="d-flex mb-2 align-items-center osrd-config-item-container">
```
padding seems useless here, as the full vertical margin

you could also change the vertical margin the same way in Itinerary.tsx

2023-11-03 14:22 UTC, Yohh approved these changes
LGTM :muscle:

2023-11-03 14:41 UTC, clarani requested changes
Left 1 small comment.
Can you squash your commits and rebase ? Thanks ! :)

2023-11-03 14:41 UTC, clarani commented on front/src/modules/stdcmAllowances/components/STDCMAllowances.tsx
> +    <div className="d-flex mb-2 align-items-center osrd-config-item-container">
I'm not sure align-items-center is useful here, I removed it and it didn't change anything. What do you think ?
```suggestion
    <div className="d-flex mb-2 osrd-config-item-container">
```

2023-11-03 15:12 UTC, RomainValls commented
C'est fait, merci !

2023-11-08 15:31 UTC, clarani approved these changes
LGTM thanks !! tested :white_check_mark:

2023-11-16 10:12 UTC, merged