editoast: fix sql request and add test
OpenRailAssociation/osrd pull request #5615
Opened 2023-11-07 14:36 UTC by anglnn

closes #5376

2023-11-08 09:34 UTC, leovalais requested changes
Looks good! Left some comments. You also need to format your code using `rustfmt`, you can configure your editor to do it by itself on save.

2023-11-08 09:34 UTC, leovalais commented on editoast/src/schema/rolling_stock/light_rolling_stock.rs
> +    #[serde(skip_deserializing)]
```suggestion
    #[serde(skip)]
```

2023-11-08 09:34 UTC, leovalais commented on editoast/src/views/light_rolling_stocks.rs
> +        let uri = format!("{}{}","/light_rolling_stock/?page_size=",count.to_string());
```suggestion
        let uri = format!("/light_rolling_stock/?page_size={count}");
```

2023-11-08 09:34 UTC, leovalais commented on editoast/src/views/light_rolling_stocks.rs
> +        vec_ids.dedup();
```suggestion
```

We want the test to fail if there are duplicates.

2023-11-09 09:15 UTC, Khoyo commented
Please fix your commit message ;)

2023-11-13 11:00 UTC, leovalais reviewed
LGTM, a few cosmetic suggestions:

2023-11-13 11:00 UTC, leovalais commented on editoast/src/views/light_rolling_stocks.rs
> +        let vec_fixtures = (0..10)
```suggestion
        // Generate some rolling stocks
        let vec_fixtures = (0..10)
```

2023-11-13 11:00 UTC, leovalais commented on editoast/src/views/light_rolling_stocks.rs
> +        let app = create_test_service().await;
```suggestion

        // Fetch all rolling stocks using /light_rolling_stock
        let app = create_test_service().await;
```

2023-11-13 11:00 UTC, leovalais commented on editoast/src/views/light_rolling_stocks.rs
> +        let vec_ids = response
```suggestion

        // Ensures that AT LEAST all the rolling stocks created above are returned, in order
        let vec_ids = response
```

2023-11-13 11:00 UTC, leovalais commented on editoast/src/views/light_rolling_stocks.rs
> +        assert!(expected_ids.is_subset(&ids));
```suggestion
        // Since tests are not properly isolated, some rolling stock fixture may "leak" from another test, so maybe ids.len() > expected_ids.len()
        assert!(expected_ids.is_subset(&ids));
```

2023-11-13 11:00 UTC, leovalais commented on editoast/src/fixtures.rs
> +    pub async fn rolling_stock_livery_set(
```suggestion
    pub async fn rolling_stock_livery(
```

2023-11-16 09:57 UTC, Tguisnet requested changes

2023-11-16 09:57 UTC, Tguisnet commented on editoast/src/views/light_rolling_stocks.rs
> +        // Ensure that AT LEAST al lthe rolling stocks create above are returned, in order
```suggestion
        // Ensure that AT LEAST all the rolling stocks create above are returned, in order
```

2023-11-16 09:57 UTC, Tguisnet commented on editoast/src/fixtures.rs
> +    pub struct RollingStockLiveryFixtureSet {
```suggestion
    pub struct RollingStockLiveryFixture {
```

2023-11-16 11:32 UTC, Tguisnet approved these changes

2023-11-16 11:44 UTC, leovalais approved these changes

2023-11-16 11:56 UTC, merged