front: allowances: fix allowances components
OpenRailAssociation/osrd pull request #5643
Opened 2023-11-09 15:12 UTC by clarani

closes #5223

2023-11-17 08:44 UTC, alexandredamiron requested changes

2023-11-17 08:44 UTC, alexandredamiron commented on front/src/common/BootstrapSNCF/InputGroupSNCF.tsx
> +        value={value !== undefined ? value : ''}
you can use the nullish coalescent operator
```suggestion
        value={value ?? ''}
```

2023-11-20 08:53 UTC, clarani commented on front/src/common/BootstrapSNCF/InputGroupSNCF.tsx
> +        value={value !== undefined ? value : ''}
I've added a new test, so I think I can't use the nullish coalescent operator now

2023-11-20 15:59 UTC, alexandredamiron commented on front/src/common/BootstrapSNCF/InputGroupSNCF.tsx
> +        value={value !== undefined ? value : ''}
ok closing

2023-11-20 15:59 UTC, alexandredamiron approved these changes

2023-11-22 12:51 UTC, nicolaswurtz approved these changes

2023-11-22 15:42 UTC, merged