front : disable date and arrival time stdcm
OpenRailAssociation/osrd pull request #5704
Opened 2023-11-16 08:19 UTC by RomainValls

closes #5636

2023-11-16 08:58 UTC, flomonster reviewed
Tested. You can't visually see that the elements are deactivated. This issue might not be part of this PR.

2023-11-16 09:06 UTC, SharglutDev requested changes
Thank you for the PR. Seems to work as expected but I would like to wait for the PO's / UX approval to be sure that's the behavior we want.

PS : don't forget to remove your comments

2023-11-16 09:06 UTC, SharglutDev commented on front/src/modules/trainschedule/components/ManageTrainSchedule/Itinerary/DisplayItinerary/Destination.tsx
> +                  // disabled={isByOrigin}
You left a comment there

2023-11-16 09:06 UTC, SharglutDev commented on front/src/modules/trainschedule/components/ManageTrainSchedule/Itinerary/DisplayItinerary/Destination.tsx
> +                  // readonly={isByOrigin}
same here

2023-11-16 11:36 UTC, SharglutDev requested changes
Don't forget to remove in `Origin.tsx` component `{radioButton}` const and its call in the tsx

2023-11-16 17:56 UTC, SharglutDev approved these changes
Lgtm, tested and everything looks as expected, good job !

Thank you for squashing your old commits.

2023-11-17 14:49 UTC, clarani requested changes
Nice job ! Can I ask you to remove some dead code as we are removing these radio buttons ?
- remove updateStdcmMode function (in reducer and in slice) since it will not be used anymore
- remove getStdcmMode selector
- remove isByDestination in Origin
- in formatStdcmCong, remove isByOrigin and isByDestination booleans. You can also remove the test `if (!osrdconf.destinationTime && isByDestination) {...}` line 48 but you need to keep the test line 30 (only remove isByOrigin test)

2023-11-17 14:49 UTC, clarani commented on front/src/modules/trainschedule/components/ManageTrainSchedule/Itinerary/DisplayItinerary/Origin.tsx
> +  const { isByDestination } = makeEnumBooleans(STDCM_MODES, stdcmMode);
Can you also remove the isByDestination here please ? Thanks ! :)

2023-12-05 15:57 UTC, clarani approved these changes
LGTM, it works perfectly !! :white_check_mark: 
Thanks for this PR !

2023-12-06 09:50 UTC, merged