add supplementary axis
OpenRailAssociation/osrd pull request #5747
Opened 2023-11-17 16:23 UTC by alexandredamiron

#fix #5725

2023-11-21 10:29 UTC, Yohh commented on front/src/modules/simulationResult/components/SpeedSpaceChart/SpeedSpaceChart.tsx
> +
why this useEffect?

2023-11-21 10:35 UTC, Yohh approved these changes
LGTM

2023-11-22 15:18 UTC, clarani requested changes
Thanks for this PR, left some comments

2023-11-22 15:18 UTC, clarani commented on front/src/modules/simulationResult/components/ChartHelpers/enableInteractivity.tsx
> +  supplementaryValues: ChartAxes[], // more values to display on the same chart
```suggestion
    additionalValues: ChartAxes[], // more values to display on the same chart
```

2023-11-22 15:18 UTC, clarani commented on front/src/modules/simulationResult/components/ChartHelpers/enableInteractivity.tsx
> +  supplementaryValues: ChartAxes[], // more values to display on the same chart
Can you move this argument so that it is the last of the list ? This way, you can set a default value
```suggestion
  additionalValues: ChartAxes[] = [], // more values to display on the same chart
```

2023-11-22 15:18 UTC, clarani commented on front/src/modules/simulationResult/components/ChartHelpers/enableInteractivity.tsx
> +  const supplementaryXAxis = supplementaryValues.map((value) => getAxis(value, 'x', rotate));
The xAxis will always be the same, only the yAxis can change
```suggestion
```

2023-11-22 15:18 UTC, clarani commented on front/src/modules/simulationResult/components/ChartHelpers/enableInteractivity.tsx
> +      })
```suggestion
      .x((d) => newX(d[xAxis as keyof T] as number | Date))
```

2023-11-22 15:18 UTC, clarani commented on front/src/modules/simulationResult/components/SpaceTimeChart/SpaceTimeChart.tsx
> +        [], // There are no supplementary data to display in this chart, fill that if it's come to change
```suggestion
```

2023-11-22 15:18 UTC, clarani commented on front/src/modules/simulationResult/components/SpeedSpaceChart/SpeedSpaceChart.tsx
> +  const [enabledAxes, setEnabledAxes] = useState<ChartAxes[]>([]);
```suggestion
  const [additionalCurves, setAdditionalCurves] = useState<ChartAxes[]>([]);
```

2023-11-22 15:18 UTC, clarani commented on front/src/modules/simulationResult/components/SpeedSpaceChart/SpeedSpaceChart.tsx
> +  }, [localSettings]);
I think it's better to use a useMemo that is recomputed each time localSettings changes. Also, you can move the const settingToAxisMap outside the component to prevent if from being reinstantiated at each re-render (and also rename it SETTING_TO_AXIS in capital letters)
```suggestion
  const additionalCurves = useMemo(
    () =>
      Object.keys(settingToAxisMap)
        .filter((key) => localSettings[key as keyof typeof localSettings])
        .map((key) => settingToAxisMap[key as keyof typeof settingToAxisMap] as ChartAxes),
    [localSettings]
  );
```

2023-11-23 10:33 UTC, alexandredamiron commented on front/src/modules/simulationResult/components/SpeedSpaceChart/SpeedSpaceChart.tsx
> +  }, [localSettings]);
Okay, but this array is of type ChartAxes, so I still prefer to call it additionalAxes

2023-11-23 10:33 UTC, alexandredamiron commented on front/src/modules/simulationResult/components/SpaceTimeChart/SpaceTimeChart.tsx
> +        [], // There are no supplementary data to display in this chart, fill that if it's come to change
done

2023-11-23 10:34 UTC, alexandredamiron commented on front/src/modules/simulationResult/components/SpeedSpaceChart/SpeedSpaceChart.tsx
> +  const [enabledAxes, setEnabledAxes] = useState<ChartAxes[]>([]);
as I employ useMemo I removed that

2023-11-23 10:34 UTC, alexandredamiron commented on front/src/modules/simulationResult/components/ChartHelpers/enableInteractivity.tsx
> +  supplementaryValues: ChartAxes[], // more values to display on the same chart
done

2023-11-23 10:34 UTC, alexandredamiron commented on front/src/modules/simulationResult/components/ChartHelpers/enableInteractivity.tsx
> +  supplementaryValues: ChartAxes[], // more values to display on the same chart
done

2023-11-23 10:34 UTC, alexandredamiron commented on front/src/modules/simulationResult/components/ChartHelpers/enableInteractivity.tsx
> +  const supplementaryXAxis = supplementaryValues.map((value) => getAxis(value, 'x', rotate));
It can change, if you use rotation in SpeedSpaceChart

2023-11-23 10:35 UTC, alexandredamiron commented on front/src/modules/simulationResult/components/ChartHelpers/enableInteractivity.tsx
> +      })
you may have supp xAxis

2023-11-23 15:05 UTC, clarani commented on front/src/modules/simulationResult/components/ChartHelpers/enableInteractivity.tsx
> +  const supplementaryXAxis = supplementaryValues.map((value) => getAxis(value, 'x', rotate));
My bad, you are right ! Thanks :pray:

2023-11-23 15:09 UTC, clarani reviewed
LGTM, you just need to rebase and squash your commits :white_check_mark:

2023-11-23 15:54 UTC, clarani approved these changes

2023-11-23 16:03 UTC, merged