front: fix stdcm origin time panel behaviour
OpenRailAssociation/osrd pull request #5761
Opened 2023-11-20 16:55 UTC by clarani

closes #4419

2023-11-22 17:41 UTC, Math-R requested changes

2023-11-22 17:41 UTC, Math-R commented on front/src/reducers/osrdconf/helpers.ts
> +  console.log({
Need to remove it

2023-11-23 11:26 UTC, clarani commented on front/src/reducers/osrdconf/helpers.ts
> +  console.log({
Done

2023-11-23 14:46 UTC, Math-R approved these changes
LGTM ! nicely done :)

2023-11-23 15:18 UTC, merged