front: fix longitudinal curve in op studies
OpenRailAssociation/osrd pull request #5767
Opened 2023-11-21 10:55 UTC by RomainValls

Add one additional Y axis on the right of the chart
Red curve (speed slopes) now stays in the frame

closes #4312

2023-11-21 15:37 UTC, alexandredamiron requested changes, later dismissed
Thank you for this request. I am not sure about the whole duplication of behavior logic. Could you expand the capabilities of defineChart and drawCurve instead ?

2023-11-21 15:37 UTC, alexandredamiron commented on front/src/modules/simulationResult/components/ChartHelpers/defineChartDoubleY.tsx
> +    // .attr('height', height + margin.top + margin.bottom)
dead code

2023-11-21 15:37 UTC, alexandredamiron commented on front/src/modules/simulationResult/components/SpaceCurvesSlopes.tsx
> +    .text('TEST');
nowhere text ?

2023-11-29 10:18 UTC, Yohh requested changes
very nice work!

one small issue:
curves start jump to zero when draging speedSpaceChart or slopesChart, maybe should you look to enableInteractivity

2023-11-29 10:18 UTC, Yohh commented on front/src/modules/simulationResult/components/ChartHelpers/defineChart.ts
> +  let originalScaleY2;
can you type those variables?

2023-12-07 13:18 UTC, Yohh approved these changes

2023-12-08 10:28 UTC, clarani requested changes
Almost there, great work !! :tada: I left some comments

Thanks for the comments on enableInteractivity, it's super clear now :)

2023-12-08 10:28 UTC, clarani commented on front/src/modules/simulationResult/components/ChartHelpers/defineChart.ts
> +  let originalScaleY2: SimulationD3Scale;
No need for these variables, you can create them when you need them. The only one you need to instantiate outside of the if is the one you will reuse after the end of the if (here rightAxis) :) 
```suggestion
```

2023-12-08 10:28 UTC, clarani commented on front/src/modules/simulationResult/components/ChartHelpers/defineChart.ts
> +    const axisRightY = isSpaceSlopesCurves(keyValues) ? d3.axisRight(y2) : undefined;
You can move the condition ` isSpaceSlopesCurves(keyValues) ` line 90 and remove the 2nd if loop
-> `if (defineY2 && isSpaceSlopesCurves(keyValues) ) {...}`
```suggestion
    const axisRightY = d3.axisRight(y2);
```

2023-12-08 10:28 UTC, clarani commented on front/src/modules/simulationResult/components/ChartHelpers/defineChart.ts
> +      originalScaleY2 = y2;
You can set it directly line 105
```suggestion
```

2023-12-08 10:28 UTC, clarani commented on front/src/modules/simulationResult/components/ChartHelpers/drawCurve.ts
> +  const isHeight = yAxis === 'height';
I think this bool is more relevant, and then you can use it to change the class and the axis used in the drawZone function
```suggestion
  const onY2Axis = yAxis === 'height' && chart.y2;
```

2023-12-08 10:28 UTC, clarani commented on front/src/modules/simulationResult/components/ChartHelpers/drawCurve.ts
> +  }
```suggestion
  drawZone
    .append('path')
    .attr('class', `line zoomable ${onY2Axis && 'additional-y'} ${classes}`)
    .datum(dataSimulation)
    .attr('fill', 'none')
    .attr('stroke-width', 1)
    .attr(
      'd',
      d3
        .line<T>()
        .x((d) => chart.x(d[xAxis as keyof T] as number))
        .y((d) =>
          onY2Axis && chart.y2
            ? chart.y2(d[yAxis as keyof T] as number)
            : chart.y(d[yAxis as Key] as number)
        )
        .curve(d3[interpolation as keyof d3.CurveFactory])
    );
```

It's not very pretty because we have to test twice that chart.y2 exists, as typescript does not detect it alone, but at least it avoids code duplication and you can clearly see what changes between the 2 cases. You can also remove the second test chart.y2 and add a ! if you prefer (`chart.y2!(...)` line 43)

2023-12-08 10:28 UTC, clarani commented on front/src/modules/simulationResult/components/ChartHelpers/drawPowerRestriction.ts
I feel like drawPowerRestriction and drawElectricalProfile have a lot of code in common. Maybe we can refacto them later

2023-12-08 10:28 UTC, clarani commented on front/src/modules/simulationResult/components/SpaceTimeChart/createSpaceTimeChart.ts
> +    defineY2
I think spaceTimeChart does not need y2, so it should always be undefined
```suggestion
```

2023-12-08 10:28 UTC, clarani commented on front/src/modules/simulationResult/components/SpeedSpaceChart/SpeedSpaceChart.tsx
> +      createChartAndTrain();
Be careful, you need to keep this, for the case you have zoomed in or out before clicking on reset ;)
```suggestion
       if (chart && setSharedXScaleDomain) {
        setSharedXScaleDomain((prevState) => ({
          ...prevState,
          current: prevState.initial,
          source: undefined,
        }));
      } else {
        createChartAndTrain();
      }
```

2023-12-08 10:28 UTC, clarani commented on front/src/modules/simulationResult/components/SpeedSpaceChart/SpeedSpaceChart.tsx
> +      traceVerticalLine(chart, CHART_AXES.SPACE_SPEED, positionValues, false, timePosition);
Can you change the order of the parameters of traceVerticalLine to put rotate as the last param and set it by default to false ? Then you can remove it like this. Don't forget to change the param order in the other places where traceVerticalLine is called
```suggestion
      traceVerticalLine(chart, CHART_AXES.SPACE_SPEED, positionValues, timePosition);
```

2023-12-08 10:28 UTC, clarani commented on front/src/modules/simulationResult/components/SpeedSpaceChart/d3Helpers.ts
> +    .attr('y', 20);
I think you forgot to remove this
```suggestion
```

2023-12-08 10:28 UTC, clarani commented on front/src/modules/simulationResult/components/SpeedSpaceChart/d3Helpers.ts
> +      false
Can you make the rotate parameter in drawCurve false by default ? Then you can remove it everywhere in this file
```suggestion
```

2023-12-08 10:28 UTC, clarani commented on front/src/modules/simulationResult/components/simulationResultsConsts.ts
> +export type Y2Axis = ChartAxes[1];
This would be more precise. We could also remove space_height from YAxis
```suggestion
export type Y2Axis = typeof CHART_AXES.SPACE_HEIGHT;
```

2023-12-08 10:28 UTC, clarani commented on front/src/modules/simulationResult/components/ChartHelpers/enableInteractivity.tsx
> +  const axisRightY = d3.axisRight(newY2 as d3.ScaleTime<number, number>);
Move this line below:
```suggestion
  if (chart.y2Axis) {
    const axisRightY = d3.axisRight(newY2 as d3.ScaleTime<number, number>);
    chart.y2Axis.call(axisRightY);
  }
```

2023-12-08 10:28 UTC, clarani commented on front/src/modules/simulationResult/components/ChartHelpers/enableInteractivity.tsx
> +        })
I think you can even simplify it like this:
```suggestion
        .x((d) => newX(d[xAxis as keyof T]))
        .y((d) => newY2(d['height' as keyof T]))
```

2023-12-08 10:28 UTC, clarani commented on front/src/modules/simulationResult/components/ChartHelpers/enableInteractivity.tsx
> +        x: zoomFunctions.newX,
Do you think you can rename `zoomFunctions` ? I think the name is not very appropriate, maybe newAxis would be better ? zoomedAxis ? updatedAxis ?

2023-12-19 10:59 UTC, clarani reviewed
Left 4 small comments, and 2 previous comments are still not resolved :)

2023-12-19 10:59 UTC, clarani commented on front/src/modules/simulationResult/components/ChartHelpers/defineChart.ts
>      if (axisRightY) {
You don't need this test anymore since axisRightY is always defined
```suggestion
```

2023-12-19 10:59 UTC, clarani commented on front/src/modules/simulationResult/components/ChartHelpers/defineChart.ts
> +      const originalScaleY2 = y2;
You can directly set it in rightAxis:
```
      rightAxis = {
        y2,
        y2Axis,
        y2AxisGrid,
        originalScaleY2: y2,
      };
```

```suggestion
```

2023-12-19 10:59 UTC, clarani commented on front/src/modules/simulationResult/components/SpeedSpaceChart/SpeedSpaceChart.tsx
> +    } else {
You also need to keep the if (resetChart)
```suggestion
    if (resetChart) {
      if (chart && setSharedXScaleDomain) {
        setSharedXScaleDomain((prevState) => ({
          ...prevState,
          current: prevState.initial,
          source: undefined,
        }));
      } else {...}
```

2023-12-19 10:59 UTC, clarani commented on front/src/modules/simulationResult/components/SpaceTimeChart/SpaceTimeChart.tsx
> +      traceVerticalLine(chart, CHART_AXES.SPACE_TIME, positionValues, timePosition);
You need to keep the rotate here, SpaceTimeChart is the only chart that can rotate (just change the order of parameters)
```suggestion
      traceVerticalLine(chart, CHART_AXES.SPACE_TIME, positionValues, timePosition, rotate);
```

2023-12-20 16:41 UTC, clarani approved these changes
LGTM and tested !! :white_check_mark: Very nice PR :white_check_mark:

2024-01-05 14:22 UTC, merged