front: fix various bugs related to PSLs edition
OpenRailAssociation/osrd pull request #5791
Opened 2023-11-22 10:39 UTC by jacomyal

This PR contains 3 commits that fix tickets:
  - #4975 
  - #4982 
  - #5789 
  - #5790

2023-11-22 11:07 UTC, flomonster reviewed
I've tested it and found out few bugs/irritants

- **Bug**: We cannot save a newly created PSL with panels. Editoast expects some kp but we cannot provide them through the form.
- **Bug**: When editing a speed limit some track sections can't be added or removed from the speed limit. I didn't find the reasons why these tracks couldn't be selected.
- **Irritant**: There is no way to see which speed section is currently edited.

Note: I don't know if these points need to be fixed by this PR. We can open new tickets if you wish.

2023-11-22 14:49 UTC, jacomyal commented
> **Bug**: We cannot save a newly created PSL with panels. Editoast expects some kp but we cannot provide them through the form.

New ticket #5792 will be handled outside this PR, since it involves back as well.

> **Bug**: When editing a speed limit some track sections can't be added or removed from the speed limit. I didn't find the reasons why these tracks couldn't be selected.

Ticket #5800 will be added to this PR if I find a fix before it's reviewed.

> **Irritant**: There is no way to see which speed section is currently edited.

Ticket #5799 will be added to this PR if I find a fix before it's reviewed.

2023-11-22 15:14 UTC, SharglutDev requested changes
Thank you for the PR.

Left one comment and you have some warnings left in the code.

2023-11-22 15:14 UTC, SharglutDev commented on front/src/common/Map/Layers/GeoJSONs.tsx
> +    if (blackList.length) conditions.push(['!in', fieldId, ...blackList]);
It's not related to your PR but as we are on a open source project (and anyhow), I think we should use another syntax than "whitelist" and "blacklist"

2023-11-22 16:06 UTC, SharglutDev approved these changes
Thank you for the changes and comments on the function. Lgtm !

2023-11-23 15:03 UTC, clarani approved these changes
LGTM, tested :white_check_mark:

2023-11-23 15:09 UTC, merged