front: improves PSLs highlighting in editor
OpenRailAssociation/osrd pull request #5814
Opened 2023-11-23 09:57 UTC by jacomyal

Fix #5799.

Details:
- Moves hardcoded speed colors from SpeedLimits.tsx and SNCF_PSL.tsx to colors.ts (so that they are transformed by transformTheme in GeoJSONs.tsx)
- Always adds edited entity ID to selection in SpeedSectionEditionLayers so that GeoJSONs always draws everything else as unemphasized
- Improves the transformTheme call in GeoJSONs.tsx, so that bright colors are not always turned to white (the old formula was not working well with the speed colors)

2023-11-23 15:58 UTC, SharglutDev requested changes
Thank you for the PR, it seems there is one case where the selected speedlimit loses the PSL layer too : if we toggle the speedlimit / psl layers with the left panel.

[Capture vidéo du 23-11-2023 16:51:36.webm](https://github.com/osrd-project/osrd/assets/113104137/9fccabdd-00ad-4874-8395-984a1dde0de5)

2023-11-23 16:31 UTC, SharglutDev commented
Ok that was just bad luck, I was selecting a speed section without a PSL thats why this layer disappeared...

2023-11-23 16:32 UTC, SharglutDev approved these changes
Lgtm, good job :)

2023-11-24 09:29 UTC, clarani approved these changes
LGTM, tested :white_check_mark:

2023-11-24 09:35 UTC, merged