front: fix train initial speed when updating a train
OpenRailAssociation/osrd pull request #5846
Opened 2023-11-24 10:51 UTC by clarani

close #4216

2023-11-24 10:54 UTC, Wadjetz approved these changes

2023-11-24 10:56 UTC, woshilapin approved these changes

2023-11-24 10:59 UTC, SharglutDev requested changes

2023-11-24 10:59 UTC, SharglutDev commented on front/src/modules/trainschedule/components/ImportTrainSchedule/Map.tsx
> -import Platforms from 'common/Map/Layers/Platforms';
You have a warning
```suggestion
import { Platforms } from 'common/Map/Layers/Platforms';
```

2023-11-24 11:22 UTC, clarani commented on front/src/modules/trainschedule/components/ImportTrainSchedule/Map.tsx
> -import Platforms from 'common/Map/Layers/Platforms';
Correct, thanks :pray:

2023-11-24 11:25 UTC, SharglutDev approved these changes

2023-11-27 15:49 UTC, Math-R approved these changes

2023-11-27 15:57 UTC, merged