editoast: update readme for onboarding
OpenRailAssociation/osrd pull request #5991
Opened 2023-12-04 14:34 UTC by bougue-pe

also follow-up on 'docker compose' propagation

2023-12-04 14:45 UTC, shenriotpro reviewed
Thanks

2023-12-04 14:45 UTC, shenriotpro commented on editoast/README.md
> +- A postgresql database (get inspiration from the [main docker-compose.yml](/docker-compose.yml), especially for database init)
Why not give a `docker compose up ...` command, like in tests/?

2023-12-04 14:55 UTC, woshilapin approved these changes

2023-12-05 09:01 UTC, flomonster approved these changes

2023-12-05 10:43 UTC, bougue-pe commented on editoast/README.md
> +- A postgresql database (get inspiration from the [main docker-compose.yml](/docker-compose.yml), especially for database init)
Good idea indeed (didn't read that part), done in https://github.com/osrd-project/osrd/compare/c60304cbe08a710c0a7807c99a88a048dbfc64c0..a65d4f54681e6b31ecace2060cecc15612aaf132

2023-12-05 10:51 UTC, woshilapin requested changes

2023-12-05 10:51 UTC, woshilapin commented on editoast/README.md
> +- [tarpaulin](https://github.com/xd009642/tarpaulin): Check code coverage `cargo tarpaulin --skip-clean -o Lcov --output-dir target/tarpaulin/`
I actually believe that `tarpaulin` has been removed from our stack of tools (in the [CI revamp](https://github.com/osrd-project/osrd/pull/5889)). Coverage results are now produced with `grcov`. See https://github.com/osrd-project/osrd/blob/5ac767c5ed078abc7a1c749219d5b3369e74e504/.github/workflows/build.yml#L354.

2023-12-05 21:56 UTC, bougue-pe commented on editoast/README.md
> +- [tarpaulin](https://github.com/xd009642/tarpaulin): Check code coverage `cargo tarpaulin --skip-clean -o Lcov --output-dir target/tarpaulin/`
Good catch, change done: https://github.com/osrd-project/osrd/compare/a65d4f54681e6b31ecace2060cecc15612aaf132..7fd21214b2d0fdd40196294cc35da7514ccc8b14

2023-12-06 11:28 UTC, shenriotpro reviewed
LGTM

2023-12-06 14:05 UTC, woshilapin approved these changes

2023-12-06 15:51 UTC, shenriotpro approved these changes

2023-12-06 16:00 UTC, merged