editoast: handle out of range (punctual objects) case in auto fixes
OpenRailAssociation/osrd pull request #5994
Opened 2023-12-04 15:37 UTC by hamz2a

2023-12-04 15:47 UTC, woshilapin approved these changes

2023-12-04 15:54 UTC, bougue-pe requested changes

2023-12-04 15:54 UTC, bougue-pe commented on editoast/src/views/infra/auto_fixes.rs
> +        | InfraErrorType::OutOfRange { .. } => Ok([Operation::Delete(DeleteOperation {
I think that you have to filter on object-type too, as and "out-of-range" can be issued for other objects than punctual objects, see https://github.com/osrd-project/osrd/issues/5943.

It would be nice to have a test that no removal of speed-section, catenary, etc. is done, too, depending on the difficulty of it.

2023-12-04 16:37 UTC, hamz2a commented on editoast/src/views/infra/auto_fixes.rs
> +        | InfraErrorType::OutOfRange { .. } => Ok([Operation::Delete(DeleteOperation {
Done.

2023-12-04 17:57 UTC, bougue-pe requested changes
Just 2 copy/paste, LGTM otherwise

2023-12-04 17:57 UTC, bougue-pe commented on editoast/src/views/infra/auto_fixes.rs
> +            obj_type: ObjectType::Signal,
```suggestion
            obj_type: ObjectType::Catenary,
```

2023-12-04 17:57 UTC, bougue-pe commented on editoast/src/views/infra/auto_fixes.rs
> +            obj_type: ObjectType::Detector,
```suggestion
            obj_type: ObjectType::OperationalPoint,
```

2023-12-04 22:16 UTC, bougue-pe approved these changes

2023-12-05 08:58 UTC, flomonster approved these changes

2023-12-05 09:23 UTC, merged