front: fix speed multiplier input in op study
OpenRailAssociation/osrd pull request #6107
Opened 2023-12-12 14:06 UTC by RomainValls

closes #5986

2023-12-14 08:41 UTC, SharglutDev requested changes
Thank you for your PR.

It seems that without the min in the input, we can do that with a copy/paste. As it wasn't possible before, maybe we should check with @nicolaswurtz if this behavior is ok.

![Capture d’écran 2023-12-14 à 09 38 21](https://github.com/osrd-project/osrd/assets/113104137/123b26ee-7c36-450f-bb40-7f011df2382e)

2023-12-14 15:01 UTC, anisometropie requested changes

2023-12-14 15:01 UTC, anisometropie commented on front/src/modules/simulationResult/components/TimeButtons.tsx
> +        value={simulationSpeed !== null ? simulationSpeed : ''}
```suggestion
        value={simulationSpeed ?? ''}
```

2023-12-14 15:19 UTC, Akctarus reviewed
Need to fix previous comments before approving

2024-01-11 16:57 UTC, nicolaswurtz commented
I don't understand what is precisely the question, but if I guess right, the new behavior will allow negative values. This shouldn't be allowed. Min should be 1.

2024-01-22 14:48 UTC, SharglutDev approved these changes
Lgtm and tested. Just squash your commits please as they aren't anything in commit 2 and 3.

2024-01-23 13:36 UTC, anisometropie reviewed
This bug should not but handled manually at this level, this should be handle by a dedicated component that we use everytime we need to have an Input with numbers

2024-01-24 10:57 UTC, nicolaswurtz approved these changes

2024-01-24 10:58 UTC, nicolaswurtz commented
> This bug should not but handled manually at this level, this should be handle by a dedicated component that we use everytime we need to have an Input with numbers

Yes! It will be part of future input component from `ui-core`.

2024-01-25 08:16 UTC, anisometropie approved these changes

2024-01-29 16:44 UTC, merged