editoast: utoipa for /single_simulation
OpenRailAssociation/osrd pull request #6153
Opened 2023-12-19 08:43 UTC by Tristramg

2024-01-10 15:35 UTC, flomonster approved these changes
LGTM (didn't review front part)

2024-01-12 14:49 UTC, leovalais requested changes
Thanks! Left a few minor comments.

I believe the following schemas are not used anymore and could be removed from openapi_legacy:

```
Comfort
SimulationReportByTrain
PowerRestrictionRangeItem
```

2024-01-12 14:49 UTC, leovalais commented on editoast/src/views/single_simulation.rs
> +    #[schema(required)]
Given what was in the openapi before, this was both nullable and not required.

2024-01-12 14:49 UTC, leovalais commented on editoast/src/views/single_simulation.rs
> +    #[schema(required)]
Likewise

2024-01-12 14:49 UTC, leovalais commented on editoast/src/views/single_simulation.rs
> +    #[schema(required)]
Likewise

2024-01-12 14:49 UTC, leovalais commented on editoast/src/core/simulation.rs
> +#[derive(Debug, Serialize, ToSchema)]
This schema is not included in schemas!, is this change necessary then?

2024-01-12 14:49 UTC, leovalais commented on editoast/src/views/single_simulation.rs
> +    ScheduleArgs,
You don't need to add ScheduleArgs to components/schemas since you inlined it in SingleSimulationRequest. Also duplicated :D

2024-01-12 14:49 UTC, leovalais commented on editoast/src/views/layers/mod.rs
> +    ViewMetadata,
ViewMetadata is inlined, no need to add it to components/scheams

2024-02-23 10:54 UTC, leovalais approved these changes
LGTM and tested, thanks ! :)

2024-02-23 10:54 UTC, leovalais commented on editoast/src/views/single_simulation.rs
> +    ScheduleArgs,
```suggestion
```

You inlined it in the request ;)

2024-02-26 14:20 UTC, clarani approved these changes
LGTM, tested :heavy_check_mark:

2024-02-26 15:00 UTC, merged