front: lock infra editor
OpenRailAssociation/osrd pull request #6173
Opened 2023-12-20 13:44 UTC by Akctarus

closes #6077

2023-12-21 11:39 UTC, Uriel-Sautron reviewed
LGTM, good job.
Just a comment on the translation.

2023-12-21 11:39 UTC, Uriel-Sautron commented on front/src/applications/editor/Editor.tsx
> +              <div className="infra-locked bg-yellow">{t('Editor.infra-locked')}</div>
```suggestion
              <div className="infra-locked bg-yellow">{t('Editor.infra-errors.infra-locked')}</div>
```

2023-12-22 16:36 UTC, clarani commented on front/src/applications/editor/Editor.tsx
> +  const [getInfraById, { data: infra }] = osrdEditoastApi.endpoints.getInfraById.useLazyQuery({});
I think this call to the api can be avoided, since we always have information on the selected infra. We should add a store variable to store whether the infra is locked or not (in the editor store). If we do it like this, we can update the value of the context each time the value in the store changes (or get the value from the store directly ? Not sure if it is very practical for our usecases)

2024-01-08 12:57 UTC, clarani requested changes
Bug: when I select a track, I can still edit it. I also left some comments :)

2024-01-08 12:57 UTC, clarani commented on front/src/common/InfraSelector/InfraSelectorModalBodyStandard.tsx
> +  function setInfraID(id: number, locked: boolean) {
Change the function so it takes the infra as an arg
```suggestion
  function setInfraID(infra: Infra) {
```

2024-01-08 12:57 UTC, clarani commented on front/src/reducers/infra/index.ts
> +    },
We should update the lockStatus at the same time than the id to avoid any inconsistencies. You can add this in updateInfraID and remove updateInfraLockStatus
```suggestion
    updateInfraID(state: Draft<S>, action: PayloadAction<Infra>) {
      state.infraID = action.payload.id;
      state.infraLockStatus = action.payload.locked;
    },
```

2024-01-08 12:57 UTC, clarani commented on front/src/reducers/infra/index.ts
> +  infraLockStatus: false,
I think infraLockStatus is a very good name (true, false, what does it mean ?). infraIsLocked seems better, but maybe you can find smth even better ;)
```suggestion
  infraIsLocked: false,
```

2024-01-08 12:57 UTC, clarani commented on front/src/reducers/osrdconf/osrdConfCommon/__tests__/utils.ts
> +  describe('should handle updateInfraLockStatus', () => {
You can merge the tests with the updateInfraID tests:
- should update infraID and infraIsLocked

2024-01-08 12:57 UTC, clarani commented on front/src/applications/editor/Editor.tsx
> +      isLocked,
You should rename it (right now it is not used in the left panels, so if you select a track for instance, you can still save it)
```suggestion
      infraIsLocked: isLocked,
```

2024-01-12 12:55 UTC, Akctarus commented on front/src/applications/editor/Editor.tsx
> +      isLocked,
fixed

2024-01-12 12:55 UTC, Akctarus commented on front/src/reducers/osrdconf/osrdConfCommon/__tests__/utils.ts
> +  describe('should handle updateInfraLockStatus', () => {
fixed

2024-01-12 12:55 UTC, Akctarus commented on front/src/reducers/infra/index.ts
> +  infraLockStatus: false,
fixed

2024-01-12 12:56 UTC, Akctarus commented on front/src/common/InfraSelector/InfraSelectorModalBodyStandard.tsx
> +  function setInfraID(id: number, locked: boolean) {
fixed

2024-01-19 14:12 UTC, Math-R approved these changes

2024-01-25 11:28 UTC, clarani approved these changes
LGTM, tested :white_check_mark:

2024-01-25 14:38 UTC, merged