all: handle 'V' unit for electrification in data only
OpenRailAssociation/osrd pull request #6229
Opened 2023-12-28 12:24 UTC by bougue-pe

Front does not add 'V' as unit anymore (but some hard-coded front processing is not tackled and just migrated).
The responsibility for unit is on the data side (rolling stock, catenaries, electrical profiles).

Hand-tested (cards, edit and curves on rolling-stock, legend and catenaries on map, traction on study's speed-space graph):
- OK to load a dump, migrate and use
- OK to load a dump and use without migration (front crashes on speed-space graph as expected for traction)

`osrd` part of https://github.com/osrd-project/osrd-dags/issues/135 (dags not migrated, both should be merged at the same time)

2023-12-28 12:35 UTC, shenriotpro approved these changes
OK for tests/

2024-01-03 13:49 UTC, Castavo approved these changes
Works fine !

I ran the migration successfully, the run time with our current dump seems very acceptable.

I tested the cartography, RS editor and Electrification in the GEV, all seem to work fine after the migration.  
I did not check before migration.

2024-01-03 13:49 UTC, Castavo commented on front/public/locales/fr/simulation.json
> +    "15000V": "15000V 16/2/3",
I feel like this hardcoding could be removed by also changing the import of "15000V" to "15000V 16/2/3"

2024-01-03 13:49 UTC, Castavo commented on front/public/locales/fr/translation.json
> +        "voltage": "{{voltage}}"
Isn't this field useless now ?

2024-01-04 08:42 UTC, clarani commented on front/public/locales/fr/translation.json
> +        "voltage": "{{voltage}}"
I agree, I think we can remove it

2024-01-04 09:31 UTC, clarani approved these changes
LGTM, tested with the migration :white_check_mark: 
Tested the rs editor, the infra editor, the reference map, the rs selector and the gev

2024-01-04 09:31 UTC, clarani commented on front/public/locales/en/simulation.json
> +    "1500V": "1500V",
We can remove those translations (and also 3000V)

2024-01-04 09:31 UTC, clarani commented on front/public/locales/en/translation.json
> +        "voltage": "{{voltage}}"
To remove here too

2024-01-04 10:29 UTC, bougue-pe commented on front/public/locales/fr/simulation.json
> +    "15000V": "15000V 16/2/3",
I'll remove as much as possible for now, but the question is not decided and deferred to https://github.com/osrd-project/osrd-dags/issues/135#issuecomment-1876857154
So keeping the hard-coding for `15000V` -> `15000V 16/2/3`

2024-01-05 08:31 UTC, bougue-pe commented on front/public/locales/fr/translation.json
> +        "voltage": "{{voltage}}"
Done in https://github.com/osrd-project/osrd/pull/6229/commits/8adfa05b0aac95d281834018901ec8e3f8b264e1

2024-01-05 08:43 UTC, bougue-pe commented on front/public/locales/fr/simulation.json
> +    "15000V": "15000V 16/2/3",
It looks like this was dead-code before anyway, so I removed and hand-tested study and stdcm in https://github.com/osrd-project/osrd/commit/8adfa05b0aac95d281834018901ec8e3f8b264e1
Maybe more tests would be nice (if you have an idea of its usage).

2024-01-05 08:44 UTC, bougue-pe commented on front/public/locales/en/translation.json
> +        "voltage": "{{voltage}}"
Done in https://github.com/osrd-project/osrd/commit/8adfa05b0aac95d281834018901ec8e3f8b264e1

2024-01-05 08:46 UTC, bougue-pe commented on front/public/locales/en/simulation.json
> +    "1500V": "1500V",
Done, for details please check reply in https://github.com/osrd-project/osrd/pull/6229#discussion_r1442622039

2024-01-08 14:48 UTC, Tguisnet requested changes

2024-01-08 14:48 UTC, Tguisnet commented on editoast/migrations/2023-12-26-152659_add_electrification_unit/up.sql
> +UPDATE infra SET "version" = (NULLIF("version", '0')::int + 1)::text;
not useful

2024-01-08 17:16 UTC, bougue-pe commented on editoast/migrations/2023-12-26-152659_add_electrification_unit/up.sql
> +UPDATE infra SET "version" = (NULLIF("version", '0')::int + 1)::text;
Removed: https://github.com/osrd-project/osrd/pull/6229/commits/86ec961e505544f08eceb15cd7421f38a0e417c7

2024-01-11 09:44 UTC, Tguisnet approved these changes
Lgtm

2024-01-11 10:33 UTC, Erashin approved these changes
Core part lgtm.

2024-01-12 13:38 UTC, Castavo approved these changes
I checked with the last data dump, works fine !

I tested map, RS editor and simulation with electrical profiles.

2024-01-12 14:05 UTC, merged