Ebe/editoast use serial test
OpenRailAssociation/osrd pull request #6249
Opened 2024-01-02 12:17 UTC by Wadjetz

2024-01-03 09:25 UTC, shenriotpro commented on .github/workflows/build.yml
Should we update the editoast README as well?

2024-01-03 09:56 UTC, shenriotpro commented
Thanks for the PR. I'm a bit skeptical for reasons I explained in https://github.com/osrd-project/osrd/issues/5886. Sorry I didn't notice earlier.

2024-01-03 11:11 UTC, Castavo reviewed
I'm also surprised that 175 tests need to be serialsed

For some of them we could do as for the rolling stocks and change the hard coded string which break unicity constraints I believe

Also, have you considered creating several serial "threads" (like described in [the docs](https://docs.rs/serial_test/2.0.0/serial_test/attr.serial.html)) ?  
I feel like not all tests which are serialized here need to be isolated from **all** other tests.

2024-01-03 11:11 UTC, Castavo commented on editoast/README.md
>  <!--- TODO: when tests are isolated, allow multiple threads (4 may be a good tradeoff for speed/DB pool)  --->
You could also remove this line

2024-01-03 14:21 UTC, shenriotpro requested changes

2024-01-03 14:21 UTC, shenriotpro commented on .github/workflows/build.yml
> -            /bin/bash -c "diesel migration run --locked-schema && cargo test --verbose -- --test-threads=1 && grcov . --binary-path ./target/debug/ -s . -t lcov --branch --ignore-not-existing --ignor
Please keep a somewhat low thread limit. In this state, tests fail on my machine (cleanup fails as well).

2024-01-03 14:21 UTC, shenriotpro commented on .github/workflows/build.yml
> -            /bin/bash -c "diesel migration run --locked-schema && cargo test --verbose -- --test-threads=1 && grcov . --binary-path ./target/debug/ -s . -t lcov --branch --ignore-not-existing --ignor
(also applies for README)

2024-01-03 15:34 UTC, shenriotpro approved these changes
Thanks

2024-01-05 15:33 UTC, Tguisnet approved these changes
lgtm !

2024-01-11 10:14 UTC, ElysaSrc approved these changes
LGTM

2024-01-11 15:48 UTC, merged