front: rename catenary to electrification
OpenRailAssociation/osrd pull request #6262
Opened 2024-01-03 13:45 UTC by Akctarus

close #6115

2024-01-03 16:59 UTC, shenriotpro approved these changes
OK for tests/

2024-01-04 09:26 UTC, eckter approved these changes

2024-01-04 13:33 UTC, Wadjetz approved these changes

2024-01-04 16:23 UTC, SharglutDev requested changes
Thank you for the PR. Tested the front part, only one comment :)

2024-01-04 16:23 UTC, SharglutDev commented on front/public/locales/en/translation.json
> +      "electrifications": "electrifications",
```suggestion
      "electrifications": "Electrifications",
```

2024-01-05 08:31 UTC, Akctarus commented on front/public/locales/en/translation.json
> +      "electrifications": "electrifications",
Ty ! fixed :)

2024-01-05 11:34 UTC, SharglutDev approved these changes

2024-01-11 09:42 UTC, flomonster approved these changes
LGTM (review and tested)

2024-01-11 10:02 UTC, Tguisnet approved these changes

2024-01-11 11:40 UTC, merged