provide a undefined speed limit when user provide empty field
OpenRailAssociation/osrd pull request #6428
Opened 2024-01-23 14:21 UTC by kmer2016

fix the first problem of [this issue](https://github.com/osrd-project/osrd/issues/6407)

The problem was that the way we converted the values entered in Speed limit field returned 0 when the field was left empty.

2024-01-23 16:00 UTC, Akctarus approved these changes
Tested, LGTM

2024-01-24 14:39 UTC, Yohh requested changes

2024-01-24 14:39 UTC, Yohh commented on front/src/applications/editor/tools/rangeEdition/speedSection/SpeedSectionMetadataForm.tsx
> +          <div key={index} className="form-group field field-string">
can you use anything but the index in the key?

2024-01-25 09:05 UTC, flomonster approved these changes
Tested and it works :tada:.

2024-01-25 10:32 UTC, Yohh commented on front/src/applications/editor/tools/rangeEdition/speedSection/SpeedSectionMetadataForm.tsx
> +          <div key={index} className="form-group field field-string">
ok for fixing it in another pr

2024-01-25 10:33 UTC, Yohh approved these changes

2024-01-25 10:35 UTC, SharglutDev approved these changes
Lgtm and tested. As specified by @Yohh, the key issue demands more work and will be fixed in a different [PR](https://github.com/osrd-project/osrd/pull/6461)

2024-01-25 11:08 UTC, merged