front: fix overlapping names
OpenRailAssociation/osrd pull request #6487
Opened 2024-01-29 14:53 UTC by Akctarus

closes #6444 

<img width="1470" alt="Capture d’écran 2024-01-29 à 15 48 44" src="https://github.com/osrd-project/osrd/assets/80635161/5cf8a429-beec-4efd-b894-6546d655e9ef">

<img width="794" alt="Capture d’écran 2024-01-29 à 15 44 46" src="https://github.com/osrd-project/osrd/assets/80635161/f2724df2-a131-4c92-aad9-e427d662443a">

<img width="485" alt="Capture d’écran 2024-01-29 à 15 44 23" src="https://github.com/osrd-project/osrd/assets/80635161/5ecd7e2d-a307-41fa-b7de-e061ef7846dd">

2024-01-30 09:35 UTC, Wadjetz approved these changes

2024-01-30 14:40 UTC, SharglutDev requested changes
Thank you for your PR. 
There are  small UI issues with the breadcrumb : 

![Capture d’écran 2024-01-30 à 15 03 50](https://github.com/osrd-project/osrd/assets/113104137/c30a4b4c-2f87-4a94-abba-a2731bf78ab1)

- one next-arrow icon is missing between the project and the study
- the icons aren't evenly spaced between the project/study/scenario names 
- the icons (excepted the first one) are not vertically centered

2024-02-01 13:33 UTC, SharglutDev reviewed
Thank you for the changes, everything works great, good job !

2024-02-01 14:09 UTC, SharglutDev approved these changes

2024-02-01 14:49 UTC, merged