front: render unique tags for composition codes in timetable
OpenRailAssociation/osrd pull request #6549
Opened 2024-02-01 15:22 UTC by RomainValls

2024-02-14 09:18 UTC, SarahBellaha requested changes
Nice PR ! Left some comments :)

2024-02-14 09:18 UTC, SarahBellaha commented on front/src/modules/trainschedule/components/Timetable/Timetable.tsx
> +  const debouncedRollingstockFilter = useDebounce(rollingStockFilter, 500) as string;
```suggestion
  const debouncedFilter = useDebounce(filter, 500);
  const debouncedRollingstockFilter = useDebounce(rollingStockFilter, 500);
```
I don't think you need this here :)

2024-02-14 09:18 UTC, SarahBellaha commented on front/src/modules/trainschedule/components/Timetable/Timetable.tsx
> +        const rollingStockName = rollingStock?.name || '';
```suggestion
        const { family = '', detail = '', series = '' } = rollingStock?.metadata || {};
```
You don't need to check the name of the rs, it's already done by the `keepTrain()` function l.147

2024-02-14 09:18 UTC, SarahBellaha commented on front/src/modules/trainschedule/components/Timetable/Timetable.tsx
> +          )
```suggestion
![family, detail, series].some((v) =>
            v.toLowerCase().includes(debouncedRollingstockFilter.toLowerCase())
          )
```

2024-02-14 09:18 UTC, SarahBellaha commented on front/src/modules/trainschedule/components/Timetable/Timetable.tsx
> +                    displayTag = t('timetable.noSpeedLimitTags');
```suggestion
    const displayTag = tag !== 'NO CODE' ? tag : 
    t('timetable.noSpeedLimitTags');
```

2024-02-14 09:18 UTC, SarahBellaha commented on front/public/locales/fr/operationalStudies/scenario.json
> +  "advancedFiltersPlaceholder": "Filtre par type, série, détail",
This key seems unused, we can maybe remove it ?

2024-02-14 09:18 UTC, SarahBellaha commented on front/src/modules/trainschedule/components/Timetable/Timetable.tsx
> +                id="scenarios-filter"
```suggestion
                id="timetable-label-filter"
```
As you don't really filter a list of scenarios, maybe you can name it differently, like this ?
Same thing for the `name`, and the `data-testid` attributes.

2024-02-14 09:18 UTC, SarahBellaha commented on front/src/modules/trainschedule/components/Timetable/Timetable.tsx
> +                id="rolling-stock-filter"
```suggestion
                id="timetable-rollingstock-filter"
```
Same as above.

2024-02-14 09:18 UTC, SarahBellaha commented on front/src/modules/trainschedule/components/Timetable/Timetable.tsx
> +                      className={`btn btn-sm  ${selectedTags.has(tag) ? 'btn-success' : ''}`}
```suggestion
                      className={cx('btn', 'btn-sm', { 'btn-success': selectedTags.has(tag) })}
```

2024-02-14 09:18 UTC, SarahBellaha commented on front/src/modules/trainschedule/components/Timetable/Timetable.tsx
> +    setUniqueTags(Array.from(compositionCodes));
```suggestion
    const compositionCodes = trainsList.map((train) => extractTagCode(train.speed_limit_tags));
    setUniqueTags(uniq(compositionCodes));
```

2024-02-14 09:18 UTC, SarahBellaha commented on front/src/modules/trainschedule/components/Timetable/Timetable.tsx
> +    return tag;
```suggestion
    const matches = tag.match(/\w+$/);

    return matches ? matches[0] : tag;
```

2024-02-15 09:27 UTC, nicolaswurtz requested changes

2024-02-15 09:27 UTC, nicolaswurtz commented on front/src/common/BootstrapSNCF/ChipsSNCF.tsx
Since you won't use this component, could you remove changes about it?

2024-02-15 09:27 UTC, nicolaswurtz commented on front/src/modules/trainschedule/components/Timetable/Timetable.tsx
> +        <div className="row">
Why a row ? Use `d-flex` instead.
Pro-tip: never use `row` without `col`. Thx ;)

2024-02-15 09:27 UTC, nicolaswurtz commented on front/src/styles/scss/applications/operationalStudies/_scenario.scss
> +        // padding: 0.25rem;
To remove

2024-02-15 09:27 UTC, nicolaswurtz commented on front/src/styles/scss/applications/operationalStudies/_scenario.scss
> +          background-color: var(--secondary);
Don't Repeat Yourself! You've already wrote this above, please try to use common classes.

2024-02-15 09:27 UTC, nicolaswurtz commented on front/src/styles/scss/applications/operationalStudies/_scenario.scss
> +        }
Don't Repeat Yourself! You've already wrote this below, please try to use common classes.

2024-02-16 14:40 UTC, nicolaswurtz approved these changes

2024-02-16 14:41 UTC, RomainValls commented on front/src/modules/trainschedule/components/Timetable/Timetable.tsx
> +  const debouncedRollingstockFilter = useDebounce(rollingStockFilter, 500) as string;
Done

2024-02-16 14:41 UTC, RomainValls commented on front/src/modules/trainschedule/components/Timetable/Timetable.tsx
> +        const rollingStockName = rollingStock?.name || '';
Done

2024-02-16 14:42 UTC, RomainValls commented on front/src/modules/trainschedule/components/Timetable/Timetable.tsx
> +          )
Done

2024-02-16 14:42 UTC, RomainValls commented on front/src/modules/trainschedule/components/Timetable/Timetable.tsx
> +                    displayTag = t('timetable.noSpeedLimitTags');
Done

2024-02-16 14:42 UTC, RomainValls commented on front/src/modules/trainschedule/components/Timetable/Timetable.tsx
> +                id="scenarios-filter"
Done

2024-02-16 14:42 UTC, RomainValls commented on front/public/locales/fr/operationalStudies/scenario.json
> +  "advancedFiltersPlaceholder": "Filtre par type, série, détail",
Done

2024-02-16 14:43 UTC, RomainValls commented on front/src/modules/trainschedule/components/Timetable/Timetable.tsx
> +                id="rolling-stock-filter"
Done

2024-02-16 14:43 UTC, RomainValls commented on front/src/modules/trainschedule/components/Timetable/Timetable.tsx
> +                      className={`btn btn-sm  ${selectedTags.has(tag) ? 'btn-success' : ''}`}
Done

2024-02-16 14:43 UTC, RomainValls commented on front/src/modules/trainschedule/components/Timetable/Timetable.tsx
> +    setUniqueTags(Array.from(compositionCodes));
Done

2024-02-16 14:43 UTC, RomainValls commented on front/src/modules/trainschedule/components/Timetable/Timetable.tsx
> +    return tag;
Done

2024-02-16 14:43 UTC, SarahBellaha approved these changes
GJ 💪

2024-02-16 15:01 UTC, merged