front: fix overlapping itinerary buttons
OpenRailAssociation/osrd pull request #6551
Opened 2024-02-01 15:54 UTC by Omar-938

- Itinerary.tsx : add flex wrap on line 113 and add margin bottom on line 130

2024-02-01 16:11 UTC, Yohh reviewed
nice, good work

can you update the "add vias" column with responsive behavior as talked earlier?

2024-02-05 14:24 UTC, clarani commented
Pro tip :wink: : You can add in the description of your PR the line `closes #[the number of your issue]`, in your case #6364. This way, the PR is linked directly to the board (see the screenshot below) 
![image](https://github.com/osrd-project/osrd/assets/45000526/2ed5c5c7-2ac0-478e-b145-94d35c9a318b)

2024-02-13 10:35 UTC, Caracol3 requested changes
Good job for the PR!! Did you use ESlint and prettier in vscode? It helps to deal with formating issues

2024-02-13 10:35 UTC, Caracol3 commented on front/src/modules/trainschedule/components/ManageTrainSchedule/Itinerary/Itinerary.tsx
> +        <div className="d-flex flex-column flex-sm-row flex-wrap"style={{ gap: '0.5rem' }}>
You should put the style in the css file or find the associated class in bootstrap if it exists

2024-02-13 12:50 UTC, Math-R commented on front/src/modules/trainschedule/components/ManageTrainSchedule/Itinerary/Itinerary.tsx
> +        <div className="d-flex flex-column flex-sm-row flex-wrap"style={{ gap: '0.5rem' }}>
Yes, please avoid inline style

2024-02-15 13:58 UTC, Yohh requested changes
please configure your linter and your formatter, you have many formatting issues that can't and will not be merged

please link your PR to the associated issue

2024-02-15 13:58 UTC, Yohh commented on front/src/modules/trainschedule/components/ManageTrainSchedule/Itinerary/Itinerary.tsx
> +        <div className="d-flex flex-column flex-sm-row flex-wrap gap-2 btn-itinerary-gap">
```suggestion
        <div className="d-flex flex-column flex-sm-row flex-wrap btn-itinerary-gap">
```

2024-07-03 16:06 UTC, closed without merging

2024-07-03 16:06 UTC, clarani commented
Not relevant anymore