front: add supported_signaling_systems field in rolling stock editor for tvm
OpenRailAssociation/osrd pull request #6552
Opened 2024-02-01 17:53 UTC by SarahBellaha

Closes #6356

2024-02-06 09:09 UTC, flomonster requested changes
Thanks for this PR. 

I reviewed the PR #6377 after it was merged.
We assume a static list of signaling systems in the schema defining the `SignalingSystem` enum. To be consistent with the application we should consider signaling systems as dynamic data.

Some editoast changes should be made (in another PR).

2024-02-06 09:09 UTC, flomonster commented on front/src/modules/rollingStock/consts.ts
> +    enum: ['BAL', 'BAPR', 'TVM300', 'TVM430'],
This enum should not be statically defined in the front. You have an endpoint to retrieve the list of signaling systems the application supports. Check out this endpoint  `/sprites/signaling_systems`.

2024-02-14 09:55 UTC, nicolaswurtz requested changes
![image](https://github.com/osrd-project/osrd/assets/6003856/e9287067-681e-4138-9e27-1b2d72484200)

Hi! Thx for this work ;)
- missing translation/title
- missing alphabetic order of checkbox

2024-02-14 10:04 UTC, clarani requested changes
Thanks for this PR, great job :clap: Some remarks:
- use the new hook to get the rollingStock schema (and remove it from the props)
- simplify RollingStockEditorOnboardSystemEquipmentForm: only 1 component, don't try to make it generic as we don't need it for the moment

Thanks :)

2024-02-14 10:04 UTC, clarani commented on front/public/locales/en/rollingstock.json
> +  "confirmAddRollingStock": "Confirm the addition of the rolling stock ?",
```suggestion
  "confirmAddRollingStock": "Are you sure you want to add this rolling stock ?",
```

2024-02-14 10:04 UTC, clarani commented on front/public/locales/fr/rollingstock.json
> +  "confirmAddRollingStock": "Confirmer l'ajout du matériel roulant ?",
```suggestion
  "confirmAddRollingStock": "Êtes-vous sûr de vouloir ajouter ce matériel roulant ?",
```

2024-02-14 10:04 UTC, clarani commented on front/src/common/api/enhancedEditoastApi.ts
Can we sort the sprites in editoast rather than in the frontend ?

2024-02-14 10:04 UTC, clarani commented on front/src/modules/rollingStock/components/RollingStockCard/RollingStockCardDetail.tsx
> +  const leftColumn = rollingStock && (
You can do an early return just above this, if there is no rollingstock, then you can display the loader

2024-02-14 10:04 UTC, clarani commented on front/src/modules/rollingStock/components/RollingStockCard/RollingStockCardDetail.tsx
> +        {rollingStock.supported_signaling_systems &&
signaling_systems cannot be undefined :) 
```suggestion
        {
```

2024-02-14 10:04 UTC, clarani commented on front/src/modules/rollingStock/consts.ts
> +export function useCompleteRollingStockSchemasProperties(): readonly SchemaProperty[] {
Can you move this hook in a new file ? 
Maybe some comments will help to faster understand what this piece of code does

2024-02-14 10:04 UTC, clarani commented on front/src/modules/rollingStock/components/RollingStockEditor/RollingStockEditorFormHelpers.tsx
> +  refList?: string[];
refList is not used
```suggestion
```

2024-02-14 10:04 UTC, clarani commented on front/src/modules/rollingStock/components/RollingStockEditor/RollingStockEditorFormHelpers.tsx
> +                  'align-items-center': isMassProperty,
```suggestion
                  'd-flex align-items-center': property.title === 'mass',
```

2024-02-14 10:04 UTC, clarani commented on front/src/modules/rollingStock/components/RollingStockEditor/RollingStockEditorFormHelpers.tsx
>                label={t(`${property.title}`)}
```suggestion
              label={t(property.title)}
```

2024-02-14 10:04 UTC, clarani commented on front/src/modules/rollingStock/components/RollingStockEditor/RollingStockEditorFormHelpers.tsx
> +  } = groupBy(rollingStockSchemasProperties, 'side') as { [key: string]: SchemaProperty[] };
Can you also filter here if the properties which need to be displayed ? This way we can filter them only once, and not 3 times in each parameterFormColumn

2024-02-14 10:04 UTC, clarani commented on front/src/modules/rollingStock/components/RollingStockEditor/RollingStockEditorFormHelpers.tsx
> +export const RollingStockEditorOnboardSystemEquipmentForm = ({
You can merge this component & RollingStockEditorOnboardSystemEquipmentFormColumn

2024-02-14 10:04 UTC, clarani commented on front/src/modules/rollingStock/components/RollingStockEditor/RollingStockEditorFormHelpers.tsx
> +};
Simplify the props like this. Don't try to make a generate component, we don't have this need for the moment and it's complicating the code for nothing :) 
```suggestion
type RollingStockEditorOnboardSystemEquipmentFormProps = {
  rollingStockSignalingSystems: string[];
  setRollingStockValues: (
    rollingStockValue: React.SetStateAction<RollingStockParametersValues>
  ) => void;
};
```

2024-02-14 10:04 UTC, clarani commented on front/src/modules/rollingStock/consts.ts
> +}
No need for this anymore

2024-02-14 10:04 UTC, clarani commented on front/src/modules/rollingStock/components/RollingStockEditor/RollingStockEditorFormHelpers.tsx
> +  rollingStockSchemasProperties,
Use the hook to get the rollingStockSchema
```suggestion
```

2024-02-15 16:13 UTC, clarani reviewed
Almost there, thanks for the work :rocket:

2024-02-15 16:13 UTC, clarani commented on front/src/utils/hooks/useCompleteRollingStockSchemasProperties.ts
Maybe we can ask for other points of view, but I would rather put it in modules/rollingStock/hooks

2024-02-15 16:13 UTC, clarani commented on front/src/modules/rollingStock/components/RollingStockEditor/RollingStockEditorFormHelpers.tsx
> +  const updateSigSystemsList = (value: string) => (e: React.ChangeEvent<HTMLInputElement>) => {
```suggestion
  const updateSigSystemsList = (sigSystem: string) => (e: React.ChangeEvent<HTMLInputElement>) => {
```

2024-02-15 16:13 UTC, clarani commented on front/src/modules/rollingStock/components/RollingStockEditor/RollingStockEditorFormHelpers.tsx
> +  const list = sigSystemProperty.enum!.map((sigSystem, index) => {
```suggestion
  const SignalingSystemCheckboxes = sigSystemProperty.enum!.map((sigSystem, index) => {
```

2024-02-15 16:13 UTC, clarani commented on front/src/modules/rollingStock/components/RollingStockEditor/RollingStockEditorFormHelpers.tsx
> +    });
You can remove rollingStockValues from the props and only give rsSignalingSystems (=rollingStockValues.supportedSignalingSystems) as a prop
```suggestion
    setRollingStockValues((prevRollingStockValues) => {
      ...prevRollingStockValues,
      supportedSignalingSystems: newList,
    });
```

2024-02-15 16:13 UTC, clarani commented on front/src/modules/rollingStock/helpers/utils.ts
Very nice function, thanks !

2024-02-15 16:13 UTC, clarani commented on front/src/modules/rollingStock/helpers/utils.ts
> +  refList: string[],
Maybe we can find a more explicit name, what do you think of this ?
```suggestion
  propertyNamesToDisplay: string[],
```

2024-02-15 16:13 UTC, clarani commented on front/src/modules/rollingStock/helpers/utils.ts
> +  rollingStockSchemasProperties: readonly SchemaProperty[],
You don't need this since you use RS_SCHEMA_PROPERTIES (if I'm not wrong)
```suggestion
```

2024-02-15 17:01 UTC, clarani reviewed
Only 1 typo and LGTM, you can already rebase and squash your commits :white_check_mark:

2024-02-15 17:01 UTC, clarani commented on front/src/modules/rollingStock/components/RollingStockEditor/RollingStockEditorFormHelpers.tsx
> +  const rollingStockSchemasPropertiees = useCompleteRollingStockSchemasProperties();
Typo
```suggestion
  const rollingStockSchemasProperties = useCompleteRollingStockSchemasProperties();
```

2024-02-16 09:34 UTC, clarani approved these changes
LGTM and tested :white_check_mark:

2024-02-16 09:42 UTC, anisometropie commented on front/src/modules/rollingStock/hooks/useCompleteRollingStockSchemasProperties.ts
> +      enum: supportedSignalingSystems?.toSorted() || [],
didn’t we already sort in enhancedEditoastApi.ts ?

2024-02-16 09:49 UTC, nicolaswurtz approved these changes

2024-02-16 09:49 UTC, anisometropie reviewed
I guess we need to use rollingStockSchemasProperties everywhere rather than RS_SCHEMA_PROPERTIES, it’s more confusing than anything to have two version in circulation and to wonder which one to use where.

2024-02-16 17:15 UTC, anisometropie commented on front/src/common/api/enhancedEditoastApi.ts
We’ll do that in another PR I think

2024-02-19 10:30 UTC, flomonster approved these changes
LGTM

2024-02-19 10:47 UTC, merged