editoast: new pathfinding endpoint
OpenRailAssociation/osrd pull request #6753
Opened 2024-02-27 13:36 UTC by younesschrifi

2024-03-01 10:58 UTC, flomonster reviewed
Overall it looks good. We should add some documentation on all `pathfinding.rs` functions.

2024-03-01 10:58 UTC, flomonster commented on editoast/src/redis_utils.rs
> +            Some(v) => Ok(serde_json::from_str(&v)?),
We should transform the `SerdeError` into a `Redis` custom error (we can type it as `Serialize`). This will throw a 500 instead of a 400.

2024-03-01 10:58 UTC, flomonster commented on editoast/src/redis_utils.rs
> +        let str_value = serde_json::to_string(value)?;
We should transform the SerdeError into a Redis custom error (we can type it as Serialize). This will throw a 500 instead of a 400.

2024-03-01 10:58 UTC, flomonster commented on editoast/src/views/v2/pathfinding.rs
> +    let res = res.unwrap();
```suggestion
    let pathfinding_result = pathfinding_core(track_offsets)?;
```

2024-03-01 10:58 UTC, flomonster commented on editoast/src/views/v2/pathfinding.rs
> +    let seconds = chrono::TimeDelta::weeks(1).num_seconds();
We can `use chrono::Duration` in headers.

```suggestion
    let seconds = Duration::weeks(1).num_seconds();
```

2024-03-01 10:58 UTC, flomonster commented on editoast/src/views/v2/pathfinding.rs
> +/// Hash all the path input informations
```suggestion
/// Generates a unique hash based on the pathfinding entries.
/// We need to recalculate the path if:
///   - The path entry is different
///   - The infrastructure has been modified
///   - The application has been updated (the algorithm or payloads may have changed)
```

2024-03-01 10:58 UTC, flomonster commented on editoast/src/views/v2/pathfinding.rs
> +struct TrackOffset {
```suggestion
#[derive(Debug, Clone, Serialize)]
struct TrackOffset {
```

2024-03-01 10:58 UTC, flomonster commented on editoast/src/views/v2/pathfinding.rs
> +    // Iterate over path_items to collect trigrams, UICs, and operational point IDs
```suggestion
```

2024-03-01 14:33 UTC, flomonster commented on editoast/src/views/v2/pathfinding.rs
> +        blocks: Vec<NonBlankString>,
```suggestion
        blocks: Vec<NonBlankString>,
        routes: Vec<NonBlankString>,
```

2024-03-01 14:33 UTC, flomonster commented on editoast/src/views/v2/pathfinding.rs
> +pub struct PathfindingInput {
Missing loading gauge

2024-03-01 14:33 UTC, flomonster commented on editoast/src/views/v2/pathfinding.rs
> +
```suggestion
```

2024-03-04 13:46 UTC, Wadjetz approved these changes

2024-03-04 15:36 UTC, leovalais requested changes
Mostly lgtm, a few changes and cosmetic remarks:

2024-03-04 15:36 UTC, leovalais commented on editoast/src/views/v2/pathfinding.rs
> +    OK {
```suggestion
    Success {
```

2024-03-04 15:36 UTC, leovalais commented on editoast/src/views/v2/pathfinding.rs
> +pub struct TrackRanges {
```suggestion
pub struct TrackRange {
```

2024-03-04 15:36 UTC, leovalais commented on editoast/src/views/v2/pathfinding.rs
> +) -> Result<std::result::Result<Vec<Vec<TrackOffset>>, PathfindingResult>> {
Could you make a `type` alias to make that more readable?

2024-03-04 15:36 UTC, leovalais commented on editoast/src/views/v2/pathfinding.rs
> +        OperationalPointModel::retrieve_batch::<_, Vec<_>>(conn, ops_id).await?;
Ignoring missing ids seems sketchy, maybe better call retrieve_batch_or_fail and either panic! or return an error.

2024-03-04 15:36 UTC, leovalais commented on editoast/src/views/v2/pathfinding.rs
> +fn track_offset_from_op(op: &OperationalPointModel) -> Vec<TrackOffset> {
Move as `schema::OperationalPoint::track_offset()`?

2024-03-04 15:36 UTC, leovalais commented on editoast/src/views/v2/pathfinding.rs
> +            track: el.track.0.into(),
```suggestion
            track: el.track,
```

2024-03-04 15:36 UTC, leovalais commented on editoast/src/views/v2/pathfinding.rs
> +                ops = secondary_code_filter(secondary_code, ops);
```suggestion
                let ops = secondary_code_filter(secondary_code, ops);
```
shadowing > mut :p

2024-03-04 15:36 UTC, leovalais commented on editoast/src/views/v2/pathfinding.rs
> +        let (_, missings): (Vec<_>, _) = TrackSectionModel::retrieve_batch(conn, ids).await?;
retrieve_batch_or_fail

2024-03-04 15:36 UTC, leovalais commented on editoast/src/views/v2/pathfinding.rs
> +fn track_offset_from_ops(ops: &[OperationalPointModel]) -> Vec<TrackOffset> {
```suggestion
fn track_offsets_from_ops(ops: &[OperationalPointModel]) -> Vec<TrackOffset> {
```

2024-03-04 15:36 UTC, leovalais commented on editoast/openapi.yaml
> +            - o_k
🤣

2024-03-05 08:47 UTC, flomonster commented on editoast/src/views/v2/pathfinding.rs
> +        OperationalPointModel::retrieve_batch::<_, Vec<_>>(conn, ops_id).await?;
Ideally, we can fail here, but we need to know which waypoint fails (we need the index). The check is performed later when iterating over the waypoints. If the waypoint operation point cannot be found in the hashmap, we return the error.

2024-03-05 15:51 UTC, leovalais commented on editoast/src/views/v2/pathfinding.rs
> +        OperationalPointModel::retrieve_batch::<_, Vec<_>>(conn, ops_id).await?;
Good point. In this case I'd go for:

```rust
// a check for missing ids is performed later
let ids_to_ops: HashMap<_, _> = OperationalPointModel::retrieve_batch_unchecked::<_, Vec<_>>(conn, ops_id)
         .await?
         .into_iter()
         .map(|op| (op.obj_id.clone(), op))
         .collect();
```

2024-03-06 09:01 UTC, younesschrifi commented on editoast/src/views/v2/pathfinding.rs
> +        let (_, missings): (Vec<_>, _) = TrackSectionModel::retrieve_batch(conn, ids).await?;
retrieve_batch_or_fail return an `Err` and we want to return an `Ok`

2024-03-06 09:48 UTC, leovalais approved these changes
LGTM

2024-03-06 09:59 UTC, merged