front: Update translations and display errors count based on filter l…
OpenRailAssociation/osrd pull request #6844
Opened 2024-03-11 17:00 UTC by achrafmohye

Closes #6807

2024-03-20 14:05 UTC, clarani requested changes

2024-03-20 14:05 UTC, clarani commented on front/public/locales/en/translation.json
>          "total-error_zero": "No error found",
You need to add keys _one and _zero for the 2 new keys. You also have to update the existing keys
```suggestion
        "total-errors": "{{count}} errors found",
        "total-all": "{{count}} errors and warnings found",
        "total-warnings": "{{count}} warnings found",
        "total-errors_one": "One error found",
        "total-errors_zero": "No error found",
```

2024-03-22 15:20 UTC, clarani approved these changes
LGTM, tested :white_check_mark:

2024-03-28 16:49 UTC, kmer2016 commented on front/public/locales/fr/translation.json
> +        "total-errors_zero": "Aucune erreur trouvée",
```suggestion
        "total-all": "{{count}} erreurs et avertissements trouvés",
        "total-all_one": "Une erreur ou un avertissement trouvé",
        "total-all_zero": "Aucune erreur ni avertissement trouvé",
        "total-warnings": "{{count}} avertissements trouvés",
        "total-warnings_zero": "Aucun avertissement trouvé",
        "total-warnings_one": "Un avertissement trouvés",
        "total-errors": "{{count}} erreurs trouvées",
        "total-errors_one": "Une erreur trouvée",
        "total-errors_zero": "Aucune erreur trouvée",
```

Just group by message type

2024-03-28 16:49 UTC, kmer2016 commented on front/public/locales/en/translation.json
> +        "total-errors": "{{count}} errors found",
same comment than the previous one

2024-04-04 14:40 UTC, kmer2016 approved these changes
LGTM !

2024-04-04 14:52 UTC, merged