front: fix infra lock status
OpenRailAssociation/osrd pull request #7078
Opened 2024-04-03 08:38 UTC by Akctarus

closes #6952

2024-04-03 10:24 UTC, Uriel-Sautron reviewed
LGTM, good work thank you.
Just a comment.

2024-04-03 10:24 UTC, Uriel-Sautron commented on front/src/applications/editor/tools/rangeEdition/tool-factory.tsx
> +            return isInfraLocked || false;
```suggestion
            return !!isInfraLocked;
```

2024-04-03 12:08 UTC, Akctarus commented on front/src/applications/editor/tools/rangeEdition/tool-factory.tsx
> +            return isInfraLocked || false;
Thank you ! Fixed

2024-04-04 13:49 UTC, clarani requested changes
The save button is not disabled in the speed limit tab :/ 
![image](https://github.com/osrd-project/osrd/assets/45000526/a9e5d0b9-e80e-4811-aba2-97f5e379529d)

2024-04-04 13:49 UTC, clarani commented on front/src/applications/editor/Editor.tsx
> +  const [getInfraById, { data: infra }] = osrdEditoastApi.endpoints.getInfraById.useLazyQuery({});
Don't use a lazy query, use useQuery directly

2024-04-05 12:09 UTC, Akctarus commented on front/src/applications/editor/Editor.tsx
> +  const [getInfraById, { data: infra }] = osrdEditoastApi.endpoints.getInfraById.useLazyQuery({});
Fixed !

2024-04-05 12:51 UTC, clarani approved these changes
LGTM, tested :white_check_mark:

2024-04-05 13:24 UTC, merged