editoast: move rolling stock to schemas
OpenRailAssociation/osrd pull request #7128
Opened 2024-04-08 12:27 UTC by Wadjetz

2024-04-08 14:30 UTC, leovalais requested changes
Thanks for this PR. There are a few things to change, including some changes that went while I was off:

1. As stated in the tracking issue https://github.com/osrd-project/osrd/issues/7048#issue-2213585803, there should be only one definition of RollingStock in editoast_schemas.
2. RollingStockWithLiveries is a view response, not a schema. It should be moved into views/.
3. Please reference the tracking issues in the description of the PR, that helps the review ;)

2024-04-08 14:30 UTC, leovalais commented on editoast/editoast_schemas/src/rolling_stock/mod.rs
>  editoast_common::schemas! {
I'd prefer to keep that declaration just below the imports.

2024-04-08 15:08 UTC, woshilapin approved these changes
Looks good. Thanks.

2024-04-09 10:47 UTC, leovalais requested changes

2024-04-09 10:47 UTC, leovalais commented on editoast/src/views/rolling_stocks/mod.rs
> +        assert_eq!(response_body.name, Some(rolling_stock_form.name));
The changeset conversion doesn't seem necessary.

2024-04-09 10:47 UTC, leovalais commented on editoast/editoast_schemas/src/rolling_stock/mod.rs
As the split progresses we want to adopt the Rust 2018 modules convention. Could you mv this file to `editoast_schemas/src/rolling_stock.rs`?

2024-04-09 10:47 UTC, leovalais commented on editoast/editoast_schemas/src/rolling_stock/mod.rs
>  editoast_common::schemas! {
I'd also prefer to have a `schema!` declaration in each module a schema is defined. 

```rust
schema! {
    RollingStock,
    gamma:schemas(),
    energy_source::schemas()
    ...
}
```

2024-04-09 10:52 UTC, Wadjetz commented on editoast/editoast_schemas/src/rolling_stock/mod.rs
yes, but it trigger clippy modules inception warning

2024-04-09 17:11 UTC, leovalais approved these changes
LGTM thanks!

2024-04-09 17:11 UTC, leovalais commented on editoast/src/views/rolling_stocks/mod.rs
> +        assert_eq!(Some(response_body.name), Some(rolling_stock_form.name));
```suggestion
        assert_eq!(response_body.name, rolling_stock_form.name);
```

2024-04-10 07:51 UTC, clarani approved these changes
LGTM :white_check_mark:

2024-04-10 08:01 UTC, merged