Cnh/intregate UI core from npm
OpenRailAssociation/osrd pull request #7162
Opened 2024-04-10 09:03 UTC by kmer2016

Testing the integration of ui-core into osrd/front. 

:warning: Do not merge before removing the last commit, which is only there to test the integration of the ui-core input into an osrd form (rollingstockEditor). 
![image](https://github.com/OpenRailAssociation/osrd/assets/19575568/e5f26658-564b-4000-9137-b85f0ee2b403)

To handle the integration properly, we need to reset some styles. This is due to the base style of Tailwind that comes with ui-core, which sets the default style for these HTML elements. In particular : 

- the display of **img** and **svg** is set to display:block, which positions them above or below their sibling elements. (i[ssue reported here](https://github.com/tailwindlabs/tailwindcss/issues/942)).

- the height of the img is set to auto, which causes the img to take up all the available space of the parent element even if you define a height in the style ([issue reported here](https://github.com/tailwindlabs/tailwindcss/pull/7742#issuecomment-1061332148)). 

- The **button** has a background-color transparent as mentionned [here](https://github.com/tailwindlabs/tailwindcss/issues/6602)

2024-04-15 12:51 UTC, SharglutDev reviewed
When I try to focus an input with tab, I get this : 

![image](https://github.com/OpenRailAssociation/osrd/assets/113104137/19b6b8d7-b1bf-46d8-a53e-a21dd43bbb77)

Is that normal ?

2024-04-23 14:19 UTC, clarani requested changes
Great PR, I spotted some bugs:

- display is broken if I click on the arrow next to the eye in the scenario page :eye: 
![image](https://github.com/OpenRailAssociation/osrd/assets/45000526/8610c6a9-b322-4d72-aa26-53c4e61d4c71)

- the display of the simulation parameters is not correct, same for the import tab and the stdcm page
![image](https://github.com/OpenRailAssociation/osrd/assets/45000526/d27ca95c-ec19-485a-a041-a88e0740eef5)
![image](https://github.com/OpenRailAssociation/osrd/assets/45000526/f0db7597-a9a5-4b15-88d7-ccc52c2f2ecc)
![image](https://github.com/OpenRailAssociation/osrd/assets/45000526/d80d7174-d0a0-4da1-a034-6ea3df15bc82)

- the rolling stock image is very small in the rolling stock selector
![image](https://github.com/OpenRailAssociation/osrd/assets/45000526/0160867a-606f-4dfb-8a28-057cc5bbe40e)

- the label is transparent on the editor
![image](https://github.com/OpenRailAssociation/osrd/assets/45000526/bf3545d8-88e8-481f-a373-7ed795935fea)

- the selector modal is broken in the editor
![image](https://github.com/OpenRailAssociation/osrd/assets/45000526/e1f07e90-df0d-41f2-a2d1-73beacc5b37d)

- the popover to search the map is too large
![image](https://github.com/OpenRailAssociation/osrd/assets/45000526/b53df244-811e-4fa7-bb1c-6aef3d1a3269)

- the popover to select the data layer is also broken in the main map
![image](https://github.com/OpenRailAssociation/osrd/assets/45000526/13ce3fda-8eac-4bc6-bdcd-872c96c86b03)

2024-04-23 14:19 UTC, clarani commented on front/src/styles/styles.scss
> +@import 'scss/_uiCoreIintegration.scss';
You forgot an empty line here :)

2024-04-25 09:26 UTC, clarani reviewed
The interface is perfect now, thanks, I only noticed that the input does not seem to work and you forgot a new line :+1:

2024-04-25 09:26 UTC, clarani commented on front/src/styles/scss/_uiCoreIntegration.scss
> +}
Missing new line

2024-04-25 10:54 UTC, clarani approved these changes
LGTM :white_check_mark: You can merge after you have done these few things:
- [ ] fix the missing new line
- [ ] remove the commit which test the new input component

The bugs related to the input will be fixed later in osrd-ui

2024-04-25 11:20 UTC, clarani approved these changes

2024-04-25 11:44 UTC, merged