editoast: adapt endpoint for routes from switches
OpenRailAssociation/osrd pull request #7239
Opened 2024-04-17 07:25 UTC by SarahBellaha

Closes #7019

2024-04-18 13:06 UTC, woshilapin reviewed
Nice work. There is one closure that, I believe, start to get too big and that we should work on. Let me know if you agree with that or if you want to discuss it.

2024-04-18 13:06 UTC, woshilapin commented on editoast/src/views/infra/routes.rs
> +        }));
Maybe you can `#[derive(Default)]` on `RoutesFromNodesPositions` and use it here with `RoutesFromNodesPositions::default()`?

2024-04-18 13:06 UTC, woshilapin commented on editoast/src/views/infra/routes.rs
>          .filter(|(_, route)| {
This makes a huge closure, that does multiple things at once (filtering, filling up some `HashMap`), with some side effects (the `HashMap` filling up). Sometimes, we don't have a choice for such complex code but in this case, I believe we can try to improve a bit the situation.

I propose the following code https://github.com/OpenRailAssociation/osrd/pull/7263, which I made as a PR targeting directly your branch. So if you're happy with it, you can just merge the PR (or `cherry-pick` it) to include it in your branch. Do not hesitate to ping me if you're not familiar with how to do it.

2024-04-18 13:22 UTC, leovalais approved these changes
Thanks for this PR :) I second @woshilapin on the complexity of the closure.

On a more general note, Rust allows us to write code in both imperative and functional programming styles. But these do not really work well together and shouldn't be mixed (exceptions exist ofc 😁).
If you're modifying an algorithm written in imperative style, better stick to it, and vice versa. And sometimes your evolution doesn't fit the paradigm, in which case you can always rewrite the whole function in your preferred style ;)

I approved @woshilapin fix.

2024-04-18 13:22 UTC, leovalais commented on editoast/src/views/infra/routes.rs
> +            let process_available_positions = |positions: &HashMap<String, Vec<String>>| {
```suggestion
            fn process_available_positions(positions: &HashMap<String, Vec<String>>) -> Vec<String, Vec<String>> {
```

Making a closure this way usually suggests you're capturing some value, `fn` makes it clear that you're not.

2024-04-18 13:22 UTC, leovalais commented on editoast/src/views/infra/routes.rs
> +            got_available_positions.sort();
You can sort in your processing function directly, so you don't need mutability.

2024-04-18 19:22 UTC, woshilapin approved these changes

2024-04-19 13:15 UTC, Math-R approved these changes
lgtm

2024-04-22 17:10 UTC, flomonster requested changes
Thanks for your PR.

2024-04-22 17:10 UTC, flomonster commented on editoast/src/views/infra/routes.rs
> +    available_node_positions: HashMap<String, Vec<String>>,
We should add documentation on these fields.

2024-04-22 17:10 UTC, flomonster commented on editoast/src/views/infra/routes.rs
> +    available_node_positions: HashMap<String, Vec<String>>,
We should use `HashSet` since we don't want duplicated values. It will also simplify the code bellow.

```suggestion
    available_node_positions: HashMap<String, HashSet<String>>,
```

2024-04-22 17:10 UTC, flomonster commented on editoast/src/views/infra/routes.rs
> +                        }
You don't have to do this if you're using the appropriate data structure (`HashSet` instead of a `Vec`).

2024-04-22 17:10 UTC, flomonster commented on editoast/src/views/infra/routes.rs
> +                for (switch_id, switch_state) in route.switches_directions.iter() {
What you are doing here is:

1. Iterate over the `X` nodes of the route
2. If the switch is part of the `N` `node_states` do something otherwise do nothing

This is not optimal. Since we know the `N` nodes, we can iterate over this list without a filter.

2024-04-23 16:00 UTC, flomonster approved these changes
LGTM

2024-04-24 08:23 UTC, merged