editoast: add get rolling stock by name endpoint
OpenRailAssociation/osrd pull request #7243
Opened 2024-04-17 11:12 UTC by younesschrifi

Add an enpoint to retrieve a rolling stock given its name.

2024-04-17 12:10 UTC, leovalais requested changes
Mostly lgtm, just some details:

2024-04-17 12:10 UTC, leovalais commented on editoast/src/views/rolling_stocks/mod.rs
> -    NotFound { rolling_stock_id: i64 },
Either make a second variant or do something like:

```
KeyNotFound { rolling_stock_key: RollingStockKey }

#serde tag = "type"
enum RollingStockKey = Id(i64) | Name(String)
```

because a RS ID is not a string ;)

2024-04-17 12:10 UTC, leovalais commented on editoast/src/views/rolling_stocks/mod.rs
> +pub async fn retrieve_existing_rolling_stock<T>(
If you decide to make an enum `RollingStockKey` you can pass it in parameter here, eliminating the need for generics.

Otherwise I'd suggest naming the key `K` to stay consistent with the definitions of `modelsv2::prelude`.

2024-04-17 12:10 UTC, leovalais commented on editoast/src/views/rolling_stocks/mod.rs
> +        let response = call_service(&app, req).await;
Could you move that into a new test case?

2024-04-17 12:10 UTC, leovalais commented on editoast/src/views/rolling_stocks/mod.rs
> +        let app = create_test_service().await;
likewise

2024-04-18 07:59 UTC, leovalais approved these changes
LGTM, thanks!

2024-04-18 09:06 UTC, flomonster approved these changes
LGTM

2024-04-18 09:15 UTC, SharglutDev approved these changes
Lgtm. You can rest now :)

2024-04-18 10:45 UTC, merged