front: initilize stdcm v2
OpenRailAssociation/osrd pull request #7414
Opened 2024-05-15 07:00 UTC by kmer2016

2024-05-22 12:43 UTC, clarani reviewed
Use const instead of function in all the files to be coherent with the existing code base

2024-05-22 12:43 UTC, clarani commented on front/src/applications/stdcm/Home.tsx
I think you can gather Home, HomeV1 and Homev2 since the 3 files are almost empty

2024-05-22 12:43 UTC, clarani commented on front/src/applications/stdcmV2/views/StdcmViewV2.tsx
> +export default function StdcmViewV2() {
```suggestion
const StdcmViewV2 = () => {
```
and at the end of the file:
```
export default StdcmViewV2;
```

2024-05-22 13:15 UTC, clarani commented on front/src/applications/stdcmV2/components/StdcmConsist.tsx
> +  const selectedRs = rollingStocks.find((rs) => rs.id === rollingStockID);
Use useStoreDataForRollingStockSelector instead
```suggestion
  const { rollingStock: selectedRs } = useStoreDataForRollingStockSelector();
```

2024-05-22 13:15 UTC, clarani commented on front/src/applications/stdcmV2/components/StdcmConsist.tsx
> +    });
Move this endpoint call in useFilterRollingStock

2024-05-22 13:15 UTC, clarani commented on front/src/applications/stdcm/views/useStdcm.tsx
move this file in src/applications/stdcm, you can create a folder hooks

2024-05-22 13:15 UTC, clarani commented on front/src/modules/rollingStock/components/RollingStockCard/useFilterRollingStock.tsx
Move this hook in modules/rollingStock/hooks

2024-05-22 13:15 UTC, clarani commented on front/src/modules/rollingStock/components/RollingStockCard/useFilterRollingStock.tsx
> +  filteredRollingStockList: LightRollingStockWithLiveries[];
This is not used
```suggestion
```

2024-05-22 13:43 UTC, Akctarus reviewed
Good PR, thank you for the refactor. Tested and LGTM for the start of V2 implementation. Left few comments.

2024-05-22 13:43 UTC, Akctarus commented on front/src/reducers/osrdconf/types.ts
> +export type Sillon = {
```suggestion
export type Path/TrainPath = {
```

2024-05-22 13:43 UTC, Akctarus commented on front/src/applications/stdcmV2/components/StdcmConsist.tsx
> +      <RollingStock2Img rollingStock={rollingStock} />
When you select a long rolling stock (e.g. : US TGV 2N2 (M+8R+R) -- 1TGV2N2), the section gets too big. The style used in RollingStockSelector.tsx should be recovered to reduce the image size and hide the overflow.

2024-05-22 13:43 UTC, Akctarus commented on front/src/applications/stdcmV2/components/StdcmConsist.tsx
> +            label="Engin de traction"
Where the text will remain, wouldn't it be better to add the translations to the translation file and use them?

2024-05-22 14:59 UTC, clarani commented on front/src/applications/stdcmV2/components/StdcmConsist.tsx
> +    useState<LightRollingStockWithLiveries[]>(rollingStocks);
Move this in the hook
```suggestion
```

2024-05-22 14:59 UTC, clarani commented on front/src/modules/rollingStock/components/RollingStockCard/useFilterRollingStock.tsx
> +      effortCurves?.modes,
```suggestion
      effortCurves.modes,
```

2024-05-22 14:59 UTC, clarani commented on front/src/modules/rollingStock/components/RollingStockCard/useFilterRollingStock.tsx
> +    const passNotlockedFilter = rollingStockPassesNotlockedFilter(locked as boolean, filters);
```suggestion
    const passLockedFilter = rollingStockPassesLockedFilter(locked, filters);
    const passNotlockedFilter = rollingStockPassesNotlockedFilter(locked, filters);
```

2024-05-22 15:02 UTC, clarani commented on front/src/modules/rollingStock/components/RollingStockCard/useFilterRollingStock.tsx
> +  return rollingStockList?.filter(({ name, metadata, effort_curves: effortCurves, locked }) => {
```suggestion
  return rollingStockList.filter(({ name, metadata, effort_curves: effortCurves, locked }) => {
```

2024-05-23 09:05 UTC, clarani commented on front/src/applications/stdcmV2/views/StdcmViewV2.tsx
> +          <div className="stdcm-v2-simulation-itinirary">
I think we should show all the cards only if infraId is defined (if a scenario is selected. If no scenario is selected, then infraId should be undefined)

2024-05-23 09:05 UTC, clarani commented on front/src/applications/stdcmV2/components/StdcmConsist.tsx
> +    if (subseries) res += series ? ` (${subseries})` : subseries;
Add a test 'if (metadata)', also clean the tests for metadata (remove the ? and the || '')
```suggestion
    if (metadata) {
      const series = metadata.series ?? metadata.reference;
      const subseries =
        metadata.series && metadata.series !== metadata.subseries
          ? metadata.subseries
          : metadata.detail;

      if (series) res += series;
      if (subseries) res += series ? ` (${subseries})` : subseries;
    }
```

2024-05-23 09:05 UTC, clarani commented on front/src/applications/stdcmV2/components/StdcmConsist.tsx
> +    }
```suggestion
    } else {
      searchMateriel('');
    }
```

2024-05-23 09:05 UTC, clarani commented on front/src/applications/stdcmV2/components/StdcmConsist.tsx
> +  useEffect(() => {
There is a bug in useStoreDataForRollingStockSelector, can you update what you return ? If rollingStockId is undefined, you should also return undefined for the rollingStock (and not the previous rs selected)

2024-05-23 09:10 UTC, clarani commented on front/src/applications/rollingStockEditor/views/RollingStockEditor.tsx
> +export default function RollingStockEditor() {
use const

2024-05-23 09:10 UTC, clarani commented on front/src/applications/stdcm/views/StdcmRequestModal.tsx
Very nice ! You can move the useEffect in the parent component in StdcmView directly and only give 1 singleProps to the modal: isOpen={currentStdcmRequestStatus === STDCM_REQUEST_STATUS.pending}

2024-05-23 09:51 UTC, clarani commented on front/src/applications/stdcmV2/components/StdcmSuggestions.tsx
> +  const [isSelectVisible, setIsSelectVisible] = useState(!isEmpty(options));
By default, it should be close
```suggestion
  const [isSelectVisible, setIsSelectVisible] = useState(false);
```

2024-05-23 09:51 UTC, clarani commented on front/src/common/BootstrapSNCF/SelectSNCF.tsx
> +          <option key={`${index}-${getOptionValue(option)}`} value={getOptionValue(option)}>
Why did you add that ? Actually, we should not have any duplicates in the options

2024-05-23 09:51 UTC, clarani commented on front/src/common/BootstrapSNCF/SelectImprovedSNCF.tsx
> +      filteredOptions.map((option, index) => (
Each option should be unique, you should remove the duplicates before giving the options to the component and revert these change

2024-05-23 09:51 UTC, clarani commented on front/src/common/BootstrapSNCF/NavBarSNCF.tsx
> +                disabled={pathname === '/'}
Do you still want to keep that or Théo fixed the bug ? If we keep this change, can you add a comment "TODO  TS v2: remove this disabled" ? Thanks :)

2024-05-23 09:51 UTC, clarani commented on front/src/assets/pictures/views/stdcm_v2_loader.jpg
Have you minified the image ?

2024-05-23 09:51 UTC, clarani commented on front/src/common/Map/Search/useSearchOperationalPoint.tsx
> +  } = props || {};
use const, export default and rename searchTerm and chCodeFilter in the type
```suggestion
const useSearchOperationalPoint = ({
  debounceDelay = 150,
  mainOperationalPointsOnly = false,
  initialSearchTerm = '',
  initialChCodeFilter = '',
}: SearchOperationalPoint) => {
```

2024-05-23 09:51 UTC, clarani commented on front/src/common/Map/Search/useSearchOperationalPoint.tsx
> +    };
Rename the function and simplify it
```suggestion
    const shouldInclude = (result: SearchResultItemOperationalPoint) => {
      if (!chCodeFilter) return true;
      return result.ch.toLocaleLowerCase().includes(chCodeFilter.trim().toLowerCase());
    };
```

2024-05-23 09:51 UTC, clarani commented on front/src/common/Map/Search/useSearchOperationalPoint.tsx
> +      results.sort((a, b) => a.name.localeCompare(b.name) || a.ch?.localeCompare(b.ch));
```suggestion
      results.sort((a, b) => a.name.localeCompare(b.name) || a.ch.localeCompare(b.ch));
```

2024-05-23 09:51 UTC, clarani commented on front/src/common/Map/Search/useSearchOperationalPoint.tsx
> +    });
You can replace that by a reduce if you want (optional)

2024-05-23 09:51 UTC, clarani commented on front/src/common/Map/Search/useSearchOperationalPoint.tsx
> +    const sortedOtherPoints = sortResults(otherPoints);
Sort the otherPoints after the test mainOperationalPointsOnly

2024-05-23 09:51 UTC, clarani commented on front/src/common/Map/Search/useSearchOperationalPoint.tsx
> +    () => [...compact(sortedResults.sort().map((result) => result.ch))],
Remove duplicates, you can use the function removeDuplicates of utils/array

2024-05-23 09:51 UTC, clarani commented on front/src/common/Map/Search/useSearchOperationalPoint.tsx
> +export const mainOperationalPointsCHCodes = ['', '00', 'BV'];
I would prefer screaming case for static array like this (MAIN_OP_CH_CODES). Also if you don't replace its other usages, you should not export it

2024-05-23 13:48 UTC, SharglutDev requested changes
Thank you for this great PR. As there has been 2 review already, I just compared your UI to the one of the model and left some comments.

2024-05-23 13:48 UTC, SharglutDev commented on front/src/applications/stdcmV2/views/StdcmViewV2.tsx
> +            {isPending && <StdcmLoader cancelStdcmRequest={cancelStdcmRequest} ref={loaderRef} />}
Here is what I see on your PR : 
![Capture d’écran 2024-05-23 à 15 13 06](https://github.com/OpenRailAssociation/osrd/assets/113104137/3db223d7-1a6d-4d7c-b79e-d517e243b0ea)

On the sketch model : 
![Capture d’écran 2024-05-23 à 15 14 59](https://github.com/OpenRailAssociation/osrd/assets/113104137/25311c3d-ba5e-4258-af3e-dd989f28265c)

It seems that the text should be center and in bold. Also It seems that here is still this kind of teal inline border at the top of your button which doesn't seem to be there in the model.

2024-05-23 13:48 UTC, SharglutDev commented on front/src/styles/scss/applications/stdcmV2/_card.scss
> +        // font-family: "IBMPlexSans-SemiBold";
Why is this commented ? It looks like the font used doesn't match exactly the one from the model.

If the font isn't ready yet, maybe we should leave a comment or TODO here.

2024-05-23 13:48 UTC, SharglutDev commented on front/src/applications/stdcmV2/components/StdcmOperationalPoint.tsx
> +          label="CI"
![Capture d’écran 2024-05-23 à 15 26 53](https://github.com/OpenRailAssociation/osrd/assets/113104137/f636a5eb-4cc1-4814-942b-f533528db420)

The spacing between the label and the selector seems to be bigger than the one of the model (with all inputs): 
![Capture d’écran 2024-05-23 à 15 28 15](https://github.com/OpenRailAssociation/osrd/assets/113104137/862e60a0-010a-4084-8a3b-9652b46de4ed)

2024-05-23 13:48 UTC, SharglutDev commented on front/src/applications/stdcmV2/components/StdcmOrigin.tsx
> +        </div>
![Capture d’écran 2024-05-23 à 15 30 29](https://github.com/OpenRailAssociation/osrd/assets/113104137/5ac8d19f-0039-440c-9e42-39dd8742f8b0)

First and second rows are not aligned

2024-05-23 13:48 UTC, SharglutDev commented on front/src/styles/scss/applications/stdcmV2/_card.scss
> +        border-right: 20px solid transparent;
![Capture d’écran 2024-05-23 à 15 42 24](https://github.com/OpenRailAssociation/osrd/assets/113104137/67947526-a23b-4233-9316-06ebdfbff75d)

The arrow is longer and doesn't have the box shadow from the model : 

![Capture d’écran 2024-05-23 à 15 35 42](https://github.com/OpenRailAssociation/osrd/assets/113104137/bc817787-eafa-4271-bbd1-35530954180a)

2024-05-23 13:48 UTC, SharglutDev commented on front/src/applications/stdcmV2/components/StdcmConsist.tsx
> +    >
Not sure if its on purpose but on model (screen below), the rolling stock image seems to "ride" on the top of the card body but yours is centered.

![Capture d’écran 2024-05-23 à 15 43 47](https://github.com/OpenRailAssociation/osrd/assets/113104137/20ef0280-f42f-4285-a223-142927815092)

2024-05-24 11:00 UTC, clarani commented on front/src/applications/stdcmV2/components/StdcmCard.tsx
> +        {title && title}
```suggestion
        {title}
```

2024-05-24 11:00 UTC, clarani commented on front/src/applications/stdcmV2/components/StdcmConsist.tsx
> +  const [isSelectChanged, setIsSelectChanged] = useState(false);
I think the name of the variable is not very clear, what do you think of rsSelectedByClick ? or rsJustSelectedByClick ?
```suggestion
  const [rsSelectedByClick, setRsSelectedByClick] = useState(false);
```

2024-05-24 11:00 UTC, clarani commented on front/src/applications/stdcmV2/components/StdcmDestination.tsx
> +        </div>
We should remove this because I think the backend is not even ready for this feature
```suggestion
```

2024-05-24 11:00 UTC, clarani commented on front/src/applications/stdcmV2/components/StdcmHeader.tsx
> +      <a href="#notification">Plus d’informations</a>
Hide the link if it does not show anything for the moment

2024-05-24 11:00 UTC, clarani commented on front/src/applications/stdcmV2/components/StdcmLoader.tsx
> +          Pour votre demande, le temps nécessaire <br /> est généralement de 90 secondes
Do not use <br /> but rather use css
```suggestion
          Pour votre demande, le temps nécessaire est généralement de 90 secondes
```

2024-05-24 11:00 UTC, clarani commented on front/src/applications/stdcmV2/components/StdcmConsist.tsx
> +const StdcmConsist = ({ isPending = false }: { isPending?: boolean }) => {
```suggestion
const StdcmConsist = ({ disabled = false }: { disabled?: boolean }) => {
```

2024-05-24 11:00 UTC, clarani commented on front/src/applications/stdcmV2/components/StdcmDestination.tsx
> +const StdcmDestination = ({ isPending = false }: { isPending?: boolean }) => {
```suggestion
const StdcmDestination = ({ disabled = false }: { disabled?: boolean }) => {
```

2024-05-24 11:00 UTC, clarani commented on front/src/applications/stdcmV2/components/StdcmOrigin.tsx
> +const StdcmOrigin = ({ isPending = false }: { isPending?: boolean }) => {
```suggestion
const StdcmOrigin = ({ disabled = false }: { disabled?: boolean }) => {
```

2024-05-24 16:20 UTC, clarani commented on front/src/modules/rollingStock/components/RollingStockSelector/__tests__/RollingStockModal.spec.ts
> +import { rollingStockPassesEnergeticModeFilters } from '../../../hooks/useFilterRollingStock';
Don't use relative imports

2024-05-24 16:20 UTC, clarani commented on front/src/modules/rollingStock/hooks/useFilterRollingStock.tsx
> +  const updateSearch = () => {
This function is only used in a useEffect, I think it's better if we remove it and move its code in the useEffect directly

2024-05-24 16:20 UTC, clarani commented on front/src/modules/rollingStock/hooks/useFilterRollingStock.tsx
> +  }, [mustResetFilters]);
You already return the resetFilters function, I think it is enough.
Remove this hook and the props mustResetFilters and setMustResetFilters, and in RollingStock editor remove the const isDuplicating and use directly resetFilters in RollingStockEditorButtons
```suggestion
```

2024-05-24 16:20 UTC, clarani commented on front/src/modules/rollingStock/hooks/useFilterRollingStock.tsx
> +  function handleRollingStockLoaded() {
This function is only used once, you can remove it and move its code directly in the useEffect since it's quite straightforward

2024-05-24 16:20 UTC, clarani commented on front/src/modules/rollingStock/hooks/useFilterRollingStock.tsx
> +  return rollingStockList.filter(({ name, metadata, effort_curves: effortCurves, locked }) => {
(only suggestion) I would rather keep rollingStock, it's clearer
```suggestion
  return rollingStockList.filter((rollingStock) => {
```

2024-05-24 16:20 UTC, clarani commented on front/src/modules/rollingStock/hooks/useFilterRollingStock.tsx
> +function rollingStockPassesNotlockedFilter(locked: boolean, filters: RollingStockFilters) {
Same for rollingStockPassesLockedFilter
```suggestion
function rollingStockPassesNotlockedFilter(isLocked: boolean, filters: RollingStockFilters) {
```

2024-05-24 16:20 UTC, clarani commented on front/src/modules/rollingStock/hooks/useFilterRollingStock.tsx
> +) {
You can create a const initialFilters and then check that the filters have changed. This avoid the .filter on the rollingStocks for nothing:
```suggestion
) {
  if (filters === initialFilters) return rollingStockList;
```

2024-05-24 16:20 UTC, clarani commented on front/src/applications/stdcm/views/StdcmViewV1.tsx
>            currentStdcmRequestStatus={currentStdcmRequestStatus}
```suggestion
          isOpen={currentStdcmRequestStatus=STDCM_REQUEST_STATUS.pending}
```

2024-05-24 16:20 UTC, clarani commented on front/src/applications/stdcm/views/StdcmRequestModal.tsx
Line 38, you can remove the test {currentStdcmRequestStatus === STDCM_REQUEST_STATUS.pending && ... }

2024-05-24 16:20 UTC, clarani commented on front/src/common/Map/Search/MapSearchOperationalPoint.tsx
> +                </span>
```suggestion
                {!MAIN_OP_CH_CODES.includes(searchResult.ch) && (
                  <span className="ch">{searchResult.ch}</span>
                )}
```

2024-05-24 16:20 UTC, clarani commented on front/src/common/Map/Search/useSearchOperationalPoint.tsx
> +  const { debounceDelay = 150, initialSearchTerm = '', initialChCodeFilter } = props || {};
```suggestion
export default function useSearchOperationalPoint({
  debounceDelay = 150,
  initialSearchTerm = '',
  initialChCodeFilter,
}: SearchOperationalPoint) {
```

2024-05-24 16:20 UTC, clarani commented on front/src/modules/rollingStock/components/RollingStockSelector/SearchRollingStock.tsx
> +            onChange={(e) => toggleFilter(e.target.name as 'elec')}
Can you change the other functions onChange ?
```suggestion
            onChange={() => toggleFilter('elec')}
```

2024-05-24 16:20 UTC, clarani commented on front/src/modules/rollingStock/components/RollingStockSelector/SearchRollingStock.tsx
> +import { type RollingStockFilters } from '../../hooks/useFilterRollingStock';
Don't use relatif paths

2024-05-24 16:20 UTC, clarani commented on front/src/reducers/user/index.ts
> +      state.StdcmV2Activated = !state.StdcmV2Activated;
```suggestion
      state.stdcmV2Activated = !state.stdcmV2Activated;
```

2024-05-24 16:20 UTC, clarani commented on front/src/reducers/user/userReducer.spec.ts
> +    expect(userState.StdcmV2Activated).toBe(true);
```suggestion
    expect(userState.stdcmV2Activated).toBe(true);
```

2024-05-24 16:20 UTC, clarani commented on front/src/reducers/osrdconf/types.ts
> +  maximumDepartureDelay?: number;
Not used, to remove
```suggestion
```

2024-05-24 16:20 UTC, clarani commented on front/src/reducers/osrdconf/stdcmConf/selectors.ts
> +    getMaximumDepartureDelay: makeOsrdConfSelector('maximumDepartureDelay'),
Not used, to remove
```suggestion
```

2024-05-24 16:20 UTC, clarani commented on front/src/reducers/osrdconf/stdcmConf/index.ts
> +  maximumDepartureDelay: undefined,
Not used, to remove
```suggestion
```

2024-05-24 16:20 UTC, clarani commented on front/src/common/UserSettings.tsx
> +                dispatch(updateTimetableID(undefined));
I think you can also reset the infraId
```suggestion
                dispatch(updateTimetableID(undefined));
                dispatch(updateInfraID(undefined));
```

2024-05-24 16:20 UTC, clarani commented on front/src/modules/rollingStock/hooks/useFilterRollingStock.tsx
> +// notLocked: true if the rolling stock is created by the user, can be updated/deleted
```suggestion
/**
 * - text: a string to search in the rolling stock name, detail, reference, series, type, grouping
 * - elec: true if the rolling stock has an electric mode
 * - thermal: true if the rolling stock has a thermal mode
 * - locked: true if the rolling stock is native in the database, can't be updated/deleted
 * - notLocked: true if the rolling stock is created by the user, can be updated/deleted
 */
```

2024-05-24 16:20 UTC, clarani commented on front/src/modules/rollingStock/hooks/useFilterRollingStock.tsx
> +    allRollingStocks,
Not used
```suggestion
```

2024-05-24 16:20 UTC, clarani commented on front/src/modules/rollingStock/hooks/useFilterRollingStock.tsx
> +    setFilters,
Not used
```suggestion
```

2024-05-24 16:20 UTC, clarani commented on front/src/modules/rollingStock/hooks/useFilterRollingStock.tsx
> +  const toggleFilter = (filter: 'elec' | 'thermal' | 'locked' | 'notLocked') => {
(suggestion) add tests for this function

2024-05-30 16:56 UTC, SharglutDev approved these changes

2024-05-30 20:20 UTC, clarani commented on front/src/applications/stdcm/views/StdcmRequestModal.tsx
>    const { t } = useTranslation(['translation', 'stdcm']);
You don't use the translation file 'translation' so you can remove it and everywhere in the file, you can remove the 'stdcm:' before the translation key
```suggestion
  const { t } = useTranslation('stdcm');
```

2024-05-30 20:20 UTC, clarani commented on front/src/applications/stdcmV2/components/StdcmConsist.tsx
> +            autoComplete="off"
Is it necessary ?
```suggestion
```

2024-05-30 20:20 UTC, clarani commented on front/src/applications/stdcmV2/components/StdcmHeader.tsx
> +      Phase 1 : de J-7 à J-1 17h, sur l’axe Perrigny—Miramas.{' '}
Missing translation (but I'm not sure it is required)

2024-05-30 20:20 UTC, clarani commented on front/src/applications/stdcmV2/components/StdcmLoader.tsx
> +        <p className="stdcm-v2-loader__img-signature">La ligne TGV Nord</p>
Missing translation

2024-05-30 20:20 UTC, clarani commented on front/src/common/UserSettings.tsx
> +            <p className="ml-3">STDCM nouvelle interface</p>
Missing translation

2024-05-30 20:20 UTC, clarani commented on front/src/applications/stdcmV2/components/StdcmOperationalPoint.tsx
> +const StdcmOperationalPoint = ({ updatePoint, point, isPending }: StdcmOperationalPointProps) => {
```suggestion
const StdcmOperationalPoint = ({ updatePoint, point, disabled }: StdcmOperationalPointProps) => {
```

2024-05-30 20:20 UTC, clarani commented on front/src/common/Map/Search/useSearchOperationalPoint.tsx
> +    const isSearchingByTrigram = !Number.isInteger(+debouncedSearchTerm) && searchTerm.length < 4;
```suggestion
    const isSearchingByTrigram = !Number.isInteger(+debouncedSearchTerm) && debouncedSearchTerm.length < 4;
```

2024-05-30 20:20 UTC, clarani commented on front/src/applications/stdcmV2/components/StdcmOperationalPoint.tsx
> +  const operationalPointsSuggestions = [...sortedSearchResults].reduce(
Do you want to use a useMemo here ?

2024-05-30 20:20 UTC, clarani commented on front/src/applications/stdcmV2/components/StdcmOperationalPoint.tsx
> +      [...sortedSearchResults].reduce(
reduce does not mutate the array, so the copy of the dict is not necessary
```suggestion
      sortedSearchResults.reduce(
```

2024-05-30 20:20 UTC, clarani commented on front/src/applications/stdcmV2/components/StdcmOperationalPoint.tsx
> +  const operationalPointsSuggestions = [...sortedSearchResults].reduce(
```suggestion
  const operationalPointsSuggestions = sortedSearchResults.reduce(
```

2024-05-30 20:20 UTC, clarani commented on front/src/applications/stdcmV2/components/StdcmOperationalPoint.tsx
> +        : null;
Use undefined here, then you can simplify the type in dispatchNewPoint (don't forget to update the test l107)
```suggestion
        : undefined;
```

2024-05-30 20:20 UTC, clarani commented on front/src/applications/stdcmV2/components/StdcmOperationalPoint.tsx
> +    );
```suggestion
    const newPoint = p
      ? {
          name: p.name,
          ch: p.ch,
          id: nextId(),
          uic: p.uic,
          coordinates: p.geographic.coordinates,
        }
      : null;
    dispatch(updatePoint(newPoint));
```

2024-05-31 13:18 UTC, clarani reviewed
Almost good !

2024-05-31 15:23 UTC, clarani approved these changes
LGTM, thanks :white_check_mark:

2024-05-31 17:02 UTC, merged