Add utoipa annotation to edition endpoint
OpenRailAssociation/osrd pull request #7553
Opened 2024-05-29 16:22 UTC by leovalais

Also moves `RailjsonObject` into `editoast_schemas` under `InfraObject`.

> [!TIP]
> Review each commit individually.

2024-05-30 14:04 UTC, woshilapin approved these changes
Mostly some renaming, nice job.

2024-05-30 14:04 UTC, woshilapin commented on editoast/src/infra_cache/mod.rs
> +    fn from(railjson: InfraObject) -> Self {
```suggestion
    fn from(infra_object: InfraObject) -> Self {
```

2024-05-30 14:04 UTC, woshilapin commented on editoast/src/infra_cache/operation/create.rs
> +    railjson_object: &'r InfraObject,
```suggestion
    infra_object: &'r InfraObject,
```

2024-05-30 14:04 UTC, woshilapin commented on editoast/src/infra_cache/operation/mod.rs
> +    pub fn try_from_operation(operation: &Operation, railjson_object: InfraObject) -> Result<Self> {
```suggestion
    pub fn try_from_operation(operation: &Operation, infra_object: InfraObject) -> Result<Self> {
```

2024-05-30 14:04 UTC, woshilapin commented on editoast/src/views/infra/auto_fixes/mod.rs
> +                .map(|railjson_object: InfraObject| Operation::Create(Box::new(railjson_object)))
```suggestion
                .map(|infra_object: InfraObject| Operation::Create(Box::new(infra_object)))
```

2024-05-30 14:04 UTC, woshilapin commented on editoast/src/views/infra/auto_fixes/mod.rs
> +            patch_infra_object(&railjson_object, &railjson_patch)
This one will need to modify the initialization in the destructuring above.

```suggestion
            patch_infra_object(&infra_object, &railjson_patch)
```

2024-05-30 15:32 UTC, flomonster approved these changes
LGTM (reviewed + tested)

2024-06-10 13:27 UTC, woshilapin commented
Test comment

2024-06-10 13:28 UTC, woshilapin approved these changes
Test approve

2024-06-14 07:56 UTC, Uriel-Sautron approved these changes
LGTM (tested)

2024-06-14 14:43 UTC, SharglutDev requested changes
Thank you for the PR, tested it works great. Just left some comments.

2024-06-14 14:43 UTC, SharglutDev commented on front/src/applications/editor/types.ts
> +export type CreateOperation = Operation & { operation_type: 'CREATE' };
When narrowing the type like that, if I hover on `CreateOperation`, I have that : 

![Capture d’écran 2024-06-14 à 16 20 16](https://github.com/OpenRailAssociation/osrd/assets/113104137/cde69429-05a6-4977-a6ff-f3a3918fb010)

We can see that `operation_type: 'CREATE'` appears two times. It doesn't result to any error as we can't assign two times the same property in the object, but a moree elegant way would be to define it like that : 

```suggestion
export type CreateOperation = Extract<Operation, { operation_type: 'CREATE' }>;
```

2024-06-14 14:43 UTC, SharglutDev commented on front/src/applications/editor/types.ts
> +export type DeleteOperation = Operation & { operation_type: 'DELETE' };
Same thing for these two

2024-06-14 14:43 UTC, SharglutDev commented on front/src/applications/editor/data/utils.ts
> +  } as unknown as CreateOperation;
It seems to work without `as unknown `

```suggestion
  } as CreateOperation;
```

2024-06-17 09:11 UTC, SharglutDev approved these changes
Lgtm and tested

2024-06-17 09:36 UTC, merged