editoast: refactor infra tests part 5
OpenRailAssociation/osrd pull request #7705
Opened 2024-06-13 09:34 UTC by hamz2a

Part of #6980

2024-06-13 13:12 UTC, leovalais commented
Thanks for this PR. Can we please delay merging it until the OpenApi migration is complete? Sadly there's some overlap that I won't be able to fix since I'll be in vacation, and I'd like these to be merged asap :/

Cf. #7553 #7677 #7686

2024-06-14 09:40 UTC, woshilapin approved these changes
🚀

2024-06-27 15:02 UTC, leovalais requested changes
Thanks for letting all OpenApi PRs being merged before this one, it really helped! 😄 

Just a few minor details and we're good to go 🚀

2024-06-27 15:02 UTC, leovalais commented on editoast/src/views/infra/auto_fixes/mod.rs
>          })));
Better to assert over the whole collection (`assert_eq!(operations, ...)`): we want this test to fail if there is another error.

Another (weaker) way of doing so would be to check that there is no error before removing the track.

2024-06-27 15:02 UTC, leovalais commented on editoast/src/views/infra/objects.rs
> +        let response = call_service(&app.service, req).await;
Better use `app.fetch` when possible for consistency.

2024-06-27 15:22 UTC, hamz2a commented on editoast/src/views/infra/objects.rs
> +        let response = call_service(&app.service, req).await;
Done.

2024-06-28 09:04 UTC, leovalais approved these changes
Thanks for re-arranging the PR to avoid merging short-lived code.
A few more changes and we're good :)

2024-06-28 09:04 UTC, leovalais commented on editoast/src/views/infra/objects.rs
> +            call_service(&app.service, req).await.status(),
Likewise about `app.fetch` for all other `call_service` in this file.

2024-06-28 09:04 UTC, leovalais commented on editoast/src/views/infra/routes.rs
Likewise about `app.fetch` for all other `call_service` in this file.

2024-06-28 09:15 UTC, hamz2a commented on editoast/src/views/infra/objects.rs
> +            call_service(&app.service, req).await.status(),
Done.

2024-06-28 09:28 UTC, hamz2a commented on editoast/src/views/infra/routes.rs
Done.

2024-06-28 10:31 UTC, merged