editoast: stdcm: add arrival time parameters
OpenRailAssociation/osrd pull request #7827
Opened 2024-06-24 08:59 UTC by eckter

Fix https://github.com/OpenRailAssociation/osrd/issues/7692

Adds stop time parameters and forwards them from editoast inputs to core. Departure time parameter is now optional.

There's a few other changes on the editoast side to have meaningful values as start/end times despite this change. Eventually we should use them to pre-filter the resource uses. 

There's one API change on which I'm not 100% sure: I've "deprecated" the departure time parameter, assuming the time of the first waypoint should be used instead. We could instead keep it but not let the user set a time for the first waypoint.

Note: the feature is not entirely supported by core yet. When the departure time is set, the behavior won't change. If it's not set, the departure time will be too early and the scheduled points will be ignored, but it won't crash.

2024-06-25 07:36 UTC, Erashin approved these changes
Core part is fine.

2024-06-25 15:51 UTC, flomonster requested changes

2024-06-25 15:51 UTC, flomonster commented on editoast/src/core/v2/stdcm.rs
> +    pub arrival_time_tolerance_after: Option<u64>,
We could have an optional struct. So we ensure `tolerance_before` only when `arrival_time` is defined.

2024-06-27 07:32 UTC, flomonster approved these changes
LGTM (reviewed editoast part)

2024-06-27 07:32 UTC, flomonster commented on editoast/src/views/v2/timetable/stdcm.rs
> +    start_time: Option<DateTime<Utc>>,
We can get rid of this once the front end uses the new api?

2024-06-27 08:24 UTC, SarahBellaha approved these changes
LGTM

2024-06-27 08:25 UTC, kmer2016 reviewed
LGTM

2024-06-27 11:18 UTC, kmer2016 approved these changes

2024-06-27 12:47 UTC, merged