editoast: move model v2 database tools to editoast_models
OpenRailAssociation/osrd pull request #7864
Opened 2024-06-27 12:41 UTC by Wadjetz

2024-07-02 07:28 UTC, flomonster approved these changes
LGTM

2024-07-02 07:28 UTC, flomonster commented on editoast/editoast_models/src/lib.rs
> +pub mod database;
```suggestion
pub mod database;

pub use database::DbConnection;
pub use database::DbConnectionPool;
```

2024-07-02 09:23 UTC, woshilapin requested changes
Yes, I did it, I reviewed it all 🎉 Thank you for this refactorization. Don't forget the license.

2024-07-02 09:23 UTC, woshilapin commented on editoast/editoast_models/src/database/connection_pool.rs
> +    /// ```ignore
Why do we need to ignore all the doc-tests in this file?

2024-07-02 09:23 UTC, woshilapin commented on editoast/editoast_models/src/lib.rs
> +pub mod database;
If you expose the `struct`  directly, maybe you don't need to expose the module anymore?

```suggestion
mod database;
```

2024-07-02 09:23 UTC, woshilapin commented on editoast/editoast_models/Cargo.toml
> +edition = "2021"
```suggestion
edition = "2021"
license = "LGPL-3.0"
```

2024-07-02 09:23 UTC, woshilapin commented on editoast/src/views/test_app.rs
> +    // modelsv2::{database::connection_pool::create_connection_pool, DbConnectionPoolV2},
Can be removed.

2024-07-02 10:46 UTC, Wadjetz commented on editoast/editoast_models/src/database/connection_pool.rs
> +    /// ```ignore
Rust doc tries to compile this code and it causes errors, ignore tell the rust doc to ignore the code inside

2024-07-02 11:58 UTC, woshilapin commented on editoast/editoast_models/src/database/connection_pool.rs
> +    /// ```ignore
OK, I get that, but why did we need to change it then? Was it not launched before? Why was it fine before?

2024-07-02 12:40 UTC, Wadjetz commented on editoast/editoast_models/src/database/connection_pool.rs
> +    /// ```ignore
i think it because we move it to a separate crate

2024-07-02 13:25 UTC, leovalais approved these changes
Thanks for this big refactoring 😄 
(I don't believe I've checked this many "viewed" since the switch to diesel_async 😅)

I'll summarize here what we discussed yesterday so that we're all on the same page.

### On errors

1. Although the crate `editoast_models` now exists, we still can't move models into it as they all rely on `InternalError`.
2. The first step would be to redesign the failures of `ModelV2`'s API.
3. Then we'd have to figure out a way to forward the information of the errors defined in sub-crates up to `editoast_views` without manually reading all fields of all variants.
4. Only then will we be able to start moving models around.


### On `diesel*` dependencies

The goal is to remove the `diesel` dependencies in all crates but `editoast_models`.

1. We need to finalize the pool V2 and tests migration (which depends on dropping TSV1 ofc 🙃)
2. The `DbConnection` type must be made opaque.
3. All db queries in the views must be moved into the most relevant model.

That's all I believe?

2024-07-02 13:25 UTC, leovalais commented on editoast/editoast_models/src/database/connection_pool.rs
> +    /// ```ignore
Yeah doc tests cannot be run for a bin.

2024-07-02 13:25 UTC, leovalais commented on editoast/editoast_models/src/lib.rs
> +pub mod database;
+1

2024-07-03 13:19 UTC, woshilapin commented on editoast/editoast_models/src/database/connection_pool.rs
> +    /// ```ignore
So I added functioning doc-tests to the PR in [ca951fa](https://github.com/OpenRailAssociation/osrd/pull/7864/commits/ca951faa07d6faa82c727f0d90fded1b9921bc76). cc @leovalais

2024-07-03 13:26 UTC, woshilapin approved these changes

2024-07-03 13:56 UTC, leovalais commented on editoast/editoast_models/src/database/connection_pool.rs
> +    /// ```ignore
Even better! Thanks @woshilapin :D

2024-07-03 15:33 UTC, merged