front: localize pathfinding errors
OpenRailAssociation/osrd pull request #7883
Opened 2024-06-28 09:10 UTC by emersion

The list of pathfinding error codes can be found here:

https://github.com/OpenRailAssociation/osrd/blob/9f12cd44573cdb498155484cf8ac42372b06a622/core/src/main/kotlin/fr/sncf/osrd/api/api_v2/pathfinding/PathfindingBlockResponse.kt#L84

Closes: https://github.com/OpenRailAssociation/osrd/issues/7862

2024-06-28 09:35 UTC, theocrsb approved these changes
LGTM and tested

2024-06-28 10:29 UTC, axrolld requested changes
Quelques suggestions de renommage. A discuter si besoin :)

2024-06-28 10:29 UTC, axrolld commented on front/public/locales/fr/operationalStudies/manageTrainSchedule.json
> +    "pathfinding_failed": "Recherche d'itinéraire infructueuse"
Quelques suggestions si ce sont ces messages qui apparaissent dans le front. Le but est d'aider l'utilisateur à fix son infra grâce à l'éditeur pour trouver un chemin, donc voici ce que je propose pour les messages (anglais à adapter aussi si on applique ces changements) :

```suggestion
    "not_found_in_blocks": "Canton manquant",
    "not_found_in_routes": "Itinéraire manquant",
    "not_found_in_tracks": "Voie manquante",
    "incompatible_electrification": "Électrification incompatible",
    "incompatible_loading_gauge": "Gabarit incompatible",
    "incompatible_signaling_system": "Système de signalisation incompatible",
    "not_enough_path_items": "Eléments manquants pour la recherche : Origine, Destination, Matériel roulant",
    "pathfinding_failed": "Aucun chemin trouvé"
```

2024-06-28 10:29 UTC, axrolld commented on front/public/locales/fr/operationalStudies/manageTrainSchedule.json
> +    "not_enough_path_items": "Pas assez d'éléments de chemin",
Sur ce point spécifiquement on avait ça avant : 
![image](https://github.com/OpenRailAssociation/osrd/assets/86296016/7080e2ed-f836-4a41-942a-188abae2c18e)

Est-ce que c'est voué à disparaitre ?

2024-06-28 14:35 UTC, kmer2016 approved these changes
LGTM

2024-07-01 13:25 UTC, emersion commented
From my understanding after Eloi explained me this stuff, here's the meaning of each error:

- `not_found_in_blocks`: could find a path of tracks from origin to destination, but could not find a chain of blocks from origin to destination (tracks are not directional, blocks are)
- `not_found_in_routes`: could find a chain of blocks from origin to destination, but at some point we're missing a route in a junction
- `not_found_in_tracks`: could not find a path of tracks at all (origin and destination are not connected)
- `not_enough_path_items`: missing origin/destination
- `pathfinding_failed`: generic error

2024-07-01 13:28 UTC, emersion commented on front/public/locales/fr/operationalStudies/manageTrainSchedule.json
> +    "not_enough_path_items": "Pas assez d'éléments de chemin",
Cette erreur est générée par le front avant de soumettre la requête au backend, donc cette erreur va rester. Elle est plus détaillée que l'erreur du backend donc ça fait probablement sens de garder.

2024-07-02 07:59 UTC, emersion commented on front/public/locales/fr/operationalStudies/manageTrainSchedule.json
> +    "pathfinding_failed": "Recherche d'itinéraire infructueuse"
Suggestion appliquée ! (La traduction anglaise a également été mise à jour.)

2024-07-04 07:25 UTC, Yohh approved these changes

2024-07-04 08:30 UTC, axrolld approved these changes
🚀 Thank you !

2024-07-04 13:20 UTC, emersion commented
Trivial rebase against the `dev` branch.

2024-07-04 13:39 UTC, merged