front: highlight train not keep timetable
OpenRailAssociation/osrd pull request #7959
Opened 2024-07-05 12:02 UTC by theocrsb

For the moment I have just highlighted the trains which do not keep their timetable because the data on the back side is a simple boolean

#7738

2024-07-05 14:26 UTC, Akctarus reviewed
Tested, LGTM, left few comments :)

2024-07-05 14:26 UTC, Akctarus commented on front/src/modules/trainschedule/components/TimetableV2/hooks.ts
> + * @param scheduledPointsHonoredFilter filter for trains that keeps their timetable or not
```suggestion
 * @param scheduledPointsHonoredFilter filter for trains that keep their timetables or not
```

2024-07-05 14:26 UTC, Akctarus commented on front/src/modules/trainschedule/components/TimetableV2/hooks.ts
> +        }
```suggestion
const isHonored = trainSummary.scheduled_points_honored;
  if (
    (scheduledPointsHonoredFilter === 'honored' && !isHonored) ||
    (scheduledPointsHonoredFilter === 'notHonored' && isHonored)
  ) {
    return false;
  }
```

2024-07-05 14:26 UTC, Akctarus commented on front/src/modules/trainschedule/components/TimetableV2/TimetableTrainCardV2.tsx
> +              <div className="mr-2">{!train.scheduledPointsHonored && <Clock size="lg" />}</div>
```suggestion
              <div className="ml-1">{!train.scheduledPointsHonored && <Clock size="lg" />}</div>
```

2024-07-05 14:26 UTC, Akctarus commented on front/src/modules/trainschedule/components/TimetableV2/TimetableTrainCardV2.tsx
> +              <div className="mr-2">{!train.scheduledPointsHonored && <Clock size="lg" />}</div>
I don't think mr-2 does anything, ml-1 looks better

2024-07-05 14:46 UTC, theocrsb commented on front/src/modules/trainschedule/components/TimetableV2/hooks.ts
> + * @param scheduledPointsHonoredFilter filter for trains that keeps their timetable or not
Done

2024-07-05 14:46 UTC, theocrsb commented on front/src/modules/trainschedule/components/TimetableV2/hooks.ts
> +        }
Done

2024-07-05 14:46 UTC, theocrsb commented on front/src/modules/trainschedule/components/TimetableV2/TimetableTrainCardV2.tsx
> +              <div className="mr-2">{!train.scheduledPointsHonored && <Clock size="lg" />}</div>
Done

2024-07-05 14:52 UTC, Akctarus approved these changes

2024-07-08 13:33 UTC, clarani requested changes
Small bugs:
- the invalid trains are not filtered when I chose to display only the trains which honored their waypoints or not
- the train invalid has the yellow band

![image](https://github.com/OpenRailAssociation/osrd/assets/45000526/42cb76c5-6204-4f3d-b56c-1ebda822c87e)

2024-07-08 13:33 UTC, clarani commented on front/src/modules/trainschedule/components/TimetableV2/hooks.ts
> +        if (scheduledPointsHonoredFilter !== 'both' && trainSummary.status === 'success') {
If a train status is not success, then it should be filtered

2024-07-08 13:33 UTC, clarani commented on front/src/modules/trainschedule/components/TimetableV2/TimetableTrainCardV2.tsx
> +              <div className="ml-1">{!train.scheduledPointsHonored && <Clock size="lg" />}</div>
I think it's better if you simply not render the div, so you should test like this:
```suggestion
              {!train.scheduledPointsHonored && (
                <div className="ml-1">
                  <Clock size="lg" />
                </div>
              )}
```

2024-07-08 13:33 UTC, clarani commented on front/src/modules/trainschedule/components/TimetableV2/hooks.ts
> +                  scheduledPointsHonored: false,
I think you can just remove this line, make the field nullable in the type TrainScheduleWithDetails (you can just add a ?)
```suggestion
```

2024-07-08 21:46 UTC, theocrsb commented on front/src/modules/trainschedule/components/TimetableV2/hooks.ts
> +        if (scheduledPointsHonoredFilter !== 'both' && trainSummary.status === 'success') {
Done

2024-07-08 21:46 UTC, theocrsb commented on front/src/modules/trainschedule/components/TimetableV2/TimetableTrainCardV2.tsx
> +              <div className="ml-1">{!train.scheduledPointsHonored && <Clock size="lg" />}</div>
Done

2024-07-08 21:46 UTC, theocrsb commented on front/src/modules/trainschedule/components/TimetableV2/hooks.ts
> +                  scheduledPointsHonored: false,
Done

2024-07-09 11:04 UTC, clarani commented on front/src/modules/trainschedule/components/TimetableV2/hooks.ts
> +                  scheduledPointsHonored: trainSummary.scheduled_points_honored,
Maybe it would be better to use the contrary, this way, in the TimetableTrainCardV2, you can display the yellow band only if `scheduledPointsNotHonored` is true. It will solve the problem that a invalid train has the yellow band
```suggestion
                  scheduledPointsNotHonored: trainSummary.scheduled_points_honored,
```

2024-07-09 11:04 UTC, clarani commented on front/src/modules/trainschedule/components/TimetableV2/hooks.ts
> +          } else if (scheduledPointsHonoredFilter === 'honored') {
I think that we should filter all the trains that are invalid when we use the filter scheduledPointsHonored. I check this with Giuliana
```suggestion
          } else {
```

2024-07-09 13:06 UTC, theocrsb commented on front/src/modules/trainschedule/components/TimetableV2/hooks.ts
> +          } else if (scheduledPointsHonoredFilter === 'honored') {
Done

2024-07-09 13:07 UTC, theocrsb commented on front/src/modules/trainschedule/components/TimetableV2/hooks.ts
> +                  scheduledPointsHonored: trainSummary.scheduled_points_honored,
Done

2024-07-09 17:05 UTC, clarani commented on front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/formatMargin.ts
Hum it seems that you have your 2 PRs mixed in this one :/ These change should be in https://github.com/OpenRailAssociation/osrd/pull/7980

2024-07-09 17:05 UTC, clarani commented on front/src/modules/trainschedule/components/TimetableV2/hooks.ts
> +                  scheduledPointsNotHonored: trainSummary.scheduled_points_honored,
I think you forgot the ! here :)
```suggestion
                  scheduledPointsNotHonored: !trainSummary.scheduled_points_honored,
```

2024-07-09 17:24 UTC, theocrsb commented on front/src/modules/trainschedule/components/TimetableV2/hooks.ts
> +                  scheduledPointsNotHonored: trainSummary.scheduled_points_honored,
yes, I forgot. Done

2024-07-09 17:31 UTC, theocrsb commented on front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/formatMargin.ts
Oh, my bad. Normally it's good I pushed the modification on the good PR and I put the 'formatMargin.ts' file back to its initial state

2024-07-10 08:04 UTC, clarani approved these changes
LGTM :white_check_mark:

2024-07-10 11:36 UTC, merged