front: ensure destination is last in formatSuggestedViasToRowVias()
OpenRailAssociation/osrd pull request #8037
Opened 2024-07-12 11:39 UTC by emersion

See individual commits (some cleanups are also included).

See https://github.com/OpenRailAssociation/osrd/pull/8032#discussion_r1675411754

2024-07-12 11:42 UTC, emersion commented
I tried isolating the logic in a function to avoid repetition, but ended up with something that was IMHO harder to read. (Maybe could have a function to do the `findIndex()` call?)

2024-07-12 13:02 UTC, SharglutDev requested changes

2024-07-12 13:02 UTC, SharglutDev commented on front/src/modules/timesStops/utils.ts
I think your logic works great if origin/destination comes from the rocket but as we check only `if ('uic' in origin && 'ch' in origin)`, it won't work for an origin/destination added by map click (to test it, you can do a Paris St Lazare - Dieppe by clicking on map and see the destination at the wrong place).

2024-07-12 13:14 UTC, emersion commented on front/src/modules/timesStops/utils.ts
Do you think it would make sense to leverage `matchPathStepAndOp()` here? I was worried about breaking stuff since the checks are a bit different (`name` is checked, not `kp`).

2024-07-12 13:26 UTC, SharglutDev commented on front/src/modules/timesStops/utils.ts
I thought about your new util too which should be the best way to change this behavior. I just tested by putting `kp` instead of `name` and it seems to be working fine as well.
An easy test with multiple ops at position 0, is using a path "PNO AS". If you comment the origin switch logic, you will see the origin at the wrong place in the table and both fix with kp or name works.

2024-07-16 09:17 UTC, emersion commented on front/src/modules/timesStops/utils.ts
Done!

2024-07-23 09:12 UTC, SharglutDev approved these changes
Lgtm and tested

2024-07-23 09:42 UTC, merged