front: fix scroll overflow in rollingstock editor
OpenRailAssociation/osrd pull request #8233
Opened 2024-07-29 14:52 UTC by RomainValls

close #7404

2024-08-02 09:27 UTC, SharglutDev requested changes
Thank you for the fix ! Everything works but probably you can simplify it, see comments

2024-08-02 09:27 UTC, SharglutDev commented on front/src/styles/scss/applications/editor/_editor.scss
I think just by using the panel-container class instead of panel-box just did the trick you don't need any of the other changes : 
- `flex-shrink` in `.infra-locked`
- you van remove flex-grow and overflow in `.panel-box`
- you can remove flex and flex-column in `.panel-container`

Or did I miss something ?

2024-08-08 09:52 UTC, RomainValls commented on front/src/styles/scss/applications/editor/_editor.scss
You're right, done 👍 !

2024-08-08 09:59 UTC, SharglutDev approved these changes
Lgtm and tested

2024-08-08 10:31 UTC, merged