stdcm: simulation report map is not showing the path
OpenRailAssociation/osrd pull request #8256
Opened 2024-07-30 12:53 UTC by SarahBellaha

Closes #8016
Closes #8198 
Closes #8620

2024-08-06 14:48 UTC, emersion reviewed
Seems like this TypeScript error pops up:

```
 [TypeScript] Type '{ hideAttribution: true; hideItinerary: true; preventPointSelection: true; pathProperties: ManageTrainSchedulePathProperties | undefined; }' is not assignable to type 'IntrinsicAttributes & MapProps'. Property 'preventPointSelection' does not exist on type 'IntrinsicAttributes & MapProps'.

/app/src/applications/stdcmV2/components/StdcmConfig.tsx:115:44
```

By spamming clicks on the map markers (when the cursor appears as a hand), I can get it in a weird state where the markers are offset:

![out](https://github.com/user-attachments/assets/ef428e3a-3683-4fd1-810e-650261f11984)

(Could maybe be fixed with `pointer-events: none`?)

2024-08-06 14:48 UTC, emersion commented on front/src/modules/trainschedule/components/ManageTrainSchedule/Map.tsx
> +  isLiteVersion?: boolean;
Maybe `isReadOnly` would be a more descriptive name?

2024-08-06 14:48 UTC, emersion commented on front/src/applications/stdcmV2/views/StdcmViewV2.tsx
> +            // pathProperties={pathProperties}
Remnant from the past?

2024-08-06 14:48 UTC, emersion commented on front/src/styles/scss/applications/stdcmV2/_home.scss
> +        width: 100%;
Would probably be a tad better to use `flex-grow: 1` instead of `width: 100%` since the parent is a flex container.

2024-08-06 14:48 UTC, emersion commented on front/src/styles/scss/applications/stdcmV2/_home.scss
> +        width: 100%;
TBH it's a bit strange to me to make the map width adaptive, I would've expected the table on the left side to be `flex-grow: 1` and the map to have a fixed size?

2024-08-06 14:48 UTC, emersion commented on front/src/applications/stdcmV2/components/StdcmConfig.tsx
> +  const { pathfindingState } = usePathfindingV2(setPathProperties, pathProperties);
Hm, I think this state is too high up: the path properties may be different for each simulation result. Maybe there are 3 simulation results and each have their own different origin/destination.

(Of course, in this branch there is only a single simulation result, but I think it'd make sense to put the state at the correct level from the start.)

2024-08-29 16:02 UTC, SharglutDev requested changes
Thank you for this PR ! Tested and it works great. Left some comments.

2024-08-29 16:02 UTC, SharglutDev commented on front/src/modules/trainschedule/components/ManageTrainSchedule/Map.tsx
> +  isReadOnly?: boolean;
What is the difference with `preventPointSelection` ? Maybe we can replace it with `isReadOnly` ?

2024-08-29 16:02 UTC, SharglutDev commented on front/src/modules/trainschedule/components/ManageTrainSchedule/Map.tsx
> +          dragPan: true,
Works perfectly (and I also agree that there is no point to play with the map on this view) but as it was not really what @Castavo asked to solve the issue, maybe you should check with him that this fix is ok :)

2024-08-29 16:02 UTC, SharglutDev commented on front/src/modules/trainschedule/components/ManageTrainSchedule/ManageTrainScheduleMap/ItineraryMarkersV2.tsx
> +}) => {
As we know have two props, could you extract them in a `ItineraryMarkersProps` type ? :)

2024-08-29 16:02 UTC, SharglutDev commented on front/src/modules/trainschedule/components/ManageTrainSchedule/ManageTrainScheduleMap/ItineraryMarkersV2.tsx
> +    () => extractMarkerInformation(simulationPathSteps || pathSteps),
Not sure to understand why we might need `simulationPathSteps` ? We don't pass it to the map from StdcmConfig but informations seem to be the same as in StdcmResults.

2024-08-30 07:54 UTC, SharglutDev commented on front/src/modules/trainschedule/components/ManageTrainSchedule/Map.tsx
> +  isReadOnly?: boolean;
isReadOnly also blocks the map interactivity for zoom and moving on it so we don't want that for the map in the config.

2024-08-30 07:55 UTC, SharglutDev commented on front/src/modules/trainschedule/components/ManageTrainSchedule/Map.tsx
> +          dragPan: true,
Nevermind for that, it works as expected

2024-08-30 07:56 UTC, SharglutDev commented on front/src/modules/trainschedule/components/ManageTrainSchedule/ManageTrainScheduleMap/ItineraryMarkersV2.tsx
> +    () => extractMarkerInformation(simulationPathSteps || pathSteps),
After discussions, we need it in case we change some inputs in the config so it doesn't affect the markers in the results map

2024-08-30 07:57 UTC, SharglutDev approved these changes
Lgtm and tested, good job for the fix !

2024-08-30 13:39 UTC, emersion approved these changes
LGTM, thanks! (Sorry for the delay!)

2024-09-02 06:20 UTC, merged