editoast: add roles check to rolling stocks
OpenRailAssociation/osrd pull request #8362
Opened 2024-08-08 08:53 UTC by Wadjetz

2024-08-09 08:57 UTC, hamz2a approved these changes
LGTM.

2024-08-20 13:49 UTC, leovalais requested changes

2024-08-20 13:49 UTC, leovalais commented on editoast/src/views/light_rolling_stocks.rs
missing `get` endpoint

2024-08-29 09:50 UTC, leovalais approved these changes

2024-08-29 12:25 UTC, merged