misc: ignore .vscode in root .gitignore
OpenRailAssociation/osrd pull request #8471
Opened 2024-08-16 10:54 UTC by Castavo

I offer that we move all of those in once place. What do you think ?
This also ignores .vscode folders created in python/ subfolders by the way

2024-08-16 10:58 UTC, ElysaSrc approved these changes

2024-08-16 11:00 UTC, Khoyo requested changes
you missed core/.gitignore

2024-08-16 11:05 UTC, Castavo commented
@Khoyo thanks, my bad
(Who uses vscode with core ?)

2024-08-17 05:08 UTC, Khoyo approved these changes

2024-08-19 07:26 UTC, clarani approved these changes

2024-08-20 07:55 UTC, leovalais approved these changes

2024-08-20 08:11 UTC, merged