editoast: harmonize comfort type
OpenRailAssociation/osrd pull request #8525
Opened 2024-08-21 21:01 UTC by younesschrifi

Close #8254

2024-08-29 17:43 UTC, SharglutDev requested changes
Thank you for this PR ! Left comments, we need to test carefully to see if we missed something.

2024-08-29 17:43 UTC, SharglutDev commented on front/src/common/api/generatedEditoastApi.ts
Could you use `Comfort` type in the `TrainScheduleBase` `comfort` property as well ?

2024-08-29 17:43 UTC, SharglutDev commented on front/src/modules/rollingStock/components/RollingStockCard/RollingStockCard.tsx
>  } from 'common/api/osrdEditoastApi';
To fix your build issue

```suggestion
import type { Comfort, LightRollingStockWithLiveries } from 'common/api/osrdEditoastApi';
```

2024-08-29 17:43 UTC, SharglutDev commented on front/src/modules/rollingStock/components/RollingStockCurve.tsx
>    );
You can remove all this (from l.53 to l.57) and replace `curvesComfortListsV2` by `curvesComfortList` in this function

2024-08-29 17:43 UTC, SharglutDev commented on front/src/modules/rollingStock/components/RollingStockCurve.tsx
>                  )}
```suggestion
              <span className="curves-chart-tooltip-comfort">
                {comfort2pictogram(transformedCurve.comfort)}
```

2024-08-29 17:43 UTC, SharglutDev commented on front/src/modules/rollingStock/components/RollingStockCurve.tsx
>              comfort2pictogram(curve.comfort === 'AC' ? 'AIR_CONDITIONING' : curve.comfort)}
You can remove the comment and the condition

```suggestion
          {curve.comfort !== STANDARD_COMFORT_LEVEL &&
            !isOnEditionMode &&
            comfort2pictogram(curve.comfort)}
```

2024-08-29 17:43 UTC, SharglutDev commented on front/src/modules/rollingStock/components/RollingStockCard/RollingStockCard.tsx
In the `RollingStockCardButtons` component, you should change the `curvesComfortList` prop l.16 with `Comfort[]` instead of `string[]`. This way we can spot a warning l.57 and replace `'AC'` by `'AIR_CONDITIONING'`

2024-08-29 17:43 UTC, SharglutDev commented on front/src/modules/rollingStock/components/RollingStockEditor/RollingStockEditorCurves.tsx
>  } from 'common/api/osrdEditoastApi';
To prevent CI to fail because of eslint warning

```suggestion
import type { EffortCurves, RollingStock, Comfort } from 'common/api/osrdEditoastApi';
```

2024-08-29 17:43 UTC, SharglutDev commented on front/src/modules/rollingStock/components/RollingStockEditor/CurveParamSelectors.tsx
>  } from 'common/api/osrdEditoastApi';
Linter error

```suggestion
import type { ConditionalEffortCurve, RollingStock, Comfort } from 'common/api/osrdEditoastApi';
```

2024-08-29 17:43 UTC, SharglutDev commented on front/src/modules/rollingStock/consts.ts
> +import type { Comfort, Comfort } from 'common/api/osrdEditoastApi';
```suggestion
import type { Comfort } from 'common/api/osrdEditoastApi';
```

2024-08-29 17:43 UTC, SharglutDev commented on front/src/common/api/generatedEditoastApi.ts
In modules/powerRestriction/helpers/___tests___/sampleData.ts, you need to replace all `comfort: 'AC'` by `comfort: 'AIR_CONDITIONING'`

2024-08-29 17:43 UTC, SharglutDev commented on front/src/common/api/generatedEditoastApi.ts
In RollingStockEditorCurves.spec.ts l.8, you need to replace `'AC'` by `'AIR_CONDITIONING'`

2024-08-29 17:43 UTC, SharglutDev commented on front/src/common/api/generatedEditoastApi.ts
In 007-op-rollingstock-tab.spec.ts l.80, you can replace `// Select the comfort AC` by `// Select the comfort AIR_CONDITIONING`

2024-08-29 17:43 UTC, SharglutDev commented on front/src/common/api/generatedEditoastApi.ts
In tests/assets/rollingStock/dual-mode_rolling_stock.json l.274 and l.355, replace `'AC'` by `'AIR_CONDITIONING'`

2024-08-29 17:43 UTC, SharglutDev commented on front/src/common/api/generatedEditoastApi.ts
In rolling_stock.py l.25, maybe you will have an issue with `AC` also ?

2024-08-29 17:43 UTC, SharglutDev commented on front/src/common/api/generatedEditoastApi.ts
In tests/data/rolling_stocks/electric_rolling_stock.json, replace all `'AC'` with `'AIR_CONDITIONING'`

2024-08-29 17:43 UTC, SharglutDev commented on front/src/common/api/generatedEditoastApi.ts
In rollingstock.json (for fr and en trads), remove the line `"AC": "Air conditioning"`

2024-08-29 17:43 UTC, SharglutDev commented on front/src/common/api/generatedEditoastApi.ts
In some .java files, I see some `AC` use (you can find them by searching `AC` in the app), will it be an issue for the simulation ?

2024-08-30 08:47 UTC, shenriotpro approved these changes
LGTM for tests/

2024-08-30 09:21 UTC, woshilapin approved these changes
Nice clean up and homogenization. Thank you.

2024-08-30 09:46 UTC, Erashin requested changes

2024-08-30 09:46 UTC, Erashin commented on core/osrd-railjson/src/main/java/fr/sncf/osrd/railjson/schema/rollingstock/RJSComfortType.java
>  public enum RJSComfortType {
This struct should not be needed anymore. It has no difference with `RollingStock.Comfort` used everywhere else in the code. You should be able to remove it, remove the corresponding method `parseComfort`, and directly use `var comfort: RollingStock.Comfort? = null` in `STDCMRequest.kt`. There's a few modifications needed elsewhere afterwards :)

2024-08-30 13:42 UTC, flomonster approved these changes
LGTM

2024-09-02 12:56 UTC, Erashin approved these changes
GJ :)

2024-09-02 15:44 UTC, flomonster commented on editoast/migrations/2024-09-02-132335_replace_mode_ac_with_air_conditioning/up.sql
The easiest way is to serialize the JSON and replace occurrences of `AC` with `AIR_CONDITIONING`.
See an example here: https://github.com/OpenRailAssociation/osrd/blob/dev/editoast/migrations/2024-07-18-092453_adapt-train-schedules-v2/up.sql

2024-09-03 07:39 UTC, flomonster commented on editoast/migrations/2024-09-02-132335_replace_mode_ac_with_air_conditioning/up.sql
> +SET effort_curves = REGEXP_REPLACE(effort_curves::text, 'AC', 'AIR_CONDITIONING', 'g')::jsonb;
To be more restrictive in the regex. I did not test it...

```suggestion
SET effort_curves = REGEXP_REPLACE(effort_curves::text, '"AC"', '"AIR_CONDITIONING"', 'g')::jsonb;
```

2024-09-03 10:37 UTC, SharglutDev approved these changes
Lgtm and tested, thank you for this PR !

2024-09-03 11:01 UTC, merged