editoast: db connection v3
OpenRailAssociation/osrd pull request #8712
Opened 2024-09-03 09:04 UTC by Wadjetz

2024-09-04 14:56 UTC, woshilapin requested changes
Big work, will be much better. I request a change on the documentation of the re-implementation of `transaction` since it's a central but non-trivial function of this new `DbConnection` so I think it's important to give as much context as possible to ease future maintenance.

2024-09-04 14:56 UTC, woshilapin commented on editoast/editoast_models/src/db_connection_pool.rs
> +    }
I believe this piece of code takes inspiration from the existing implementation inside `diesel` crate (see [`TransactionManager::transaction()`](https://docs.rs/diesel/2.1.6/src/diesel/connection/transaction_manager.rs.html#50-71)). It's probably a good idea to keep a link to it and refer to it so the next developer that needs to maintain this function know it should also take inspiration on the `diesel` crate. Maybe also add a comment on the reason why we have to reimplement it ourselves and we can't use the existing one.

2024-09-04 14:56 UTC, woshilapin commented on editoast/src/modelsv2/fixtures.rs
> -    // let image = document_example(db_pool.clone()).await;
Can be removed.

2024-09-04 14:56 UTC, woshilapin commented on editoast/src/modelsv2/fixtures.rs
> +}
Why do we need these new functions in a PR that only change the `DbConnection`?

2024-09-05 09:28 UTC, woshilapin commented on editoast/src/modelsv2/fixtures.rs
> +}
Removed in https://github.com/OpenRailAssociation/osrd/pull/8712/commits/e8c0350489cfc4c6543056d5fb81ba53621c7e21.

2024-09-05 09:29 UTC, woshilapin commented on editoast/editoast_models/src/db_connection_pool.rs
> +    }
Proposition of documentation in https://github.com/OpenRailAssociation/osrd/pull/8712/commits/9fef9a6a13826c3c8cf2c5ba809dc1aa61b2314c. @leovalais What do you think?

2024-09-05 12:55 UTC, leovalais requested changes
Huge work! I have a few comments about the API, especially for errors.

That's work for another PR since this one is already massive:

1. Most functions don't require a `conn: &mut DbConnection` but rather just a `conn: DbConnection` which became cheap to clone.
2. Maybe we could implement `Future` for `DbConnection` so that `conn.await` <=> `conn.write().await.deref_mut()`
3. Some sync test util functions might declutter the boilerplate the `RwLock` introduced.

2024-09-05 12:55 UTC, leovalais commented on editoast/editoast_derive/src/model.rs
Unless I misunderstood something, `DieselConnection` is supposed to be an `editoast_models` internal type. I'd say that these functions should take a `DbConnection` just like before instead.

2024-09-05 12:55 UTC, leovalais commented on editoast/editoast_models/src/lib.rs
> +}
I don't understand this change. There was two different types `DatabaseError` and `DatabasePoolError` that

1. serve different purposes, cf. their error messages
2. allows `editoast_models` to forward errors without exposing diesel's errors

Besides, `DatabasePoolError` also forwards `diesel::result::Error`. Its seems to me that the error types don't require any modification.

2024-09-05 12:55 UTC, leovalais commented on editoast/editoast_models/src/lib.rs
> +pub type DieselConnection = AsyncPgConnection;
Why is this type still `pub`? We'd like to only expose `DbConnection` outside of the crate. Am I missing something?

2024-09-05 12:55 UTC, leovalais commented on editoast/src/modelsv2/auth.rs
> +            .clone()
`clone`?

2024-09-05 13:09 UTC, leovalais commented on editoast/editoast_derive/src/model.rs
Oops scratch that... it's Model V1

2024-09-05 14:12 UTC, leovalais approved these changes
Approving in order not to block the PR, but since I made the modifications myself, this doesn't account for much 🤣

2024-09-05 14:44 UTC, woshilapin approved these changes

2024-09-05 16:09 UTC, merged