core: infra: improve error reporting when ports are reused
OpenRailAssociation/osrd pull request #873
Opened 2022-04-29 14:56 UTC by eckter

2022-05-02 12:08 UTC, flomonster requested changes

2022-05-02 12:08 UTC, flomonster commented on core/src/main/java/fr/sncf/osrd/infra/implementation/tracks/undirected/UndirectedInfraBuilder.java
> +                            continue;
We could use `&&` instead of nested `if`.

2022-05-02 14:26 UTC, multun submitted a review, later dismissed

2022-05-03 09:43 UTC, flomonster approved these changes, later dismissed

2022-05-03 10:16 UTC, flomonster approved these changes

2022-05-03 10:53 UTC, merged