front: add debug components in stdcm interface
OpenRailAssociation/osrd pull request #8812
Opened 2024-09-10 06:40 UTC by SarahBellaha

Closes #8590

2024-09-10 15:59 UTC, Yohh commented on front/src/applications/stdcm/hooks/useStdcm.ts
> +const useStdcm = (isDebugMode: boolean = false, showFailureNotification: boolean = true) => {
```suggestion
const useStdcm = (isDebugMode = false, showFailureNotification = true) => {
```

2024-09-10 15:59 UTC, Yohh commented on front/src/applications/stdcm/utils/formatStdcmConfV2.ts
> +  isDebugMode: boolean = false
```suggestion
  stdcmV2Activated = true,
  isDebugMode = false
```

2024-09-10 15:59 UTC, Yohh commented on front/src/styles/scss/applications/stdcmV2/_header.scss
> +      }
```suggestion
&.debug-on {
        box-shadow: 0 0 0 0.125rem rgba(255, 255, 255) inset;
        border: 0.0625rem solid rgba(92, 89, 85);
        background-color: rgba(255, 242, 179);
        &:hover {
          border: 0.1875rem solid rgba(255, 255, 255);
          border: 0.0625rem solid rgba(0, 0, 0);
          background-color: rgba(0, 0, 0, 0.05);
        }
      }

      &.debug-off {
        color: rgba(114, 168, 247, 1);
        border: 0.0625rem solid rgba(114, 168, 247);
        &:hover {
          color: rgba(31, 15, 150);
          border: 0.0625rem solid rgba(31, 15, 150);
          background-color: rgba(255, 255, 255);
        }
      }
```

2024-09-11 14:26 UTC, kmer2016 reviewed
Thank you for the PR! I've left a few comments.

I have a couple of questions regarding the behavior:

- Should the debug button always be displayed?
- Is it expected that the space-time graph shows only the STDCM train? (Is this acceptable for now?)"

2024-09-11 14:26 UTC, kmer2016 commented on front/src/applications/stdcmV2/components/StdcmResults/StdcmResults.tsx
> +              selectedSimulation.outputs.pathProperties.manchetteOperationalPoints ? (
```suggestion
              selectedSimulation.outputs?.pathProperties.manchetteOperationalPoints ? (
```

2024-09-11 14:26 UTC, kmer2016 commented on front/src/applications/stdcmV2/components/StdcmResults/StdcmResults.tsx
> +      {isDebugMode && (
Once we have the component that merges 'Manchette' and GET, we'll need to use it here. How about adding a TODO to ensure we don't forget?

2024-09-11 14:26 UTC, kmer2016 commented on front/src/applications/stdcmV2/types.ts
> +    rollingStock: RollingStockWithLiveries;
Do we need to include `rollingStock` in `output.speedChartData` as well, considering it's already in input.consist.tractionEngine? Having the same data in two different places could be confusing.

2024-09-11 14:26 UTC, kmer2016 commented on front/src/modules/scenario/components/ScenarioExplorer/ScenarioExplorer.tsx
> +      );
It seems that we are using multiple actions (`updateTimetableID` and `updateInfraID`) to update the infrastructure and timetable IDs, and then also using the `updateStdcmEnvironment` action to update the stdcm environment with the same IDs. This can lead to redundancies and unnecessary state updates.

To simplify and improve the efficiency of the code, I propose:
- Keep the `updateStdcmEnvironment` action: Use this single action to update all necessary IDs at once.
- Remove redundant actions: Remove the `updateTimetableID` and `updateInfraID` actions to avoid redundancies.

```suggestion
      // We also set the stdcm environment in case we select a scenario from the stdcm interface.
      dispatch(
        updateStdcmEnvironment({
          infraID: scenario.infra_id,
          timetableID: scenario.timetable_id,
          electricalProfileSetId: undefined,
          workScheduleGroupId: undefined,
          searchDatetimeWindow: undefined,
        })
      );
```

2024-09-11 14:26 UTC, kmer2016 commented on front/src/modules/scenario/components/ScenarioExplorer/ScenarioExplorer.tsx
> +  const { updateStdcmEnvironment } = useOsrdConfActions() as StdcmConfSliceActions;
Can be merge in a single instruction
```suggestion
  const { updateInfraID, updateTimetableID, updateScenarioID, updateStdcmEnvironment } = useOsrdConfActions() as StdcmConfSliceActions;
```

2024-09-11 17:36 UTC, SarahBellaha commented on front/src/modules/scenario/components/ScenarioExplorer/ScenarioExplorer.tsx
> +      );
Absolutely right ! I didn't pay attention to that, thanks.

2024-09-11 18:10 UTC, SarahBellaha commented on front/src/applications/stdcmV2/types.ts
> +    rollingStock: RollingStockWithLiveries;
It comes from the useSpeedSpaceChart hook which is also used in the operational studies that need it and doesn't have the information.
We should maybe consider refactoring that part ?

2024-09-12 08:15 UTC, kmer2016 commented on front/src/applications/stdcmV2/types.ts
> +    rollingStock: RollingStockWithLiveries;
Oh, okay. Do we need all the fields in speedSpaceChartData? It seems like we only need `formattedPowerRestrictions` and `formattedPathProperties`.

2024-09-12 08:58 UTC, kmer2016 commented
small style problem ln time table margin labels
![image](https://github.com/user-attachments/assets/929895b2-d821-4294-be30-1da422658f35)

2024-09-12 09:31 UTC, kmer2016 reviewed
In debug mode, the `speedSpaceChart` only displays the requested path without showing the other trains in the scenario. I don't see this being addressed in the other tickets, which could make debugging the scenario difficult in its current state.

2024-09-12 09:56 UTC, kmer2016 requested changes
When a simulation has no results, the graphs display loaders.
![image](https://github.com/user-attachments/assets/a03c3b50-85f1-48f6-bfb2-58afe7ae3211)

2024-09-25 15:45 UTC, kmer2016 approved these changes
Very good job !

2024-09-26 08:36 UTC, merged