front: add times and stops e2e test for operational studies
OpenRailAssociation/osrd pull request #8961
Opened 2024-09-23 15:51 UTC by Maymanaf

Closes [#8646](https://github.com/OpenRailAssociation/osrd/issues/8646)

2024-09-25 09:31 UTC, emersion commented
This component will be re-designed and rewritten soon. I wonder, is now a good time to merge a test, given we're going to have to rewrite it soon?

2024-09-27 07:03 UTC, Uriel-Sautron reviewed
Thank you for this test, but it sometimes fails locally and is wobbly in the CI

2024-10-01 14:34 UTC, kmer2016 commented
> This component will be re-designed and rewritten soon. I wonder, is now a good time to merge a test, given we're going to have to rewrite it soon?
After talking with @clarani, we both think it still makes sense to merge these tests. Since the structure will mostly change but the content will stay the same, this will help standardize the input table and make it easier when we update it later.

2024-10-02 08:06 UTC, kmer2016 approved these changes

2024-10-02 09:57 UTC, Uriel-Sautron approved these changes
LGTM, tested

2024-10-02 09:57 UTC, Uriel-Sautron commented on front/tests/pages/op-timetable-page-model.ts
> +  readonly speedSapceChart: Locator;
```suggestion
  readonly speedSpaceChart: Locator;
```
Typo

2024-10-03 10:16 UTC, anisometropie requested changes

2024-10-03 10:16 UTC, anisometropie commented on front/tests/pages/op-input-table-page-model.ts
> +      if (normalizedHeaderText === normalizedHeaderName) {
normalizedHeaderText / normalizedHeaderName
a bit hard to follow, you could use more explicit names.

headerText   = currentColumnHeader ?
normalizedheaderName = columnHeader

2024-10-03 10:41 UTC, Maymanaf commented on front/tests/pages/op-input-table-page-model.ts
> +      if (normalizedHeaderText === normalizedHeaderName) {
changed to : 
headerText = columnHeader
normalizedHeaderText = currentColumnHeader
normalizedHeaderName = expectedColumnHeader

2024-10-03 10:43 UTC, anisometropie approved these changes

2024-10-03 11:09 UTC, merged