front: stdcm loader adjustments
OpenRailAssociation/osrd pull request #9007
Opened 2024-09-26 06:19 UTC by SarahBellaha

Closes [STDCM: Loader adjustments](https://github.com/osrd-project/osrd-confidential/issues/681)

2024-09-26 08:34 UTC, clarani commented on front/src/styles/scss/applications/stdcmV2/_loader.scss
> +}
Why not group stdcm-v2-loader-background and stdcm-v2-loader?

2024-09-26 08:34 UTC, clarani commented on front/src/applications/stdcmV2/components/StdcmStatusBanner.tsx
> +      <div className="banner-content">
Why add this div ? Maybe you can merge its style with its parent's style ?

2024-09-26 08:34 UTC, clarani commented on front/src/applications/stdcmV2/views/StdcmViewV2.tsx
Nice, thanks for moving these 2 components here, it makes more sense :+1:

2024-09-26 09:25 UTC, anisometropie commented
Got this
![Screenshot_20240926_112515](https://github.com/user-attachments/assets/e3b57723-1ee4-4752-92b7-2c1a40eb7100)

2024-09-26 09:35 UTC, anisometropie commented
the 2 shades of gray were already on dev, but the text was below and bounded

2024-09-26 12:29 UTC, clarani reviewed
Can you change the legend of the image too ? "Vue matinale du relais de locomotives du dépôt du Bourget" in french

2024-09-26 12:29 UTC, clarani commented on front/src/styles/scss/applications/stdcmV2/_loader.scss
> +}
OK this implies more refacto, it will be done in an other PR

2024-09-26 12:30 UTC, clarani commented on front/src/applications/stdcmV2/components/StdcmStatusBanner.tsx
> +      <div className="banner-content">
OK this implies more refacto, it will be done in an other PR

2024-10-02 08:08 UTC, clarani approved these changes
LGTM :white_check_mark:

2024-10-02 08:39 UTC, clarani requested changes
- The padding under the legend is not correct.
On the app:
![image](https://github.com/user-attachments/assets/3a88a41d-57f5-4ba7-8d74-ede57dabd107)

On the mockup:
![image](https://github.com/user-attachments/assets/857d5e46-53df-4bb5-8760-b6bab7b47efb)

- the high of the image should not be set in the css

2024-10-02 14:07 UTC, anisometropie approved these changes

2024-10-08 11:09 UTC, clarani approved these changes
LGTM, thanks :pray: :white_check_mark:

2024-10-09 07:35 UTC, merged