osrdyne: hide sensitive information in logs
OpenRailAssociation/osrd pull request #9250
Opened 2024-10-08 12:09 UTC by woshilapin

2024-10-09 11:06 UTC, ElysaSrc approved these changes

2024-10-09 11:09 UTC, Khoyo requested changes
I don't think this will work after this. https://github.com/OpenRailAssociation/osrd/pull/9261

2024-10-09 11:27 UTC, ElysaSrc reviewed
Indeed, my bad : I reviewed without thinking of the changes I've made on the other PR.

2026-01-16 13:54 UTC, flomonster commented
Can we close this PR?

2026-01-16 14:11 UTC, closed without merging