front: fix relief on map
OpenRailAssociation/osrd pull request #9342
Opened 2024-10-15 07:53 UTC by clarani

closes #9341

2024-10-15 08:46 UTC, anisometropie requested changes

2024-10-15 08:46 UTC, anisometropie commented on front/src/common/Map/Layers/HillShade.tsx
> +import { getTerrain3DExaggeration } from 'reducers/map/selectors';
Hillshade is just one word, no need to rename that file

2024-10-15 09:05 UTC, clarani commented on front/src/common/Map/Layers/HillShade.tsx
> +import { getTerrain3DExaggeration } from 'reducers/map/selectors';
Done :white_check_mark:

2024-10-15 12:44 UTC, Synar approved these changes
LGTM!

2024-10-15 13:38 UTC, Math-R approved these changes
lgtm !

2024-10-16 07:28 UTC, anisometropie approved these changes

2024-10-16 07:41 UTC, merged