editoast: stdcm max speed handle zero value
OpenRailAssociation/osrd pull request #9654
Opened 2024-11-08 09:34 UTC by Wadjetz

2024-11-08 10:30 UTC, woshilapin reviewed
The code is fine (only some minor comments), but I'm questioning the original ticket https://github.com/OpenRailAssociation/osrd/issues/9637 in which I made a comment. I propose to not merge the current PR until we do have an answer.

2024-11-08 10:30 UTC, woshilapin commented on editoast/src/core/simulation.rs
> +        }
You can express that with a filter.

```rust
self.max_speed
  .filter(|max_speed_parameter| *max_speed_parameter != 0.0)
  .map(|max_speed_parameter| f64::min(self.traction_engine.max_speed, max_speed_parameter))
  .unwrap_or(self.traction_engine.max_speed)
```

2024-11-08 10:30 UTC, woshilapin commented on editoast/src/views/timetable/stdcm.rs
> +    #[validate(range(min = 1.0))]
Where does this `1.0` value comes from. I believe the ticket only mentions excluding `0.0`. You should be able to do that with the following.

```suggestion
    #[validate(range(exclusive_min = 0.0))]
```

2024-11-08 10:30 UTC, woshilapin commented on editoast/src/views/timetable/stdcm.rs
> +    #[validate(range(min = 1.0))]
```suggestion
    #[validate(range(exclusive_min = 0.0))]
```

2024-11-08 10:30 UTC, woshilapin commented on editoast/src/views/timetable/stdcm.rs
> +    #[validate(range(min = 1.0))]
```suggestion
    #[validate(range(exclusive_min = 0.0))]
```

2024-11-08 13:50 UTC, hamz2a approved these changes
LGTM, thanks!

2024-11-15 10:17 UTC, flomonster approved these changes
LGTM. Can you fixup your commits before merge.

2024-12-04 10:53 UTC, woshilapin requested changes
I don't think we should filter the zero, for the same reason I mentioned in https://github.com/OpenRailAssociation/osrd/issues/9637#issuecomment-2464324459. The fact that the field is optional should be enough.

2024-12-04 13:39 UTC, woshilapin approved these changes
Thank you.

2024-12-04 14:30 UTC, leovalais commented
Ping @Tristramg: changes in rolling stock speed calculations, probably best to rebase before typing quantities any further :)

2024-12-04 15:08 UTC, SharglutDev approved these changes
Lgtm for front (not tested)

2024-12-05 15:22 UTC, merged