Yci/add weight field to op
OpenRailAssociation/osrd pull request #9775
Opened 2024-11-19 00:07 UTC by younesschrifi

2024-11-20 14:57 UTC, shenriotpro approved these changes
LGTM for tests/

2024-11-22 14:37 UTC, flomonster requested changes
Weirdly this file: `osrd-railjson/src/main/java/fr/sncf/osrd/railjson/schema/infra/RJSInfra.java` has a version set to `3.4.11`. Can you check? If it 's not use we can refacto this in another PR.

2024-11-22 14:37 UTC, flomonster commented on editoast/migrations/2024-11-19-143456_add_weight_to_operational_point/up.sql
> +);
Since the field  has a default value it does not require a migration.

2024-11-22 14:37 UTC, flomonster commented on front/tests/assets/infra/infra.json
> +      "weight": null
```suggestion
```

Same, it should not be required.

2024-11-25 09:59 UTC, woshilapin approved these changes
Nice job.

I believe all commits should be squashed together before merge since they all relate to the same atomic modification. Also, can you edit the title of the PR to not let the default branch name?

2024-11-25 09:59 UTC, woshilapin commented on python/railjson_generator/railjson_generator/schema/infra/operational_point.py
> +        self.weight = None
nitpick: Would it make sense to do that instead?

```suggestion
    def __init__(self, label: str, trigram: Optional[str] = None, uic: int = 0, weight: Optional[int] = None):
        self.label = label
        self.trigram = trigram or label[:3].upper()
        self.parts = list()
        self.uic = uic
        self.weight = weight
```

2024-11-26 10:25 UTC, SharglutDev approved these changes
Lgtm fro front (not tested)

2024-12-02 14:49 UTC, Erashin approved these changes
Is the PR title fine? Not used to see this format.
Core lgtm otherwise.

2024-12-02 16:58 UTC, Maymanaf approved these changes
LGTM for e2e tests 
You just need to wait for this [PR](https://github.com/OpenRailAssociation/osrd/pull/9913) to be merged before

2024-12-06 09:35 UTC, flomonster approved these changes
LGTM

2024-12-06 09:58 UTC, Khoyo commented
> Is the PR title fine? Not used to see this format.

The default title for multi-commit pr is the name of the branch (instead of the commit title). It's not an ideal title but they don't end up in the git history anyway as we do fast-forward merges only

2024-12-06 10:03 UTC, emersion commented
They do end up in release notes though (and in general are not very readable).

2024-12-06 10:04 UTC, younesschrifi commented
Thank you @emersion for your comment. I'll do better next time :)

2024-12-06 10:05 UTC, woshilapin requested changes
I'm sorry, I removed this PR from the merge queue.

Sure, most commits are separated which helps for review, but this doesn't make for a reasonable atomic change. So before merging, I believe these should be squashed. For example, changing the schemas in `osrd_schemas` without changing the corresponding schemas in `editoast` in the same commit is a mistake to me. That's the reason why we do have a monorepo and change can be done everywhere in one operation. What do you think?

And yes, sure, the title of the PR is not kept around in the git repository, but it's still kept in the Github where all the other PR titles respects some kind of standard formatting. And they end up in the release.

I could also argue that the description of the PR doesn't really help understand the full context (it links to an issue where there is nothing but a title).

Most of the contributions guidelines are [here](https://osrd.fr/en/docs/guides/contribute/contribute-code/share-changes/). I know we not always follow them to the line, but here, there is multiple problems and I believe some of them should be addressed (PR title, PR description, non-atomic commits).

2024-12-06 10:25 UTC, woshilapin approved these changes

2024-12-06 11:05 UTC, merged