core: remove the middle green signals in the STD
OpenRailAssociation/osrd pull request #9906
Opened 2024-11-29 16:17 UTC by Khoyo

Currently, VL (green) blocks only have a meaning before the train, and the meaning is "I require this signal to be open to keep to my schedule".
After/during the train, the meaning would be "I don't constrain this signal" which is actually what blank means. So let's keep those cases blank.

Case appears when diverging from the projected path, stopping on closed signal, then converging (stop in the same station, but different track)
Before:
![image](https://github.com/user-attachments/assets/8d3da6f8-aab5-4334-b3e6-0cf0ae091365)
After this PR:
![image](https://github.com/user-attachments/assets/695fc98f-6608-493c-806d-23c51b04d79a)

Relates to 1 part of https://github.com/osrd-project/osrd-confidential/issues/886

2024-11-29 18:21 UTC, bougue-pe requested changes, later dismissed
(completed the main description)

It doesn't work from my test.
Maybe be should also shorten the first free block? 🤔

2024-11-30 19:54 UTC, Khoyo commented
> (completed the main description)
> 
> It doesn't work from my test. Maybe be should also shorten the first free block? 🤔

Nah, we should do it in the right file.

So... I also removed the old signal projection logic and adapted the v1 signal projection endpoint

2024-12-04 09:18 UTC, bougue-pe reviewed
I'm not sure I understand what you did on the SignalProjectionEndpoint (v1): why can't we completely remove it?
If we keep it like this, we probably need a clear todo to accelerate future cleanup work.

2024-12-04 09:18 UTC, bougue-pe commented on core/src/main/java/fr/sncf/osrd/api/SignalProjectionEndpoint.kt
> +            val tvm430 = sigSystemManager.findSignalingSystemOrThrow("TVM430")
Those are unused vars

2024-12-04 09:18 UTC, bougue-pe commented on core/src/main/java/fr/sncf/osrd/api/SignalProjectionEndpoint.kt
Shouldn't we put it in a kt dir?
Or should we just not care and add a `deprecated` comment right away?

2024-12-04 09:18 UTC, bougue-pe commented on core/src/main/kotlin/fr/sncf/osrd/signal_projection/SignalProjection.kt
>              val nextEvent = events[i + 1]
As there is no special filter for the last event anymore, the code can probably be mutualized.
Something along this (there is probably something more idiomatic to be done):
```suggestion
            val endTime = if (i < events.size) events[i + 1].time else simulationEndTime
```

2024-12-04 23:51 UTC, Khoyo commented on core/src/main/java/fr/sncf/osrd/api/SignalProjectionEndpoint.kt
The kotlin directory is not necessary anymore since at least Kotlin 1.0. I believe we should probably just merge the kotlin and java dirs

2024-12-04 23:54 UTC, Khoyo commented
> I'm not sure I understand what you did on the SignalProjectionEndpoint (v1): why can't we completely remove it?

We're keeping the TSv1 endpoints for a few more months (I believe until some time in January). But there is not reason to keep the old logic if we can avoid it.

2024-12-05 09:02 UTC, Erashin approved these changes
This looks like it's working as intended.
Give me your opinion on the kotlin/java module question.
I'd love a unit test on this case as well.

2024-12-05 09:02 UTC, Erashin commented on core/src/main/java/fr/sncf/osrd/api/SignalProjectionEndpoint.kt
Hmm. Personal opinion: I'd rather not merge the directories, since the end goal is probably just to have the whole thing in kotlin, it makes a clear distinction between what we have to keep and what we have to migrate.
For that reason as well, as long as we separate them,  I'd rather have the kotlin files in the kotlin directory (especially since it already exists).

2024-12-06 11:02 UTC, Khoyo commented on core/src/main/java/fr/sncf/osrd/api/SignalProjectionEndpoint.kt
> I'd rather not merge the directories, since the end goal is probably just to have the whole thing in kotlin, it makes a clear distinction between what we have to keep and what we have to migrate.

I really don't get that. If it's about the kotlin/java migration, just `find -name '*.java'`?

If it's about the obsolete v1 APIs, this is an obsolete v1 api file :p

2025-12-08 10:16 UTC, Erashin reviewed
Is this actually still up to date? Been one year.

2025-12-08 12:16 UTC, Khoyo commented
Well, I've just found it again while spring cleaning my git branches, the bug still isn't fixed, and I ~~finally~~ wrote the unit test, so yeah, now it is.

2025-12-08 14:23 UTC, Erashin approved these changes

2025-12-08 14:56 UTC, merged