front: fix constraint distribution state in simulation settings
OpenRailAssociation/osrd pull request #9932
Opened 2024-12-03 15:11 UTC by RomainValls

close #9811

2024-12-03 17:03 UTC, clarani requested changes
Hum it would be better to fix this directly in the action `selectTrainToEdit` ;) you can get the `constraint_distribution` of the trainSchedule there and directly set the state

2024-12-05 17:12 UTC, clarani commented on front/src/applications/operationalStudies/views/ManageTrainSchedule.tsx
You don't need the change of this file anymore ;)

2024-12-06 10:39 UTC, clarani approved these changes
LGTM :white_check_mark:

2024-12-09 10:07 UTC, Math-R approved these changes
LGTM !

2024-12-12 09:14 UTC, Yohh approved these changes

2024-12-12 11:51 UTC, merged